= Core concepts

Cypher queries match patterns in a graph.
This page provides a brief overview of three core concepts used to construct Cypher queries: nodes, relationships, and patterns.

For a more detailed overview, see the link:{neo4j-docs-base-uri}/getting-started/{page-version}/cypher-intro/[Getting Started Guide -> Introduction to Cypher]

The examples below use the clauses xref:clauses/match.adoc[] and clauses/return.adoc[] to find and display the desired graph patterns.
To learn more about these and many other Cypher clauses, see the section on xref:clauses/index.adoc[].

== Nodes

The data entities in a Neo4j knowledge graph are referred to as nodes.
The below query demonstrates the fundamental concepts when querying nodes with Cypher:

[source, cypher]
----
MATCH (p:Person {name:'Keanu Reeves'})
RETURN p.born AS birthYear
----

Nodes are referred to in Cypher using brackets`()`.
Everything inside the brackets is referred to as a node pattern.

This includes: 
* A `Person` label.
A node may have none, one, or several node labels, and they are used as tags to enable the retrieval of specific data entities.
It also includes a `name` property set to `Keanu Reeves`.
Properties are defined within curly brackets, `{}`, and are used to provide nodes with specific information.

The node pattern includes a variable, `p`.
Variables are used to bind a particular node pattern in order that they may be retrieved by subsequent clauses.

In this query, the first `MATCH` clause finds all `Person`nodes in the graph with the `name` property set to `Keanu Reeves`, and binds them to the variable `p`.
The variable `p` is then passed along to the next `RETURN` clause which returns the value of a different property (`born`) belonging to the same bound node.

== Relationships

Nodes in a graph can be connected with relationships.
A relationship must have a start node and an end node.
Relationships are represented in Cypher with dashes (`-`) and arrows (e.g. `-->`).

The below query demonstrates the fundamental concepts when querying relationships with Cypher:

[source, cypher]
----
MATCH (p:Person {name: 'Keanu Reeves'})-[r:ACTED_IN {roles: "Neo"}]->(c:Movie)
RETURN count(r)
----

Unlike nodes, information within a relationship pattern must be enclosed by square brackets.
In this case, the bound relationship pattern from the `Person` nodes to the `Car` nodes in the graph must have the relationship type `OWNS` with the property `since` set to earlier than `2022`. 

Note that while nodes can have several labels, relationships can only have one type.

== Patterns

Graph patterns consists of nodes and relationships and sits at the very core of Cypher.
By applying a declarative path pattern in a query, you can find simple or complex patterns of fixed or varied lengths.
For example:



(m:Person)-[:KNOWS]->(n:Person) WHERE m.born < n.born){1,5}

