<create index statement> ::= 
  "CREATE" <index specification> [ <command options> ]

<command options> ::= 
  "OPTIONS" <map value or parameter specification>

<index specification> ::= 
    <fulltext index>
  | <lookup index>
  | <point index>
  | <range index>
  | <text index>
  | <vector index>

<map value or parameter specification> ::= 
    <map value constructor>
  | <general parameter reference>