<lookup index> ::= 
  "LOOKUP" <index prefix> { <node lookup index for and on> | <relationship lookup index for and on> }

<index prefix> ::= 
  "INDEX" [ <index name> | <general parameter reference> ] [ "IF NOT EXISTS" ]

<node lookup index for and on> ::= 
  "FOR" "(" <binding variable> ")" "ON EACH" <function name> "(" <binding variable> ")"

<relationship lookup index for and on> ::= 
  "FOR" <lookup index relationship pattern> "ON" [ "EACH" ] <function name> "(" <binding variable> ")"

<lookup index relationship pattern> ::= 
  "()" { "<-[" <binding variable> "]-" | "-[" <binding variable> "]->" | "<-[" <binding variable> "]->" | "-[" <binding variable> "]-" } "()"