# create-text-index

<text index> ::= 
  "TEXT" <index prefix> "FOR" { <command node pattern> | <command relationship pattern> } "ON" <property names specification>

<property names specification> ::= 
    <property name specification>
  | "(" <property name specification> [ { "," <property name specification> }... ] ")"

<property name specification> ::= 
  <binding variable> "." <property name>

<index prefix> ::= 
  "INDEX" [ <index name> | <general parameter reference> ] [ "IF NOT EXISTS" ]

<command node pattern> ::= 
  "(" <binding variable> ":" <label name> ")"

<command relationship pattern> ::= 
  "()" { "<-[" <binding variable> ":" <label name> "]-" | "-[" <binding variable> ":" <label name> "]->" | "<-[" <binding variable> ":" <label name> "]->" | "-[" <binding variable> ":" <label name> "]-" } "()"