# create-fulltext-index

<fulltext index> ::= 
  "FULLTEXT" <index prefix> "FOR" { <fulltext index node pattern> | <fulltext index relationship pattern> } "ON EACH" <bracketed property names specification>

<bracketed property names specification> ::= 
  "[" <property name specification> [ { "," <property name specification> }... ] "]"

<property name specification> ::= 
  <binding variable> "." <property name>

<index prefix> ::= 
  "INDEX" [ <index name> | <general parameter reference> ] [ "IF NOT EXISTS" ]

<fulltext index node pattern> ::= 
  "(" <binding variable> ":" <label name> [ { "|" <label name> }... ] ")"

<fulltext index relationship pattern> ::= 
  "()" { "<" <fulltext index relationship body> | <fulltext index relationship body> ">" | "<" <fulltext index relationship body> ">" | <fulltext index relationship body> } "()"

<fulltext index relationship body> ::= 
  "-[" <binding variable> ":" <label name> [ { "|" <label name> }... ] "]-"