# create-vector-index

<vector index> ::= 
  "VECTOR" <index prefix> "FOR" <command element pattern> "ON" <property names specification>

<property names specification> ::= 
    <property name specification>
  | "(" <property name specification> [ { "," <property name specification> }... ] ")"

<property name specification> ::= 
  <binding variable> "." <property name>

<index prefix> ::= 
  "INDEX" [ <index name> | <general parameter reference> ] [ "IF NOT EXISTS" ]

<command element pattern> ::= 
    <command node pattern>
  | <command relationship pattern>

<command node pattern> ::= 
  "(" <binding variable> ":" <label name> ")"

<command relationship pattern> ::= 
  "()" { "<-[" <binding variable> ":" <label name> "]-" | "-[" <binding variable> ":" <label name> "]->" | "<-[" <binding variable> ":" <label name> "]->" | "-[" <binding variable> ":" <label name> "]-" } "()"