<show indexes statement> ::= 
  "SHOW" [ <show index type> ] <index keywords> [ <show result clause> ]

<show index type> ::= 
    "ALL"
  | "FULLTEXT"
  | "LOOKUP"
  | "POINT"
  | "RANGE"
  | "TEXT"
  | "VECTOR"

<show result clause> ::= 
    <show yield result clause>
  | <show where result clause>

<show yield result clause> ::= 
  "YIELD" <yield item list> [ <order by clause> ] [ <offset clause> ] [ <limit clause> ] [ <where clause> ] [ <return statement> ]

<show where result clause> ::= 
  <where clause>

<index keywords> ::= 
    "INDEX"
  | "INDEXES"