:description: Information about using a schema in Neo4j for ensuring data integrity.
= Schema

Neo4j is a natively schema-free database.
This allows for the rapid development of graphs that can continue to evolve and expand by incorporating new sources of data.

You can, however, impose an open schema in Neo4j.
An open schema applies constraints only to the data explicitly included in the schema.
This approach maintains a flexible framework that makes it easy to adapt and grow your data model as new requirements emerge, while also allowing for enforcing the shape of the most stable and established part of the data model.

There are two methods of imposing an open schema in Neo4j:

* xref:schema/graph-types/index.adoc[]: enforces holistically an open schema, providing a defined structure for an entire graph. label:cypher[Cypher 25 only] label:new[Introduced in Neo4j 2025.xx] label:enterprise-edition[]
* xref:schema/constraints/index.adoc[]: enforces specific constraints on node or relationship properties.

[NOTE]
====
All constraints created using the older xref:schema/constraints/create-constraints.adoc[`CREATE CONSTRAINT`] syntax will automatically be added to the graph type of a database.
Not all constraint types can be created using this syntax, however, and maintaining individual constraints can become complicated over time as their number increases.

*It is, therefore, recommended to define a schema using a graph type, which offers both additional, more sophisticated constraint types and a more holistic and simplified approach for constraining and maintaining the shape of the data in a graph.*
====



