:description: Syntax for how to manage graph types and constraints in Neo4j.
:table-caption!:
:page-aliases: constraints/syntax.adoc
= Syntax

This page contains the syntax for the graph types and constraints commands.
More details about the syntax can be found in the link:{neo4j-docs-base-uri}/operations-manual/current/database-administration/syntax/#administration-syntax-reading[Operations Manual -> Cypher syntax for administration commands].

[role=label--cypher-25-only label--enterprise-edition label--new-Neo4j-2025.xx]
[[graph-types]]
== Graph types

[[element-types]]
=== Node and relationship element types

.Syntax for node element types, <node element type>
[source, syntax]
----
([alias] {IS | :} IdentifyingLabelName {=> | IMPLIES} [{IS | :} ImpliedLabelName[&...]] [“{“ {propertyName [[IS] :: | IS TYPED] <TYPE> [IS [NODE] {KEY | UNIQUE}]}[, ...] “}”])
[REQUIRE {alias.propertyName | (alias.propertyName[, ...])} IS [NODE] {KEY | UNIQUE}][...]
----

[NOTE]
A node element type requires either one or more implied labels or a non-empty property map.

For more information, see xref:schema/graph-types/set-graph-types.adoc#node-element-types[Set graph types -> Node element types].

.Syntax for relationship element types, <relationship element type>
[source, syntax]
-----
([nodeAlias | [nodeAlias] {IS | :} LabelName [=> | IMPLIES]])-”[“ [alias] {IS | :} IDENTIFYING_RELATIONSHIP_TYPE {=> | IMPLIES} [“{“ {propertyName [[IS] :: | IS TYPED] <TYPE> [IS [REL[ATIONSHIP]] {KEY | UNIQUE}]}[, ...] “}”] “]”->([nodeAlias | [nodeAlias] {IS | :} LabelName [=> | IMPLIES]])
[REQUIRE {alias.propertyName | (alias.propertyName[, ...])} IS [REL[ATIONSHIP]] {KEY | UNIQUE}][...]
-----

[NOTE]
====
A relationship element type requires either:

* A non-empty source or a target node.
* A non-empty property map.
====

For more information, see xref:schema/graph-types/set-graph-types.adoc#relationship-element-types[Set graph types -> Relationship element types].

`<TYPE>` can be one of the property types listed in xref:schema/syntax.adoc#constraints-definitions[constraint definitions in graph types], the `NOT NULL` versions of those types, or `ANY NOT NULL`.
Allowed syntax variations of these types are listed in xref:values-and-types/property-structural-constructed.adoc#types-synonyms[Values and types -> Types and their synonyms].

The three variations of the property type expression, `IS ::`, `::`, and `IS TYPED` are syntactic synonyms for the same expression.
The preferred syntax when defining node and relationship element types in a graph type is the `::` variant.

[[constraints-definitions]]
=== Constraint definitions in graph types

.Syntax for property uniqueness and key constraints on identifying node labels and relationship types, <constraint on identifying label/type>
[cols="1a, 3a", options="noheader"]
|===
| Property uniqueness and key constraints on labels identifying node element types
a|
[source, syntax]
----
CONSTRAINT [constraint_name]
FOR (alias [{IS \| :} IdentifyingLabelName [=> \| IMPLIES]])
REQUIRE {alias.propertyName \| (alias.propertyName[, ...])} IS [NODE] {KEY \| UNIQUE}
----

| Property uniqueness and key constraints on relationship types identifying relationship element types
a|
[source, syntax]
----
CONSTRAINT [constraint_name]
FOR ()-”[“alias [{IS \| :} IDENTIFYING_RELATIONSHIP_TYPE [=> \| IMPLIES]] “]”->()
REQUIRE {alias.propertyName \| (alias.propertyName[, ...])} IS [REL[ATIONSHIP]] {KEY \| UNIQUE}
----
|===

For more information, see xref:schema/graph-types/set-graph-types.adoc#constraints-on-identifying-labels-and-types[Set graph types -> Property uniqueness and key constraints on identifying node labels and relationship types].

.Syntax for property uniqueness, property existence, property type, and key constraints on non-identifying node labels and relationship types, <constraint on non-identifying label/type>
[cols="1a, 3a", options="noheader"]
|===
| Node key and property uniqueness constraint
a|
[source, syntax]
----
CONSTRAINT [constraint_name]
FOR (alias {IS \| :} NonIdentifyingLabelName)
REQUIRE {alias.propertyName \| (alias.propertyName[, ...])} IS [NODE] {KEY \| UNIQUE}
----

| Node property existence and property type constraint
a|
[source, syntax]
----
CONSTRAINT [constraint_name]
FOR (alias {IS \| :} NonIdentifyingLabelName)
REQUIRE {alias.propertyName \| (alias.propertyName)} { IS NOT NULL \| {[IS] :: \| IS TYPED} <TYPE> }
----

| Relationship key and property uniqueness constraint
a|
[source, syntax]
----
CONSTRAINT [constraint_name]
FOR ()-”[“alias {IS \| :} NON_IDENTIFYING_RELATIONSHIP_TYPE “]”->()
REQUIRE {alias.propertyName \| (alias.propertyName[, ...])} IS [REL[ATIONSHIP]] {KEY \| UNIQUE}
----

| Relationship property existence and property type constraint
a|
[source, syntax]
----
CONSTRAINT [constraint_name]
FOR ()-”[“alias {IS \| :} NON_IDENTIFYING_RELATIONSHIP_TYPE “]”->()
REQUIRE {alias.propertyName \| (alias.propertyName)} { IS NOT NULL \| {[IS] :: \| IS TYPED} <TYPE> }
----
|===

For more information, see see xref:schema/graph-types/set-graph-types.adoc#constraints-on-non-identifying-labels-and-types[Set graph types -> Constraints on non-identifying labels and types].

The three variations of the property type expression, `IS ::`, `::`, and `IS TYPED` are syntactic synonyms for the same expression.
The preferred syntax when defining constraints in a graph type is the `IS ::` variant.

`<TYPE>` can be one of the following property types:

* `BOOLEAN`
* `STRING`
* `INTEGER`
* `FLOAT`
* `DATE`
* `LOCAL TIME`
* `ZONED TIME`
* `LOCAL DATETIME`
* `ZONED DATETIME`
* `DURATION`
* `POINT`
* `LIST<BOOLEAN NOT NULL>`
* `LIST<STRING NOT NULL>`
* `LIST<INTEGER NOT NULL>`
* `LIST<FLOAT NOT NULL>`
* `LIST<DATE NOT NULL>`
* `LIST<LOCAL TIME NOT NULL>`
* `LIST<ZONED TIME NOT NULL>`
* `LIST<LOCAL DATETIME NOT NULL>`
* `LIST<ZONED DATETIME NOT NULL>`
* `LIST<DURATION NOT NULL>`
* `LIST<POINT NOT NULL>`
* Any closed dynamic union of the above types, e.g. `INTEGER | FLOAT | STRING`.

Allowed syntax variations of these types are listed in xref:values-and-types/property-structural-constructed.adoc#types-synonyms[Values and types -> Types and their synonyms].

[[set-graph-types]]
=== Set graph types

[NOTE]
====
Setting a graph type requires the following privileges:

* link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-constraints[`CREATE CONSTRAINT`]
* link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-constraints[`DROP CONSTRAINT`]
* link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-tokens[`NAME MANAGEMENT`] (if graph type includes node labels, relationship types, or properties not already in the graph)
====

.Syntax for `ALTER CURRENT GRAPH TYPE SET`
[source, syntax]
----
ALTER CURRENT GRAPH TYPE SET “{“
  [{<node element type> | <relationship element type> | <constraint on identifying label/type> | <constraint on non-identifying label/type>}[, ...]]
“}”
----

For more information, see xref:schema/graph-types/set-graph-types.adoc[].

[[extend-graph-types]]
=== Extend graph types

[NOTE]
====
Extending a graph type requires the following privileges:

* link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-constraints[`CREATE CONSTRAINT`]
* link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-tokens[`NAME MANAGEMENT`] (if graph type includes node labels, relationship types, or properties not already in the graph)
====

.Syntax for `ALTER CURRENT GRAPH TYPE ADD`
[source, syntax]
----
ALTER CURRENT GRAPH TYPE ADD “{“
  [{<node element type> | <relationship element type> | <constraint on identifying label/type> | <constraint on non-identifying label/type>}[, ...]]
“}”
----

[NOTE]
Any added element types and constraints must, together with the existing ones, form a valid graph type.
This means, for example, that `ADD` cannot modify existing element types but only add new ones.
Independent constraints cannot be added to node labels/relationship types that serve as the identifying labels/types of element types.
Nor can element types be added if their identifying labels/types already have independent constraints defined on them.

For more information, see xref:schema/graph-types/extend-graph-types.adoc[].

[[alter-element-types]]
=== Alter element types

[NOTE]
====
Altering element types in a graph type requires the following privileges:

* link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-constraints[`CREATE CONSTRAINT`]
* link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-constraints[`DROP CONSTRAINT`]
* link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-tokens[`NAME MANAGEMENT`] (if graph type includes node labels, relationship types, or properties not already in the graph)
====

.Syntax for `ALTER CURRENT GRAPH TYPE ALTER`
[source, syntax]
----
ALTER CURRENT GRAPH TYPE ALTER “{“
  [{<node element type> | <relationship element type>}[, ...]]
“}”
----

[NOTE]
====
Note the following:

* Key or property uniqueness constraints cannot be included when altering an element type.
* `ALTER` cannot introduce new element types to the graph type, only modify existing ones.
And it replaces the previous definition of that element type with the new definition.
====

For more information, see xref:schema/graph-types/alter-element-types.adoc[].

[[list-graph-types]]
=== Show graph types

[NOTE]
Showing a graph type requires the link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-constraints[`SHOW CONSTRAINTS` privilege].

.Syntax to list the current graph type with default return columns
[source, syntax]
----
SHOW CURRENT GRAPH TYPE
  [WHERE expression]
----

.Syntax to list the current graph type with full return columns
[source, syntax]
----
SHOW CURRENT GRAPH TYPE 
YIELD { * | field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

For more information, see xref:schema/graph-types/list-graph-types.adoc[].
For full details of the columns returned by the `SHOW CURRENT GRAPH TYPE` command, see xref:schema/graph-types/list-graph-types.adoc#result-columns[Show graph types -> Result columns for `SHOW CURRENT GRAPH TYPE`].

[[drop-graph-type-elements]]
=== Drop graph type elements

[NOTE]
Dropping element types and constraints from a graph type requires the link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-constraints[`DROP CONSTRAINT` privilege].

.Syntax for dropping node element type, <drop node element type>
[cols="1a, 3a", options="noheader"]
|===
| Full definition
a|
[source, syntax]
----
([alias] {IS \| :} IdentifyingLabelName {=> \| IMPLIES} [{IS \| :} ImpliedLabelName[&...]] [“{“ {propertyName [[IS] :: \| IS TYPED] <TYPE>}[, ...] “}”])
----

| Identifying label only
a|
[source, syntax]
----
([alias] {IS \| :} IdentifyingLabelName {=> \| IMPLIES})
----
|===

.Syntax for dropping relationship element type, <drop node relationship type>
[cols="1a, 3a", options="noheader"]
|===
| Full definition
a|
[source, syntax]
----
([nodeAlias \| [nodeAlias] {IS \| :} LabelName [=> \| IMPLIES]])-”[“ [alias] {IS \| :} IDENTIFYING_RELATIONSHIP_TYPE {=> \| IMPLIES} [“{“ {propertyName [[IS] :: \| IS TYPED] <TYPE>}[, ...] “}”] “]”->([nodeAlias \| [nodeAlias] {IS \| :} LabelName [=> \| IMPLIES]])
----

| Identifying type only
a|
[source, syntax]
----
()-”[“ [alias] {IS \| :} IDENTIFYING_RELATIONSHIP_TYPE {=> \| IMPLIES} “]”->()
----
|===

`<TYPE>` can be the same property types as for xref:schema/syntax.adoc#element-types[node and relationship element types].

[NOTE]
If the full definition is provided, then it needs to match exactly the node or relationship element type being dropped.

.Syntax for dropping constraints on identifying or non-identifying labels/types, <drop constraint>
[source, syntax]
----
CONSTRAINT constraint_name
----

.Syntax for `ALTER CURRENT GRAPH TYPE DROP`
[source, syntax]
----
ALTER CURRENT GRAPH TYPE DROP “{“
  [{<drop node element type> | <drop relationship element type> | <drop constraint>}[, ...]]
“}”
----

For more information, see xref:schema/graph-types/drop-graph-type-elements.adoc[].

[[constraints]]
== Constraints

[[create-constraint]]
=== Create constraints

Constraints are created with the `CREATE CONSTRAINT` command.
When creating a constraint, it is recommended to provide a constraint name.
This name must be unique among both indexes and constraints.
If a name is not explicitly given, a unique name will be auto-generated.

[NOTE]
Creating a constraint requires the link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-constraints[`CREATE CONSTRAINT` privilege].

The `CREATE CONSTRAINT` command is optionally idempotent. 
This means its default behavior is to throw an error if an attempt is made to create the same constraint twice.
With the `IF NOT EXISTS` flag, no error is thrown and nothing happens should a constraint with the same name or same schema and constraint type already exist.
It may still throw an error if conflicting data, indexes, or constraints exist.
Examples of this are nodes with missing properties, indexes with the same name, or constraints with same schema but a different conflicting constraint type.
An informational notification is returned in case nothing happens showing the existing constraint which blocks the creation.

[[create-property-uniqueness-constraints]]
==== Create property uniqueness constraints

.Syntax for creating a node property uniqueness constraint on a single property
[source, syntax]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR (n:LabelName)
REQUIRE n.propertyName IS [NODE] UNIQUE
----

.Syntax for creating a composite node property uniqueness constraint on multiple properties
[source, syntax]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR (n:LabelName)
REQUIRE (n.propertyName_1, ..., n.propertyName_n) IS [NODE] UNIQUE
----

.Syntax for creating a relationship property uniqueness constraint on a single property
[source, syntax]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR ()-"["r:RELATIONSHIP_TYPE"]"-()
REQUIRE r.propertyName IS [REL[ATIONSHIP]] UNIQUE
----

.Syntax for creating a composite relationship property uniqueness constraint on multiple properties
[source, syntax]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR ()-"["r:RELATIONSHIP_TYPE"]"-()
REQUIRE (r.propertyName_1, ..., r.propertyName_n) IS [REL[ATIONSHIP]] UNIQUE
----

For examples on how to create property uniqueness constraints, see  xref:schema/constraints/create-constraints.adoc#create-property-uniqueness-constraints[Create constraints -> Create property uniqueness constraint].
Property uniqueness constraints are xref:schema/constraints/create-constraints.adoc#constraints-and-indexes[index-backed].

[role=label--enterprise-edition]
[[create-property-existence-constraints]]
==== Create property existence constraints

.Syntax for creating a node property existence constraint
[source, syntax]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR (n:LabelName)
REQUIRE n.propertyName IS NOT NULL
----

.Syntax for creating a relationship property existence constraint
[source, syntax]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR ()-"["r:RELATIONSHIP_TYPE"]"-()
REQUIRE r.propertyName IS NOT NULL
----

For examples on how to create property existence constraints, see  xref:schema/constraints/create-constraints.adoc#create-property-existence-constraints[Create constraints -> Create property existence constraints].

[role=label--enterprise-edition]
[[create-property-type-constraints]]
==== Create property type constraints

.Syntax for creating a node property type constraint
[source, syntax]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR (n:LabelName)
REQUIRE n.propertyName {[IS] :: | IS TYPED} <TYPE>
----

.Syntax for creating a relationship property type constraint
[source, syntax]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR ()-"["r:RELATIONSHIP_TYPE"]"-()
REQUIRE r.propertyName {[IS] :: | IS TYPED} <TYPE>
----

The three variations of the expression, `IS ::`, `::`, and `IS TYPED` are syntactic synonyms for the same expression.
The preferred syntax is the `IS ::` variant.

Where `<TYPE>` is one of the following property types:

* `BOOLEAN`
* `STRING`
* `INTEGER`
* `FLOAT`
* `DATE`
* `LOCAL TIME`
* `ZONED TIME`
* `LOCAL DATETIME`
* `ZONED DATETIME`
* `DURATION`
* `POINT`
* `LIST<BOOLEAN NOT NULL>`
* `LIST<STRING NOT NULL>`
* `LIST<INTEGER NOT NULL>`
* `LIST<FLOAT NOT NULL>`
* `LIST<DATE NOT NULL>`
* `LIST<LOCAL TIME NOT NULL>`
* `LIST<ZONED TIME NOT NULL>`
* `LIST<LOCAL DATETIME NOT NULL>`
* `LIST<ZONED DATETIME NOT NULL>`
* `LIST<DURATION NOT NULL>`
* `LIST<POINT NOT NULL>`
* Any closed dynamic union of the above types, e.g. `INTEGER | FLOAT | STRING`.

Allowed syntax variations of these types are listed in  xref::values-and-types/property-structural-constructed.adoc#types-synonyms[Types and their synonyms].

For examples on how to create property type constraints, see  xref:schema/constraints/create-constraints.adoc#create-property-type-constraints[Create constraints -> Create property type constraints].


[role=label--enterprise-edition]
[[create-key-constraints]]
==== Create key constraints

.Syntax for creating a node key constraint on a single property
[source, syntax]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR (n:LabelName)
REQUIRE n.propertyName IS [NODE] KEY
----

.Syntax for creating a composite node key constraint on multiple properties
[source, syntax]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR (n:LabelName)
REQUIRE (n.propertyName_1, ..., n.propertyName_n) IS [NODE] KEY
----

.Syntax for creating a relationship key constraint on a single property
[source, syntax]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR ()-"["r:RELATIONSHIP_TYPE"]"-()
REQUIRE r.propertyName IS [REL[ATIONSHIP]] KEY
----

.Syntax for creating a composite relationship key constraint on multiple properties
[source, syntax]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR ()-"["r:RELATIONSHIP_TYPE"]"-()
REQUIRE (r.propertyName_1, ..., r.propertyName_n) IS [REL[ATIONSHIP]] KEY
----

For examples on how to create key constraints, see  xref:schema/constraints/create-constraints.adoc#create-key-constraints[Create constraints -> Create key constraints].
Key constraints are xref:schema/constraints/create-constraints.adoc#constraints-and-indexes[index-backed].


[[list-constraints]]
=== Show constraints

To list all constraints with the default output columns, use `SHOW CONSTRAINTS`.
If all columns are required, use `SHOW CONSTRAINTS YIELD *`.
If only specific columns are required, use `SHOW CONSTRAINTS YIELD field[, ...]`.
The `SHOW CONSTRAINTS` clause can also be filtered using the xref:clauses/where.adoc[`WHERE`] clause.

[NOTE]
Listing constraints requires the link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-constraints[`SHOW CONSTRAINTS` privilege].

.Syntax to list constraints with default return columns
[source, syntax]
----
SHOW [
      ALL
     |NODE [PROPERTY] UNIQUE[NESS]
     |REL[ATIONSHIP] [PROPERTY] UNIQUE[NESS]
     |[PROPERTY] UNIQUE[NESS]
     |NODE [PROPERTY] EXIST[ENCE]
     |REL[ATIONSHIP] [PROPERTY] EXIST[ENCE]
     |[PROPERTY] EXIST[ENCE]
     |NODE PROPERTY TYPE
     |REL[ATIONSHIP] PROPERTY TYPE
     |PROPERTY TYPE
     |NODE KEY
     |REL[ATIONSHIP] KEY
     |KEY
] CONSTRAINT[S]
  [WHERE expression]
----

.Syntax for listing constraints with full return columns
[source, syntax]
----
SHOW [
      ALL
     |NODE [PROPERTY] UNIQUE[NESS]
     |REL[ATIONSHIP] [PROPERTY] UNIQUE[NESS]
     |[PROPERTY] UNIQUE[NESS]
     |NODE [PROPERTY] EXIST[ENCE]
     |REL[ATIONSHIP] [PROPERTY] EXIST[ENCE]
     |[PROPERTY] EXIST[ENCE]
     |NODE PROPERTY TYPE
     |REL[ATIONSHIP] PROPERTY TYPE
     |PROPERTY TYPE
     |NODE KEY
     |REL[ATIONSHIP] KEY
     |KEY
] CONSTRAINT[S]
YIELD { * | field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

The type filtering keywords filters the returned constraints on constraint type:

[[constraints-syntax-list-type-filter]]
.Type filters
[options="header", width="100%", cols="4m,6a"]
|===
| Filter | Description

| ALL
| Returns all constraints, no filtering on constraint type.
This is the default if none is given.

| NODE [PROPERTY] UNIQUE[NESS]
| Returns node property uniqueness constraints.

| REL[ATIONSHIP] [PROPERTY] UNIQUE[NESS]
| Returns relationship property uniqueness constraints.

| [PROPERTY] UNIQUE[NESS]
| Returns property uniqueness constraints, for both nodes and relationships.

| NODE PROPERTY EXIST[ENCE]
| Returns node property existence constraints.

| REL[ATIONSHIP] PROPERTY EXIST[ENCE]
| Returns relationship property existence constraints.

| PROPERTY EXIST[ENCE]
| Returns property existence constraints, for both nodes and relationships.

| NODE EXIST[ENCE]
| Returns node existence constraints.

| REL[ATIONSHIP] EXIST[ENCE]
| Returns relationship existence constraints.

| EXIST[ENCE]
| Returns existence constraints, for both nodes and relationships.

| NODE PROPERTY TYPE
| Returns node property type constraints.

| REL[ATIONSHIP] PROPERTY TYPE
| Returns relationship property type constraints.

| PROPERTY TYPE
| Returns property type constraints, for both nodes and relationships.

| NODE KEY
| Returns node key constraints.

| REL[ATIONSHIP] KEY
| Returns relationship key constraints.

| KEY
| Returns key constraints, for both nodes and relationships.

|===

For examples on how to list constraints, see  xref:schema/constraints/list-constraints.adoc[Show constraints].
For full details of the result columns for the `SHOW CONSTRAINTS` command, see xref:schema/constraints/list-constraints.adoc#list-constraints-result-columns[Show constraints -> Result columns for listing constraints].

[[drop-constraint]]
=== Drop constraints

Constraints are dropped using the `DROP` CONSTRAINT` command.
Dropping a constraint is done by specifying the name of the constraint.

[NOTE]
Dropping a constraint requires the link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-constraints[`DROP CONSTRAINT` privilege].

.Syntax for dropping a constraint by name
[source, syntax]
----
DROP CONSTRAINT constraint_name [IF EXISTS]
----

This command is optionally idempotent.
This means its default behavior is to throw an error if an attempt is made to drop the same constraint twice.
With the `IF EXISTS` flag, no error is thrown and nothing happens should the constraint not exist.
Instead, an informational notification is returned detailing that the constraint does not exist.

For examples on how to drop constraints, see  xref:schema/constraints/drop-constraints.adoc[Drop constraints].