[[administration-databases]]
= Database management
:description: This chapter explains how to use Cypher to manage Neo4j databases: creating, deleting, starting and stopping individual databases within a single server. 

Neo4j supports the management of multiple databases within the same DBMS.
The metadata for these databases, including the associated security model, is maintained in a special database called the `system` database.
All multi-database administrative commands must be run against the `system` database.
These administrative commands are automatically routed to the `system` database when connected to the DBMS over Bolt.

The syntax of the database management commands is as follows:

.Database management command syntax
[options="header", width="100%", cols="1,5a"]
|===
| Command | Syntax
| Show Database
| [source]
SHOW { DATABASE name \| DATABASES \| DEFAULT DATABASE \| HOME DATABASE }
[WHERE expression]

[source]
SHOW { DATABASE name \| DATABASES \| DEFAULT DATABASE \| HOME DATABASE }
YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
| Create Database
| [source]
CREATE DATABASE name [IF NOT EXISTS]
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]

[source]
CREATE OR REPLACE DATABASE name [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
|Stop Database
| [source]
STOP DATABASE name [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
|Start Database
| [source]
START DATABASE name [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
|Drop Database
| [source]
DROP DATABASE name [IF EXISTS] [{DUMP\|DESTROY} [DATA]] [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
|===


[[administration-databases-show-databases]]
== Listing databases

There are three different commands for listing databases. Listing all databases, listing a particular database or listing the default database.

All available databases can be seen using the command `SHOW DATABASES`.


.Query
[source, cypher]
----
SHOW DATABASES
----

.Result
[role="queryresult",options="header,footer",cols="8*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+ | +default+ | +home+
| +"movies"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+ | +false+
| +"neo4j"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +true+ | +true+
| +"northwind-graph"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+ | +false+
| +"system"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+ | +false+
8+d|Rows: 4
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
SHOW DATABASES
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Note that the results of this command are filtered according to the `ACCESS` privileges the user has.
However, a user with `CREATE/DROP DATABASE` or `DATABASE MANAGEMENT` privileges can see all databases regardless of their `ACCESS` privileges.
If a user has not been granted `ACCESS` privilege to any databases, the command can still be executed but will only return the `system` database, which is always visible.


====

The number of databases can be seen using a `count()` aggregation with `YIELD` and `RETURN`.


.Query
[source, cypher]
----
SHOW DATABASES YIELD * RETURN count(*) as count
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +count+
| +4+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
SHOW DATABASES YIELD * RETURN count(*) as count
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

A particular database can be seen using the command `SHOW DATABASE name`.


.Query
[source, cypher]
----
SHOW DATABASE system
----

.Result
[role="queryresult",options="header,footer",cols="8*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+ | +default+ | +home+
| +"system"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+ | +false+
8+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
SHOW DATABASE system
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The default database can be seen using the command `SHOW DEFAULT DATABASE`.


.Query
[source, cypher]
----
SHOW DEFAULT DATABASE
----

.Result
[role="queryresult",options="header,footer",cols="6*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+
| +"neo4j"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+
6+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
SHOW DEFAULT DATABASE
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The home database for the current user can be seen using the command `SHOW HOME DATABASE`.


.Query
[source, cypher]
----
SHOW HOME DATABASE
----

.Result
[role="queryresult",options="header,footer",cols="6*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+
| +"neo4j"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+
6+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
SHOW HOME DATABASE
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

It is also possible to filter and sort the results by using `YIELD`, `ORDER BY` and `WHERE`.


.Query
[source, cypher]
----
SHOW DATABASES YIELD name, currentStatus, requestedStatus ORDER BY currentStatus WHERE name CONTAINS 'e'
----

In this example:

* The number of columns returned has been reduced with the `YIELD` clause.
* The order of the returned columns has been changed.
* The results have been filtered to only show database names containing 'e'.
* The results are ordered by the 'currentStatus' column using `ORDER BY`.

It is also possible to use `SKIP` and `LIMIT` to paginate the results.


.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| +name+ | +currentStatus+ | +requestedStatus+
| +"neo4j"+ | +"online"+ | +"online"+
| +"system"+ | +"online"+ | +"online"+
| +"movies"+ | +"online"+ | +"online"+
3+d|Rows: 3
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
SHOW DATABASES YIELD name, currentStatus, requestedStatus ORDER BY currentStatus WHERE name CONTAINS 'e'
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Note that for failed databases, the `currentStatus` and `requestedStatus` are different.
This often implies an error, but **does not always**.
For example, a database may take a while to transition from `offline` to `online` due to performing recovery.
Or, during normal operation a database's `currentStatus` may be transiently different from its `requestedStatus` due to a necessary automatic process, such as one Neo4j instance copying store files from another.
The possible statuses are `initial`, `online`, `offline`, `store copying` and `unknown`.


====

[role=enterprise-edition]
[[administration-databases-create-database]]
== Creating databases

Databases can be created using `CREATE DATABASE`.


.Query
[source, cypher]
----
CREATE DATABASE customers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
CREATE DATABASE customers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Database names are subject to the xref:syntax/naming.adoc[standard Cypher restrictions on valid identifiers].
The following naming rules apply:


* Database name length must be between 3 and 63 characters.
* The first character must be an ASCII alphabetic character.
* Subsequent characters can be ASCII alphabetic (`mydatabase`), numeric characters (`mydatabase2`), dots (`main.db`), and dashes (enclosed within backticks, e.g., `CREATE DATABASE ++`main-db`++`).
* Names cannot end with dots or dashes.
* Names that begin with an underscore or with the prefix `system` are reserved for internal use.
          


====

When a database has been created, it will show up in the listing provided by the command `SHOW DATABASES`.


.Query
[source, cypher]
----
SHOW DATABASES
----

.Result
[role="queryresult",options="header,footer",cols="8*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+ | +default+ | +home+
| +"customers"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+ | +false+
| +"movies"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+ | +false+
| +"neo4j"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +true+ | +true+
| +"northwind-graph"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+ | +false+
| +"system"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+ | +false+
8+d|Rows: 5
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
SHOW DATABASES
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[role=enterprise-edition]
[[administration-databases-create-database-existing]]
=== Handling Existing Databases

This command is optionally idempotent, with the default behavior to throw an exception if the database already exists. Appending `IF NOT EXISTS` to the command will ensure that no exception is thrown and nothing happens should the database already exist. Adding `OR REPLACE` to the command will result in any existing database being deleted and a new one created.


.Query
[source, cypher]
----
CREATE DATABASE customers IF NOT EXISTS
----

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
CREATE DATABASE customers IF NOT EXISTS
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
CREATE OR REPLACE DATABASE customers
----

This is equivalent to running `DROP DATABASE customers IF EXISTS` followed by `CREATE DATABASE customers`.

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
CREATE OR REPLACE DATABASE customers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
The `IF NOT EXISTS` and `OR REPLACE` parts of this command cannot be used together.


====

[role=enterprise-edition]
[[administration-databases-create-database-options]]
=== Options

The create database command can have a map of options, e.g. `OPTIONS { key : 'value'}`


[options="header"]
|===
| Key | Value | Description
| `existingData` | `use` | Controls how the system handles existing data on disk when creating the database.
Currently this is only supported with `existingDataSeedInstance` and must be set to `use` which indicates the existing data files should be used for the new database.
| `existingDataSeedInstance` | instance ID of the cluster node | Defines which instance is used for seeding the data of the created database.
The instance id can be taken from the id column of the `dbms.cluster.overview()` procedure. Can only be used in clusters.
|===


[NOTE]
====
The `existingData` and `existingDataSeedInstance` options cannot be combined with the `OR REPLACE` part of this command.


====

[role=enterprise-edition]
[[administration-databases-stop-database]]
== Stopping databases

Databases can be stopped using the command `STOP DATABASE`.


.Query
[source, cypher]
----
STOP DATABASE customers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
STOP DATABASE customers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The status of the stopped database can be seen using the command `SHOW DATABASE name`.


.Query
[source, cypher]
----
SHOW DATABASE customers
----

.Result
[role="queryresult",options="header,footer",cols="8*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+ | +default+ | +home+
| +"customers"+ | +"localhost:7687"+ | +"standalone"+ | +"offline"+ | +"offline"+ | +""+ | +false+ | +false+
8+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
SHOW DATABASE customers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[role=enterprise-edition]
[[administration-databases-start-database]]
== Starting databases

Databases can be started using the command `START DATABASE`.


.Query
[source, cypher]
----
START DATABASE customers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
START DATABASE customers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The status of the started database can be seen using the command `SHOW DATABASE name`.


.Query
[source, cypher]
----
SHOW DATABASE customers
----

.Result
[role="queryresult",options="header,footer",cols="8*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+ | +default+ | +home+
| +"customers"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+ | +false+
8+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
SHOW DATABASE customers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[role=enterprise-edition]
[[administration-databases-drop-database]]
== Deleting databases

Databases can be deleted using the command `DROP DATABASE`.


.Query
[source, cypher]
----
DROP DATABASE customers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
DROP DATABASE customers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

When a database has been deleted, it will no longer show up in the listing provided by the command `SHOW DATABASES`.


.Query
[source, cypher]
----
SHOW DATABASES
----

.Result
[role="queryresult",options="header,footer",cols="8*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+ | +default+ | +home+
| +"movies"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+ | +false+
| +"neo4j"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +true+ | +true+
| +"northwind-graph"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+ | +false+
| +"system"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+ | +false+
8+d|Rows: 4
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
SHOW DATABASES
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

This command is optionally idempotent, with the default behavior to throw an exception if the database does not exists. Appending `IF EXISTS` to the command will ensure that no exception is thrown and nothing happens should the database not exist.


.Query
[source, cypher]
----
DROP DATABASE customers IF EXISTS
----

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
DROP DATABASE customers IF EXISTS
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The `DROP DATABASE` command will remove a database entirely. However, you can request that a dump of the store files is produced first, and stored in the path configured using the `dbms.directories.dumps.root` setting (by default `<neo4j-home>/data/dumps`). This can be achieved by appending `DUMP DATA` to the command (or `DESTROY DATA` to explicitly request the default behavior). These dumps are equivalent to those produced by `neo4j-admin dump` and can be similarly restored using `neo4j-admin load`.


.Query
[source, cypher]
----
DROP DATABASE customers DUMP DATA
----

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
DROP DATABASE customers DUMP DATA
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The options `IF EXISTS` and  `DUMP DATA`/ `DESTROY DATA` can also be combined. An example could look like this:


.Query
[source, cypher]
----
DROP DATABASE customers IF EXISTS DUMP DATA
----

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
DROP DATABASE customers IF EXISTS DUMP DATA
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[role=enterprise-edition]
[[administration-wait-nowait]]
== Wait options

Aside from `SHOW DATABASES`, all database management commands accept an optional
`WAIT`/`NOWAIT` clause. The `WAIT`/`NOWAIT` clause allows you to specify a time limit in 
which the command must complete and return. The options are:

* `WAIT n SECONDS` - Return once completed or when the specified time limit of `n` seconds is up.
* `WAIT` - Return once completed or when the default time limit of 300 seconds is up.
* `NOWAIT` - Return immediately.

A command using a `WAIT` clause will automatically commit the current transaction when it executes successfully, as the
command needs to run immediately for it to be possible to `WAIT` for it to complete. Any subsequent commands executed will
therefore be performed in a new transaction. This is different to the usual transactional behavior, and for this reason
it is recommended that these commands be run in their own transaction. The default behavior is `NOWAIT`, so if no clause
is specified the transaction will behave normally and the action is performed in the background post-commit.


.Query
[source, cypher]
----
CREATE DATABASE slow WAIT 5 SECONDS
----

.Result
[role="queryresult",options="header,footer",cols="4*<m"]
|===
| +address+ | +state+ | +message+ | +success+
| +"localhost:7687"+ | +"CaughtUp"+ | +"caught up"+ | +true+
4+d|Rows: 1
|===

The `success` column provides an aggregate status of whether or not the command is considered
successful and thus every row will have the same value. The intention of this column is to make it
easy to determine, for example in a script, whether or not the command completed successfully without
timing out.

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE DATABASE `movies`
CREATE DATABASE `northwind-graph`

]]></database><command><![CDATA[
CREATE DATABASE slow WAIT 5 SECONDS
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
A command with a `WAIT` clause may be interrupted whilst it is waiting to complete. In this event
the command will continue to execute in the background and will not be aborted.


====

