:description: Cypher is a graph query language that is constantly evolving.

[[cypher-deprecations-additions-removals-compatibility]]
= Deprecations, additions and compatibility

[abstract]
--
Cypher is a graph query language that is constantly evolving.
New features are added to the language continuously, and occasionally, some features become deprecated and are subsequently removed.
--

This section list all of the features that have been removed, deprecated, added, or extended in different Cypher versions.
Replacement syntax for deprecated and removed features are also indicated.


[[cypher-deprecations-additions-removals-5.0]]
== Version 5.0


=== Removed features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:functionality[]
label:removed[]
[source, cypher, role="noheader"]
----
CYPHER 3.5
...
----
a|
The ability to specify a cypher version has been removed.

* Prepending a query with a cypher version option (for example `CYPHER 3.5`) has been removed.
* The configuration `cypher.default_language_version` has been removed.


a|
label:functionality[]
label:removed[]
[source, cypher, role="noheader"]
----
DROP INDEX ON :Label(prop)
----
a|
The ability to drop an index based on the schema has been removed.

Use the command to drop an index by the name of the index instead, `DROP INDEX index_name`.


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
CREATE INDEX ON :Label(prop)
----
a|
Deprecated syntax for creating an index has been removed.

Replaced by:
[source, cypher, role="noheader"]
----
CREATE INDEX FOR (n:Label) ON (n.prop)
----


a|
label:functionality[]
label:removed[]

[source, cypher, role="noheader", indent=0]
----
DROP CONSTRAINT ON (n:Label) ASSERT (n.prop) IS NODE KEY
----

[source, cypher, role="noheader", indent=0]
----
DROP CONSTRAINT ON (n:Label) ASSERT (n.prop) IS UNIQUE
----

[source, cypher, role="noheader", indent=0]
----
DROP CONSTRAINT ON (n:Label) ASSERT exists(n.prop)
----

[source, cypher, role="noheader", indent=0]
----
DROP CONSTRAINT ON ()-[r:Type]-() ASSERT exists(r.prop)
----
a|
The ability to drop a constraint based on the schema has been removed.

Use the command to drop a constraint by the name of the constraint instead, `DROP CONSTRAINT constraint_name`.


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT ON ... ASSERT ...
----
a|
Deprecated syntax for creating a constraint has been removed.

Replaced by:
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT FOR ... REQUIRE ...
----


a|
label:functionality[]
label:removed[]
[source, cypher, role="noheader"]
----
CREATE BTREE INDEX ...
----
.2+.^a|
B-tree indexes are removed.

B-tree indexes used for string queries are replaced by:

[source, cypher, role="noheader"]
----
CREATE TEXT INDEX ...
----

B-tree indexes used for spatial queries are replaced by:

[source, cypher, role="noheader"]
----
CREATE POINT INDEX ...
----

B-tree indexes used for general queries or property value types are replaced by:

[source, cypher, role="noheader"]
----
CREATE [RANGE] INDEX ...
----

These new indexes may be combined for multiple use cases.

a|
label:functionality[]
label:removed[]
[source, cypher, role="noheader"]
----
CREATE INDEX ...
OPTIONS "{" btree-option: btree-value[, ...] "}"
----


a|
label:functionality[]
label:removed[]
[source, cypher, role="noheader"]
----
SHOW BTREE INDEXES
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW {POINT \| RANGE \| TEXT} INDEXES
----

B-tree indexes are removed.


a|
label:functionality[]
label:removed[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT
...
OPTIONS "{" btree-option: btree-value[, ...] "}"
----
a|
Node key and uniqueness constraints backed by B-tree indexes are removed.

Replaced by:
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT ...
----

Constraints used for string properties require an additional text index to cover the string queries properly.
Constraints used for point properties require an additional point index to cover the spatial queries properly.

|
label:functionality[]
label:removed[]
[source, cypher, role="noheader"]
----
SHOW INDEXES YIELD uniqueness
----
a|
The `uniqueness` output has been removed along with the concept of index uniqueness, as it actually belongs to the constraint and not the index.

The new output `owningConstraint` was introduced to indicate whether an index belongs to a constraint or not.


a|
label:functionality[]
label:removed[]
[source, cypher, role="noheader"]
----
SHOW CONSTRAINTS YIELD ownedIndexId
----
a|
The `ownedIndexId` output has been removed and replaced by the new `ownedIndex` output.


a|
label:functionality[]
label:removed[]
[source, cypher, role="noheader"]
----
USING BTREE INDEX
----
a|
B-tree index (`BTREE INDEX`) has been removed.

Replaced by:
[source, cypher, role="noheader"]
----
USING {POINT \| RANGE \| TEXT} INDEX
----


a|
label:functionality[]
label:removed[]
[source, cypher, role="noheader"]
----
distance(n.prop, point({x:0, y:0})
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
point.distance(n.prop, point({x:0, y:0})
----


a|
label:functionality[]
label:removed[]
[source, cypher, role="noheader"]
----
point({x:0, y:0}) <= point({x:1, y:1}) <= point({x:2, y:2})
----
a|
The ability to use operators `+<+`, `+<=+`, `+>+`, and `+>=+` on spatial points is removed.

Instead, use:
[source, cypher, role="noheader"]
----
point.withinBBox(point({x:1, y:1}), point({x:0, y:0}), point({x:2, y:2}))
----


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
USING PERIODIC COMMIT ...
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
CALL {
  ...
} IN TRANSACTIONS
----


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
CREATE (a {prop:7})-[r:R]->(b {prop: a.prop})
----
a|
It is no longer allowed to have `CREATE` clauses in which a variable introduced in the pattern is also referenced from the same pattern.


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
CALL { RETURN 1 }
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
CALL { RETURN 1 AS one }
----

Unaliased expressions are no longer supported in subquery `RETURN` clauses.


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
MATCH (a) RETURN (a)--()
----
a|
Pattern expressions producing lists of paths are no longer supported, but they can still be used as existence predicates, for example in `WHERE` clauses.

Instead, use a pattern comprehension:
[source, cypher, role="noheader"]
----
MATCH (a) RETURN [p=(a)--() \| p]
----


a|
label:functionality[]
label:removed[]
[source, cypher, role="noheader"]
----
MATCH (n) RETURN n.propertyName_1, n.propertyName_2 + count(*)
----
a|
Implied grouping keys are no longer supported.
Only expressions that do _not_ contain aggregations are still considered grouping keys.

In expressions that contain aggregations, the leaves must be either:

- An aggregation.
- A literal.
- A parameter.
- A variable, *ONLY IF* it is either: +
1) A projection expression on its own (e.g. the `n` in `RETURN n AS myNode, n.value + count(*)`). +
2) A local variable in the expression (e.g the `x` in `RETURN n, n.prop + size([ x IN range(1, 10) \| x ]`).
- Property access, *ONLY IF* it is also a projection expression on its own (e.g. the `n.prop` in `RETURN n.prop, n.prop + count(*)`).
- Map access, *ONLY IF* it is also a projection expression on its own (e.g. the `map.prop` in `WITH {prop: 2} AS map RETURN map.prop, map.prop + count(*)`).


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
SHOW INDEXES BRIEF
----
a|
The keyword `BRIEF` for the command `SHOW INDEXES` has been removed.

Replaced by:
[source, cypher, role="noheader"]
----
SHOW INDEXES
----


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
SHOW INDEXES VERBOSE
----
a|
The keyword `VERBOSE` for the command `SHOW INDEXES` has been removed.

Replaced by:
[source, cypher, role="noheader"]
----
SHOW INDEXES YIELD *
----


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
SHOW CONSTRAINTS BRIEF
----
a|
The keyword `BRIEF` for the command `SHOW CONSTRAINTS` has been removed.

Replaced by:
[source, cypher, role="noheader"]
----
SHOW CONSTRAINTS
----


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
SHOW CONSTRAINTS VERBOSE
----
a|
The keyword `VERBOSE` for the command `SHOW CONSTRAINTS` has been removed.

Replaced by:
[source, cypher, role="noheader"]
----
SHOW CONSTRAINTS YIELD *
----


a|
label:syntax[]
label:removed[]

[source, cypher, role="noheader"]
----
SHOW EXISTS CONSTRAINTS
----

[source, cypher, role="noheader"]
----
SHOW NODE EXISTS CONSTRAINTS
----

[source, cypher, role="noheader"]
----
SHOW RELATIONSHIP EXISTS CONSTRAINTS
----
a|
Replaced by:

[source, cypher, role="noheader"]
----
SHOW [PROPERTY] EXIST[ENCE] CONSTRAINTS
----

[source, cypher, role="noheader"]
----
SHOW NODE [PROPERTY] EXIST[ENCE] CONSTRAINTS
----

[source, cypher, role="noheader"]
----
SHOW REL[ATIONSHIP] [PROPERTY] EXIST[ENCE] CONSTRAINTS
----


a|
label:syntax[]
label:removed[]

For privilege commands:
[source, cypher, role="noheader"]
----
ON DEFAULT DATABASE
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
ON HOME DATABASE
----


a|
label:syntax[]
label:removed[]

For privilege commands:
[source, cypher, role="noheader"]
----
ON DEFAULT GRAPH
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
ON HOME GRAPH
----


a|
label:procedure[]
label:removed[]

[source, cypher, role="noheader"]
----
dbms.procedures
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW PROCEDURE[S]
[EXECUTABLE [BY {CURRENT USER \| username}]]
[YIELD ...]
[WHERE ...]
[RETURN ...]
----


a|
label:procedure[]
label:removed[]

[source, cypher, role="noheader"]
----
dbms.functions
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW [ALL \| BUILT IN \| USER DEFINED] FUNCTION[S]
[EXECUTABLE [BY {CURRENT USER \| username}]]
[YIELD ...]
[WHERE ...]
[RETURN ...]
----


a|
label:procedure[]
label:removed[]

[source, cypher, role="noheader"]
----
dbms.listTransactions
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW TRANSACTION[S] [transaction-id[,...]]
[YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----


a|
label:procedure[]
label:removed[]

[source, cypher, role="noheader"]
----
dbms.killTransaction
----

[source, cypher, role="noheader"]
----
dbms.killTransactions
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
TERMINATE TRANSACTION[S] transaction-id[,...]
----


a|
label:procedure[]
label:removed[]

[source, cypher, role="noheader"]
----
dbms.listQueries
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW TRANSACTION[S] [transaction-id[,...]]
[YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----


a|
label:procedure[]
label:removed[]

[source, cypher, role="noheader"]
----
dbms.killQuery
----

[source, cypher, role="noheader"]
----
dbms.killQueries
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
TERMINATE TRANSACTION[S] transaction-id[,...]
----


a|
label:functionality[]
label:removed[]
[source, cypher, role="noheader"]
----
SHOW TRANSACTIONS YIELD allocatedBytes
----
a|
The `allocatedBytes` output has been removed, because it was never tracked and thus was always `0`.


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
0...
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
0o...
----

An octal is prepended with `0o`.

For example: `0o1372`, `-0o5671`.

a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
0X...
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
0x...
----

A hexadecimal is prepended with `0x`.

Only `+0x...+` (lowercase x) is supported.

For example: `0x13af`, `0xFC3A9`, `-0x66eff`.


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
WHERE [1, 2, 3]
----
a|
Automatic coercion of a list to a boolean is removed.

Replaced by:
[source, cypher, role="noheader"]
----
WHERE NOT isEmpty([1, 2, 3])
----


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
MATCH ()-[r]-()
RETURN [ ()-[r]-()-[r]-() \| r ] AS rs
----
a|
Remaining support for repeated relationship variables is removed.


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
exists(prop)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
prop IS NOT NULL
----

Check if a property is not `null`.

a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
NOT exists(prop)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
prop IS NULL
----

Check if a property is `null`.

|===


=== Deprecated features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
MATCH (n)-[r:REL]->(m)
SET n = r
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
MATCH (n)-[r:REL]->(m)
SET n = properties(r)
----

The `SET` clause can be used with a map -- provided as a literal or a parameter -- to set properties.

Use the `properties()` function instead to get the map of properties of nodes/relationships that can then be used in a `SET` clause.


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
MATCH (a), (b), allShortestPaths((a)-[r]->(b)) RETURN b

MATCH (a), (b), shortestPath((a)-[r]->(b)) RETURN b
----
a|
The `shortestPath` and `allShortestPaths` functions without xref::syntax/patterns.adoc#cypher-pattern-varlength[variable-length relationship] are deprecated.

Instead, use a `MATCH` with a `LIMIT` of `1` or:

[source, cypher, role="noheader"]
----
MATCH (a), (b), shortestPath((a)-[r*1..1]->(b)) RETURN b
----


a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
id(node_or_relationship)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
elementId(node_or_relationship)
----

The function `elementId` returns an ID for the given input value (node or relationship).

|===


// === Restricted features


=== Updated features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
CREATE INDEX ...
----
a|
The default index type is changed from B-tree to range index.


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW TRANSACTIONS YIELD *
----
a|
New outputs for the `+SHOW TRANSACTIONS YIELD *+` command.

* `currentQueryStartTime`
* `currentQueryStatus`
* `currentQueryActiveLockCount`
* `currentQueryElapsedTime`
* `currentQueryCpuTime`
* `currentQueryWaitTime`
* `currentQueryIdleTime`
* `currentQueryAllocatedBytes`
* `currentQueryPageHits`
* `currentQueryPageFaults`


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
TERMINATE TRANSACTION[S] transaction-id[,...]
YIELD { * \| field[, ...] }
[ORDER BY field[, ...]]
[SKIP n]
[LIMIT n]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----
a|
The `TERMINATE TRANSACTIONS` command now allows yielding (`YIELD`) outputs.

Note for the `TERMINATE TRANSACTIONS` command; when using the `WHERE` or `RETURN` clauses, the `YIELD` clause is mandatory and must not be omitted.


a|
label:functionality[]
label:updated[]

[source, cypher, role="noheader"]
----
SHOW TRANSACTIONS [transaction-id[,...]]
----

[source, cypher, role="noheader"]
----
TERMINATE TRANSACTIONS transaction-id[,...]
----

a|
`transaction-id` now allows general expressions resolving to a string or a list of strings instead of just parameters.


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW TRANSACTIONS [transaction-id[,...]]
YIELD field[, ...]
  [ORDER BY field[, ...]]
  [SKIP n]
  [LIMIT n]
  [WHERE expression]
TERMINATE TRANSACTIONS transaction-id[,...]
YIELD field[, ...]
  [ORDER BY field[, ...]]
  [SKIP n]
  [LIMIT n]
  [WHERE expression]
RETURN field[, ...]
  [ORDER BY field[, ...]]
  [SKIP n]
  [LIMIT n]
----
a|
The `SHOW` and `TERMINATE TRANSACTIONS` commands can be combined in the same query.
The query does not require a specific order and there can be zero or more of each command type, however at least one command is needed.

When the command is not in standalone mode, the `YIELD` and `RETURN` clauses are mandatory.
`+YIELD *+` is not allowed.

`transaction-id` is a comma-separated list of one or more quoted strings.
It could also be an expression resolving to a string or a list of strings (for example the output column from `SHOW`).


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
GRANT EXECUTE BOOSTED PROCEDURE ...
----
a|
This is not a syntax change but a semantic one.

The `EXECUTE BOOSTED PROCEDURE` privilege will no longer include an implicit `EXECUTE PROCEDURE` privilege when granted.

For a role to be able to execute a procedure with boosted privileges both `EXECUTE PROCEDURE` and `EXECUTE BOOSTED PROCEDURE` are needed.


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
GRANT EXECUTE BOOSTED FUNCTION ...
----
a|
This is not a syntax change but a semantic one.

The `EXECUTE BOOSTED FUNCTION` privilege will no longer include an implicit `EXECUTE FUNCTION` privilege when granted.

For a role to be able to execute a function with boosted privileges both `EXECUTE FUNCTION` and `EXECUTE BOOSTED FUNCTION` are needed.


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW INDEXES
----
a|
The new output `owningConstraint` was added and will be returned by default from now on.

The output `owningConstraint` list the name of the constraint that the index is associated with or `null`, in case it is not associated with any constraint.


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW CONSTRAINTS
----
a|
The new output `ownedIndex` was added and will be returned by default from now on.

The output `ownedIndex` list the name of the index associated with the constraint or `null`, in case no index is associated with it.

a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW DATABASES YIELD *
----
a|
New outputs has been added.

* `creationTime` -- The date and time at which the database was created.
* `lastStartTime` -- The date and time at which the database was last started.
* `lastStopTime` -- The date and time at which the database was last stopped.
* `store` -- Information about the storage engine and the store format.

These outputs are returned in the full result set (`+YIELD *+`) and not by default.

|===


=== New features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:syntax[]
label:added[]
[source, cypher, role="noheader"]
----
1_000_000, 0x_FF_FF, 0o_88_88
----
a|
Cypher now supports number literals with underscores between digits.

a|
label:functionality[]
label:added[]
[source, cypher, role="noheader"]
----
isNaN(value)
----
a|
The new function `isNaN` returns `true` if the given numeric value is `NaN` (Not a Number).


a|
label:functionality[]
label:added[]
[source, cypher, role="noheader"]
----
elementId(node_or_relationship)
----
a|
The new function `elementId` returns an ID for the given input value (node or relationship).

|===



[[cypher-deprecations-additions-removals-4.4]]
== Version 4.4


=== Deprecated features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
MATCH (n) RETURN n.propertyName_1, n.propertyName_2 + count(*)
----
a|
Implied grouping keys are deprecated.
Only expressions that do _not_ contain aggregations are still considered grouping keys.

In expressions that contain aggregations, the leaves must be either:

- An aggregation.
- A literal.
- A parameter.
- A variable, *ONLY IF* it is either: +
1) A projection expression on its own (e.g. the `n` in `RETURN n AS myNode, n.value + count(*)`). +
2) A local variable in the expression (e.g the `x` in `RETURN n, n.prop + size([ x IN range(1, 10) \| x ]`).
- Property access, *ONLY IF* it is also a projection expression on its own (e.g. the `n.prop` in `RETURN n.prop, n.prop + count(*)`).
- Map access, *ONLY IF* it is also a projection expression on its own (e.g. the `map.prop` in `WITH {prop: 2} AS map RETURN map.prop, map.prop + count(*)`).


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
USING PERIODIC COMMIT ...
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
CALL {
  ...
} IN TRANSACTIONS
----


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
CREATE (a {prop:7})-[r:R]->(b {prop: a.prop})
----
a|
`CREATE` clauses in which a variable introduced in the pattern is also referenced from the same pattern are deprecated.


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT ON ... ASSERT ...
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT FOR ... REQUIRE ...
----

a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
CREATE BTREE INDEX ...
----
.2+.^a|
B-tree indexes are deprecated.

B-tree indexes used for string queries are replaced by:
[source, cypher, role="noheader"]
----
CREATE TEXT INDEX ...
----

B-tree indexes used for spatial queries are replaced by:
[source, cypher, role="noheader"]
----
CREATE POINT INDEX ...
----

B-tree indexes used for general queries or property value types will be replaced by:
[source, cypher, role="noheader"]
----
CREATE RANGE INDEX ...
----

These new indexes may be combined for multiple use cases.

a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
CREATE INDEX
...
OPTIONS "{" btree-option: btree-value[, ...] "}"
----


a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
SHOW BTREE INDEXES
----
a|
B-tree indexes are deprecated.

Replaced by the new and future index types:
[source, cypher, role="noheader"]
----
SHOW {POINT \| RANGE \| TEXT} INDEXES
----


a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
USING BTREE INDEX
----
a|
B-tree indexes are deprecated.

Replaced by:
[source, cypher, role="noheader"]
----
USING {POINT \| RANGE \| TEXT} INDEX
----


a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT
...
OPTIONS "{" btree-option: btree-value[, ...] "}"
----
a|
Node key and uniqueness constraints with b-tree options are deprecated and will be replaced in 5.0 by range options, see xref::indexes-for-search-performance.adoc[].
In 4.4, the b-tree index-backed constraints are still the correct alternative to use.

Replaced by:
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT
...
OPTIONS "{" range-option: range-value[, ...] "}"
----
Constraints used for string properties will also require an additional text index to cover the string queries properly.
Constraints used for point properties will also require an additional point index to cover the spatial queries properly.


a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
distance(n.prop, point({x:0, y:0})
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
point.distance(n.prop, point({x:0, y:0})
----

a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
point({x:0, y:0}) <= point({x:1, y:1}) <= point({x:2, y:2})
----
a|
Using inequality operators `<`, `+<=+`, `>`, and `+>=+` on spatial points is deprecated.
Please instead use:
[source, cypher, role="noheader"]
----
point.withinBBox(point({x:1, y:1}), point({x:0, y:0}), point({x:2, y:2}))
----


a|
label:procedure[]
label:deprecated[]

[source, cypher, role="noheader"]
----
dbms.listTransactions
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW TRANSACTION[S] [transaction-id[,...]]
[YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----


a|
label:procedure[]
label:deprecated[]

[source, cypher, role="noheader"]
----
dbms.killTransaction
----

[source, cypher, role="noheader"]
----
dbms.killTransactions
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
TERMINATE TRANSACTION[S] transaction-id[,...]
----


a|
label:procedure[]
label:deprecated[]

[source, cypher, role="noheader"]
----
dbms.listQueries
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW TRANSACTION[S] [transaction-id[,...]]
[YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----


a|
label:procedure[]
label:deprecated[]

[source, cypher, role="noheader"]
----
dbms.killQuery
----

[source, cypher, role="noheader"]
----
dbms.killQueries
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
TERMINATE TRANSACTION[S] transaction-id[,...]
----

|===


=== New features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CALL {
  ...
} IN TRANSACTIONS
----
a|
New clause for evaluating a subquery in separate transactions.
Typically used when modifying or importing large amounts of data.
See xref::clauses/call-subquery.adoc#subquery-call-in-transactions[`+CALL { ... } IN TRANSACTIONS+`].

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT FOR ... REQUIRE ...
----
a|
New syntax for creating constraints, applicable to all constraint types.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR (n:LabelName)
REQUIRE (n.propertyName_1, …, n.propertyName_n) IS UNIQUE
[OPTIONS "{" option: value[, ...] "}"]
----
a|
Unique property constraints now allow multiple properties, ensuring that the combination of property values are unique.

a|
label:functionality[]
label:new[]
label:deprecated[]
[source, cypher, role="noheader"]
----
DROP CONSTRAINT
ON (n:LabelName)
ASSERT (n.propertyName_1, ..., n.propertyName_n) IS UNIQUE
----
a|
Unique property constraints now allow multiple properties.

Replaced by:
[source, cypher, role="noheader"]
----
DROP CONSTRAINT name [IF EXISTS]
----

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR ...
REQUIRE ... IS NOT NULL
OPTIONS "{" "}"
----
a|
Existence constraints now allow an `OPTIONS` map, however, at this point there are no available values for the map.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE LOOKUP INDEX [index_name] [IF NOT EXISTS]
FOR ... ON ...
OPTIONS "{" option: value[, ...] "}"
----
a|
Lookup indexes now allow an `OPTIONS` map to specify the index provider.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE TEXT INDEX ...
----
a|
Allows creating text indexes on nodes or relationships with a particular label or relationship type, and property combination.
They can be dropped by using their name.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE RANGE INDEX ...
----
a|
Allows creating range indexes on nodes or relationships with a particular label or relationship type, and properties combination.
They can be dropped by using their name.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT
...
OPTIONS "{" indexProvider: 'range-1.0' "}"
----
a|
Allows creating node key and uniqueness constraints backed by range indexes by providing the range index provider in the `OPTIONS` map.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE POINT INDEX ...
----
a|
Allows creating point indexes on nodes or relationships with a particular label or relationship type, and property combination.
They can be dropped by using their name.

a|
label:syntax[]
label:new[] +
New privilege:
[source, cypher, role="noheader"]
----
IMPERSONATE
----
a|
New privilege that allows a user to assume privileges of another one.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
SHOW TRANSACTION[S] [transaction-id[,...]]
[YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----
a|
List transactions on the current server.

The `transaction-id` is a comma-separated list of one or more quoted strings, a string parameter, or a list parameter.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
TERMINATE TRANSACTION[S] transaction-id[,...]
----
a|
Terminate transactions on the current server.

The `transaction-id` is a comma-separated list of one or more quoted strings, a string parameter, or a list parameter.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
ALTER DATABASE ...  [IF EXISTS]
SET ACCESS {READ ONLY \| READ WRITE}
----
a|
New Cypher command for modifying a database by changing its access mode.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
ALTER DATABASE
----
a|
New privilege that allows a user to modify databases.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
SET DATABASE ACCESS
----
a|
New privilege that allows a user to modify database access mode.
a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE ALIAS ... [IF NOT EXISTS]
FOR DATABASE ...
----
a|
New Cypher command for creating an alias for a database name. Remote aliases are only supported from version 4.4.8.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE OR REPLACE ALIAS ...
FOR DATABASE ...
----
a|
New Cypher command for creating or replacing an alias for a database name. Remote aliases are only supported from version 4.4.8.
a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
ALTER ALIAS ... [IF EXISTS]
SET DATABASE ...
----
a|
New Cypher command for altering an alias. Remote aliases are only supported from version 4.4.8.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
DROP ALIAS ... [IF EXISTS] FOR DATABASE
----
a|
New Cypher command for dropping a database alias.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
SHOW ALIASES FOR DATABASE
----
a|
New Cypher command for listing database aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
ALIAS MANAGEMENT
----
a|
New privilege that allows a user to create, modify, delete and list aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
CREATE ALIAS
----
a|
New privilege that allows a user to create aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
ALTER ALIAS
----
a|
New privilege that allows a user to modify aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
DROP ALIAS
----
a|
New privilege that allows a user to delete aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
SHOW ALIAS
----
a|
New privilege that allows a user to show aliases. Only supported since version 4.4.8.

|===


[[cypher-deprecations-additions-removals-4.3]]
== Version 4.3


=== Deprecated features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT [name]
ON (node:Label)
ASSERT exists(node.property)
----
a| Replaced by:
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT [name]
ON (node:Label)
ASSERT node.property IS NOT NULL
----


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT [name]
ON ()-[rel:REL]-()
ASSERT exists(rel.property)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT [name]
ON ()-[rel:REL]-()
ASSERT rel.property IS NOT NULL
----


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
exists(prop)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
prop IS NOT NULL
----


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
NOT exists(prop)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
prop IS NULL
----

a|
label:syntax[]
label:deprecated[]
`BRIEF [OUTPUT]` for `SHOW INDEXES` and `SHOW CONSTRAINTS`.
a|
Replaced by default output columns.


a|
label:syntax[]
label:deprecated[]
`VERBOSE [OUTPUT]` for `SHOW INDEXES` and `SHOW CONSTRAINTS`.
a|
Replaced by:
[source, cypher, role="noheader"]
----
YIELD *
----

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
SHOW EXISTS CONSTRAINTS
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW [PROPERTY] EXIST[ENCE] CONSTRAINTS
----
Still allows `BRIEF` and `VERBOSE` but not `YIELD` or `WHERE`.


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
SHOW NODE EXISTS CONSTRAINTS
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW NODE [PROPERTY] EXIST[ENCE] CONSTRAINTS
----
Still allows `BRIEF` and `VERBOSE` but not `YIELD` or `WHERE`.


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
SHOW RELATIONSHIP EXISTS CONSTRAINTS
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW RELATIONSHIP [PROPERTY] EXIST[ENCE] CONSTRAINTS
----
Still allows `BRIEF` and `VERBOSE` but not `YIELD` or `WHERE`.

a|
label:syntax[]
label:deprecated[]

For privilege commands:
[source, cypher, role="noheader"]
----
ON DEFAULT DATABASE
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
ON HOME DATABASE
----


a|
label:syntax[]
label:deprecated[]

For privilege commands:
[source, cypher, role="noheader"]
----
ON DEFAULT GRAPH
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
ON HOME GRAPH
----


a|
label:procedure[]
label:deprecated[]

[source, cypher, role="noheader"]
----
dbms.procedures
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW PROCEDURE[S]
[EXECUTABLE [BY {CURRENT USER \| username}]]
[YIELD ...]
[WHERE ...]
[RETURN ...]
----


a|
label:procedure[]
label:deprecated[]

[source, cypher, role="noheader"]
----
dbms.functions
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW [ALL \| BUILT IN \| USER DEFINED] FUNCTION[S]
[EXECUTABLE [BY {CURRENT USER \| username}]]
[YIELD ...]
[WHERE ...]
[RETURN ...]
----

|===


=== Updated features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW INDEXES WHERE ...
----
a|
Now allows filtering for:
[source, cypher, role="noheader"]
----
SHOW INDEXES
----


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW CONSTRAINTS WHERE ...
----
a|
Now allows filtering for:
[source, cypher, role="noheader"]
----
SHOW CONSTRAINTS
----


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW INDEXES YIELD ...
[WHERE ...]
[RETURN ...]
----
a|
Now allows `YIELD`, `WHERE`, and `RETURN` clauses to `SHOW INDEXES` to change the output.


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW CONSTRAINTS YIELD ...
[WHERE ...]
[RETURN ...]
----
a|
Now allows `YIELD`, `WHERE`, and `RETURN` clauses to `SHOW CONSTRAINTS` to change the output.


a|
label:syntax[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW [PROPERTY] EXIST[ENCE] CONSTRAINTS
----
a|
New syntax for filtering `SHOW CONSTRAINTS` on property existence constraints.
Allows `YIELD` and `WHERE` but not `BRIEF` or `VERBOSE`.


a|
label:syntax[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW NODE [PROPERTY] EXIST[ENCE] CONSTRAINTS
----
a|
New syntax for filtering `SHOW CONSTRAINTS` on node property existence constraints.
Allows `YIELD` and `WHERE` but not `BRIEF` or `VERBOSE`.


a|
label:syntax[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW REL[ATIONSHIP] [PROPERTY] EXIST[ENCE] CONSTRAINTS
----
a|
New syntax for filtering `SHOW CONSTRAINTS` on relationship property existence constraints.
Allows `YIELD` and `WHERE` but not `BRIEF` or `VERBOSE`.


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW FULLTEXT INDEXES
----
a|
Now allows easy filtering for `SHOW INDEXES` on fulltext indexes.
Allows `YIELD` and `WHERE` but not `BRIEF` or `VERBOSE`.


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW LOOKUP INDEXES
----
a|
Now allows easy filtering for `SHOW INDEXES` on lookup indexes.
Allows `YIELD` and `WHERE` but not `BRIEF` or `VERBOSE`.

|===


=== New features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE DATABASE ...
[OPTIONS {...}]
----
a|
New syntax to pass options to `CREATE DATABASE`.
This can be used to specify a specific cluster node to seed data from.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT [name]
ON (node:Label)
ASSERT node.property IS NOT NULL
----
a|
New syntax for creating node property existence constraints.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT [name]
ON ()-[rel:REL]-()
ASSERT rel.property IS NOT NULL
----
a|
New syntax for creating relationship property existence constraints.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
ALTER USER name IF EXISTS ...
----
a|
Makes altering users idempotent.
If the specified name does not exists, no error is thrown.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
ALTER USER ...
SET HOME DATABASE ...
----
a|
Now allows setting home database for user.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
ALTER USER ...
REMOVE HOME DATABASE
----
a|
Now allows removing home database for user.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE USER ...
SET HOME DATABASE ...
----
a|
`CREATE USER` now allows setting home database for user.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
SHOW HOME DATABASE
----
a|
New syntax for showing the home database of the current user.


a|
label:syntax[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
SET USER HOME DATABASE
----
a|
New Cypher command for administering privilege for changing users home database.


a|
label:syntax[]
label:new[]
For privilege commands:
[source, cypher, role="noheader"]
----
ON HOME DATABASE
----
a|
New syntax for privileges affecting home database.


a|
label:syntax[]
label:new[]

For privilege commands:
[source, cypher, role="noheader"]
----
ON HOME GRAPH
----
a|
New syntax for privileges affecting home graph.

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE FULLTEXT INDEX ...
----
a|
Allows creating fulltext indexes on nodes or relationships.
They can be dropped by using their name.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE INDEX FOR ()-[r:TYPE]-() ...
----
a|
Allows creating indexes on relationships with a particular relationship type and property combination.
They can be dropped by using their name.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE LOOKUP INDEX ...
----
a|
Create lookup index for nodes with any labels or relationships with any relationship type.
They can be dropped by using their name.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
RENAME ROLE
----
a|
New Cypher command for changing the name of a role.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
RENAME USER
----
a|
New Cypher command for changing the name of a user.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
SHOW PROCEDURE[S]
[EXECUTABLE [BY {CURRENT USER \| username}]]
[YIELD ...]
[WHERE ...]
[RETURN ...]
----
a|
New Cypher commands for listing procedures.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
SHOW [ALL \| BUILT IN \| USER DEFINED] FUNCTION[S]
[EXECUTABLE [BY {CURRENT USER \| username}]]
[YIELD ...]
[WHERE ...]
[RETURN ...]
----
a|
New Cypher commands for listing functions.

|===


[[cypher-deprecations-additions-removals-4.2]]
== Version 4.2


=== Deprecated features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
0...
----
a|
Replaced by `+0o...+`.


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
0X...
----
a|
Only `+0x...+` (lowercase x) is supported.

a|
label:procedure[]
label:deprecated[]
[source, role="noheader"]
----
db.createIndex
----
a|
Replaced by `CREATE INDEX` command.


a|
label:procedure[]
label:deprecated[]
[source, role="noheader"]
----
db.createNodeKey
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT ... IS NODE KEY
----


a|
label:procedure[]
label:deprecated[]
[source, role="noheader"]
----
db.createUniquePropertyConstraint
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT ... IS UNIQUE
----

a|
label:procedure[]
label:deprecated[]
[source, role="noheader"]
----
db.indexes
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW INDEXES
----


a|
label:procedure[]
label:deprecated[]
[source, role="noheader"]
----
db.indexDetails
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW INDEXES YIELD *
----


a|
label:procedure[]
label:deprecated[]
[source, role="noheader"]
----
db.constraints
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW CONSTRAINTS
----


a|
label:procedure[]
label:deprecated[]
[source, role="noheader"]
----
db.schemaStatements
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW INDEXES YIELD *
----
[source, cypher, role="noheader"]
----
SHOW CONSTRAINTS YIELD *
----

|===


=== Updated features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW ROLE name PRIVILEGES
----
a|
Can now handle multiple roles.
[source, cypher, role="noheader"]
----
SHOW ROLES n1, n2, ... PRIVILEGES
----


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW USER name PRIVILEGES
----
a|
Can now handle multiple users.
[source, cypher, role="noheader"]
----
SHOW USERS n1, n2, ... PRIVILEGES
----


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
round(expression, precision)
----
a|
The `round()` function can now take an additional argument to specify rounding precision.


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
round(expression, precision, mode)
----
a|
The `round()` function can now take two additional arguments to specify rounding precision and rounding mode.

|===


=== New features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
SHOW PRIVILEGES [AS [REVOKE] COMMAND[S]]
----
a|
Privileges can now be shown as Cypher commands.

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
DEFAULT GRAPH
----
a|
New optional part of the Cypher commands for xref::access-control/database-administration.adoc[database privileges].


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
0o...
----
a|
Cypher now interprets literals with prefix `0o` as an octal integer literal.

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
SET [PLAINTEXT \| ENCRYPTED] PASSWORD
----
a|
For `CREATE USER` and `ALTER USER`, it is now possible to set (or update) a password when the plaintext password is unknown, but the encrypted password is available.


a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
EXECUTE
----
a|
New Cypher commands for administering privileges for executing procedures and user defined functions.

See xref::access-control/dbms-administration.adoc#access-control-dbms-administration-execute[The DBMS `EXECUTE` privileges].


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE [BTREE] INDEX ... [OPTIONS {...}]
----
a|
Allows setting index provider and index configuration when creating an index.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT ... IS NODE KEY [OPTIONS {...}]
----
a|
Allows setting index provider and index configuration for the backing index when creating a node key constraint.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT ... IS UNIQUE [OPTIONS {...}]
----
a|
Allows setting index provider and index configuration for the backing index when creating a uniqueness constraint.

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
SHOW CURRENT USER
----
a|
New Cypher command for showing current logged-in user and roles.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
SHOW [ALL \| BTREE] INDEX[ES] [BRIEF \| VERBOSE [OUTPUT]]
----
a|
New Cypher commands for listing indexes.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
SHOW [ALL \| UNIQUE \| NODE EXIST[S] \| RELATIONSHIP EXIST[S] \| EXIST[S] \| NODE KEY] CONSTRAINT[S] [BRIEF \| VERBOSE [OUTPUT]]
----
a|
New Cypher commands for listing constraints.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
SHOW INDEX
----
a|
New Cypher command for administering privilege for listing indexes.


a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
SHOW CONSTRAINT
----
a|
New Cypher command for administering privilege for listing constraints.

|===


[[cypher-deprecations-additions-removals-4.1.3]]
== Version 4.1.3


=== New features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE INDEX [name] IF NOT EXISTS FOR ...
----
a|
Makes index creation idempotent. If an index with the name or schema already exists no error will be thrown.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
DROP INDEX name IF EXISTS
----
a|
Makes index deletion idempotent. If no index with the name exists no error will be thrown.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT [name] IF NOT EXISTS ON ...
----
a|
Makes constraint creation idempotent. If a constraint with the name or type and schema already exists no error will be thrown.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
DROP CONSTRAINT name IF EXISTS
----
a|
Makes constraint deletion idempotent. If no constraint with the name exists no error will be thrown.

|===


[[cypher-deprecations-additions-removals-4.1]]
== Version 4.1


=== Restricted features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:functionality[]
label:restricted[]
[source, cypher, role="noheader"]
----
REVOKE ...
----
a|
No longer revokes sub-privileges when revoking a compound privilege, e.g. when revoking `INDEX MANAGEMENT`, any `CREATE INDEX` and `DROP INDEX` privileges will no longer be revoked.


a|
label:functionality[]
label:restricted[]
[source, cypher, role="noheader"]
----
ALL DATABASE PRIVILEGES
----
a|
No longer includes the privileges `START DATABASE` and `STOP DATABASE`.

|===


=== Updated features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:procedure[]
label:updated[]
[source, cypher, role="noheader"]
----
queryId
----
a|
The `queryId` procedure format has changed, and no longer includes the database name.
For example, `mydb-query-123` is now `query-123`.

This change affects the procedures: `dbms.listQueries()`, `dbms.listActiveLocks(queryId)`, `dbms.killQueries(queryIds)`, and `dbms.killQuery(queryId)`.

a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader"]
----
SHOW PRIVILEGES
----
a|
The returned privileges are a closer match to the original grants and denies, e.g. if granted `MATCH` the command will show that specific privilege and not the `TRAVERSE` and `READ` privileges.
Added support for `YIELD` and `WHERE` clauses to allow filtering results.

|===


=== New features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:functionality[]
label:new[]
New role:
[source, cypher, role="noheader"]
----
PUBLIC
----
a|
The `PUBLIC` role is automatically assigned to all users, giving them a set of base privileges.


a|
label:syntax[]
label:new[]
For privileges:
[source, cypher, role="noheader"]
----
REVOKE MATCH
----
a|
The `MATCH` privilege can now be revoked.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
SHOW USERS
----
a|
New support for `YIELD` and `WHERE` clauses to allow filtering results.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
SHOW ROLES
----
a|
New support for `YIELD` and `WHERE` clauses to allow filtering results.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
SHOW DATABASES
----
a|
New support for `YIELD` and `WHERE` clauses to allow filtering results.


a|
label:functionality[]
label:new[]
xref::access-control/database-administration.adoc#access-control-database-administration-transaction[TRANSACTION MANAGEMENT] privileges
a|
New Cypher commands for administering transaction management.


a|
label:functionality[]
label:new[]
DBMS xref::access-control/dbms-administration.adoc#access-control-dbms-administration-user-management[USER MANAGEMENT] privileges
a|
New Cypher commands for administering user management.


a|
label:functionality[]
label:new[]
DBMS xref::access-control/dbms-administration.adoc#access-control-dbms-administration-database-management[DATABASE MANAGEMENT] privileges
a|
New Cypher commands for administering database management.


a|
label:functionality[]
label:new[]
DBMS xref::access-control/dbms-administration.adoc#access-control-dbms-administration-privilege-management[PRIVILEGE MANAGEMENT] privileges
a|
New Cypher commands for administering privilege management.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
ALL DBMS PRIVILEGES
----
a|
New Cypher command for administering role, user, database and privilege management.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
ALL GRAPH PRIVILEGES
----
a|
New Cypher command for administering read and write privileges.


a|
label:functionality[]
label:new[]
Write privileges
a|
New Cypher commands for administering write privileges.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
ON DEFAULT DATABASE
----
a|
New optional part of the Cypher commands for xref::access-control/database-administration.adoc[database privileges].

|===


[[cypher-deprecations-additions-removals-4.0]]
== Version 4.0


=== Removed features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:function[]
label:removed[]
[source, cypher, role="noheader"]
----
rels()
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
relationships()
----

See xref::functions/list.adoc#functions-relationships[`relationships()`].


a|
label:function[]
label:removed[]
[source, cypher, role="noheader"]
----
toInt()
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
toInteger()
----

See xref::functions/scalar.adoc#functions-tointeger[`toInteger()`].


a|
label:function[]
label:removed[]
[source, cypher, role="noheader"]
----
lower()
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
toLower()
----

See xref::functions/string.adoc#functions-tolower[`toLower()`].

a|
label:function[]
label:removed[]
[source, cypher, role="noheader"]
----
upper()
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
toUpper()
----

See xref::functions/string.adoc#functions-toupper[`toUpper()`].

a|
label:function[]
label:removed[]
[source, cypher, role="noheader"]
----
extract()
----
a|
Replaced by xref::syntax/lists.adoc#cypher-list-comprehension[list comprehension].


a|
label:function[]
label:removed[]
[source, cypher, role="noheader"]
----
filter()
----
a|
Replaced by xref::syntax/lists.adoc#cypher-list-comprehension[list comprehension].


a|
label:functionality[]
label:removed[]
For Rule planner:
[source, cypher, role="noheader"]
----
CYPHER planner=rule
----
a|
The `RULE` planner was removed in 3.2, but still possible to trigger using `START` or `CREATE UNIQUE` clauses.
Now it is completely removed.


a|
label:functionality[]
label:removed[]
Explicit indexes
a|
The removal of the `RULE` planner in 3.2 was the beginning of the end for explicit indexes.
Now they are completely removed, including the removal of the link:https://neo4j.com/docs/cypher-manual/3.5/schema/index/#explicit-indexes-procedures[built-in procedures for Neo4j 3.3 to 3.5].


a|
label:functionality[]
label:removed[]
For compiled runtime:
[source, cypher, role="noheader"]
----
CYPHER runtime=compiled
----
a|
Replaced by the new `pipelined` runtime which covers a much wider range of queries.


a|
label:clause[]
label:removed[]
[source, cypher, role="noheader"]
----
CREATE UNIQUE
----
a|
Running queries with this clause will cause a syntax error.


a|
label:clause[]
label:removed[]
[source, cypher, role="noheader"]
----
START
----
a|
Running queries with this clause will cause a syntax error.


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
MATCH (n)-[:A\|:B\|:C {foo: 'bar'}]-() RETURN n
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
MATCH (n)-[:A\|B\|C {foo: 'bar'}]-() RETURN n
----

a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
MATCH (n)-[x:A\|:B\|:C]-() RETURN n
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
MATCH (n)-[x:A\|B\|C]-() RETURN n
----

a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
MATCH (n)-[x:A\|:B\|:C*]-() RETURN n
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
MATCH (n)-[x:A\|B\|C*]-() RETURN n
----

a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader"]
----
{parameter}
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
$parameter
----

See xref::syntax/parameters.adoc[].

|===


=== Deprecated features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
MATCH (n)-[rs*]-() RETURN rs
----
a|
As in Cypher 3.2, this is replaced by:
[source, cypher, role="noheader"]
----
MATCH p=(n)-[*]-() RETURN relationships(p) AS rs
----


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
CREATE INDEX ON :Label(prop)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
CREATE INDEX FOR (n:Label) ON (n.prop)
----


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
DROP INDEX ON :Label(prop)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
DROP INDEX name
----


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
DROP CONSTRAINT ON (n:Label) ASSERT (n.prop) IS NODE KEY
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
DROP CONSTRAINT name
----


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
DROP CONSTRAINT ON (n:Label) ASSERT (n.prop) IS UNIQUE
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
DROP CONSTRAINT name
----

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
DROP CONSTRAINT ON (n:Label) ASSERT exists(n.prop)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
DROP CONSTRAINT name
----

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
DROP CONSTRAINT ON ()-[r:Type]-() ASSERT exists(r.prop)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
DROP CONSTRAINT name
----

|===


=== Restricted features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:function[]
label:restricted[]
[source, cypher, role="noheader"]
----
length()
----
a|
Restricted to only work on paths.

See xref::functions/scalar.adoc#functions-length[`length()`].


a|
label:function[]
label:restricted[]
[source, cypher, role="noheader"]
----
size()
----
a|
No longer works for paths.
Only works for strings, lists and pattern expressions.

See xref::functions/scalar.adoc[`size()`].

|===


=== Updated features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:syntax[]
label:extended[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT [name] ON ...
----
a|
The create constraint syntax can now include a name.

|===


=== New features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:functionality[]
label:new[]
Pipelined runtime:
[source, cypher, role="noheader"]
----
CYPHER runtime=pipelined
----
a|
This Neo4j Enterprise Edition only feature involves a new runtime that has many performance enhancements.


a|
label:functionality[]
label:new[]
xref::databases.adoc[Multi-database administration]
a|
New Cypher commands for administering multiple databases.


a|
label:functionality[]
label:new[]
xref::access-control/index.adoc[Access control]
a|
New Cypher commands for administering role-based access control.


a|
label:functionality[]
label:new[]
xref::access-control/manage-privileges.adoc[Fine-grained security]
a|
New Cypher commands for administering dbms, database, graph and sub-graph access control.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE INDEX [name] FOR (n:Label) ON (n.prop)
----
a|
New syntax for creating indexes, which can include a name.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
DROP INDEX name
----
a|
xref::indexes-for-search-performance.adoc#administration-indexes-drop-an-index[New command] for dropping an index by name.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
DROP CONSTRAINT name
----
a|
xref::constraints/syntax.adoc#administration-constraints-syntax-drop[New command] for dropping a constraint by name, no matter the type.


a|
label:clause[]
label:new[]
[source, cypher, role="noheader"]
----
WHERE EXISTS {...}
----
a|
Existential sub-queries are sub-clauses used to filter the results of a `MATCH`, `OPTIONAL MATCH`, or `WITH` clause.


a|
label:clause[]
label:new[]
[source, cypher, role="noheader"]
----
USE neo4j
----
a|
New clause to specify which graph a query, or query part, is executed against.

|===


[[cypher-deprecations-additions-removals-3.5]]
== Version 3.5


=== Deprecated features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:functionality[]
label:deprecated[]
Compiled runtime:
[source, cypher, role="noheader"]
----
CYPHER runtime=compiled
----
a|
The compiled runtime will be discontinued in the next major release. It might still be used for default queries in order to not cause regressions, but explicitly requesting it will not be possible.


a|
label:function[]
label:deprecated[]
[source, cypher, role="noheader"]
----
extract()
----
a|
Replaced by xref::syntax/lists.adoc#cypher-list-comprehension[list comprehension].


a|
label:function[]
label:deprecated[]
[source, cypher, role="noheader"]
----
filter()
----
a|
Replaced by xref::syntax/lists.adoc#cypher-list-comprehension[list comprehension].

|===


[[cypher-deprecations-additions-removals-3.4]]
== Version 3.4

[cols="4", options="header"]
|===
| Feature | Type | Change | Details

| xref::syntax/spatial.adoc[Spatial point types]
| Functionality
| Amendment
|
A point -- irrespective of which Coordinate Reference System is used -- can be stored as a property and is able to be backed by an index.
Prior to this, a point was a virtual property only.

| xref::functions/spatial.adoc#functions-point-cartesian-3d[`point()` - Cartesian 3D]
| Function
| Added
|

| xref::functions/spatial.adoc#functions-point-wgs84-3d[`point()` - WGS 84 3D]
| Function
| Added
|

| xref::functions/scalar.adoc#functions-randomuuid[`randomUUID()`]
| Function
| Added
|

| xref::syntax/temporal.adoc[Temporal types]
| Functionality
| Added
| Supports storing, indexing and working with the following temporal types: `Date`, `Time`, `LocalTime`, `DateTime`, `LocalDateTime`, and `Duration`.

| xref::functions/temporal/index.adoc[Temporal functions]
| Functionality
| Added
| Functions allowing for the creation and manipulation of values for each temporal type: `Date`, `Time`, `LocalTime`, `DateTime`, `LocalDateTime`, and `Duration`.

| xref::syntax/operators.adoc#query-operators-temporal[Temporal operators]
| Functionality
| Added
| Operators allowing for the manipulation of values for each temporal type: `Date`, `Time`, `LocalTime`, `DateTime`, `LocalDateTime`, and `Duration`.

| xref::functions/string.adoc#functions-tostring[`toString()`]
| Function
| Extended
| Now also allows temporal values as input (i.e. values of type `Date`, `Time`, `LocalTime`, `DateTime`, `LocalDateTime`, or `Duration`).

|===


[[cypher-deprecations-additions-removals-3.3]]
== Version 3.3

[cols="4", options="header"]
|===
| Feature | Type | Change | Details

| `START`
| Clause
| Removed
|
As in Cypher 3.2, any queries using the `START` clause will revert back to Cypher 3.1 `planner=rule`.
However, there are link:https://neo4j.com/docs/cypher-manual/3.5/schema/index/#explicit-indexes-procedures[built-in procedures for Neo4j versions 3.3 to 3.5] for accessing explicit indexes. The procedures will enable users to use the current version of Cypher and the cost planner together with these indexes.
An example of this is `+CALL db.index.explicit.searchNodes('my_index', 'email:me*')+`.

| `CYPHER runtime=slotted` (Faster interpreted runtime)
| Functionality
| Added
| Neo4j Enterprise Edition only.

| xref::functions/aggregating.adoc#functions-max[`max()`], xref::functions/aggregating.adoc#functions-min[`min()`]
| Function
| Extended
| Now also supports aggregation over sets containing lists of strings and/or numbers, as well as over sets containing strings, numbers, and lists of strings and/or numbers.

|===


[[cypher-deprecations-additions-removals-3.2]]
== Version 3.2

[cols="4", options="header"]
|===
| Feature | Type | Change | Details

| `CYPHER planner=rule` (Rule planner)
| Functionality
| Removed
| All queries now use the cost planner. Any query prepended thus will fall back to using Cypher 3.1.

| `CREATE UNIQUE`
| Clause
| Removed
| Running such queries will fall back to using Cypher 3.1 (and use the rule planner).

| `START`
| Clause
| Removed
| Running such queries will fall back to using Cypher 3.1 (and use the rule planner).

a|
[source, cypher, role="noheader"]
----
MATCH (n)-[rs*]-() RETURN rs
----
| Syntax
| Deprecated
a|
Replaced by:
[source, cypher, role="noheader"]
----
MATCH p=(n)-[*]-() RETURN relationships(p) AS rs`
----

a|
[source, cypher, role="noheader"]
----
MATCH (n)-[:A\|:B\|:C {foo: 'bar'}]-() RETURN n
----
| Syntax
| Deprecated
a|
Replaced by:
[source, cypher, role="noheader"]
----
MATCH (n)-[:A\|B\| C {foo: 'bar'}]-() RETURN n
----

a|
[source, cypher, role="noheader"]
----
MATCH (n)-[x:A\|:B\|:C]-() RETURN n
----
| Syntax
| Deprecated
a|
Replaced by:
[source, cypher, role="noheader"]
----
MATCH (n)-[x:A\|B\|C]-() RETURN n
----

a|
[source, cypher, role="noheader"]
----
MATCH (n)-[x:A\|:B\|:C*]-() RETURN n
----
| Syntax
| Deprecated
a|
Replaced by:
[source, cypher, role="noheader"]
----
MATCH (n)-[x:A\|B\|C*]-() RETURN n
----

| xref:5.0@java-reference:ROOT:extending-neo4j/aggregation-functions.adoc#extending-neo4j-aggregation-functions[User-defined aggregation functions]
| Functionality
| Added
|

| xref::indexes-for-search-performance.adoc[Composite indexes]
| Index
| Added
|

| xref::constraints/examples.adoc#administration-constraints-node-key[Node Key]
| Index
| Added
| Neo4j Enterprise Edition only.

| `CYPHER runtime=compiled` (Compiled runtime)
| Functionality
| Added
| Neo4j Enterprise Edition only.

| xref::functions/list.adoc#functions-reverse-list[`reverse()`]
| Function
| Extended
| Now also allows a list as input.

| xref::functions/aggregating.adoc#functions-max[`max()`], xref::functions/aggregating.adoc#functions-min[`min()`]
| Function
| Extended
| Now also supports aggregation over a set containing both strings and numbers.

|===


[[cypher-deprecations-additions-removals-3.1]]
== Version 3.1

[cols="4", options="header"]
|===
| Feature | Type | Change | Details

a|
[source, cypher, role="noheader"]
----
rels()
----
| Function
| Deprecated
a|
Replaced by:
[source, cypher, role="noheader"]
----
relationships()
----

See xref::functions/list.adoc#functions-relationships[`relationships()`].

a|
[source, cypher, role="noheader"]
----
toInt()
----
| Function
| Deprecated
a|
Replaced by:
[source, cypher, role="noheader"]
----
toInteger()
----

See xref::functions/scalar.adoc#functions-tointeger[`toInteger()`].

a|
[source, cypher, role="noheader"]
----
lower()
----
| Function
| Deprecated
a|
Replaced by:
[source, cypher, role="noheader"]
----
toLower()
----

Replaced by xref::functions/string.adoc#functions-tolower[`toLower()`].

a|
[source, cypher, role="noheader"]
----
upper()
----
| Function
| Deprecated
a|
Replaced by:
[source, cypher, role="noheader"]
----
toUpper()
----

See xref::functions/string.adoc#functions-toupper[`toUpper()`].

a|
[source, cypher, role="noheader"]
----
toBoolean()
----
| Function
| Added
a| See xref::functions/scalar.adoc#functions-toboolean[`toBoolean()`].

| xref::syntax/maps.adoc#cypher-map-projection[Map projection]
| Syntax
| Added
|

| xref::syntax/lists.adoc#cypher-pattern-comprehension[Pattern comprehension]
| Syntax
| Added
|

| xref:5.0@java-reference:ROOT:extending-neo4j/functions.adoc#extending-neo4j-functions[User-defined functions]
| Functionality
| Added
|

| xref::clauses/call.adoc[`+CALL ... YIELD ... WHERE+`]
| Clause
| Extended
| Records returned by `YIELD` may be filtered further using `WHERE`.

|===


[[cypher-deprecations-additions-removals-3.0]]
== Version 3.0

[cols="4", options="header"]
|===
| Feature | Type | Change | Details

a|
[source, cypher, role="noheader"]
----
has()
----
| Function
| Removed
a|
Replaced by:
[source, cypher, role="noheader"]
----
exists()
----

See xref::functions/predicate.adoc#functions-exists[`exists()`].

a|
[source, cypher, role="noheader"]
----
str()
----
| Function
| Removed
a| Replaced by:
[source, cypher, role="noheader"]
----
toString()
----

See xref::functions/string.adoc#functions-tostring[`toString()`].

a|
[source, cypher, role="noheader"]
----
{parameter}
----
| Syntax
| Deprecated
a|
Replaced by:
[source, cypher, role="noheader"]
----
$parameter
----

See xref::syntax/parameters.adoc[].

a|
[source, cypher, role="noheader"]
----
properties()
----
| Function
| Added
a| See xref::functions/scalar.adoc#functions-properties[`properties()`].

a|
[source, cypher, role="noheader"]
----
CALL ... [YIELD]
----
| Clause
| Added
a| See xref::clauses/call.adoc[].

| xref::functions/spatial.adoc#functions-point-cartesian-2d[`point()` - Cartesian 2D]
| Function
| Added
|

| xref::functions/spatial.adoc#functions-point-wgs84-2d[`point()` - WGS 84 2D]
| Function
| Added
|

a|
[source, cypher, role="noheader"]
----
distance()
----
| Function
| Added
a| See xref::functions/spatial.adoc#functions-distance[`distance()`].

| xref:5.0@java-reference:ROOT:extending-neo4j/procedures.adoc#extending-neo4j-procedures[User-defined procedures]
| Functionality
| Added
|

| xref::functions/string.adoc#functions-tostring[`toString()`]
| Function
| Extended
| Now also allows Boolean values as input.

|===

