:description: Cypher is a graph query language that is constantly evolving.

[[cypher-deprecations-additions-removals-compatibility]]
= Deprecations, additions and compatibility

[abstract]
--
Cypher is a graph query language that is constantly evolving.
New features are added to the language continuously, and occasionally, some features become deprecated and are subsequently removed.
--

This section list all of the features that have been removed, deprecated, added, or extended in different Cypher versions.
Replacement syntax for deprecated and removed features are also indicated.

[[cypher-deprecations-additions-removals-4.4]]
== Version 4.4

=== Deprecated features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
MATCH (n) RETURN n.propertyName_1, n.propertyName_2 + count(*)
----
a|
Implied grouping keys are deprecated.
Only expressions that do _not_ contain aggregations are still considered grouping keys.

In expressions that contain aggregations, the leaves must be either:

- An aggregation.
- A literal.
- A parameter.
- A variable, *ONLY IF* it is either: +
1) A projection expression on its own (e.g. the `n` in `RETURN n AS myNode, n.value + count(*)`). +
2) A local variable in the expression (e.g the `x` in `RETURN n, n.prop + size([ x IN range(1, 10) \| x ]`).
- Property access, *ONLY IF* it is also a projection expression on its own (e.g. the `n.prop` in `RETURN n.prop, n.prop + count(*)`).
- Map access, *ONLY IF* it is also a projection expression on its own (e.g. the `map.prop` in `WITH {prop: 2} AS map RETURN map.prop, map.prop + count(*)`).


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
USING PERIODIC COMMIT ...
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
CALL {
  ...
} IN TRANSACTIONS
----


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
CREATE (a {prop:7})-[r:R]->(b {prop: a.prop})
----
a|
`CREATE` clauses in which a variable introduced in the pattern is also referenced from the same pattern are deprecated.


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT ON ... ASSERT ...
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT FOR ... REQUIRE ...
----

a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
CREATE BTREE INDEX ...
----
.2+.^a|
B-tree indexes are deprecated, partially replaced for now, and will be fully replaced in 5.0 by xref::indexes-for-search-performance.adoc#indexes-future-indexes[future indexes].
In 4.4, b-tree indexes are still the correct alternative to use.

B-tree indexes used for string queries are replaced by:
[source, cypher, role="noheader"]
----
CREATE TEXT INDEX ...
----

B-tree indexes used for spatial queries will be replaced by:
[source, cypher, role="noheader"]
----
CREATE POINT INDEX ...
----

B-tree indexes used for general queries or property value types will be replaced by:
[source, cypher, role="noheader"]
----
CREATE RANGE INDEX ...
----

These new indexes may be combined for multiple use cases.

a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
CREATE INDEX
...
OPTIONS "{" btree-option: btree-value[, ...] "}"
----


a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
SHOW BTREE INDEXES
----
a|
B-tree indexes are deprecated, partially replaced for now, and will be fully replaced in 5.0 by xref::indexes-for-search-performance.adoc#indexes-future-indexes[future indexes].
In 4.4, b-tree indexes are still the correct alternative to use.

Replaced by the new and future index types:
[source, cypher, role="noheader"]
----
SHOW {POINT \| RANGE \| TEXT} INDEXES
----


a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
USING BTREE INDEX
----
a|
B-tree indexes are deprecated.

Replaced by:
[source, cypher, role="noheader"]
----
USING {POINT \| RANGE \| TEXT} INDEX
----


a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT
...
OPTIONS "{" btree-option: btree-value[, ...] "}"
----
a|
Node key and uniqueness constraints with b-tree options are deprecated and will be replaced in 5.0 by range options, see xref::indexes-for-search-performance.adoc#indexes-future-indexes[range indexes].
In 4.4, the b-tree index-backed constraints are still the correct alternative to use.

Will be replaced by:
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT
...
OPTIONS "{" range-option: range-value[, ...] "}"
----
Constraints used for string properties will also require an additional text index to cover the string queries properly.
Constraints used for point properties will also require an additional point index to cover the spatial queries properly, see xref::indexes-for-search-performance.adoc#indexes-future-indexes[point indexes].


a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
distance(n.prop, point({x:0, y:0})
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
point.distance(n.prop, point({x:0, y:0})
----

a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader"]
----
point({x:0, y:0}) <= point({x:1, y:1}) <= point({x:2, y:2})
----
a|
The ability to use the `+<+`, `+<=+`, `+>+`, and `+>=+` on spatial points is deprecated.

Instead use:
[source, cypher, role="noheader"]
----
point.withinBBox(point({x:1, y:1}), point({x:0, y:0}), point({x:2, y:2}))
----


a|
label:procedure[]
label:deprecated[]

[source, cypher, role="noheader"]
----
dbms.listTransactions
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW TRANSACTION[S] [transaction-id[,...]]
[YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----


a|
label:procedure[]
label:deprecated[]

[source, cypher, role="noheader"]
----
dbms.killTransaction
----

[source, cypher, role="noheader"]
----
dbms.killTransactions
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
TERMINATE TRANSACTION[S] transaction-id[,...]
----


a|
label:procedure[]
label:deprecated[]

[source, cypher, role="noheader"]
----
dbms.listQueries
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
SHOW TRANSACTION[S] [transaction-id[,...]]
[YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----


a|
label:procedure[]
label:deprecated[]

[source, cypher, role="noheader"]
----
dbms.killQuery
----

[source, cypher, role="noheader"]
----
dbms.killQueries
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
TERMINATE TRANSACTION[S] transaction-id[,...]
----

|===


=== New features

[cols="2", options="header"]
|===
| Feature | Details

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CALL {
  ...
} IN TRANSACTIONS
----
a|
New clause for evaluating a subquery in separate transactions.
Typically used when modifying or importing large amounts of data.
See xref::clauses/call-subquery.adoc#subquery-call-in-transactions[`+CALL { ... } IN TRANSACTIONS+`].

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT FOR ... REQUIRE ...
----
a|
New syntax for creating constraints, applicable to all constraint types.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR (n:LabelName)
REQUIRE (n.propertyName_1, …, n.propertyName_n) IS UNIQUE
[OPTIONS "{" option: value[, ...] "}"]
----
a|
Unique property constraints now allow multiple properties, ensuring that the combination of property values are unique.

a|
label:functionality[]
label:new[]
label:deprecated[]
[source, cypher, role="noheader"]
----
DROP CONSTRAINT
ON (n:LabelName)
ASSERT (n.propertyName_1, ..., n.propertyName_n) IS UNIQUE
----
a|
Unique property constraints now allow multiple properties.

Replaced by:
[source, cypher, role="noheader"]
----
DROP CONSTRAINT name [IF EXISTS]
----

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR ...
REQUIRE ... IS NOT NULL
OPTIONS "{" "}"
----
a|
Existence constraints now allow an `OPTIONS` map, however, at this point there are no available values for the map.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE LOOKUP INDEX [index_name] [IF NOT EXISTS]
FOR ... ON ...
OPTIONS "{" option: value[, ...] "}"
----
a|
Token lookup indexes now allow an `OPTIONS` map to specify the index provider.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE TEXT INDEX ...
----
a|
Allows creating text indexes on nodes or relationships with a particular label or relationship type, and property combination.
They can be dropped by using their name.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE RANGE INDEX ...
----
a|
xref::indexes-for-search-performance.adoc#indexes-future-indexes[FUTURE INDEX]: Allows creating range indexes on nodes or relationships with a particular label or relationship type, and properties combination.
They can be dropped by using their name.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE CONSTRAINT
...
OPTIONS "{" indexProvider: 'range-1.0' "}"
----
a|
xref::indexes-for-search-performance.adoc#indexes-future-indexes[FUTURE CONSTRAINT]: Allows creating node key and uniqueness constraints backed by range indexes by providing the range index provider in the `OPTIONS` map.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE POINT INDEX ...
----
a|
xref::indexes-for-search-performance.adoc#indexes-future-indexes[FUTURE INDEX]: Allows creating point indexes on nodes or relationships with a particular label or relationship type, and property combination.
They can be dropped by using their name.

a|
label:syntax[]
label:new[] +
New privilege:
[source, cypher, role="noheader"]
----
IMPERSONATE
----
a|
New privilege that allows a user to assume privileges of another one.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
SHOW TRANSACTION[S] [transaction-id[,...]]
[YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----
a|
List transactions on the current server.

The `transaction-id` is a comma-separated list of one or more quoted strings, a string parameter, or a list parameter.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
TERMINATE TRANSACTION[S] transaction-id[,...]
----
a|
Terminate transactions on the current server.

The `transaction-id` is a comma-separated list of one or more quoted strings, a string parameter, or a list parameter.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
ALTER DATABASE ...  [IF EXISTS]
SET ACCESS {READ ONLY \| READ WRITE}
----
a|
New Cypher command for modifying a database by changing its access mode.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
ALTER DATABASE
----
a|
New privilege that allows a user to modify databases.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
SET DATABASE ACCESS
----
a|
New privilege that allows a user to modify database access mode.
a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE ALIAS ... [IF NOT EXISTS]
FOR DATABASE ...
----
a|
New Cypher command for creating an alias for a database name. Remote aliases are only supported from version 4.4.8.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CREATE OR REPLACE ALIAS ...
FOR DATABASE ...
----
a|
New Cypher command for creating or replacing an alias for a database name. Remote aliases are only supported from version 4.4.8.
a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
ALTER ALIAS ... [IF EXISTS]
SET DATABASE ...
----
a|
New Cypher command for altering an alias. Remote aliases are only supported from version 4.4.8.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
DROP ALIAS ... [IF EXISTS] FOR DATABASE
----
a|
New Cypher command for dropping a database alias.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
SHOW ALIASES FOR DATABASE
----
a|
New Cypher command for listing database aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
ALIAS MANAGEMENT
----
a|
New privilege that allows a user to create, modify, delete and list aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
CREATE ALIAS
----
a|
New privilege that allows a user to create aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
ALTER ALIAS
----
a|
New privilege that allows a user to modify aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
DROP ALIAS
----
a|
New privilege that allows a user to delete aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[]
New privilege:
[source, cypher, role="noheader"]
----
SHOW ALIAS
----
a|
New privilege that allows a user to show aliases. Only supported since version 4.4.8.


|===
