:description: Cypher is a graph query language that is constantly evolving.

[[cypher-deprecations-additions-removals-compatibility]]
= Deprecations, additions and compatibility

[abstract]
--
Cypher is a graph query language that is constantly evolving.
New features are added to the language continuously, and occasionally, some features become deprecated and are subsequently removed.
--

This section list all of the features that have been removed, deprecated, added, or extended in different Cypher versions.
Replacement syntax for deprecated and removed features are also indicated.

[[cypher-deprecations-additions-removals-4.4]]
== Version 4.4

=== Deprecated features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
MATCH (n) RETURN n.propertyName_1, n.propertyName_2 + count(*)
----
a|
Implied grouping keys are deprecated.
Only expressions that do _not_ contain aggregations are grouping keys.
In expressions that contain aggregations, the leaves of expressions must be one of:

- An aggregation
- A literal
- A Parameter
- A variable - *ONLY IF* that variable is also one of: +
1) A projection expression on its own (e.g. the `n` in `RETURN n AS myNode, n.value + count(*)`) +
2) A local variable in the expression (e.g the `x` in `RETURN n, n.prop + size([ x IN range(1, 10) \| x ]`)
- Property access - *ONLY IF* that property access is also a projection expression on its own (e.g. the `n.prop` in `RETURN n.prop, n.prop + count(*)`) +
- Map access - *ONLY IF* that map access is also a projection expression on its own (e.g. the `map.prop` in `WITH {prop: 2} AS map RETURN map.prop, map.prop + count(*)`)

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
USING PERIODIC COMMIT ...
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
CALL {
  ...
} IN TRANSACTIONS
----

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT ON ... ASSERT ...
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT FOR ... REQUIRE ...
----

a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
CREATE BTREE INDEX ...
----
.2+.^a|
B-tree indexes are deprecated, partially replaced for now, and will be fully replaced in 5.0 by xref::indexes-for-search-performance.adoc#indexes-future-indexes[future indexes].
In 4.4, b-tree indexes are still the correct alternative to use.

B-tree indexes used for string queries are replaced by:
[source, cypher, role="noheader", indent=0]
----
CREATE TEXT INDEX ...
----

B-tree indexes used for spatial queries will be replaced by:
[source, cypher, role="noheader", indent=0]
----
CREATE POINT INDEX ...
----

B-tree indexes used for general queries or property value types will be replaced by:
[source, cypher, role="noheader", indent=0]
----
CREATE RANGE INDEX ...
----

These new indexes may be combined for multiple use cases.

a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
CREATE INDEX
...
OPTIONS "{" btree-option: btree-value[, ...] "}"
----


a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
SHOW BTREE INDEXES
----
a|
B-tree indexes are deprecated, partially replaced for now, and will be fully replaced in 5.0 by xref::indexes-for-search-performance.adoc#indexes-future-indexes[future indexes].
In 4.4, b-tree indexes are still the correct alternative to use.

Replaced by the new and future index types:
[source, cypher, role="noheader", indent=0]
----
SHOW {POINT \| RANGE \| TEXT} INDEXES
----


a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT
...
OPTIONS "{" btree-option: btree-value[, ...] "}"
----
a|
Node key and uniqueness constraints with b-tree options are deprecated and will be replaced in 5.0 by range options, see xref::indexes-for-search-performance.adoc#indexes-future-indexes[range indexes].
In 4.4, the b-tree index-backed constraints are still the correct alternative to use.

Will be replaced by:
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT
...
OPTIONS "{" range-option: range-value[, ...] "}"
----
Constraints used for string properties will also require an additional text index to cover the string queries properly.
Constraints used for point properties will also require an additional point index to cover the spatial queries properly, see xref::indexes-for-search-performance.adoc#indexes-future-indexes[point indexes].


a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
distance(n.prop, point({x:0, y:0})
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
point.distance(n.prop, point({x:0, y:0})
----

a|
label:functionality[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
point({x:0, y:0}) <= point({x:1, y:1}) <= point({x:2, y:2})
----
a|
Using inequality operators `<`, `+<=+`, `>`, and `>=` on spatial points is deprecated.
Please instead use:
[source, cypher, role="noheader", indent=0]
----
point.withinBBox(point({x:1, y:1}), point({x:0, y:0}), point({x:2, y:2}))
----
|===

=== New features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CALL {
  ...
} IN TRANSACTIONS
----
a|
New clause for evaluating a subquery in separate transactions.
Typically used when modifying or importing large amounts of data.
See xref::clauses/call-subquery.adoc#subquery-call-in-transactions[+CALL { ... } IN TRANSACTIONS+].

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT FOR ... REQUIRE ...
----
a|
New syntax for creating constraints, applicable to all constraint types.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR (n:LabelName)
REQUIRE (n.propertyName_1, …, n.propertyName_n) IS UNIQUE
[OPTIONS "{" option: value[, ...] "}"]
----
a|
Unique property constraints now allow multiple properties, ensuring that the combination of property values are unique.

a|
label:functionality[]
label:new[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
DROP CONSTRAINT
ON (n:LabelName)
ASSERT (n.propertyName_1, …, n.propertyName_n) IS UNIQUE
----
a|
Unique property constraints now allow multiple properties.

Replaced by:
[source, cypher, role="noheader", indent=0]
----
DROP CONSTRAINT name [IF EXISTS]
----

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR ...
REQUIRE ... IS NOT NULL
OPTIONS "{" "}"
----
a|
Existence constraints now allow an `OPTIONS` map, however, at this point there are no available values for the map.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE LOOKUP INDEX [index_name] [IF NOT EXISTS]
FOR ... ON ...
OPTIONS "{" option: value[, ...] "}"
----
a|
Token lookup indexes now allow an `OPTIONS` map to specify the index provider.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE TEXT INDEX ...
----
a|
Allows creating text indexes on nodes or relationships with a particular label or relationship type, and property combination.
They can be dropped by using their name.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE RANGE INDEX ...
----
a|
xref::indexes-for-search-performance.adoc#indexes-future-indexes[FUTURE INDEX]: Allows creating range indexes on nodes or relationships with a particular label or relationship type, and properties combination.
They can be dropped by using their name.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT
...
OPTIONS "{" indexProvider: 'range-1.0' "}"
----
a|
xref::indexes-for-search-performance.adoc#indexes-future-indexes[FUTURE CONSTRAINT]: Allows creating node key and uniqueness constraints backed by range indexes by providing the range index provider in the `OPTIONS` map.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE POINT INDEX ...
----
a|
xref::indexes-for-search-performance.adoc#indexes-future-indexes[FUTURE INDEX]: Allows creating point indexes on nodes or relationships with a particular label or relationship type, and property combination.
They can be dropped by using their name.

a|
label:syntax[]
label:new[] +
New privilege:
[source, cypher, role="noheader", indent=0]
----
IMPERSONATE
----
a|
New privilege that allows a user to assume privileges of another one.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
SHOW TRANSACTION[S] [transaction-id[,...]]
[YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----
a|
List transactions on the current server.

The `transaction-id` is a comma-separated list of one or more quoted strings, a string parameter, or a list parameter.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
TERMINATE TRANSACTION[S] transaction-id[,...]
----
a|
Terminate transactions on the current server.

The `transaction-id` is a comma-separated list of one or more quoted strings, a string parameter, or a list parameter.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
ALTER DATABASE ...  [IF EXISTS]
SET ACCESS {READ ONLY \| READ WRITE}
----
a|
New Cypher command for modifying a database by changing its access mode.

a|
label:functionality[]
label:new[] +
New privilege:
[source, cypher, role="noheader", indent=0]
----
ALTER DATABASE
----
a|
New privilege that allows a user to modify databases.

a|
label:functionality[]
label:new[] +
New privilege:
[source, cypher, role="noheader", indent=0]
----
SET DATABASE ACCESS
----
a|
New privilege that allows a user to modify database access mode.
a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE ALIAS ... [IF NOT EXISTS]
FOR DATABASE ...
----
a|
New Cypher command for creating an alias for a database name. Remote aliases are only supported from version 4.4.8.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE OR REPLACE ALIAS ...
FOR DATABASE ...
----
a|
New Cypher command for creating or replacing an alias for a database name. Remote aliases are only supported from version 4.4.8.
a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
ALTER ALIAS ... [IF EXISTS]
SET DATABASE ...
----
a|
New Cypher command for altering an alias. Remote aliases are only supported from version 4.4.8.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
DROP ALIAS ... [IF EXISTS] FOR DATABASE
----
a|
New Cypher command for dropping a database alias.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
SHOW ALIASES FOR DATABASE
----
a|
New Cypher command for listing database aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[] +
New privilege:
[source, cypher, role="noheader", indent=0]
----
ALIAS MANAGEMENT
----
a|
New privilege that allows a user to create, modify, delete and list aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[] +
New privilege:
[source, cypher, role="noheader", indent=0]
----
CREATE ALIAS
----
a|
New privilege that allows a user to create aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[] +
New privilege:
[source, cypher, role="noheader", indent=0]
----
ALTER ALIAS
----
a|
New privilege that allows a user to modify aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[] +
New privilege:
[source, cypher, role="noheader", indent=0]
----
DROP ALIAS
----
a|
New privilege that allows a user to delete aliases. Only supported since version 4.4.8.

a|
label:functionality[]
label:new[] +
New privilege:
[source, cypher, role="noheader", indent=0]
----
SHOW ALIAS
----
a|
New privilege that allows a user to show aliases. Only supported since version 4.4.8.
|===


[[cypher-deprecations-additions-removals-4.3]]
== Version 4.3

=== Deprecated features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT [name]
ON (node:Label)
ASSERT exists(node.property)
----
a| Replaced by:
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT [name]
ON (node:Label)
ASSERT node.property IS NOT NULL
----


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT [name]
ON ()-[rel:REL]-()
ASSERT exists(rel.property)
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT [name]
ON ()-[rel:REL]-()
ASSERT rel.property IS NOT NULL
----


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
exists(prop)
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
prop IS NOT NULL
----


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
NOT exists(prop)
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
prop IS NULL
----

a|
label:syntax[]
label:deprecated[] +
`BRIEF [OUTPUT]` for `SHOW INDEXES` and `SHOW CONSTRAINTS`.
a|
Replaced by default output columns.


a|
label:syntax[]
label:deprecated[] +
`VERBOSE [OUTPUT]` for `SHOW INDEXES` and `SHOW CONSTRAINTS`.
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
YIELD *
----

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
SHOW EXISTS CONSTRAINTS
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
SHOW [PROPERTY] EXIST[ENCE] CONSTRAINTS
----
Still allows `BRIEF` and `VERBOSE` but not `YIELD` or `WHERE`.


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
SHOW NODE EXISTS CONSTRAINTS
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
SHOW NODE [PROPERTY] EXIST[ENCE] CONSTRAINTS
----
Still allows `BRIEF` and `VERBOSE` but not `YIELD` or `WHERE`.


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
SHOW RELATIONSHIP EXISTS CONSTRAINTS
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
SHOW RELATIONSHIP [PROPERTY] EXIST[ENCE] CONSTRAINTS
----
Still allows `BRIEF` and `VERBOSE` but not `YIELD` or `WHERE`.

a|
label:syntax[]
label:deprecated[] +
For privilege commands:
[source, cypher, role="noheader", indent=0]
----
ON DEFAULT DATABASE
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
ON HOME DATABASE
----


a|
label:syntax[]
label:deprecated[] +
For privilege commands:
[source, cypher, role="noheader", indent=0]
----
ON DEFAULT GRAPH
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
ON HOME GRAPH
----
|===

=== Updated features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
SHOW INDEXES WHERE ...
----
a|
Now allows filtering for:
[source, cypher, role="noheader", indent=0]
----
SHOW INDEXES
----


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
SHOW CONSTRAINTS WHERE ...
----
a|
Now allows filtering for:
[source, cypher, role="noheader", indent=0]
----
SHOW CONSTRAINTS
----


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
SHOW INDEXES YIELD ...
[WHERE ...]
[RETURN ...]
----
a|
Now allows `YIELD`, `WHERE`, and `RETURN` clauses to `SHOW INDEXES` to change the output.


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
SHOW CONSTRAINTS YIELD ...
[WHERE ...]
[RETURN ...]
----
a|
Now allows `YIELD`, `WHERE`, and `RETURN` clauses to `SHOW CONSTRAINTS` to change the output.


a|
label:syntax[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
SHOW [PROPERTY] EXIST[ENCE] CONSTRAINTS
----
a|
New syntax for filtering `SHOW CONSTRAINTS` on property existence constraints. +
Allows `YIELD` and `WHERE` but not `BRIEF` or `VERBOSE`.


a|
label:syntax[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
SHOW NODE [PROPERTY] EXIST[ENCE] CONSTRAINTS
----
a|
New syntax for filtering `SHOW CONSTRAINTS` on node property existence constraints. +
Allows `YIELD` and `WHERE` but not `BRIEF` or `VERBOSE`.


a|
label:syntax[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
SHOW REL[ATIONSHIP] [PROPERTY] EXIST[ENCE] CONSTRAINTS
----
a|
New syntax for filtering `SHOW CONSTRAINTS` on relationship property existence constraints. +
Allows `YIELD` and `WHERE` but not `BRIEF` or `VERBOSE`.


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
SHOW FULLTEXT INDEXES
----
a|
Now allows easy filtering for `SHOW INDEXES` on fulltext indexes. +
Allows `YIELD` and `WHERE` but not `BRIEF` or `VERBOSE`.


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
SHOW LOOKUP INDEXES
----
a|
Now allows easy filtering for `SHOW INDEXES` on token lookup indexes. +
Allows `YIELD` and `WHERE` but not `BRIEF` or `VERBOSE`.
|===

=== New features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE DATABASE ...
[OPTIONS {...}]
----
a|
New syntax to pass options to `CREATE DATABASE`.
This can be used to specify a specific cluster node to seed data from.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT [name]
ON (node:Label)
ASSERT node.property IS NOT NULL
----
a|
New syntax for creating node property existence constraints.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT [name]
ON ()-[rel:REL]-()
ASSERT rel.property IS NOT NULL
----
a|
New syntax for creating relationship property existence constraints.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
ALTER USER name IF EXISTS ...
----
a|
Makes altering users idempotent.
If the specified name does not exists, no error is thrown.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
ALTER USER ...
SET HOME DATABASE ...
----
a|
Now allows setting home database for user.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
ALTER USER ...
REMOVE HOME DATABASE
----
a|
Now allows removing home database for user.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE USER ...
SET HOME DATABASE ...
----
a|
`CREATE USER` now allows setting home database for user.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
SHOW HOME DATABASE
----
a|
New syntax for showing the home database of the current user.


a|
label:syntax[]
label:new[] +
New privilege:
[source, cypher, role="noheader", indent=0]
----
SET USER HOME DATABASE
----
a|
New Cypher command for administering privilege for changing users home database.


a|
label:syntax[]
label:new[] +
For privilege commands:
[source, cypher, role="noheader", indent=0]
----
ON HOME DATABASE
----
a|
New syntax for privileges affecting home database.


a|
label:syntax[]
label:new[] +
For privilege commands:
[source, cypher, role="noheader", indent=0]
----
ON HOME GRAPH
----
a|
New syntax for privileges affecting home graph.

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE FULLTEXT INDEX ...
----
a|
Allows creating fulltext indexes on nodes or relationships.
They can be dropped by using their name.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE INDEX FOR ()-[r:TYPE]-() ...
----
a|
Allows creating indexes on relationships with a particular relationship type and property combination.
They can be dropped by using their name.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE LOOKUP INDEX ...
----
a|
Create token lookup index for nodes with any labels or relationships with any relationship type.
They can be dropped by using their name.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
RENAME ROLE
----
a|
New Cypher command for changing the name of a role.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
RENAME USER
----
a|
New Cypher command for changing the name of a user.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
SHOW PROCEDURE[S]
[EXECUTABLE [BY {CURRENT USER \| username}]]
[YIELD ...]
[WHERE ...]
[RETURN ...]
----
a|
New Cypher commands for listing procedures.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
SHOW [ALL \| BUILT IN \| USER DEFINED] FUNCTION[S]
[EXECUTABLE [BY {CURRENT USER \| username}]]
[YIELD ...]
[WHERE ...]
[RETURN ...]
----
a|
New Cypher commands for listing functions.

|===

[[cypher-deprecations-additions-removals-4.2]]
== Version 4.2

=== Deprecated features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
0...
----
a|
Replaced by `+0o...+`.


a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
0X...
----
a|
Only `+0x...+` (lowercase x) is supported.

a|
label:procedure[]
label:deprecated[]
[source, role="noheader", indent=0]
----
db.createIndex
----
a|
Replaced by `CREATE INDEX` command.


a|
label:procedure[]
label:deprecated[]
[source, role="noheader", indent=0]
----
db.createNodeKey
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT ... IS NODE KEY
----


a|
label:procedure[]
label:deprecated[]
[source, role="noheader", indent=0]
----
db.createUniquePropertyConstraint
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT ... IS UNIQUE
----

a|
label:procedure[]
label:deprecated[]
[source, role="noheader", indent=0]
----
db.indexes
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
SHOW INDEXES
----


a|
label:procedure[]
label:deprecated[]
[source, role="noheader", indent=0]
----
db.indexDetails
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
SHOW INDEXES YIELD *
----


a|
label:procedure[]
label:deprecated[]
[source, role="noheader", indent=0]
----
db.constraints
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
SHOW CONSTRAINTS
----


a|
label:procedure[]
label:deprecated[]
[source, role="noheader", indent=0]
----
db.schemaStatements
----
a|
Replaced by:
[source, cypher, role="noheader", indent=0]
----
SHOW INDEXES YIELD *
----
[source, cypher, role="noheader", indent=0]
----
SHOW CONSTRAINTS YIELD *
----
|===

=== Updated features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
SHOW ROLE name PRIVILEGES
----
a|
Can now handle multiple roles.
[source, cypher, role="noheader", indent=0]
----
SHOW ROLES n1, n2, ... PRIVILEGES
----


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
SHOW USER name PRIVILEGES
----
a|
Can now handle multiple users.
[source, cypher, role="noheader", indent=0]
----
SHOW USERS n1, n2, ... PRIVILEGES
----


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
round(expression, precision)
----
a|
The `round()` function can now take an additional argument to specify rounding precision.


a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
round(expression, precision, mode)
----
a|
The `round()` function can now take two additional arguments to specify rounding precision and rounding mode.
|===

=== New features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
SHOW PRIVILEGES [AS [REVOKE] COMMAND[S]]
----
a|
Privileges can now be shown as Cypher commands.

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
DEFAULT GRAPH
----
a|
New optional part of the Cypher commands for xref::access-control/database-administration.adoc[database privileges].


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
0o...
----
a|
Cypher now interprets literals with prefix `0o` as an octal integer literal.

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
SET [PLAINTEXT \| ENCRYPTED] PASSWORD
----
a|
For `CREATE USER` and `ALTER USER`, it is now possible to set (or update) a password when the plaintext password is unknown, but the encrypted password is available.


a|
label:functionality[]
label:new[] +
New privilege:
[source, cypher, role="noheader", indent=0]
----
EXECUTE
----
a|
New Cypher commands for administering privileges for executing procedures and user defined functions.
See xref::access-control/dbms-administration.adoc#access-control-dbms-administration-execute[The DBMS `EXECUTE` privileges].


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE [BTREE] INDEX ... [OPTIONS {...}]
----
a|
Allows setting index provider and index configuration when creating an index.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT ... IS NODE KEY [OPTIONS {...}]
----
a|
Allows setting index provider and index configuration for the backing index when creating a node key constraint.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT ... IS UNIQUE [OPTIONS {...}]
----
a|
Allows setting index provider and index configuration for the backing index when creating a uniqueness constraint.

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
SHOW CURRENT USER
----
a|
New Cypher command for showing current logged-in user and roles.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
SHOW [ALL \| BTREE] INDEX[ES] [BRIEF \| VERBOSE [OUTPUT]]
----
a|
New Cypher commands for listing indexes.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
SHOW [ALL \| UNIQUE \| NODE EXIST[S] \| RELATIONSHIP EXIST[S] \| EXIST[S] \| NODE KEY] CONSTRAINT[S] [BRIEF \| VERBOSE [OUTPUT]]
----
a|
New Cypher commands for listing constraints.

a|
label:functionality[]
label:new[] +
New privilege:
[source, cypher, role="noheader", indent=0]
----
SHOW INDEX
----
a|
New Cypher command for administering privilege for listing indexes.


a|
label:functionality[]
label:new[] +
New privilege:
[source, cypher, role="noheader", indent=0]
----
SHOW CONSTRAINT
----
a|
New Cypher command for administering privilege for listing constraints.
|===

[[cypher-deprecations-additions-removals-4.1.3]]
== Version 4.1.3


=== New features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE INDEX [name] IF NOT EXISTS FOR ...
----
a|
Makes index creation idempotent. If an index with the name or schema already exists no error will be thrown.

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
DROP INDEX name IF EXISTS
----
a|
Makes index deletion idempotent. If no index with the name exists no error will be thrown.

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT [name] IF NOT EXISTS ON ...
----
a|
Makes constraint creation idempotent. If a constraint with the name or type and schema already exists no error will be thrown.

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
DROP CONSTRAINT name IF EXISTS
----
a|
Makes constraint deletion idempotent. If no constraint with the name exists no error will be thrown.

|===

[[cypher-deprecations-additions-removals-4.1]]
== Version 4.1

=== Restricted features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:functionality[]
label:restricted[]
[source, cypher, role="noheader", indent=0]
----
REVOKE ...
----
a|
No longer revokes sub-privileges when revoking a compound privilege, e.g. when revoking `INDEX MANAGEMENT`, any `CREATE INDEX` and `DROP INDEX` privileges will no longer be revoked.

a|
label:functionality[]
label:restricted[]
[source, cypher, role="noheader", indent=0]
----
ALL DATABASE PRIVILEGES
----
a|
No longer includes the privileges `START DATABASE` and `STOP DATABASE`.
|===

=== Updated features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:procedure[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
queryId
----
a|
The `queryId` procedure format has changed, and no longer includes the database name. For example, `mydb-query-123` is now `query-123`. This change affects built-in procedures `dbms.listQueries()`, `dbms.listActiveLocks(queryId)`, `dbms.killQueries(queryIds)` `and dbms.killQuery(queryId)`.

a|
label:functionality[]
label:updated[]
[source, cypher, role="noheader", indent=0]
----
SHOW PRIVILEGES
----
a|
The returned privileges are a closer match to the original grants and denies, e.g. if granted `MATCH` the command will show that specific privilege and not the `TRAVERSE` and `READ` privileges. Added support for `YIELD` and `WHERE` clauses to allow filtering results.
|===

=== New features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:functionality[]
label:new[] +
New role:
[source, cypher, role="noheader", indent=0]
----
PUBLIC
----
a|
The `PUBLIC` role is automatically assigned to all users, giving them a set of base privileges.

a|
label:syntax[]
label:new[] +
For privileges:
[source, cypher, role="noheader", indent=0]
----
REVOKE MATCH
----
a|
The `MATCH` privilege can now be revoked.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
SHOW USERS
----
a|
New support for `YIELD` and `WHERE` clauses to allow filtering results.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
SHOW ROLES
----
a|
New support for `YIELD` and `WHERE` clauses to allow filtering results.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
SHOW DATABASES
----
a|
New support for `YIELD` and `WHERE` clauses to allow filtering results.

a|
label:functionality[]
label:new[] +
xref::access-control/database-administration.adoc#access-control-database-administration-transaction[TRANSACTION MANAGEMENT] privileges
a|
New Cypher commands for administering transaction management.

a|
label:functionality[]
label:new[] +
DBMS xref::access-control/dbms-administration.adoc#access-control-dbms-administration-user-management[USER MANAGEMENT] privileges
a|
New Cypher commands for administering user management.

a|
label:functionality[]
label:new[] +
DBMS xref::access-control/dbms-administration.adoc#access-control-dbms-administration-database-management[DATABASE MANAGEMENT] privileges
a|
New Cypher commands for administering database management.


a|
label:functionality[]
label:new[] +
DBMS xref::access-control/dbms-administration.adoc#access-control-dbms-administration-privilege-management[PRIVILEGE MANAGEMENT] privileges
a|
New Cypher commands for administering privilege management.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
ALL DBMS PRIVILEGES
----
a|
New Cypher command for administering role, user, database and privilege management.


a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
ALL GRAPH PRIVILEGES
----
a|
New Cypher command for administering read and write privileges.

a|
label:functionality[]
label:new[] +
Write privileges
a|
New Cypher commands for administering write privileges.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
ON DEFAULT DATABASE
----
a|
New optional part of the Cypher commands for xref::access-control/database-administration.adoc[database privileges].
|===

[[cypher-deprecations-additions-removals-4.0]]
== Version 4.0

=== Removed features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:function[]
label:removed[]
[source, cypher, role="noheader", indent=0]
----
rels()
----
a|
Replaced by xref::functions/list.adoc#functions-relationships[relationships()].

a|
label:function[]
label:removed[]
[source, cypher, role="noheader", indent=0]
----
toInt()
----
a|
Replaced by xref::functions/scalar.adoc#functions-tointeger[toInteger()].

a|
label:function[]
label:removed[]
[source, cypher, role="noheader", indent=0]
----
lower()
----
a|
Replaced by xref::functions/string.adoc#functions-tolower[toLower()].

a|
label:function[]
label:removed[]
[source, cypher, role="noheader", indent=0]
----
upper()
----
a|
Replaced by xref::functions/string.adoc#functions-toupper[toUpper()].

a|
label:function[]
label:removed[]
[source, cypher, role="noheader", indent=0]
----
extract()
----
a|
Replaced by xref::syntax/lists.adoc#cypher-list-comprehension[list comprehension].

a|
label:function[]
label:removed[]
[source, cypher, role="noheader", indent=0]
----
filter()
----
a|
Replaced by xref::syntax/lists.adoc#cypher-list-comprehension[list comprehension].

a|
label:functionality[]
label:removed[] +
For Rule planner:
[source, cypher, role="noheader", indent=0]
----
CYPHER planner=rule
----
a|
The `RULE` planner was removed in 3.2, but still possible to trigger using `START` or `CREATE UNIQUE` clauses. Now it is completely removed.


a|
label:functionality[]
label:removed[] +
Explicit indexes
a|
The removal of the `RULE` planner in 3.2 was the beginning of the end for explicit indexes. Now they are completely removed, including the removal of the link:https://neo4j.com/docs/cypher-manual/3.5/schema/index/#explicit-indexes-procedures[built-in procedures for Neo4j 3.3 to 3.5].


a|
label:functionality[]
label:removed[] +
For compiled runtime:
[source, cypher, role="noheader", indent=0]
----
CYPHER runtime=compiled
----
a|
Replaced by the new `pipelined` runtime which covers a much wider range of queries.


a|
label:clause[]
label:removed[]
[source, cypher, role="noheader", indent=0]
----
CREATE UNIQUE
----
a|
Running queries with this clause will cause a syntax error. Running with `CYPHER 3.5` will cause a runtime error due to the removal of the rule planner.

a|
label:clause[]
label:removed[]
[source, cypher, role="noheader", indent=0]
----
START
----
a|
Running queries with this clause will cause a syntax error. Running with `CYPHER 3.5` will cause a runtime error due to the removal of the rule planner.

a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader", indent=0]
----
MATCH (n)-[:A\|:B\|:C {foo: 'bar'}]-() RETURN n
----
a|
Replaced by `MATCH (n)-[:A\|B\|C {foo: 'bar'}]-() RETURN n`.

a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader", indent=0]
----
MATCH (n)-[x:A\|:B\|:C]-() RETURN n
----
a|
Replaced by `MATCH (n)-[x:A\|B\|C]-() RETURN n`.


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader", indent=0]
----
MATCH (n)-[x:A\|:B\|:C*]-() RETURN n
----
a|
Replaced by `MATCH (n)-[x:A\|B\|C*]-() RETURN n`.


a|
label:syntax[]
label:removed[]
[source, cypher, role="noheader", indent=0]
----
{parameter}
----
a|
Replaced by xref::syntax/parameters.adoc[$parameter].
|===

=== Deprecated features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
MATCH (n)-[rs*]-() RETURN rs
----
a|
As in Cypher 3.2, this is replaced by:
[source, cypher, role="noheader", indent=0]
----
MATCH p=(n)-[*]-() RETURN relationships(p) AS rs
----

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
CREATE INDEX ON :Label(prop)
----
a|
Replaced by `CREATE INDEX FOR (n:Label) ON (n.prop)`.

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
DROP INDEX ON :Label(prop)
----
a|
Replaced by `DROP INDEX name`.

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
DROP CONSTRAINT ON (n:Label) ASSERT (n.prop) IS NODE KEY
----
a|
Replaced by `DROP CONSTRAINT name`.

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
DROP CONSTRAINT ON (n:Label) ASSERT (n.prop) IS UNIQUE
----
a|
Replaced by `DROP CONSTRAINT name`.

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
DROP CONSTRAINT ON (n:Label) ASSERT exists(n.prop)
----
a|
Replaced by `DROP CONSTRAINT name`.

a|
label:syntax[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
DROP CONSTRAINT ON ()-[r:Type]-() ASSERT exists(r.prop)
----
a|
Replaced by `DROP CONSTRAINT name`.

|===

=== Restricted features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:function[]
label:restricted[]
[source, cypher, role="noheader", indent=0]
----
length()
----
a|
Restricted to only work on paths. See xref::functions/scalar.adoc#functions-length[length()] for more details.

a|
label:function[]
label:restricted[]
[source, cypher, role="noheader", indent=0]
----
size()
----
a|
No longer works for paths. Only works for strings, lists and pattern expressions. See xref::functions/scalar.adoc[size()] for more details.
|===

=== Updated features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:syntax[]
label:extended[]
[source, cypher, role="noheader", indent=0]
----
CREATE CONSTRAINT [name] ON ...
----
a|
The create constraint syntax can now include a name.

|===
=== New features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:functionality[]
label:new[] +
Pipelined runtime:
[source, cypher, role="noheader", indent=0]
----
CYPHER runtime=pipelined
----
a|
This Neo4j Enterprise Edition only feature involves a new runtime that has many performance enhancements.

a|
label:functionality[]
label:new[] +
xref::databases.adoc[Multi-database administration]
a|
New Cypher commands for administering multiple databases.

a|
label:functionality[]
label:new[] +
xref::access-control/index.adoc[Access control]
a|
New Cypher commands for administering role-based access control.

a|
label:functionality[]
label:new[] +
xref::access-control/manage-privileges.adoc[Fine-grained security]
a|
New Cypher commands for administering dbms, database, graph and sub-graph access control.

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
CREATE INDEX [name] FOR (n:Label) ON (n.prop)
----
a|
New syntax for creating indexes, which can include a name.

a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
DROP INDEX name
----
a|
xref::indexes-for-search-performance.adoc#administration-indexes-drop-an-index[New command] for dropping an index by name.


a|
label:syntax[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
DROP CONSTRAINT name
----
a|
xref::constraints/syntax.adoc#administration-constraints-syntax-drop[New command] for dropping a constraint by name, no matter the type.


a|
label:clause[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
WHERE EXISTS {...}
----
a|
Existential sub-queries are sub-clauses used to filter the results of a `MATCH`, `OPTIONAL MATCH`, or `WITH` clause.

a|
label:clause[]
label:new[]
[source, cypher, role="noheader", indent=0]
----
USE neo4j
----
a|
New clause to specify which graph a query, or query part, is executed against.

|===


[[cypher-deprecations-additions-removals-3.5]]
== Version 3.5

=== Deprecated features

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:functionality[]
label:deprecated[] +
Compiled runtime:
[source, cypher, role="noheader", indent=0]
----
CYPHER runtime=compiled
----
a|
The compiled runtime will be discontinued in the next major release. It might still be used for default queries in order to not cause regressions, but explicitly requesting it will not be possible.

a|
label:function[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
extract()
----
a|
Replaced by xref::syntax/lists.adoc#cypher-list-comprehension[list comprehension].

a|
label:function[]
label:deprecated[]
[source, cypher, role="noheader", indent=0]
----
filter()
----
a|
Replaced by xref::syntax/lists.adoc#cypher-list-comprehension[list comprehension].
|===


[[cypher-deprecations-additions-removals-3.4]]
== Version 3.4
[options="header"]
|===
| Feature          | Type | Change | Details
| xref::syntax/spatial.adoc[Spatial point types] | Functionality | Amendment | A point -- irrespective of which Coordinate Reference System is used -- can be stored as a property and is able to be backed by an index. Prior to this, a point was a virtual property only.
| xref::functions/spatial.adoc#functions-point-cartesian-3d[point() - Cartesian 3D] | Function | Added |
| xref::functions/spatial.adoc#functions-point-wgs84-3d[point() - WGS 84 3D] | Function | Added |
| xref::functions/scalar.adoc#functions-randomuuid[randomUUID()] | Function | Added |
| xref::syntax/temporal.adoc[Temporal types]  | Functionality | Added | Supports storing, indexing and working with the following temporal types: Date, Time, LocalTime, DateTime, LocalDateTime and Duration.
| xref::functions/temporal/index.adoc[Temporal functions]  | Functionality | Added | Functions allowing for the creation and manipulation of values for each temporal type -- _Date_, _Time_, _LocalTime_, _DateTime_, _LocalDateTime_ and _Duration_.
| xref::syntax/operators.adoc#query-operators-temporal[Temporal operators]  | Functionality | Added | Operators allowing for the manipulation of values for each temporal type -- _Date_, _Time_, _LocalTime_, _DateTime_, _LocalDateTime_ and _Duration_.
|  xref::functions/string.adoc#functions-tostring[toString()]   | Function  | Extended | Now also allows temporal values as input (i.e. values of type _Date_, _Time_, _LocalTime_, _DateTime_, _LocalDateTime_ or _Duration_).
|===


[[cypher-deprecations-additions-removals-3.3]]
== Version 3.3
[options="header"]
|===
| Feature          | Type | Change | Details
| `START`          | Clause | Removed | As in Cypher 3.2, any queries using the `START` clause will revert back to Cypher 3.1 `planner=rule`.
However, there are link:https://neo4j.com/docs/cypher-manual/3.5/schema/index/#explicit-indexes-procedures[built-in procedures for Neo4j versions 3.3 to 3.5] for accessing explicit indexes. The procedures will enable users to use the current version of Cypher and the cost planner together with these indexes.
An example of this is `CALL db.index.explicit.searchNodes('my_index','email:me*')`.
| `CYPHER runtime=slotted` (Faster interpreted runtime) | Functionality | Added | Neo4j Enterprise Edition only
| xref::functions/aggregating.adoc#functions-max[max()], xref::functions/aggregating.adoc#functions-min[min()] | Function  | Extended | Now also supports aggregation over sets containing lists of strings and/or numbers, as well as over sets containing strings, numbers, and lists of strings and/or numbers
|===


[[cypher-deprecations-additions-removals-3.2]]
== Version 3.2
[options="header"]
|===
| Feature          | Type | Change | Details
| `CYPHER planner=rule` (Rule planner)    | Functionality | Removed | All queries now use the cost planner. Any query prepended thus will fall back to using Cypher 3.1.
| `CREATE UNIQUE`     | Clause | Removed | Running such queries will fall back to using Cypher 3.1 (and use the rule planner)
| `START`     | Clause | Removed | Running such queries will fall back to using Cypher 3.1 (and use the rule planner)
| `MATCH (n)-[rs*]-() RETURN rs`     | Syntax | Deprecated | Replaced by `MATCH p=(n)-[*]-() RETURN relationships(p) AS rs`
| `MATCH (n)-[:A\|:B\|:C {foo: 'bar'}]-() RETURN n`     | Syntax | Deprecated | Replaced by `MATCH (n)-[:A\|B\|C {foo: 'bar'}]-() RETURN n`
| `MATCH (n)-[x:A\|:B\|:C]-() RETURN n`     | Syntax | Deprecated | Replaced by `MATCH (n)-[x:A\|B\|C]-() RETURN n`
| `MATCH (n)-[x:A\|:B\|:C*]-() RETURN n`     | Syntax | Deprecated | Replaced by `MATCH (n)-[x:A\|B\|C*]-() RETURN n`
| xref:4.4@java-reference:ROOT:extending-neo4j/aggregation-functions.adoc#extending-neo4j-aggregation-functions[User-defined aggregation functions] | Functionality | Added |
| xref::indexes-for-search-performance.adoc[Composite indexes] | Index | Added |
| xref::constraints/examples.adoc#administration-constraints-node-key[Node Key] | Index | Added | Neo4j Enterprise Edition only
| `CYPHER runtime=compiled` (Compiled runtime) | Functionality | Added | Neo4j Enterprise Edition only
| xref::functions/list.adoc#functions-reverse-list[reverse()] | Function  | Extended | Now also allows a list as input
| xref::functions/aggregating.adoc#functions-max[max()], xref::functions/aggregating.adoc#functions-min[min()] | Function  | Extended | Now also supports aggregation over a set containing both strings and numbers
|===


[[cypher-deprecations-additions-removals-3.1]]
== Version 3.1
[options="header"]
|===
| Feature     | Type | Change | Details
| `rels()`    | Function  | Deprecated | Replaced by xref::functions/list.adoc#functions-relationships[relationships()]
| `toInt()`   | Function  | Deprecated | Replaced by xref::functions/scalar.adoc#functions-tointeger[toInteger()]
| `lower()`   | Function  | Deprecated | Replaced by xref::functions/string.adoc#functions-tolower[toLower()]
| `upper()`   | Function  | Deprecated | Replaced by xref::functions/string.adoc#functions-toupper[toUpper()]
| xref::functions/scalar.adoc#functions-toboolean[toBoolean()] | Function | Added |
| xref::syntax/maps.adoc#cypher-map-projection[Map projection] | Syntax | Added |
| xref::syntax/lists.adoc#cypher-pattern-comprehension[Pattern comprehension] | Syntax | Added |
| xref:4.4@java-reference:ROOT:extending-neo4j/functions.adoc#extending-neo4j-functions[User-defined functions] | Functionality | Added |
| xref::clauses/call.adoc[CALL\...YIELD\...WHERE]   | Clause  | Extended  | Records returned by `YIELD` may be filtered further using `WHERE`
|===


[[cypher-deprecations-additions-removals-3.0]]
== Version 3.0
[options="header"]
|===
| Feature          | Type | Change | Details
| `has()`  | Function  | Removed | Replaced by xref::functions/predicate.adoc#functions-exists[exists()]
| `str()`  | Function  | Removed | Replaced by xref::functions/string.adoc#functions-tostring[toString()]
| `+{parameter}+` | Syntax | Deprecated | Replaced by xref::syntax/parameters.adoc[$parameter]
| xref::functions/scalar.adoc#functions-properties[properties()]  | Function  | Added  |
| xref::clauses/call.adoc[CALL [\...YIELD\]]   | Clause  | Added  |
| xref::functions/spatial.adoc#functions-point-cartesian-2d[point() - Cartesian 2D] | Function | Added |
| xref::functions/spatial.adoc#functions-point-wgs84-2d[point() - WGS 84 2D] | Function | Added |
| xref::functions/spatial.adoc#functions-distance[distance()] | Function | Added |
| xref:4.4@java-reference:ROOT:extending-neo4j/procedures.adoc#extending-neo4j-procedures[User-defined procedures] | Functionality | Added |
| xref::functions/string.adoc#functions-tostring[toString()]   | Function  | Extended | Now also allows Boolean values as input
|===


[[cypher-compatibility]]
== Compatibility

[NOTE]
====
Neo4j’s ability to support multiple older versions of the Cypher language has changed over time.
In versions prior to Neo4j 3.4, the backwards compatibility layer included the Cypher language parser, planner, and runtime.
All supported versions of Cypher ran on the same Neo4j kernel.
However, this changed in Neo4j 3.4 when the runtime was excluded from the compatibility layer.
When you run, e.g. a `CYPHER 3.1` query in Neo4j 3.5, the query is planned with the 3.1 planner, but run with 3.5 runtime and kernel.
The compatibility layer changed again in Neo4j 4.0 and it now includes only the Cypher language parser.
When you run a `CYPHER 3.5` query, e.g., in Neo4j 4.4, Neo4j parses the older language features, but uses the 4.4 planner, runtime, and kernel to plan and run the query.
The primary reason for these changes is the optimizations in the Cypher runtime to allow Cypher queries to perform better.
====

Older versions of the language can still be accessed if required.
There are two ways to select which version to use in queries.

. Setting a version for all queries:
You can configure your database with the configuration parameter `cypher.default_language_version`, and enter which version you'd like to use (see xref::deprecations-additions-removals-compatibility.adoc#cypher-versions[]).
Every Cypher query will use this version, provided the query hasn't explicitly been configured as described in the next item below.

. Setting a version on a query by query basis:
The other method is to set the version for a particular query.
Prepending a query with `CYPHER 3.5` will execute the query with the version of Cypher included in Neo4j 3.5.

Below is an example using the older parameter syntax `+{param}+`:

[source, cypher, role="nocopy,norun", indent=0]
----
CYPHER 3.5
MATCH (n:Person)
WHERE n.age > {agelimit}
RETURN n.name, n.age
----

Without the `CYPHER 3.5` prefix this query would fail with a syntax error. With `CYPHER 3.5` however, it will only generate a warning and still work.

[WARNING]
====
In Neo4j {neo4j-version} the Cypher parser understands some older language features, even if they are no longer supported by the Neo4j kernel.
These features result in runtime errors.
See the table at xref::deprecations-additions-removals-compatibility.adoc#cypher-deprecations-additions-removals-4.0[Cypher Version 4.0] for the list of affected features.
====


[[cypher-versions]]
== Supported language versions

Neo4j {neo4j-version} supports the following versions of the Cypher language:

* Neo4j Cypher 3.5
* Neo4j Cypher 4.3
* Neo4j Cypher 4.4

[TIP]
====
Each release of Neo4j supports a limited number of old Cypher Language Versions.
When you upgrade to a new release of Neo4j, please make sure that it supports the Cypher language version you need.
If not, you may need to modify your queries to work with a newer Cypher language version.
====
