:description: This is the Cypher Query Language documentation for Neo4j, authored by the Neo4j Team.

[[cypher-manual]]
= The Neo4j Cypher Manual v{neo4j-version}
:sectnums:

:neo4j-buildnumber: {neo4j-version}

Cypher is Neo4j graph query language that allows users to store and retrieve data from the graph database.
It is a declarative, SQL-inspired language for describing visual patterns in graphs.
The syntax provides a visual and logical way to match patterns of nodes and relationships in the graph.

This manual is written for the developer of a Neo4j client application.

[NOTE]
====
For information on upgrading and migrating Neo4j, see link:{upgrade-current-uri}/[Neo4j Upgrade and Migration Guide]. +
For instructions on how to install and deploy Neo4j, see link:https://neo4j.com/docs/operations-manual/current/[the Neo4j Operations Manual]. +
*Neo4j AuraDB* is a fully managed Neo4j database, hosted in the cloud and requires no installation.
For more information, see the link:https://neo4j.com/aura/[AuraDB product page] and link:https://neo4j.com/docs/aura/current/[AuraDB documentation].
====

== Documentation updates for Neo4j 5

* Cypher syntax improvements. 
Graph Pattern Matching -- relationship and label patterns.
This is part of the Graph Pattern Matching long-term effort in Cypher.
+
** In `MATCH` clauses, `WHERE` can be placed inside a relationship pattern to filter relationships.
You can learn more in the section on xref:clauses/where.adoc[`WHERE` clause]. 
** In `MATCH` clauses, nodes, and relationships can be filtered using more sophisticated label (type) expressions.
** Simpler alternative syntax to navigate and traverse your graph.
Support new syntax for expressing node labels.
New operators include:
*** `&`: logical `AND`
*** `|`: logical `OR`
*** `!`: logical `NOT`
*** `%`: a "wildcard", meaning "any label" (in Cypher this translates to `size(labels(n)) > 0`). +
You can find more details in the xref:syntax/expressions.adoc#label-expressions[section on Label expressions].

* New `elementID` for graph objects.
+
New IDs are introduced to uniquely identify graph elements in Neo4j databases. 
Node ID will exist throughout Neo4j 5.x series. +
See xref::functions/scalar.adoc#functions-elementid[elementId() section] for the reference.

* Composite databases. 
+
Cypher’s *COMPOSITE DATABASE* provides real time Fabric configuration (Enterprise) -- create, update, and remove Fabric configurations without a restart, whether the database is within the same Autonomous Cluster, or hosted remotely. +
See instructions on how to create composite databases xref::databases.adoc#administration-databases-create-composite-database[in the corresponding section].
You can refer also to the xref::deprecations-additions-removals-compatibility.adoc#_new_features[list of new features].

* Immutable privileges. 
+
Immutable privileges are useful for restricting the actions of users who themselves are able to administer privileges. +
Visit xref::access-control/privileges-immutable.adoc[the Immutable privileges section] to learn how to use Cypher to manage them. +

* `Execute` and `ExecuteBoosted` privileges review. 
+
Refresh of permissions for the execution of admin procedures.
These two privileges are now hierarchical related. +
Read more about xref::access-control/dbms-administration.adoc#access-control-execute-procedure[the `EXECUTE PROCEDURE` privilege] and xref::access-control/dbms-administration.adoc#access-control-execute-boosted-procedure[the `EXECUTE BOOSTED PROCEDURE` privilege].

* `EXISTS` and `COUNT` are now both expressions.
+
More information is in the xref::syntax/expressions.adoc#cypher-subquery-expressions[Subquery expressions section].

* `SHOW` and `TERMINATE TRANSACTIONS` improvements.
+
Now you are able to combine these two commands in the same query.
The ability to yield and filter the output from `TERMINATE TRANSACTIONS` has been added. +
// More information about running transaction and better control over the termination of existing transactions, especially in the light of the new `CALL … {} … IN TRANSACTIONS` clauses. +
See more information in the section xref::deprecations-additions-removals-compatibility.adoc#_updated_features[Updated features].

* Changes to Neo4j indexes
+
** The B-tree index type has been removed. 
** New Range and Point index types are available now.
** Faster Text index provider for `ENDS WITH` and `CONTAINS` queries is introduced.
** Full-text indexes can now index lists of strings.

+ 
Learn more about xref::indexes-for-search-performance.adoc[new index types]. +


ifdef::backend-html5[(C) {copyright}]
ifndef::backend-pdf[]

Documentation license: link:{common-license-page-uri}[Creative Commons 4.0]
endif::[]
ifdef::backend-pdf[]
(C) {copyright}

Documentation license: <<license, Creative Commons 4.0>>
endif::[]

ifdef::backend-pdf[]
include::license.adoc[leveloffset=+1]
endif::[]


