:description: This is the Cypher Query Language documentation for Neo4j, authored by the Neo4j Team.

[[cypher-manual]]
= The Neo4j Cypher Manual {neo4j-version}
:neo4j-buildnumber: {neo4j-version-minor}

Cypher is Neo4j's graph query language that allows users to store and retrieve data from the graph database.
It is a declarative, SQL-inspired language for describing visual patterns in graphs.
The syntax provides a visual and logical way to match patterns of nodes and relationships in the graph.


== Documentation updates for Neo4j 5

Neo4j {neo4j-version} includes a number of new features and updates.
A highlight of these include:

* Cypher syntax improvements with Graph Pattern Matching (relationships and labels):
+
** In `MATCH` clauses, `WHERE` can be placed inside a relationship pattern to filter relationships.
** In `MATCH` clauses, nodes and relationships can be filtered using more sophisticated label (type) expressions.
** Simpler alternative syntax to navigate and traverse graphs using the following operators:
*** `&`: logical `AND`
*** `|`: logical `OR`
*** `!`: logical `NOT`
*** `%`: a "wildcard", meaning "any label" (in Cypher this translates to `size(labels(n)) > 0`). +

+
For more information, see the xref:syntax/expressions.adoc#label-expressions[section on Label expressions] and in xref:clauses/where.adoc[the `WHERE` clause].

* New `elementID` for graph objects:
+
New IDs are introduced to uniquely identify graph elements in Neo4j databases. 
Node ID will exist with each release of Neo4j {neo4j-version}. 
+
For more information, see xref:functions/scalar.adoc#functions-elementid[`elementId()`].

* Composite databases.
+
Composite databases allow queries that access multiple graphs at once. 
You can create, update, and remove configurations without a restart, whether the database is within the same cluster, or hosted remotely. 
+
For more information on composite databases, and how to create composite databases, see link:https://neo4j.com/docs/operations-manual/current/composite-databases/[Operations Manual -> Composite databases], and xref:databases.adoc#administration-databases-create-composite-database[Creating composite databases].

* Immutable privileges. 
+
Immutable privileges are useful for restricting the actions of users who themselves are able to administer privileges. +
For more information, see xref:access-control/privileges-immutable.adoc[Immutable privileges].

* `Execute` and `ExecuteBoosted` privilege.
+
The permissions for the execution of admin procedures have been refreshed; these two privileges are now hierarchically related. 
+
For more information, see xref:access-control/dbms-administration.adoc#access-control-execute-procedure[the `EXECUTE PROCEDURE` privilege] and xref:access-control/dbms-administration.adoc#access-control-execute-boosted-procedure[the `EXECUTE BOOSTED PROCEDURE` privilege].

* `EXISTS` and `COUNT` are now both expressions.
+
For more information, see xref:syntax/expressions.adoc#cypher-subquery-expressions[Subquery expressions].

* `SHOW` and `TERMINATE TRANSACTIONS` improvements.
+
You can now combine these two commands in the same query.
The ability to yield and filter the output from `TERMINATE TRANSACTIONS` has been added. 
+
For more information, see xref:deprecations-additions-removals-compatibility.adoc#_updated_features[Updated features list].

* Changes to Neo4j indexes:
+
** The B-tree index type has been removed. 
** New Range and Point index types are available now.
** Faster Text index provider for `ENDS WITH` and `CONTAINS` queries is introduced.
** Full-text indexes can now index lists of strings.

+ 
For more information, see xref:indexes-for-search-performance.adoc[new index types]. 


ifdef::backend-html5[(C) {copyright}]
ifndef::backend-pdf[]

Documentation license: link:{common-license-page-uri}[Creative Commons 4.0]
endif::[]
ifdef::backend-pdf[]
(C) {copyright}

Documentation license: <<license, Creative Commons 4.0>>
endif::[]

ifdef::backend-pdf[]
include::license.adoc[leveloffset=+1]
endif::[]


