:description: Overview about Cypher's compliance to GQL.

= GQL compliance

GQL is the new link:xhttps://www.iso.org/home.html[ISO] International Standard query language for graph databases.

GQL has adopted much of Cypher’s query construction semantics, such as adhering to the `MATCH/RETURN` format.
Consequently, Cypher now accommodates most mandatory GQL features and a substantial portion of its optional ones (defined by the link:https://www.iso.org/standard/76120.html[ISO/IEC 39075:2024 - Information technology - Database languages - GQL standard]).
Users should, therefore, only expect minimal differences between crafting queries in Cypher and GQL.
For example, the following query is valid in both languages:

.Cypher and GQL
[source, cypher]
----
MATCH (a:Actor)-[:ACTED_IN]->(m:Movie)
WHERE a.name = 'Tom Hanks'
RETURN m.title
----

Neo4j is working towards full GQL conformance (meaning full support of its mandatory features).
There are, however, currently some mandatory GQL features not implemented in Cypher.
These are listed in the page xref:appendix/gql-compliance/unsupported-mandatory.adoc[].

Neo4j is also working towards increasing its support of optional GQL features.
These are listed in the page xref:appendix/gql-compliance/supported-optional.adoc[]

Additionally, some optional GQL features not yet implemented in Cypher already have analogous Cypher equivalents.
For example, Cypher and GQL support a function to return the local time. In Cypher, this is called xref:functions/temporal/index.adoc#functions-localtime[`localtime()`]; in GQL, it is called `LOCAL_TIME()`.
These features are listed in the page xref:appendix/gql-compliance/analogous-cypher.adoc[]
