:description: Overview about Cypher's conformance to GQL.
= GQL conformance

[options="header",cols="2", width=50%]
|===
| Date | Neo4j version
| 17 April 2024 | 5.19
|===

GQL is the new link:https://www.iso.org/home.html[ISO] International Standard query language for graph databases.

GQL has adopted much of Cypher’s query construction semantics, such as adhering to the `MATCH/RETURN` format.
Consequently, Cypher now accommodates most mandatory GQL features and a substantial portion of its optional ones (defined by the link:https://www.iso.org/standard/76120.html[ISO/IEC 39075:2024 - Information technology - Database languages - GQL Standard]).
Users should, therefore, only expect minimal differences between crafting queries in Cypher and GQL.
For example, the following query is valid in both languages:

.Cypher and GQL
[source, cypher]
----
MATCH (a:Actor)-[:ACTED_IN]->(m:Movie)
WHERE a.name = 'Tom Hanks'
RETURN m.title
----

Neo4j is working towards full GQL conformance (meaning full support of its mandatory features).
There are, however, currently some mandatory GQL features not implemented in Cypher.
These are listed in the page xref:appendix/gql-compliance/unsupported-mandatory.adoc[].

Neo4j is also working towards increasing its support of optional GQL features.
These are listed in the page xref:appendix/gql-compliance/supported-optional.adoc[].

Additionally, some optional GQL features not yet implemented in Cypher already have analogous Cypher equivalents.
For example, Cypher and GQL support a function to return the local time. In Cypher, this is called xref:functions/temporal/index.adoc#functions-localtime[`localtime()`]; in GQL, it is called `LOCAL_TIME()`.
These features are listed in the page xref:appendix/gql-compliance/analogous-cypher.adoc[].

[[gql-conformance]]
== Note on minimum GQL conformance

Following the GQL Standard subclause 24.2, Minimum conformance, Cypher’s support of the following mandatory GQL features is hereby explicitly declared:

* Graph with an open graph type (Feature GG01).
* Conformance to versions 13 and 15 of The Unicode® Standard, and synchronous versions of the link:https://unicode.org/reports/tr10/[Unicode Technical Standard #10](UNICODE COLLATION ALGORITHM), link:https://unicode.org/reports/tr15/[Unicode Standard Annex #15] (UNICODE NORMALIZATION FORM), and link:https://www.unicode.org/reports/tr31/[Unicode Standard Annex #31] (UNICODE IDENTIFIERS AND SYNTAX).footnote:[Support for version 15 of The Unicode Standard was introduced in Neo4j 5.14.]
* The following types are supported: `STRING`, `BOOLEAN` (`BOOL`), `SIGNED INTEGER` (`INTEGER`, or `INT`), and `FLOAT`. 
