:description: Profile a query; analyze a query by looking at its execution plan.

[[profile-a-query]]
= Profile a query

There are two options to choose from when you want to analyze a query by looking at its execution plan:

`EXPLAIN`::
If you want to see the execution plan but not run the statement, prepend your Cypher statement with `EXPLAIN`.
The statement will always return an empty result and make no changes to the database.

`PROFILE`::
If you want to run the statement and see which operators are doing most of the work, use `PROFILE`.
This will run your statement and keep track of how many rows pass through each operator, and how much each operator needs to interact with the storage layer to retrieve the necessary data.
Note that _profiling your query uses more resources,_ so you should not profile unless you are actively working on a query.

See xref::execution-plans/index.adoc[] for a detailed explanation of each of the operators contained in an execution plan.

[TIP]
====
Being explicit about what types and labels you expect relationships and nodes to have in your query helps Neo4j use the best possible statistical information, which leads to better execution plans.
This means that when you know that a relationship can only be of a certain type, you should add that to the query.
The same goes for labels, where declaring labels on both the start and end nodes of a relationship helps Neo4j find the best way to execute the statement.
====

