= Concepts

This section starts with the simple building blocks of graph patterns: node patterns and relationship patterns.
It then shows how those are composed into path patterns that match fixed-length paths, variable-length paths and paths that have cycles in them.

[[node-patterns]]
== Node patterns

Every graph pattern contains at least one node pattern. 
The simplest graph pattern is a single, empty node pattern:

[source, syntax, role=noheader]
----
MATCH ()
----

The empty node pattern matches every node in a property graph.
In order to obtain a reference to the nodes matched, a variable needs to be declared in the node pattern:

[source, syntax, role=noheader]
----
MATCH (n)
----

With this reference, node properties can be accessed:

[source, syntax, role=noheader]
----
MATCH (n)
RETURN n.name
----

Adding a label expression to the node pattern means only nodes with labels that match will be returned.
The following matches nodes that have the `Stop` label:

[source, syntax, role=noheader]
----
MATCH (n:Stop)
----

The following more complex label expression matches all nodes that are either a `TrainStation` and a `BusStation` or `StationGroup`:

[source, syntax, role=noheader]
----
MATCH (n:(TrainStation&BusStation)|StationGroup)
----

A map of property names and values can be used to match on node properties based on equality with the specified values.
The following matches nodes that have their mode property equal to `Rail`:

[source, syntax, role=noheader]
----
MATCH (n { mode: "Rail" }) 
----

More general predicates can be expressed with a `WHERE` clause.
The following matches nodes whose name property matches the regular expression `Preston.*`:

[source, syntax, role=noheader]
----
MATCH (n:Station WHERE n.name =~ "Preston.*")
----

See the xref:patterns/reference.adoc#node-pattern[node pattern] reference section for more details. 

[[rel-patterns]]
== Relationship patterns

The simplest possible relationship pattern is a pair of dashes:

[source, syntax, role=noheader]
----
--
----

This pattern matches a relationship with any direction and does not filter on any relationship type or property. 
Unlike a node pattern, a relationship pattern cannot be used in a `MATCH` clause without node patterns at both ends. 
See xref:patterns/concepts.adoc#path-patterns[] for more details.

In order to obtain a reference to the relationships matched by the pattern, a relationship variable needs to be declared in the pattern by adding the variable name in square brackets in between the dashes:

[source, syntax, role=noheader]
----
-[r]-
----

To match a specific direction, add `<` or `>` to the left or right hand side respectively:

[source, syntax, role=noheader]
----
-[r]->
----

To match on a relationship type, its name is added after a colon:

[source, syntax, role=noheader]
----
-[:CALLS_AT]->
----

Similar to node patterns, a map of property names and values can be added to filter on properties of the relationship based on equality with the specified values:

[source, syntax, role=noheader]
----
-[{ distance: 0.24, duration: "PT4M" }]->
----

A `WHERE` clause can be used for more general predicates:

[source, syntax, role=noheader]
----
-[r WHERE time() + duration(r.duration) < time("22:00") ]->
----

See the xref:patterns/reference.adoc#rel-pattern[relationship pattern] reference section for more details. 

[[path-patterns]]
== Path patterns

Any valid path starts and ends with a node, with relationships between each node (if there is more than one node).
Path patterns have the same restrictions, and for all valid path patterns the following are true:

* They have at least one node pattern.
* They begin and end with a node pattern.
* They alternate between nodes and relationships.

[options="header"cols="2a,1a"]
|===
| Valid path patterns | Invalid path patterns 

| `()` | `->`
| `(s)-(e)` | `()->`
| `(:Station)-()<-(m WHERE m.departs > time(12:00))->()-[:NEXT]->(n)` | `()->->()`

|===





