= Patterns
:description: overview page for the chapter on graph pattern matching
:page-aliases: syntax/patterns.adoc

Graph pattern matching sits at the very core of Cypher.
It is the mechanism used to navigate, describe and extract data from a graph by applying a declarative pattern.
Inside a xref:clauses/match.adoc[] clause, you specify graph patterns to search for, and return the paths that match them.
Graph pattern matching can also be used without a `MATCH` clause, in the subqueries xref::subqueries/existential.adoc[EXISTS], xref::subqueries/count.adoc[COUNT], and xref::subqueries/collect.adoc[COLLECT].

[NOTE]
====
* Pattern: a queryable specification of a graph structure.
* Path: an actual sequence of nodes and relationships in the graph that matches a pattern.
====

A graph pattern describes data using a syntax that is similar to how the nodes and relationships of a property graph are drawn on a whiteboard.
On a whiteboard, nodes are drawn as circles and relationships are drawn as arrows.
Cypher represents the circles as a pair of parentheses, and the arrows as dashes and greater-than or less-than symbols:

[source, syntax, role=noheader]
----
()-->()<--()
----

These simple patterns for nodes and relationships form the building blocks of path patterns that can match paths of a fixed length.
As well as discussing simple fixed-length patterns, this chapter covers more complex patterns, showing how to match patterns of a variable or unknown length, find the shortest paths between a given set of nodes, add inline filters for improved query performance, and add cycles and non-linear shapes to path patterns.

This chapter includes the following sections:

* xref:patterns/primer.adoc[] - a short primer on how to get started with using graph pattern matching in Cypher.
* xref:patterns/fixed-length-paths.adoc[] - information about node, relationship, and path patterns.
* xref:patterns/variable-length-paths.adoc[] - information about quantified path patterns, quantified relationships, and group variables.
* xref:patterns/non-linear-paths.adoc[] - information about equijoins and graph patterns (combined path patterns).
* xref:patterns/shortest-paths.adoc[] - information about finding the `SHORTEST` path patterns.
* xref:patterns/unique-relationship-paths.adoc[] - information about Cypher's default behavior of not re-traversing relationships in graph pattern matches.
* xref:patterns/reference.adoc[] - a reference for looking up the syntax and semantics of graph pattern matching.

The model data in the examples used in this chapter are based on the UK national rail network, using https://www.raildeliverygroup.com/our-services/rail-data/fares-timetable-data.html[publicly available datasets].

