= Graph pattern matching 

Graph pattern matching sits at the very core of Cypher.
It is the mechanism used to navigate, describe and extract data from a graph by applying a declarative pattern.

A graph pattern describes data using a syntax that is similar to how the nodes and relationships of a property graph are drawn on a whiteboard.
On a whiteboard, nodes are drawn as circles and relationships are drawn as arrows.
Cypher represents the circles as a pair of parentheses, and the arrows as dashes and greater-than or less-than symbols:

[source, syntax, role=noheader]
----
()-->()<--()
----

In addition to simple, fixed-length patterns such as the above, graph pattern matching includes features that allow you to specify filters inside the pattern as well as sub-patterns that repeat. 
Putting these together can enable complex patterns to be expressed concisely.
It also allows the Cypher engine to limit its searches by applying predicates as it traverses a graph, increasing its efficiency.

This chapter includes three sections:

* xref:patterns/concepts.adoc[Concepts] - a deep-dive into the concepts behind graph pattern matching.
* xref:patterns/tutorial.adoc[Tutorial] - a shorter primer on how to get started with using graph pattern matching in Cypher.
* xref:patterns/reference.adoc[] - a reference for looking up the syntax and semantics of graph pattern matching. 
