= Unique relationship matching

By default Cypher does not allow the same relationship to be traversed more than once in a given xref:clauses/match.adoc[`MATCH`] result, regardless of the direction it is traversed in.
The same restriction does not hold for nodes, which may be re-traversed any number of times in a matched path.

[NOTE]
====
Cypher's default match behavior can be explicitly specified using the `DIFFERENT RELATIONSHIPS` (released in Neo4j 2025.06 and only available in Cypher 25) keyword after `MATCH`.
Specifying `DIFFERENT RELATIONSHIPS` does not alter Cypher's pattern matching.
For example: `MATCH DIFFERENT RELATIONSHIPS p = (start)--{,2}(end)` is functionally equivalent to `MATCH p = (start)--{,2}(end)`.

`DIFFERENT RELATIONSHIPS` is a xref:appendix/gql-conformance/index.adoc[GQL conformant] match mode.
Match modes determine whether relationships can appear more than once in a graph pattern match.
For more information, see xref:patterns/reference.adoc#match-modes[Syntax and semantics -> Match modes]
====

[[example-graph]]
== Example graph

To explain Cypher's default matching behavior, which allows for the re-traversal of nodes but not relationships in the same `MATCH` result, this page will use the scenario of the link:https://en.wikipedia.org/wiki/Seven_Bridges_of_K%C3%B6nigsberg[Seven bridges of Königsberg], a problem studied by link:https://en.wikipedia.org/wiki/Leonhard_Euler[Leonhard Euler] in 1736 to determine if one could cross all seven bridges of Königsberg exactly once in a single walk.

image::match-modes-graph.svg[Graph showing the seven bridges of Königsberg, width=600, role=popup]

To recreate the graph, run the following query against an empty Neo4j database:

[source, cypher, role=test-setup]
----
CREATE (kneiphof:Location {name: "Kneiphof"}),
       (northBank:Location {name: "North Bank"}),
       (southBank:Location {name: "South Bank"}),
       (lomse:Location {name: "Lomse"}),

       (kneiphof)-[:BRIDGE {id: 1}]->(northBank),
       (kneiphof)-[:BRIDGE {id: 6}]->(southBank),
       (kneiphof)-[:BRIDGE {id: 7}]->(lomse),
       (northBank)-[:BRIDGE {id: 5}]->(kneiphof),
       (northBank)-[:BRIDGE {id: 2}]->(lomse),
       (southBank)-[:BRIDGE {id: 4}]->(kneiphof),
       (southBank)-[:BRIDGE {id: 3}]->(lomse)
----

[[default-traversal-rules-and-königsberg-bridges-problem]]
== Cypher's default traversal rules and the Köningsberg bridges problem

Cypher's default match behavior is ideal to showcase the Königsberg bridges problem: in the graph model, not traversing a relationship means not traversing a bridge, the problem’s key constraint.

Consider the following query, which uses a xref:patterns/variable-length-patterns.adoc#quantified-relationships[quantified relationship] to search for paths exactly `5` hops away from the start `Location` node, `Kneiphof`.
The relationships used in this query are directional, meaning paths are traversed following specific directions for each bridge (`-[:BRIDGE]\->`). 

.Find paths with a length of 5 relationships from a start node
[source, cypher]
----
MATCH p = (:Location {name: 'Kneiphof'})-[:BRIDGE]->{5}()
RETURN [n IN nodes(p) | n.name] AS locations, 
       [r IN relationships(p) | r.id] AS crossedBridges // <1>
----

<1> The xref:expressions/list-expressions.adoc#list-comprehension[list comprehensions] iterate over nodes and relationships in a path and return specific properties (the `name` property from nodes, and the `id` property from relationships).

As the results show, a node may be traversed several times in the same path, but a relationship (bridge) is never re-traversed (for example, the path `[6, 4, 1, 5, 6]`, which traverses the same bridge more than once, cannot be matched using the `DIFFERENT RELATIONSHIPS` match mode).

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| locations | crossedBridges 

| ["Kneiphof", "North Bank", "Kneiphof", "South Bank", "Kneiphof", "Lomse"]
| [1, 5, 6, 4, 7]

| ["Kneiphof", "South Bank", "Kneiphof", "North Bank", "Kneiphof", "Lomse"] 
| [6, 4, 1, 5, 7]

2+d|Rows: 2
|===

In the next example, the direction is removed from the pattern, and the path length is increased to `6`.
It shows that there are `48` valid paths with this length, where no relationships (bridges) are re-traversed.
The query returns one of those paths as a `samplePath`, showing both the nodes and relationships traversed therein.

.Find paths with a length of 6 relationships from a start node
[source, cypher]
----
MATCH p = (:Location {name: 'Kneiphof'})-[:BRIDGE]-{6}()
WITH count(p) AS pathCount, collect(p)[0] AS samplePath // <1>
ORDER BY pathCount
RETURN pathCount, 
       [n IN nodes(samplePath) | n.name] AS samplePathLocations,
       [r IN relationships(samplePath) | r.id] AS samplePathBridges
----

<1> The xref:functions/aggregating.adoc#functions-collect[`collect()`] function collects all paths and `[0]` takes the first entry as the `samplePath`.

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| pathCount | samplePathLocations | samplePathBridges

| 48
| ["Kneiphof", "North Bank", "Kneiphof", "South Bank", "Kneiphof", "Lomse", "North Bank"]
| [1, 5, 6, 4, 7, 2]

3+d|Rows: 1
|===

image::different-relationships-graph.svg[Graph showing all but one of the seven bridges of Königsberg traversed, width=500, role=popup]
_In the `samplePath` with a length of `6` returned by `DIFFERENT RELATIONSHIPS`, all bridges are traversed except for bridge `3`._

However, if the relationship count is increased to `7`, `0` paths are returned.

.Find paths with a length of 7 relationships
// tag::patterns_match_modes_different_relationships[]
[source, cypher]
----
MATCH p = (:Location {name: 'Kneiphof'})--{7}()
RETURN count(p) AS pathCount
----
// end::patterns_match_modes_different_relationships[]

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| pathCount

| 0

1+d|Rows: 1
|===

Using Cypher's default match behavior, each step must use a unique bridge.
After the first step, one bridge is used, leaving six remaining bridges to be used in the subsequent steps.
After the sixth bridge is traversed, a seventh step would require re-traversing a bridge, which is not allowed. 

This reflects the conclusion of Euler’s Seven bridges of Königsberg problem: the impossibility of crossing each bridge exactly once in a single walk.

For more information about this Cypher's default match behavior, see xref:patterns/reference.adoc#match-modes-rules-different-relationships[Syntax & semantics -> Unique relationship matching].

== Non-default `MATCH` behavior

Cypher's default matching behavior is applicable to most use cases.
It is, however, possible to alter it to solve specific problems, either by removing the constraint to re-traverse relationships using `REPEATABLE ELEMENTS` or by not allowing the re-traversal of nodes in the same path with the `ACYCLIC` keyword.

For more information, see:

* xref:patterns/repeatable-relationship-and-node-matching.adoc[]
* xref:patterns/acyclic-patterns.adoc[]
