[[query-delete]]
= DELETE
:description: The `DELETE` clause is used to delete nodes, relationships or paths. 

* xref:clauses/delete.adoc#query-delete-introduction[Introduction]
* xref:clauses/delete.adoc#delete-delete-single-node[Delete a single node]
* xref:clauses/delete.adoc#delete-delete-all-nodes-and-relationships[Delete all nodes and relationships]
* xref:clauses/delete.adoc#delete-delete-a-node-with-all-its-relationships[Delete a node with all its relationships]
* xref:clauses/delete.adoc#delete-delete-relationships-only[Delete relationships only]

[[query-delete-introduction]]
== Introduction

For removing properties and labels, see xref:clauses/remove.adoc[REMOVE].
Remember that you cannot delete a node without also deleting relationships that start or end on said node.
Either explicitly delete the relationships, or use `DETACH DELETE`.

The examples start out with the following database:

.Graph
["dot", "DELETE-1.svg", "neoviz", ""]
----
  N0 [
    label = "{Person|age = 36\lname = \'Andy\'\l}"
  ]
  N0 -> N1 [
    color = "#2e3436"
    fontcolor = "#2e3436"
    label = "KNOWS\n"
  ]
  N0 -> N2 [
    color = "#2e3436"
    fontcolor = "#2e3436"
    label = "KNOWS\n"
  ]
  N1 [
    label = "{Person|age = 25\lname = \'Timothy\'\l}"
  ]
  N2 [
    label = "{Person|age = 34\lname = \'Peter\'\l}"
  ]
  N3 [
    label = "{Person|name = \'UNKNOWN\'\l}"
  ]

----
 

[[delete-delete-single-node]]
== Delete single node

To delete a node, use the `DELETE` clause.


.Query
[source, cypher]
----
MATCH (n:Person {name: 'UNKNOWN'})
DELETE n
----

.Result
[role="queryresult",options="footer",cols="1*<m"]
|===
1+|(empty result)
1+d|Rows: 0 +
Nodes deleted: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE
  (a:Person {name: 'Andy', age: 36}),
  (p:Person {name: 'Timothy', age: 25}),
  (t:Person {name: 'Peter', age: 34}),
  (z:Person {name: 'UNKNOWN'}),
  (a)-[:KNOWS]->(t),
  (a)-[:KNOWS]->(p)

]]></database><command><![CDATA[
MATCH (n:Person {name: 'UNKNOWN'})
DELETE n
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[[delete-delete-all-nodes-and-relationships]]
== Delete all nodes and relationships

This query is not for deleting large amounts of data, but is useful when experimenting with small example data sets.


.Query
[source, cypher]
----
MATCH (n)
DETACH DELETE n
----

.Result
[role="queryresult",options="footer",cols="1*<m"]
|===
1+|(empty result)
1+d|Rows: 0 +
Nodes deleted: 4 +
Relationships deleted: 2
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE
  (a:Person {name: 'Andy', age: 36}),
  (p:Person {name: 'Timothy', age: 25}),
  (t:Person {name: 'Peter', age: 34}),
  (z:Person {name: 'UNKNOWN'}),
  (a)-[:KNOWS]->(t),
  (a)-[:KNOWS]->(p)

]]></database><command><![CDATA[
MATCH (n)
DETACH DELETE n
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[[delete-delete-a-node-with-all-its-relationships]]
== Delete a node with all its relationships

When you want to delete a node and any relationship going to or from it, use `DETACH DELETE`.


.Query
[source, cypher]
----
MATCH (n {name: 'Andy'})
DETACH DELETE n
----

.Result
[role="queryresult",options="footer",cols="1*<m"]
|===
1+|(empty result)
1+d|Rows: 0 +
Nodes deleted: 1 +
Relationships deleted: 2
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE
  (a:Person {name: 'Andy', age: 36}),
  (p:Person {name: 'Timothy', age: 25}),
  (t:Person {name: 'Peter', age: 34}),
  (z:Person {name: 'UNKNOWN'}),
  (a)-[:KNOWS]->(t),
  (a)-[:KNOWS]->(p)

]]></database><command><![CDATA[
MATCH (n {name: 'Andy'})
DETACH DELETE n
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
For `DETACH DELETE` for users with restricted security privileges, see link:{neo4j-docs-base-uri}/operations-manual/{page-version}/authentication-authorization/access-control#detach-delete-restricted-user[Operations Manual -> Fine-grained access control].


====

[[delete-delete-relationships-only]]
== Delete relationships only

It is also possible to delete relationships only, leaving the node(s) otherwise unaffected.


.Query
[source, cypher]
----
MATCH (n {name: 'Andy'})-[r:KNOWS]->()
DELETE r
----

This deletes all outgoing `KNOWS` relationships from the node with the name *'Andy'*.

.Result
[role="queryresult",options="footer",cols="1*<m"]
|===
1+|(empty result)
1+d|Rows: 0 +
Relationships deleted: 2
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE
  (a:Person {name: 'Andy', age: 36}),
  (p:Person {name: 'Timothy', age: 25}),
  (t:Person {name: 'Peter', age: 34}),
  (z:Person {name: 'UNKNOWN'}),
  (a)-[:KNOWS]->(t),
  (a)-[:KNOWS]->(p)

]]></database><command><![CDATA[
MATCH (n {name: 'Andy'})-[r:KNOWS]->()
DELETE r
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

