:description: `GROUP BY` groups results by a grouping element or a list of grouping elements.
:table-caption!:
:page-role: new-neo4j-2026.07 cypher-25-only

[[query-group-by]]
= GROUP BY

`GROUP BY` is a subclause that allows you to group the results of a `RETURN` or `WITH` clause.

`GROUP BY` arranges identically structured data into groups based on one or more columns.
For this reason, it combines well with aggregate functions like xref:functions/aggregating.adoc#functions-count[count()] or xref:functions/aggregating.adoc#functions-avg[avg()] to perform calculations on each group of data.

Cypher's `GROUP BY` functions similarly to SQL's `GROUP BY` and it is also xref:appendix/gql-conformance/supported-optional.adoc#gq15[GQL-compliant].

[[example-graph]]
== Example graph

The following graph is used for the examples below:

image::graph-group-by-clause.svg[Example graph for GROUP BY examples,role=popup]

To recreate it, run the following query against an empty Neo4j database:

[source, cypher, role=test-setup]
----
CREATE
  (jessica:Person {name: 'Jessica Chastain'}),
  (missSloane:Movie {title: 'Miss Sloane', genre: 'Drama', rating: 4.5, year: 2016}),
  (mollysGame:Movie {title: "Molly's Game", genre: 'Drama', rating: 4.4, year: 2017}),
  (darkPhoenix:Movie {title: 'X-Men: Dark Phoenix', genre: 'Action', rating: 3.5, year: 2019}),
  (it2:Movie {title: 'It: Chapter Two', genre: 'Horror', rating: 3.6, year: 2019}),
  (midsommar:Movie {title: 'Midsommar', genre: 'Horror', rating: 3.6, year: 2019}),
  (armageddon:Movie {title: 'Armageddon Time', genre: 'Drama', rating: 3.8, year: 2022}),
  (goodnurse:Movie {title: 'The Good Nurse', genre: 'Drama', rating: 4.2, year: 2022}),
  (jessica)-[:ACTED_IN]->(missSloane),
  (jessica)-[:ACTED_IN]->(mollysGame),
  (jessica)-[:ACTED_IN]->(darkPhoenix),
  (jessica)-[:ACTED_IN]->(it2),
  (jessica)-[:ACTED_IN]->(armageddon),
  (jessica)-[:ACTED_IN]->(goodnurse)
----


[[syntax]]
== Syntax

.Syntax for GROUP BY in a RETURN clause
[source, syntax]
----
RETURN <return statement body>
  GROUP BY { <grouping element> {, <grouping element> } … | () | ALL } 
  <order by and page clause>
----

.Syntax for GROUP BY in a WITH clause
[source, syntax]
----
WITH <return statement body>
  GROUP BY { <grouping element> {, <grouping element> } … | () | ALL } 
  [<order by and page clause>]
  [<where clause>]
----

[[examples]]
== Basic examples

.GROUP BY a single column
=====
[source, cypher]
----
MATCH (p: Person)-[:ACTED_IN]->(m:Movie)
RETURN m.genre AS genre, avg(m.rating) AS averageRating
  GROUP BY genre
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| genre    | averageRating 

| "Drama"  | 4.225          
| "Action" | 3.5           
| "Horror" | 3.6           
2+d|Rows: 3
|===

The four drama movies have an average rating of `4.225`.
=====


.GROUP BY two columns
=====
[source, cypher]
----
MATCH (p: Person)-[:ACTED_IN]->(m:Movie)
RETURN m.genre AS genre, m.year AS year, avg(m.rating) AS averageRating
  GROUP BY genre, year
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| genre    | year | averageRating 

| "Drama"  | 2017 | 4.4           
| "Action" | 2019 | 3.5           
| "Horror" | 2019 | 3.6           
| "Drama"  | 2022 | 4.0           
| "Drama"  | 2016 | 4.5           
        
3+d|Rows: 5
|===

Grouping by genre and year, the drama movies have three entries.
For 2022, the average is calculated for the two movies that were released that year.
=====


.GROUP BY with no grouping keys
=====
[source, cypher]
----
MATCH (p: Person)-[:ACTED_IN]->(m:Movie)
RETURN collect(m.title) AS movieTitles, avg(m.rating) AS globalAverageRating
  GROUP BY ()
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| movieTitles                                                                                                    | globalAverageRating

| ["Molly's Game", "X-Men: Dark Phoenix", "It: Chapter Two", "Armageddon Time", "The Good Nurse", "Miss Sloane"] | 4.0   
2+d|Rows: 1
|===

When using `GROUP BY` with `()`, you explicitly state that there are no grouping keys.
This means that there can be no direct projections of returned entities.
However, aggregations still work like in the showcased query.
=====


.GROUP BY ALL
=====
[source, cypher]
----
MATCH (p: Person)-[:ACTED_IN]->(m:Movie)
RETURN m.genre AS genre, m.year AS year, avg(m.rating) AS averageRating
  GROUP BY genre, year
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| genre    | year | averageRating 

| "Drama"  | 2017 | 4.4           
| "Action" | 2019 | 3.5           
| "Horror" | 2019 | 3.6           
| "Drama"  | 2022 | 4.0           
| "Drama"  | 2016 | 4.5           
        
3+d|Rows: 5
|===

`GROUP BY ALL` uses all projected expressions as grouping keys.
In this case, the query above is equivalent to the query above using two columns.
=====


== Special cases

.GROUP BY without aggregation
=====
[source, cypher]
----
MATCH (m: Movie)
RETURN m.year as year, m.rating as rating
  GROUP BY year, rating
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| year | rating 

| 2017 | 4.4    
| 2019 | 3.5    
| 2019 | 3.6    
| 2022 | 3.8    
| 2022 | 4.2    
| 2016 | 4.5    
2+d|Rows: 6
|===

In this query, `GROUP BY` is equivalent to xref:clauses/return.adoc#return-unique-results[`DISTINCT`].
Two movies with a rating of `3.6` exist for the year 2019, but the entry is not repeated.
=====


.GROUP BY and aliasing
=====

[source, cypher]
----
MATCH (m: Movie)
LET year = m.year
RETURN year, m.rating as rating
  GROUP BY year, rating
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| year | rating 

| 2017 | 4.4    
| 2019 | 3.5    
| 2019 | 3.6    
| 2022 | 3.8    
| 2022 | 4.2    
| 2016 | 4.5    
    
2+d|Rows: 6
|===

You can alias expressions with `LET` and use the alias in the `RETURN` (or `WITH`) clause as well as the `GROUP BY` clause.
=====


.GROUP BY an item that is not returned
=====
[source, cypher]
----
MATCH (m: Movie)
LET title = m.title
RETURN m.year as year, m.rating as rating
  GROUP BY title, year, rating
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| year | rating 

| 2017 | 4.4    
| 2019 | 3.5    
| 2019 | 3.6    
| 2022 | 3.8    
| 2022 | 4.2    
| 2016 | 4.5    
| 2019 | 3.6    
2+d|Rows: 7
|===

`title` is not returned, but still used as a grouping key.
=====


== Grouping keys

The following rules apply to grouping keys:

* A single grouping key or multiple grouping keys are possible
* The set of grouping keys may also be empty
* `GROUP BY ALL` makes every return item a grouping key
* If a projection clause contains a `GROUP BY` clause, then every projection item must be:
** A leaf, that is an aggregation function, constant, parameter, local variable or a grouping key expression
** A sub-expression, where all operands are either a leaf or a sub-expression
** An exact grouping key, equal to a grouping key expression
* Grouping keys which are not as well return items are not projected to the output


== Variable visibility

Variable visibility in `RETURN` with `GROUP BY`:

[source, cypher]
----
MATCH (:Account)-[t:Transfers]->(account:Account)
LET name = account.name
RETURN account, t.name AS transfer_name, SUM(t.amount) AS total_incoming
  GROUP BY account, transfer_name, name
  ORDER BY t.name, name
----

Here is the list of variables which are visible to the different parts of the `RETURN` clause, a note on how the set is defined, as well as the return columns of the clause:


* `RETURN`
** Visible variables: `{ t, account, name }`
** Result columns: `{ account, transfer_name, total_incoming }`
* Non-Aggregating return items (`account` and `t.name AS transfer_name`)
** Visible variables: `{ account, transfer_name name }`
The non-aggregating return items see grouping key expressions. 
* Aggregating return items (`SUM(t.amount) AS total_incoming`)
** Visible variables: `{ t, account, name }`
The aggregating return items see all incoming constants and variables.
* Grouping Elements 
** Visible variables: `{ t, account, name, transfer_name, t.name }`
The grouping elements see all incoming constants and variables as well as grouping return item aliases.
* Subclause expressions (`t.name` and `name` inside `ORDER BY`)
** Visible variables: `{ account, name, total_incoming, t.name, transfer_name }`

Variable visibility in `WHERE` with `GROUP BY`:

[source, cypher]
----
MATCH (:Account)-[t:Transfers]->(account:Account)
LET name = account.name
WITH account, t.name AS transfer_name, SUM(t.amount) AS total_incoming
  GROUP BY account, transfer_name, name
  ORDER BY t.name, name
  WHERE account.counter > 0
RETURN transfer_name, total_incoming
----

Here is the list of variables which are visible to the different parts of the `WITH` clause, a note on how the set is defined, as well as the return columns of the clause:

* `WITH`
** Visible variables: `{ t, account, name }`
** Outgoing: `{ account, transfer_name, total_incoming }`
* Non-Aggregating return items (`account` and `t.name AS transfer_name`)
** Visible variables: `{ account, transfer_name name }``
The non-aggregating return items see grouping key expressions.
* Aggregating return items (`SUM(t.amount) AS total_incoming`)
** Visible variables: `{ t, account, name }`
The aggregating return items see all incoming constants and variables.
* Grouping Elements 
** Visible variables: `{ t, account, name, transfer_name, t.name }`
The grouping elements see all incoming constants and variables as well as grouping return item aliases.
* Subclause expressions
** Visible variables: `{ account, name, total_incoming, t.name, transfer_name }`
The sort keys see all return item aliases and grouping keys


== Errors

.Missing grouping element in GROUP BY
=====

[source, cypher]
----
MATCH (p: Person)
LET name = p.name
RETURN p.age AS age, sum(p.age) 
  GROUP BY name
----

// TODO: GQL error code
.GQLSTATUS error chain
[role="queryresult",stripes="all", cols="1", ]
|===
| link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/42XXX/[42XXX]: error: syntax error or access rule violation - non-grouping key reference: The projection item `age` must only be dependent on grouping keys.

link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/42001/[42001]: error: syntax error or access rule violation - invalid syntax
|===

=====


.Missing grouping element in GROUP BY ()
=====

[source, cypher]
----
MATCH (p: Person)
LET name = p.name
RETURN p.age AS age, sum(p.age) 
  GROUP BY ()
----

// TODO: GQL error code
.GQLSTATUS error chain
[role="queryresult",stripes="all", cols="1", ]
|===
| link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/42XXX/[42XXX]: error: syntax error or access rule violation - non-grouping key reference: The projection item `age` must only be dependent on grouping keys.

link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/42001/[42001]: error: syntax error or access rule violation - invalid syntax
|===

=====


.Missing grouping element in GROUP BY when using DISTINCT
=====

[source, cypher]
----
MATCH (p: Person)
RETURN DISTINCT p.name AS name, p.age AS age 
  GROUP BY name
----

// TODO: GQL error code
.GQLSTATUS error chain
[role="queryresult",stripes="all", cols="1", ]
|===
| link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/42XXX/[42XXX]: error: syntax error or access rule violation - non-grouping key reference: The projection item `age` must only be dependent on grouping keys.

link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/42001/[42001]: error: syntax error or access rule violation - invalid syntax
|===

=====


.GROUP BY ALL does not allow complex grouping keys
=====

[source, cypher]
----
MATCH (n) 
RETURN n.age + 1, n.age + 1 + count(*) 
  GROUP BY ALL
----

.GQLSTATUS error chain
[role="queryresult",stripes="all", cols="1", ]
|===
| link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/42I18/[42I18]: error: syntax error or access rule violation - invalid reference to implicitly grouped expressions. The aggregation column contains implicit grouping expressions referenced by the variables `n`. Implicit grouping expressions are variables not explicitly declared as grouping keys.

link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/42001/[42001]: error: syntax error or access rule violation - invalid syntax
|===

=====

.GROUP BY with ambiguous references in grouping elements
=====

[source, cypher]
----
WITH {p: 1} AS a, 2 AS b 
RETURN a.p AS a, sum(b) 
  GROUP BY a.p
----

// TODO: GQL error code
.GQLSTATUS error chain
[role="queryresult",stripes="all", cols="1", ]
|===
| link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/42XXX/[42XXX]: error: error: syntax error or access rule violation - non-grouping key reference: The projection item `a` must only be dependent on grouping keys.

link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/42001/[42001]: error: syntax error or access rule violation - invalid syntax
|===

=====


.GROUP BY with ambiguous references in grouping elements
=====

[source, cypher]
---- 
WITH {p: 1} AS c, 2 AS b
RETURN c AS a, sum(b) 
  GROUP BY a.p
----

// TODO: GQL error code
.GQLSTATUS error chain
[role="queryresult",stripes="all", cols="1", ]
|===
| link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/42XXX/[42XXX]: error: error: syntax error or access rule violation - non-grouping key reference: The projection item `a` must only be dependent on grouping keys.

link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/42001/[42001]: error: syntax error or access rule violation - invalid syntax
|===

=====
