:description: This section contains information on all the clauses in the Cypher query language.

[[query-clause]]
= Clauses

[abstract]
--
This section contains information on all the clauses in the Cypher query language.
--


[[administration-clauses]]
== Administration clauses

These comprise clauses used to manage databases, schema and security; further details can found in xref::databases.adoc[Database management] and xref::access-control/index.adoc[Access control].

[options="header"]
|===
| Clause | Description

m| xref::databases.adoc[CREATE \| DROP \| START \| STOP DATABASE]
| Create, drop, start or stop a database.

m| xref::indexes-for-search-performance.adoc#administration-indexes-syntax[CREATE \| DROP INDEX]
| Create or drop an index on all nodes with a particular label and property.

m| xref::constraints/syntax.adoc[CREATE \| DROP CONSTRAINT]
| Create or drop a constraint pertaining to either a node label or relationship type, and a property.

| xref::access-control/index.adoc[Access control]
| Manage users, roles, and privileges for database, graph and sub-graph access control.

|===


[[importing-clauses]]
== Importing data

[options="header"]
|===
| Clause | Description

m| xref::clauses/load-csv.adoc[LOAD CSV]
| Use when importing data from CSV files.

m| --- xref::query-tuning/using.adoc#query-using-periodic-commit-hint[USING PERIODIC COMMIT]
| This query hint may be used to prevent an out-of-memory error from occurring when importing large amounts of data using `LOAD CSV`.

|===


[[listing-functions-and-procedures]]
== Listing functions and procedures

[options="header"]
|===
| Clause | Description

m| xref::clauses/listing-functions.adoc[SHOW FUNCTIONS]
| List the available functions.

m| xref::clauses/listing-procedures.adoc[SHOW PROCEDURES]
| List the available procedures.

|===


[[multiple-graphs-clauses]]
== Multiple graphs

[options="header"]
|===
| Clause | Description

m| xref::clauses/use.adoc[USE]
| Determines which graph a query, or query part, is executed against. label:fabric[]

|===


[[projecting-clauses]]
== Projecting clauses

These comprise clauses that define which expressions to return in the result set.
The returned expressions may all be aliased using `AS`.

[options="header"]
|===
| Clause | Description

m| xref::clauses/return.adoc[+RETURN ... [AS]+]
| Defines what to include in the query result set.

m| xref::clauses/with.adoc[+WITH ... [AS]+]
| Allows query parts to be chained together, piping the results from one to be used as starting points or criteria in the next.

m| xref::clauses/unwind.adoc[+UNWIND ... [AS]+]
| Expands a list into a sequence of rows.

|===


[[reading-clauses]]
== Reading clauses

These comprise clauses that read data from the database.

The flow of data within a Cypher query is an unordered sequence of maps with key-value pairs -- a set of possible bindings between the variables in the query and values derived from the database.
This set is refined and augmented by subsequent parts of the query.

[options="header"]
|===
| Clause | Description

m| xref::clauses/match.adoc[MATCH]
| Specify the patterns to search for in the database.

m| xref::clauses/optional-match.adoc[OPTIONAL MATCH]
| Specify the patterns to search for in the database while using `nulls` for missing parts of the pattern.

|===


[[reading-hints]]
== Reading hints

These comprise clauses used to specify planner hints when tuning a query.
More details regarding the usage of these -- and query tuning in general -- can be found in xref::query-tuning/using.adoc[Planner hints and the USING keyword].

[options="header"]
|===
| Hint | Description

m| xref::query-tuning/using.adoc#query-using-index-hint[USING INDEX]
| Index hints are used to specify which index, if any, the planner should use as a starting point.

m| xref::query-tuning/using.adoc#query-using-index-hint[USING INDEX SEEK]
| Index seek hint instructs the planner to use an index seek for this clause.

m| xref::query-tuning/using.adoc#query-using-scan-hint[USING SCAN]
| Scan hints are used to force the planner to do a label scan (followed by a filtering operation) instead of using an index.

m| xref::query-tuning/using.adoc#query-using-join-hint[USING JOIN]
| Join hints are used to enforce a join operation at specified points.

|===


[[reading-sub-clauses]]
== Reading sub-clauses

These comprise sub-clauses that must operate as part of reading clauses.

[options="header"]
|===
| Sub-clause | Description

m| xref::clauses/where.adoc[WHERE]
| Adds constraints to the patterns in a `MATCH` or `OPTIONAL MATCH` clause or filters the results of a `WITH` clause.

m| xref::clauses/where.adoc#existential-subqueries[+WHERE EXISTS { ... }+]
| An existential sub-query used to filter the results of a `MATCH`, `OPTIONAL MATCH` or `WITH` clause.

m| xref::clauses/order-by.adoc[+ORDER BY [ASC[ENDING] \| DESC[ENDING]]+]
| A sub-clause following `RETURN` or `WITH`, specifying that the output should be sorted in either ascending (the default) or descending order.

m| xref::clauses/skip.adoc[SKIP]
| Defines from which row to start including the rows in the output.

m| xref::clauses/limit.adoc[LIMIT]
| Constrains the number of rows in the output.

|===


[[reading-writing-clauses]]
== Reading/Writing clauses

These comprise clauses that both read data from and write data to the database.

[options="header"]
|===
| Clause | Description

m| xref::clauses/merge.adoc[MERGE]
| Ensures that a pattern exists in the graph. Either the pattern already exists, or it needs to be created.

m| --- xref::clauses/merge.adoc#query-merge-on-create-on-match[ON CREATE]
| Used in conjunction with `MERGE`, this write sub-clause specifies the actions to take if the pattern needs to be created.

m| --- xref::clauses/merge.adoc#query-merge-on-create-on-match[ON MATCH]
| Used in conjunction with `MERGE`, this write sub-clause specifies the actions to take if the pattern already exists.

m| xref::clauses/call.adoc[+CALL ... [YIELD ... ]+]
| Invokes a procedure deployed in the database and return any results.

|===


[[set-operations-clauses]]
== Set operations

[options="header"]
|===
|Clause |Description

m| xref::clauses/union.adoc[UNION]
a|
Combines the result of multiple queries into a single result set.
Duplicates are removed.

m| xref::clauses/union.adoc[UNION ALL]
a|
Combines the result of multiple queries into a single result set.
Duplicates are retained.

|===


[[subquery-clauses]]
== Subquery clauses

[options="header"]
|===
|Clause |Description

m| xref::clauses/call-subquery.adoc[+CALL { ... }+]
| Evaluates a subquery, typically used for post-union processing or aggregations.

m| xref::clauses/call-subquery.adoc#subquery-call-in-transactions[+CALL { ... } IN TRANSACTIONS+]
a|
Evaluates a subquery in separate transactions. 
Typically used when modifying or importing large amounts of data.

|===


[[transaction-commands]]
== Transaction Commands

[options="header"]
|===
| Clause | Description

m| xref:clauses/transaction-clauses.adoc#query-listing-transactions[SHOW TRANSACTIONS]
| List the available transactions.

m| xref:clauses/transaction-clauses.adoc#query-terminate-transactions[TERMINATE TRANSACTIONS]
| Terminate transactions by their IDs.

|===


[[writing-clauses]]
== Writing clauses

These comprise clauses that write the data to the database.

[options="header"]
|===
| Clause | Description

m| xref::clauses/create.adoc[CREATE]
| Create nodes and relationships.

m| xref::clauses/delete.adoc[DELETE]
a|
Delete nodes, relationships or paths.
Any node to be deleted must also have all associated relationships explicitly deleted.

m| xref::clauses/delete.adoc[DETACH DELETE]
a|
Delete a node or set of nodes.
All associated relationships will automatically be deleted.

m| xref::clauses/set.adoc[SET]
| Update labels on nodes and properties on nodes and relationships.

m| xref::clauses/remove.adoc[REMOVE]
| Remove properties and labels from nodes and relationships.

m| xref::clauses/foreach.adoc[FOREACH]
| Update data within a list, whether components of a path, or the result of aggregation.

|===

