:description: This section contains information on all the clauses in the Cypher query language.

[[query-clause]]
= Clauses

This section contains information on all the clauses and subclauses in the Cypher query language.

[[read-clauses]]
== Read clauses

These comprise clauses that read data from the database.

The flow of data within a Cypher query is an unordered sequence of maps with key-value pairs -- a set of possible bindings between the variables in the query and values derived from the database.
This set is refined and augmented by subsequent parts of the query.

[options="header"]
|===
| Clause | Description

m| xref::clauses/filter.adoc[FILTER]
| Adds filters to queries.
label:new[Introduced in Neo4j 2025.06]

m| xref::clauses/match.adoc[MATCH]
| Specify the patterns to search for in the database.

m| xref::clauses/optional-match.adoc[OPTIONAL MATCH]
| Specify the patterns to search for in the database while using `nulls` for missing parts of the pattern.

|===

[[projection-clauses]]
== Projection clauses

These comprise clauses that define which expressions to return in the result set.
The returned expressions may all be aliased using `AS`.

[options="header"]
|===
| Clause | Description

m| xref::clauses/finish.adoc[FINISH]
| Defines a query to have no result.

m| xref::clauses/let.adoc[LET]
| Binds values to variables.
label:new[Introduced in Neo4j 2025.06]

m| xref::clauses/return.adoc[RETURN ... [AS]]
| Defines what to include in the query result set.

m| xref::clauses/unwind.adoc[UNWIND ... [AS]]
| Expands a list into a sequence of rows.

m| xref::clauses/with.adoc[WITH ... [AS]]
| Allows query parts to be chained together, piping the results from one to be used as starting points or criteria in the next.

|===

[[projection-subclauses]]
== Projection subclauses

These comprise subclauses that must operate as part of reading clauses.

[options="header"]
|===
| Sub-clause | Description

m| xref::clauses/where.adoc[WHERE]
| Adds constraints to the patterns in a `MATCH` or `OPTIONAL MATCH` clause or filters the results of a `WITH` clause.

m| xref::clauses/limit.adoc[LIMIT]
| Constrains the number of rows in the output.

m| xref::clauses/order-by.adoc[ORDER BY [ASC[ENDING\] \| DESC[ENDING\]\]]
| A subclause following `RETURN` or `WITH`, specifying that the output should be sorted in either ascending (the default) or descending order.

m| xref::clauses/skip.adoc[SKIP] / xref::clauses/skip.adoc#offset-synonym[`OFFSET`]
| Defines from which row to start including the rows in the output.

|===

[[write-clauses]]
== Write clauses

These comprise clauses that write the data to the database.

[options="header"]
|===
| Clause | Description

m| xref::clauses/create.adoc[CREATE]
| Create nodes and relationships.

m| xref::clauses/delete.adoc[DELETE]
a|
Delete nodes, relationships or paths.
Any node to be deleted must also have all associated relationships explicitly deleted.

m| xref::clauses/delete.adoc#delete-all-nodes-and-relationships[DETACH DELETE]
a|
Delete a node or set of nodes.
All associated relationships will automatically be deleted.

m| xref::clauses/foreach.adoc[FOREACH]
| Update data within a list, whether components of a path, or the result of aggregation.

m| xref::clauses/set.adoc[SET]
| Update labels on nodes and properties on nodes and relationships.

m| xref::clauses/remove.adoc[REMOVE]
| Remove properties and labels from nodes and relationships.

|===

[[reade-write-clauses]]
== Reade/Write clauses

These comprise clauses that both read data from and write data to the database.

[options="header"]
|===
| Clause | Description

m| xref::clauses/merge.adoc[MERGE]
| Ensures that a pattern exists in the graph. Either the pattern already exists, or it needs to be created.

m| --- xref::clauses/merge.adoc#query-merge-on-create-on-match[ON CREATE]
| Used in conjunction with `MERGE`, this write subclause specifies the actions to take if the pattern needs to be created.

m| --- xref::clauses/merge.adoc#query-merge-on-create-on-match[ON MATCH]
| Used in conjunction with `MERGE`, this write subclause specifies the actions to take if the pattern already exists.

|===

[[graph-selection-clauses]]
== Graph selection clauses

[options="header"]
|===
| Clause | Description

m| xref::clauses/use.adoc[USE]
| Determines which graph a query, or query part, is executed against.

|===

[[invocation-clauses]]
== Invocation clauses

[options="header"]
|===
|Clause |Description

m| xref::clauses/call.adoc[CALL ... [YIELD ... ]]
| Invokes a procedure deployed in the database and return any results.

m| xref::subqueries/call-subquery.adoc[CALL { ... }]
| Evaluates a subquery, typically used for post-union processing or aggregations.

m| xref::subqueries/subqueries-in-transactions.adoc[CALL { ... } IN TRANSACTIONS]
a|
Evaluates a subquery in separate transactions.
Typically used when modifying or importing large amounts of data.

|===

[[importing-clauses]]
== Importing clauses

[options="header"]
|===
| Clause | Description

m| xref::clauses/load-csv.adoc[LOAD CSV]
| Use when importing data from CSV files.

|===


[[schema-clauses]]
== Schema clauses

[options="header"]
|===
| Clause | Description

m| xref:constraints/managing-constraints.adoc#create-constraint[CREATE CONSTRAINT]
| Create a property existence, property uniqueness, property type, or key constraint.

m| xref:constraints/managing-constraints.adoc#list-constraints[SHOW CONSTRAINTS]
| List the available constraints in a database.

m| xref:constraints/managing-constraints.adoc#drop-constraint[DROP CONSTRAINT]
| Drop a constraint.

m| xref:indexes/search-performance-indexes/managing-indexes.adoc#create-range-index[CREATE INDEX]
| Create a range, point, text, lookup, fulltext, or vector index.

m| xref:indexes/search-performance-indexes/managing-indexes.adoc#list-indexes[SHOW INDEXES]
| List the available indexes in a database.

m| xref:indexes/search-performance-indexes/managing-indexes.adoc#drop-indexes[DROP INDEX]
| Drop an index.

** xref:indexes/search-performance-indexes/managing-indexes.adoc#list-indexes[SHOW INDEXES]
** xref:indexes/search-performance-indexes/managing-indexes.adoc#drop-indexes[DROP INDEX]

|===

[[metadata-clauses]]
== Metadata clauses

[options="header"]
|===
| Clause | Description

m| xref::clauses/listing-functions.adoc[SHOW FUNCTIONS]
| List the available functions.

m| xref::clauses/listing-procedures.adoc[SHOW PROCEDURES]
| List the available procedures.

m| xref:clauses/listing-settings.adoc[SHOW SETTINGS]
| List configuration settings.

m| xref:clauses/transaction-clauses.adoc#query-listing-transactions[SHOW TRANSACTIONS]
| List the available transactions.

m| xref:clauses/transaction-clauses.adoc#query-terminate-transactions[TERMINATE TRANSACTIONS]
| Terminate transactions by their IDs.

|===


[[administration-clauses]]
== Administration clauses

Cypher includes commands to manage databases, aliases, servers, and role-based access control.
To learn more about each of these, see:

* link:{neo4j-docs-base-uri}/operations-manual/current/database-administration[Operations Manual -> Database administration]
* link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/[Operations Manual -> Authentication and authorization]
* link:{neo4j-docs-base-uri}/operations-manual/current/clustering/[Operations Manual -> Clustering]
