:description: This section explains the `SHOW FUNCTIONS` command.

[[query-listing-functions]]
= SHOW FUNCTIONS

[abstract]
--
This section explains the `SHOW FUNCTIONS` command.
--

Listing the available functions can be done with `SHOW FUNCTIONS`.

[NOTE]
====
The command `SHOW FUNCTIONS` returns only the default output.
For a full output use the optional `YIELD` command.
Full output: `SHOW FUNCTIONS YIELD *`.
====

The `SHOW FUNCTIONS` command will produce a table with the following columns:


.List functions output
[options="header", cols="4,6,2"]
|===
| Column | Description | Type

m| name
a| The name of the function. label:default-output[]
m| STRING

m| category
a| The function category, for example `scalar` or `string`. label:default-output[]
m| STRING

m| description
a| The function description. label:default-output[]
m| STRING

m| signature
a| The signature of the function.
m| STRING

m| isBuiltIn
a| Whether the function is built-in or user-defined.
m| BOOLEAN

m| argumentDescription
a| List of the arguments for the function, as map of strings with name, type, default, and description.
m| LIST OF MAP

m| returnDescription
a| The return value type.
m| STRING

m| aggregating
a| Whether the function is aggregating or not.
m| BOOLEAN

m| rolesExecution
a|
List of roles permitted to execute this function.
Is `null` without the xref::administration/access-control/dbms-administration.adoc#access-control-dbms-administration-role-management[`SHOW ROLE`] privilege.
m| LIST OF STRING

m| rolesBoostedExecution
a|
List of roles permitted to use boosted mode when executing this function.
Is `null` without the xref::administration/access-control/dbms-administration.adoc#access-control-dbms-administration-role-management[`SHOW ROLE`] privilege.
m| LIST OF STRING

|===


== Syntax

[NOTE]
====
More details about the syntax descriptions can be found xref:administration/index.adoc#administration-syntax[here].
====

List functions, either all or only built-in or user-defined::

[source, syntax, role="noheader"]
----
SHOW [ALL|BUILT IN|USER DEFINED] FUNCTION[S]
[YIELD { * | field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

[NOTE]
====
When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.
====

List functions that the current user can execute::

[source, syntax, role="noheader"]
----
SHOW [ALL|BUILT IN|USER DEFINED] FUNCTION[S] EXECUTABLE [BY CURRENT USER]
[YIELD { * | field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

[NOTE]
====
When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.
====

List functions that the specified user can execute::

[source, syntax, role="noheader", indent=0]
----
SHOW [ALL|BUILT IN|USER DEFINED] FUNCTION[S] EXECUTABLE BY username
[YIELD { * | field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

Required privilege xref::administration/access-control/dbms-administration.adoc#access-control-dbms-administration-user-management[`SHOW USER`].
This command cannot be used for LDAP users.

[NOTE]
====
When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.
====

== Listing all functions

To list all available functions with the default output columns, the `SHOW FUNCTIONS` command can be used.
If all columns are required, use `SHOW FUNCTIONS YIELD *`.


.Query
[source, cypher, role=test-result-skip]
----
SHOW FUNCTIONS
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| +name+ | +category+ | +description+

| +"abs"+
| +"Numeric"+
| +"Returns the absolute value of an integer."+

| +"abs"+
| +"Numeric"+
| +"Returns the absolute value of a floating point number."+

| +"acos"+
| +"Trigonometric"+
| +"Returns the arccosine of a number in radians."+

| +"all"+
| +"Predicate"+
| +"Returns true if the predicate holds for all elements in the given list."+

| +"any"+
| +"Predicate"+
| +"Returns true if the predicate holds for at least one element in the given list."+

| +"asin"+
| +"Trigonometric"+
| +"Returns the arcsine of a number in radians."+

| +"atan"+
| +"Trigonometric"+
| +"Returns the arctangent of a number in radians."+

| +"atan2"+
| +"Trigonometric"+
| +"Returns the arctangent2 of a set of coordinates in radians."+

| +"avg"+
| +"Aggregating"+
| +"Returns the average of a set of integer values."+

| +"avg"+
| +"Aggregating"+
| +"Returns the average of a set of floating point values."+

| +"avg"+
| +"Aggregating"+
| +"Returns the average of a set of duration values."+

| +"ceil"+
| +"Numeric"+
| +"Returns the smallest floating point number that is greater than or equal to a number and equal to a mathematical integer."+

| +"coalesce"+
| +"Scalar"+
| +"Returns the first non-null value in a list of expressions."+

| +"collect"+
| +"Aggregating"+
| +"Returns a list containing the values returned by an expression."+

| +"cos"+
| +"Trigonometric"+
| +"Returns the cosine  of a number."+

| +"cot"+
| +"Trigonometric"+
| +"Returns the cotangent of a number."+

| +"count"+
| +"Aggregating"+
| +"Returns the number of values or rows."+

| +"date"+
| +"Temporal"+
| +"Create a Date instant."+

| +"date.realtime"+
| +"Temporal"+
| +"Get the current Date instant using the realtime clock."+

| +"date.statement"+
| +"Temporal"+
| +"Get the current Date instant using the statement clock."+

3+d|Rows: 20
|===

The above table only displays the first 20 results of the query.
For a full list of all available functions in Cypher, see the chapter on xref::clauses/index.adoc[Functions].

== Listing functions with filtering on output columns

The listed functions can be filtered in multiple ways.
One way is through the type keywords, `BUILT IN` and `USER DEFINED`.
A more flexible way is to use the `WHERE` clause.
For example, getting the name of all built-in functions starting with the letter 'a':

.Query
[source, cypher]
----
SHOW BUILT IN FUNCTIONS YIELD name, isBuiltIn
WHERE name STARTS WITH 'a'
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| +name+    | +isBuiltIn+

| +"abs"+   | +true+
| +"abs"+   | +true+
| +"acos"+  | +true+
| +"all"+   | +true+
| +"any"+   | +true+
| +"asin"+  | +true+
| +"atan"+  | +true+
| +"atan2"+ | +true+
| +"avg"+   | +true+
| +"avg"+   | +true+
| +"avg"+   | +true+

2+d|Rows: 11
|===


== Listing functions with other filtering

The listed functions can also be filtered on whether a user can execute them.
This filtering is only available through the `EXECUTABLE` clause and not through the `WHERE` clause.
This is due to using the user's privileges instead of filtering on the available output columns.

There are two options, how to use the `EXECUTABLE` clause.
The first option, is to filter for the current user:

.Query
[source, cypher, role=test-result-skip]
----
SHOW FUNCTIONS EXECUTABLE BY CURRENT USER YIELD *
----

.Result
[role="queryresult",options="header,footer",cols="6*<m"]
|===
| +name+ | +category+ | +description+ | +rolesExecution+ | +rolesBoostedExecution+ | +...+

| +"abs"+
| +"Numeric"+
| +"Returns the absolute value of an integer."+
| +<null>+
| +<null>+
|

| +"abs"+
| +"Numeric"+
| +"Returns the absolute value of a floating point number."+
| +<null>+
| +<null>+
|

| +"acos"+
| +"Trigonometric"+
| +"Returns the arccosine of a number in radians."+
| +<null>+
| +<null>+
|

| +"all"+
| +"Predicate"+
| +"Returns true if the predicate holds for all elements in the given list."+
| +<null>+
| +<null>+
|

| +"any"+
| +"Predicate"+
| +"Returns true if the predicate holds for at least one element in the given list."+
| +<null>+
| +<null>+
|

| +"asin"+
| +"Trigonometric"+
| +"Returns the arcsine of a number in radians."+
| +<null>+
| +<null>+
|

| +"atan"+
| +"Trigonometric"+
| +"Returns the arctangent of a number in radians."+
| +<null>+
| +<null>+
|

| +"atan2"+
| +"Trigonometric"+
| +"Returns the arctangent2 of a set of coordinates in radians."+
| +<null>+
| +<null>+
|

| +"avg"+
| +"Aggregating"+
| +"Returns the average of a set of integer values."+
| +<null>+
| +<null>+
|

| +"avg"+
| +"Aggregating"+
| +"Returns the average of a set of floating point values."+
| +<null>+
| +<null>+
|

6+d|Rows: 10
|===

Notice that the two `roles` columns are empty due to missing the xref::administration/access-control/dbms-administration.adoc#access-control-dbms-administration-role-management[`SHOW ROLE`] privilege.

The second option, is to filter for a specific user:

.Query
[source, cypher, role=test-result-skip]
----
SHOW FUNCTIONS EXECUTABLE BY jake
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| +name+ | +category+ | +description+

| +"abs"+
| +"Numeric"+
| +"Returns the absolute value of an integer."+

| +"abs"+
| +"Numeric"+
| +"Returns the absolute value of a floating point number."+

| +"acos"+
| +"Trigonometric"+
| +"Returns the arccosine of a number in radians."+

| +"all"+
| +"Predicate"+
| +"Returns true if the predicate holds for all elements in the given list."+

| +"any"+
| +"Predicate"+
| +"Returns true if the predicate holds for at least one element in the given list."+

| +"asin"+
| +"Trigonometric"+
| +"Returns the arcsine of a number in radians."+

| +"atan"+
| +"Trigonometric"+
| +"Returns the arctangent of a number in radians."+

| +"atan2"+
| +"Trigonometric"+
| +"Returns the arctangent2 of a set of coordinates in radians."+

| +"avg"+
| +"Aggregating"+
| +"Returns the average of a set of integer values."+

| +"avg"+
| +"Aggregating"+
| +"Returns the average of a set of floating point values."+

3+d|Rows: 10
|===

