= SHOW commands

The `SHOW` command can be used to show a database's metadata.

[[common-behavior-and-rules]]
== Common behavior and rules

Some behavior and rules are common to all `SHOW` commands.
These are listed in this section.
Rules pertaining to specific `SHOW` commands are listed in the relevant sections elsewhere in the documentation.

[[using-show-with-yield]]
=== Using `SHOW` commands with `YIELD`

All `SHOW` commands have default return columns.
To return non-default columns, `YIELD` must be used either to return only specific columns or all available columns.

.Show indexes -- return only default columns
[source, cypher]
----
SHOW INDEXES
----

.Show indexes -- return specific columns with `YIELD`
----
SHOW INDEXES
YIELD name, type, indexProvider
----

.Show indexes -- return all available columns using `YIELD *`
----
SHOW INDEXES
YIELD *
----

[[using-show-with-return]]
=== Using `SHOW` commands with `RETURN`

If the `RETURN` clause is used in any `SHOW` command, `YIELD` is mandatory.

.`RETURN` after `YIELD`
----
SHOW INDEXES
YIELD name, type, indexProvider AS provider, options, createStatement
RETURN name, type, provider, options.indexConfig AS config, createStatement
----

[[filter-show-using-where]]
=== Filter `SHOW` commands using `WHERE`

All `SHOW` commands can be filtered using the xref:clauses/where.adoc[`WHERE`] clause.
This allows you to narrow down results based on specific conditions, such as names or status values.

.Filter `SHOW` command using `WHERE`
----
SHOW INDEXES
YIELD name, type, indexProvider AS provider, options, createStatement
RETURN name, type, provider, options.indexConfig AS config, createStatement
----

[NOTE]
As of Neo4j yyyy.mm, certain `SHOW` commands can be composed with additional Cypher clauses.
For more information, see xref:clauses/show.adoc#composable-show[Composable `SHOW` commands].

[[show-current-graph-type]]
== SHOW CURRENT GRAPH TYPE

.Show the graph type for a database
[source, cypher]
----
SHOW CURRENT GRAPH TYPE
----

For more information, see xref:schema/graph-types/list-graph-types.adoc[Constraints -> Show graph types].

[[show-constraints]]
== SHOW CONSTRAINTS

.Show the constraints in a database
[source, cypher]
----
SHOW CONSTRAINTS
----

For more information, see xref:schema/constraints/list-constraints.adoc[Constraints -> Show constraints]

[[show-databases]]
== SHOW DATABASES

.Show the databases in an instance
[source, cypher]
----
SHOW DATABASES
----

For more information, see the link:{neo4j-docs-base-uri}/operations-manual/current/database-administration/standard-databases/listing-databases/[Operations Manual -> List databases].

[[show-functions]]
== SHOW FUNCTIONS

.Show the functions in a database
[source, cypher]
----
SHOW DATABASES
----

For more information, see xref:functions/listing-functions.adoc[Show indexes].

[[show-indexes]]
== SHOW INDEXES

.Show indexes in a database
[source, cypher]
----
SHOW INDEXES
----

For more information, see xref:indexes/search-performance-indexes/list-indexes.adoc[Show indexes].

[[show-privileges]]
== SHOW PRIVILEGES

.Show indexes in a database
[source, cypher]
----
SHOW PRIVILEGES
----

For more information, see the link:{neo4j-docs-base-uri}/current/authentication-authorization/manage-privileges/#access-control-list-privileges[Operations Manual -> List privileges].

[[show-procedures]]
== SHOW PROCEDURES

.Show procedures available in a database
[source, cypher]
----
SHOW PROCEDURES
----


[[show-roles]]
== SHOW ROLES

.Show procedures available in a database
[source, cypher]
----
SHOW ROLES
----

For more information, see the link:{neo4j-docs-base-uri}/current/authentication-authorization/manage-roles/#access-control-list-roles[Operations Manual -> List roles].


[[show-settings]]
== SHOW SETTINGS

[[show-transactions]]
== SHOW TRANSACTIONS

[[show-user]]
== SHOW USER

[[composable-show-commands]]
== Composable `SHOW` commands


[[syntax]]
== Syntax

//Put railroad here