= SHOW

The `SHOW` command can be used to show the metadata of a database.
This page does discusses common behavior to all `SHOW` commands.
Rules pertaining to specific `SHOW` commands, as well as the different columns returned by them, are listed elsewhere in the documentation:

* xref:schema/constraints/list-constraints.adoc[Show constraints]
* xref:schema/graph-types/list-graph-types.adoc[Show current graph type]
* link:{neo4j-docs-base-uri}/operations-manual/current/database-administration/standard-databases/listing-databases/[Show databases (Operations Manual)]
* xref:functions/listing-functions.adoc[Show functions]
* xref:indexes/search-performance-indexes/list-indexes.adoc[Show indexes]
* link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/manage-privileges/#access-control-list-privileges[Show privileges (Operations Manual)]
* link:{neo4j-docs-base-uri}/operations-manual/current/[Show procedures (Operations Manual)] // TODO: Move to Ops Manual
* link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/manage-roles/#access-control-list-roles[Show roles (Operations Manual)]
* link:{neo4j-docs-base-uri}/operations-manual/current/[Show settings (Operations Manual)] // TODO: Move to Ops Manual
* link:{neo4j-docs-base-uri}/operations-manual/current/[Show transactins (Operations Manual)] // TODO: Move to Ops Manual
* link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/manage-users/#access-control-list-users[Show users (Operations Manual)]

[[common-behavior-and-rules]]
== Common behavior and rules

This section lists the behavior and rules common to all `SHOW` commands.

[[using-show-with-yield]]
=== Returning default and non-default columns using `SHOW` and `YIELD`

All `SHOW` commands have default and non-default return columns.
To return non-default columns, `YIELD` must be used either to return only specific columns or all available columns.

.Show indexes -- return only default columns
[source, cypher]
----
SHOW INDEXES
----

.Show indexes -- return specific columns with `YIELD`
----
SHOW INDEXES
YIELD name, type, indexProvider
----

.Show indexes -- return all available columns using `YIELD *`
----
SHOW INDEXES
YIELD *
----

[[using-show-with-return]]
=== Using `SHOW` commands with `RETURN`

If the `RETURN` clause is used in any `SHOW` command, `YIELD` is mandatory.

.`RETURN` after `YIELD`
----
SHOW INDEXES
YIELD name, type, indexProvider AS provider, options, createStatement
RETURN name, type, provider, options.indexConfig AS config, createStatement
----

[[filter-show-using-where]]
=== Filter `SHOW` commands using `WHERE`

All `SHOW` commands can be filtered using the xref:clauses/where.adoc[`WHERE`] clause.
This allows you to narrow down results based on specific conditions, such as names or status values.

.Filter `SHOW` command using `WHERE`
----
SHOW INDEXES
YIELD name, type, indexProvider AS provider, options, createStatement
RETURN name, type, provider, options.indexConfig AS config, createStatement
----

[role=label--new-2026.05 label--cypher-25-only]
[[composable-show-commands]]
== Composable `SHOW` commands

The following `SHOW` commands can be combined with general Cypher clauses in a single query:

* `SHOW CONSTRAINTS`
* `SHOW CURRENT GRAPH TYPE`
* `SHOW DATABASES`
* `SHOW FUNCTIONS`
* `SHOW INDEXES`
* `SHOW PROCEDURES`
* `SHOW SETTINGS`
* `SHOW TRANSACTIONS`

[NOTE]
====
When combining a `SHOW` command with other clauses, the `YIELD` clause is mandatory and must not be omitted.
In addition, `YIELD *` is not permitted.
Instead, the `YIELD` clause needs to explicitly list the yielded columns.
The query must also end with a valid last clause (like a `RETURN` or an updating clause).
====

.Return all functions and procedures
[source, cypher]
----
SHOW PROCEDURES
YIELD name, signature
RETURN name, signature, 'procedure' AS type
UNION
SHOW FUNCTIONS
YIELD name, signature
RETURN name, signature, 'function' AS type
----

.Return all functions with more than one signature
[source, cypher]
----
SHOW FUNCTIONS
YIELD name, signature
WITH name, collect(signature) AS signatures
FILTER size(signatures) > 1
RETURN name, signatures
----

[[syntax]]
== Syntax

Add railroad and grammar