:description: `WHERE` adds constraints to the patterns in a `MATCH` or `OPTIONAL MATCH` clause or filters the results of a `WITH` clause.

[[query-where]]
= WHERE

[[where-introduction]]
== Introduction

The `WHERE` clause is not a clause in its own right -- rather, it is subclause used with `MATCH`, `OPTIONAL MATCH`, and `WITH` clauses.

When used with `MATCH` and `OPTIONAL MATCH`, `WHERE` adds constraints to the patterns described.
_It should not be seen as a filter after the matching is finished._

In the case of `WITH`, however, `WHERE` simply filters the results.

In the case of multiple `MATCH` / `OPTIONAL MATCH` clauses, the predicate in `WHERE` is always a part of the patterns in the directly preceding `MATCH` / `OPTIONAL MATCH`.
Both results and performance may be impacted if `WHERE` is put inside the wrong `MATCH` clause.

xref:indexes/search-performance-indexes/managing-indexes.adoc[Indexes] may be used to optimize queries using `WHERE` in a variety of cases.

[[where-example-graph]]
== Example graph

The following graph is used for the examples below:

image::graph_where_clause.svg[width="600",role="middle"]

To recreate the graph, run the following query in an empty Neo4j database:

[source, cypher, role=test-setup]
----
CREATE
(andy:Swedish:Person {name: 'Andy', age: 36, belt: 'white'}),
(timothy:Person {name: 'Timothy', age: 25}),
(peter:Person {name: 'Peter', age: 35, email: 'peter_n@example.com'}),
(andy)-[:KNOWS {since: 2012}]->(timothy),
(andy)-[:KNOWS {since: 1999}]->(peter)
----

[[filter-on-node-label]]
=== Basic filtering

To filter nodes by label, write a label predicate after the `WHERE` keyword using `WHERE n:foo`:

.Filter by node label
[source, cypher]
----
MATCH (n)
WHERE n:Swedish
RETURN n.name, n.age
----

The `name` and `age` values for `Andy` are returned:

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| n.name | n.age
| "Andy" | 36
2+|Rows: 1
|===


To filter on a node property, write your clause after the `WHERE` keyword:

.Filter by node property
[source, cypher]
----
MATCH (n:Person)
WHERE n.age < 30
RETURN n.name, n.age
----

The `name` and `age` values for `Timothy` are returned because he is less than 30 years of age:

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| n.name | n.age
| "Timothy" | 25
2+|Rows: 1
|===

To filter on a relationship property, write your clause after the `WHERE` keyword:

.Filter on a relationship property
[source, cypher]
----
MATCH (n:Person)-[k:KNOWS]->(f)
WHERE k.since < 2000
RETURN f.name, f.age, f.email
----

The `name`, `age` and `email` values for `Peter` are returned because `Andy` has known him since before 2000:

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| f.name | f.age | f.email
| "Peter" | 35 | "peter_n@example.com"
3+|Rows: 1
|===


[[filter-on-dynamic-property]]
== Filter on dynamic properties

To filter on a property using a dynamically computed name, use square bracket syntax:

.Parameters
[source, parameters]
----
{
  "propname": "age"
}
----

.Filter on dynamically computed node property
[source, cypher]
----
MATCH (n:Person)
WHERE n[$propname] < 30
RETURN n.name, n.age
----

The `name` and `age` values for `Timothy` are returned because he is less than 30 years of age:

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| n.name | n.age
| "Timothy" | 25
2+|Rows: 1
|===


[[usage-with-with-clause]]
== Using `WITH`

As `WHERE` is not considered a clause in its own right, its scope is not limited by a `WITH` directly before it.

.Query
[source, cypher]
----
MATCH (n:Person)
WITH n.name as name
WHERE n.age = 25
RETURN name
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| name
| "Timothy"
|Rows: 1
|===


The name for `Timothy` is returned because the `WHERE` clause still acts as a filter on the `MATCH`.
`WITH` reduces the scope for the rest of the query moving forward.
In this case, `name` is now the only variable in scope for the `RETURN` clause.

[[missing-properties-and-values]]
== Missing properties and values


As missing properties evaluate to `null`, the comparison in the example will evaluate to `false` for nodes without the `belt` property:

.Query
[source, cypher]
----
MATCH (n:Person)
WHERE n.belt = 'white'
RETURN n.name, n.age, n.belt
----

Only the `name`, `age`, and `belt` values of nodes with white belts are returned:

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| n.name | n.age | n.belt
| "Andy" | 36 | "white"
3+|Rows: 1
|===


To compare node or relationship properties against missing properties, use the `IS NULL` operator:

.Query
[source, cypher]
----
MATCH (n:Person)
WHERE n.belt = 'white' OR n.belt IS NULL
RETURN n.name, n.age, n.belt
ORDER BY n.name
----

This returns all values for all nodes, even those without the `belt` property:

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| n.name | n.age | n.belt
| "Andy" | 36 | "white"
| "Peter" | 35 | <null>
| "Timothy" | 25 | <null>
3+|Rows: 3
|===


[[pattern-element-predicates]]
== Filter fixed-length patterns

`WHERE` clauses can be added to pattern elements in order to specify additional constraints.

`WHERE` can appear inside a node pattern in a `MATCH` clause or a pattern comprehension:

.Using `WHERE` inside a node pattern
[source, cypher]
----
WITH 30 AS minAge
MATCH (a:Person WHERE a.name = 'Andy')-[:KNOWS]->(b:Person WHERE b.age > minAge)
RETURN b.name
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| b.name
| "Peter"
|Rows: 1
|===

When used this way, predicates in `WHERE` can reference the node variable that the `WHERE` clause belongs to, but not other elements of the `MATCH` pattern.

The same rule applies to pattern comprehensions:

.`WHERE` inside a pattern comprehension
[source, cypher]
----
MATCH (a:Person {name: 'Andy'})
RETURN [(a)-->(b WHERE b:Person) | b.name] AS friends
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| friends
| ["Peter","Timothy"]
|Rows: 1
|===

`WHERE` can also appear inside a relationship pattern in a `MATCH` clause:

.`WHERE` inside relationship pattern
[source, cypher]
----
WITH 2000 AS minYear
MATCH (a:Person)-[r:KNOWS WHERE r.since < minYear]->(b:Person)
RETURN r.since
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| r.since
| 1999
|Rows: 1
|===

Putting predicates inside a relationship pattern can help with readability.
Note that it is strictly equivalent to using a standalone `WHERE` sub-clause.

.Query
[source, cypher]
----
WITH 2000 AS minYear
MATCH (a:Person)-[r:KNOWS]->(b:Person)
WHERE r.since < minYear
RETURN r.since
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| r.since
| 1999
|Rows: 1
|===

Relationship pattern predicates can also be used inside pattern comprehensions, where the same caveats apply:

.Query
[source, cypher]
----
WITH 2000 AS minYear
MATCH (a:Person {name: 'Andy'})
RETURN [(a)-[r:KNOWS WHERE r.since < minYear]->(b:Person) | r.since] AS years
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| years
| [1999]
|Rows: 1
|===

For information about using `WHERE` in variable-length patterns, see xref:patterns/variable-length-patterns.adoc#quantified-path-patterns-predicates[]