# Inspired from https://github.com/antlr/grammars-v4/blob/master/ebnf/bnf.g4

rulelist : rule*
rule : lhs "::=" rhs
lhs : ruleid
rhs : alternatives
alternatives : alternative ("|" alternative)*
alternative : (optional | grouping | oneormore | text | ruleid)+
optional : "[" alternatives "]"
grouping : "{" alternatives "}"
oneormore : alternative "..."

text : ESCAPED_STRING
ruleid : "<" ID ">"

ID : ("a".."z" | "A".."Z") ("a".."z" | "A".."Z" | "0".."9" | "-" | " ")+
DOUBLE_QUOTE: "\""

%import common.WS
%import common.ESCAPED_STRING
%ignore WS