= Aura and Cypher

== Introduction

Aura is Neo4j's fully managed cloud service. 
It consists of AuraDB and AuraDS.
AuraDB is a graph database service for developers building intelligent applications, and AuraDS is a graph data science service for data scientists building predictive models and workflows. 

AuraDB is available on three tiers: AuraDB Free, AuraDB Pro, and AuraDB Enterprise.
For more information, see link:{neo4j-docs-base-uri}/aura/auradb[Aura docs - Neo4j AuraDB overview].

AuraDS is available on two tiers: AuraDS Pro and AuraDS Enterprise.
For more information, see link:{neo4j-docs-base-uri}/aura/aurads[Aura docs - Neo4j AuraDS overview]

== Using Cypher on Aura

Most Cypher clauses are available on all tiers of Aura. 
There are, however, some clauses which are not possible to run on any Aura instance.
For example, it is not possible to create, alter or drop databases using Aura, nor is it possible to alter or drop servers.

There are also certain features of Cypher which are only available on AuraDB Enterprise.
These fall under the role-based access clauses of Cypher. 
For example, it is possible to create and drop roles using Aura DB Enterprise, but not using any other tier of Aura. 

The Cypher Manual uses two different labels to differentiate this distinction:

[options="header,cols=""2a,2a"]
|===
| Label | Description
| label:not-on-aura[Not available on Aura] | Cypher feature not available on any tier of Aura.
| label:aura-db-enterprise[AuraDB Enterprise] | Cypher feature only available on AuraDB Enterprise.
|===

== Aura and the Cypher Cheat Sheet

Each different tier of Aura has a customized version of the Cypher Cheat Sheet which only shows the features of Cypher available for the chosen tier. 

The Aura Cheat Sheet can be accessed here. 
Note that the default tier is AuraDB Enterprise. 
