# MATCH clause

<simple match statement> ::= 
  "MATCH" <graph pattern>

<graph pattern> ::= 
  [ <match mode> ] <path pattern> [ { "," <path pattern> }... ] [ <graph pattern where clause> ]

<path pattern> ::= 
  [ <binding variable> "=" ] [ <path pattern prefix> ] <path pattern expression>

<path pattern prefix> ::= 
    "ALL" [ "PATH" | "PATHS" ]
  | "ANY" [ <unsigned decimal integer> | "$" <parameter name> ] [ "PATH" | "PATHS" ]
  | "ALL SHORTEST" [ "PATH" | "PATHS" ]
  | "ANY SHORTEST" [ "PATH" | "PATHS" ]
  | "SHORTEST" { <unsigned decimal integer> | "$" <parameter name> } [ "PATH" | "PATHS" ]
  | "SHORTEST" [ <unsigned decimal integer> | "$" <parameter name> ] [ "PATH" | "PATHS" ] { "GROUP" | "GROUPS" }

<path pattern expression> ::= 
    <path term>
  | <legacy shortest path pattern>

<path term> ::= 
    <path factor>
  | <path term> <path factor>

<path factor> ::= 
    <path primary>
  | <path primary> <graph pattern quantifier>
  | <path primary> "?"

<path primary> ::= 
    <node pattern>
  | <relationship pattern>
  | "(" [ <binding variable> "=" ] <path pattern expression> [ "WHERE" <value expression> ] ")"

<node pattern> ::= 
  "(" [ <binding variable> [ <is node label expression> ] [ <element pattern predicate> ] | <is node label expression> [ <element pattern predicate> ] | <element pattern predicate> ] ")"

<element pattern predicate> ::= 
    "WHERE" <value expression>
  | <element property specification>
  | "$" <parameter name>

<element property specification> ::= 
  "{" <property key value pair list> "}"

<property key value pair list> ::= 
  <property key value pair> [ { "," <property key value pair> }... ]

<property key value pair> ::= 
  <property name> ":" <value expression>

<relationship pattern> ::= 
    "<-" [ "[" [ <relationship pattern filler> ] "]" ] "-"
  | "-" [ "[" [ <relationship pattern filler> ] "]" ] "->"
  | "<-" [ "[" [ <relationship pattern filler> ] "]" ] "->"
  | "-" [ "[" [ <relationship pattern filler> ] "]" ] "-"

<relationship pattern filler> ::= 
    <binding variable> [ <is relationship label expression> ] [ <path length> ] [ <element pattern predicate> ]
  | <is relationship label expression> [ <path length> ] [ <element pattern predicate> ]
  | <path length> [ <element pattern predicate> ]
  | <element pattern predicate>

<path length> ::= 
  "*" [ [ <unsigned decimal integer> ] ".." [ <unsigned decimal integer> ] | <unsigned decimal integer> ]

<graph pattern quantifier> ::= 
    "*"
  | "+"
  | "{" <unsigned integer> "}"
  | "{" [ <unsigned decimal integer> ] "," [ <unsigned decimal integer> ] "}"

<is node label expression> ::= 
    ":" <node label expression legacy>
  | { ":" | "IS" } <label expression>

<is relationship label expression> ::= 
    ":" <relationship label expression legacy>
  | { ":" | "IS" } <label expression>

<label expression> ::= 
    <label term>
  | <label expression> "|" <label term>

<label term> ::= 
    <label factor>
  | <label term> "&" <label factor>

<label factor> ::= 
    <label primary>
  | <label negation>

<label negation> ::= 
  "!" <label primary>

<label primary> ::= 
    <label name>
  | "(" <label expression> ")"
  | "%"
  | "$" [ "ALL" | "ANY" ] "(" <value expression> ")"

<value expression> ::= 
  <boolean value expression>

<boolean value expression> ::= 
    <boolean term xor>
  | <boolean value expression> "OR" <boolean term xor>

<boolean term xor> ::= 
    <boolean term>
  | <boolean term xor> "XOR" <boolean term>

<boolean term> ::= 
    <boolean factor>
  | <boolean term> "AND" <boolean factor>

<boolean factor> ::= 
  [ { "NOT" }... ] <boolean primary>

<boolean primary> ::= 
    <pattern expression>
  | <predicate>

<pattern expression> ::= 
  <node pattern> { <relationship pattern> <node pattern> }...

<label name> ::= 
  <identifier>

<property name> ::= 
  <identifier>

<binding variable> ::= 
  <identifier>