# MATCH clause short

<simple match statement> ::= 
  "MATCH" <graph pattern>

<graph pattern> ::= 
  [ <match mode> ] link:/cypher-manual/25/patterns/reference/#path-patterns[<path pattern>] [ { "," link:/cypher-manual/25/patterns/reference/#path-patterns[<path pattern>] }... ] [ <graph pattern where clause> ]

<match mode> ::= 
    "REPEATABLE" { "ELEMENT" [ "BINDINGS" ] | "ELEMENTS" }
  | "DIFFERENT" { "RELATIONSHIP" [ "BINDINGS" ] | "RELATIONSHIPS" }

link:/cypher-manual/25/patterns/reference/#path-patterns[<path pattern>] ::= 
  [ link:/cypher-manual/25/syntax/naming/[<identifier>] "=" ] [ <path pattern prefix> ] <path pattern expression>