= Predicate operators
:table-caption!:
:description: Information about using predicate operators in Cypher (including boolean, comparison, string, and list operators).

Predicate operators are used to evaluate expressions and return `BOOLEAN` values.
They are categorized as follows:

* xref:expressions/predicates/operators.adoc#boolean-operators[Boolean operators] (`AND`, `OR`, `XOR`, `NOT`)
* xref:expressions/predicates/operators.adoc#comparison-operators[Comparison operators] (`=`, `<>`, `<`, `>`, `\<=`, `>=`, `IS NULL`, `IS NOT NULL`)
*  xref:expressions/predicates/operators.adoc#string-operators[String operators] (`=~`, `STARTS WITH`, `ENDS WITH`, `CONTAINS`, `IS NORMALIZED`, `IS NOT NORMALIZED`)
* xref:expressions/predicates/operators.adoc#list-operators[List operators] (`IN`)

== Example graph

The following graph is used for the examples below:

image::predicate_operators.svg[width="500",role="middle"]

To recreate the graph, run the following query in an empty Neo4j database:

[source, cypher, role=test-setup]
----
CREATE (alice:Person {name:'Alice', age: 65, role: 'Project manager', email: 'alice@company.com'}),
       (cecil:Person {name: 'Cecil', age: 25, role: 'Software developer', email: 'cecil@private.se'}),
       (cecilia:Person {name: 'Cecilia', age: 31, role: 'Software developer'}),
       (charlie:Person {name: 'Charlie', age: 61, role: 'Security engineer'}),
       (daniel:Person {name: 'Daniel', age: 39, role: 'Director', email: 'daniel@company.com'}),
       (eskil:Person {name: 'Eskil', age: 39, role: 'CEO', email: 'eskil@company.com'})
----

[[boolean-operators]]
== Boolean operators

The boolean operators comprise:

* Conjunction: `AND`
* Disjunction: `OR`
* Exclusive disjunction: `XOR`
* Negation: `NOT`

.Truth table for boolean operators
[options="header", cols="^,^,^,^,^,^", width="85%"]
|===
|a | b | a `AND` b | a `OR` b | a `XOR` b | `NOT` a
|`FALSE` | `FALSE` | `FALSE` | `FALSE` | `FALSE` | `TRUE`
|`FALSE` | `NULL` | `FALSE` | `NULL` | `NULL` | `TRUE`
|`FALSE` | `TRUE` | `FALSE` | `TRUE` | `TRUE` | `TRUE`
|`TRUE` | `FALSE` | `FALSE` | `TRUE` | `TRUE` | `FALSE`
|`TRUE` | `NULL` | `NULL` | `TRUE` | `NULL` | `FALSE`
|`TRUE` | `TRUE` | `TRUE` | `TRUE` | `FALSE` | `FALSE`
|`NULL` | `FALSE` | `FALSE` | `NULL` | `NULL` | `NULL`
|`NULL` | `NULL` | `NULL` | `NULL` | `NULL` | `NULL`
|`NULL` | `TRUE` | `NULL` | `TRUE` | `NULL` | `NULL`
|===

.Boolean operators
=====

.`AND` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.age > 30 AND n.role = 'Software developer'
RETURN n.name AS name, n.age AS age, n.role AS role
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| name | age | role

| "Cecilia" | 31 | "Software developer"

3+d|Rows: 1
|===

.`OR` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.age < 30 OR n.role = 'Software developer'
RETURN n.name AS name, n.age AS age, n.role AS role
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| name | age | role

| "Cecilia" | 31  | "Software developer"
| "Cecil" | 25 | "Software developer"

3+d|Rows: 2
|===

.`XOR` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.age > 30 XOR n.role = 'Software developer'
RETURN n.name AS name, n.age AS age, n.role AS role
----

.Result
[role="queryresult",options="header,footer",cols="5*<m"]
|===
| name | age | role

| "Alice" | 65 | "Project manager"
| "Cecil" | 25 | "Software developer"
| "Charlie" | 61 | "Security engineer"
| "Eskil"   | 39  | "CEO"  
| "Daniel" | 39 | "Director"

3+d|Rows: 5
|===

.`NOT` operator
[source, cypher]
----
MATCH (n:Person)
WHERE NOT n.age = 39
RETURN n.name AS name, n.age AS age
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | age |

| "Alice" | 65
| "Cecil" | 25
| "Cecilia" | 31
| "Charlie" | 61

2+d|Rows: 4
|===

.Combining boolean operators
[source, cypher]
----
MATCH (n:Person)
WHERE n.role = 'Software developer' XOR (n.age > 60 AND n.role = 'Security engineer') OR NOT (n.role = 'Director' OR n.name = 'Eskil')
RETURN n.name AS name, n.age AS age, n.role AS role
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| name | age | role

| "Alice" | 65 | "Project manager"
| "Cecil"   | 25  | "Software developer" 
| "Cecilia" | 31 | "Software developer"
| "Daniel" | 39 | "Director"

3+d|Rows: 3

|===

=====

[[comparison-operators]]
== Comparison operators

The comparison operators comprise:

* Equality: `=`
* Inequality: `<>`
* Less than: `<`
* Greater than: `>`
* Less than or equal to: `\<=`
* Greater than or equal to: `>=`
* `IS NULL`
* `IS NOT NULL`

[TIP]
For more information about how Cypher orders and compares different value types, see xref:values-and-types/ordering-equality-comparison.adoc[Values and types -> Equality, ordering, and comparison of value types]

.Comparison operators
=====

.Equality operator (`=`)
[source, cypher]
----
MATCH (n:Person)
WHERE n.role = 'Software developer'
RETURN n.name AS name, n.role AS role
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | role

| "Cecil" | "Software developer"
| "Cecilia" | "Software developer"

2+d|Rows: 2
|===

.Inequality operator (`<>`)
[source, cypher]
----
MATCH (n:Person)
WHERE n.role <> 'Software developer'
RETURN n.name AS name, n.role AS role
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | role

| "Alice" | "Project manager"
| "Charlie" | "Security engineer"
| "Daniel" | "Director"
| "Eskil" | "CEO"

2+d|Rows: 4
|===

.Less than operator (`<`)
[source, cypher]
----
MATCH (n:Person)
WHERE n.age < 39
RETURN n.name AS name, n.age AS age
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | age

| "Cecil" | 25
| "Cecilia" | 31

2+d|Rows: 2
|===

.Less than or equal operator (`\<=`)
[source, cypher]
----
MATCH (n:Person)
WHERE n.age <= 39
RETURN n.name AS name, n.age AS age
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | age

| "Cecil" | 25
| "Cecilia" | 31
| "Daniel" | 39
| "Eskil" | 39

2+d|Rows: 4
|===

.Greater than operator (`>`)
[source, cypher]
----
MATCH (n:Person)
WHERE n.age > 39
RETURN n.name AS name, n.age AS age
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | age

| "Alice" | 65
| "Charlie" | 61

2+d|Rows: 2
|===

.Greater than or equal operator (`\=>`)
[source, cypher]
----
MATCH (n:Person)
WHERE n.age => 39
RETURN n.name AS name, n.age AS age
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | age

| "Alice" | 65
| "Charlie" | 61
| "Daniel" | 39
| "Eskil" | 39

2+d|Rows: 4
|===

.`IS NULL` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.email IS NULL
RETURN n.name AS name
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===

| name

| "Cecilia"
| "Charlie"

1+d|Rows: 2
|===

.`IS NOT NULL` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.email IS NOT NULL
RETURN n.name AS name, n.email AS email
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | email

| "Alice" | "alice@company.com"
| "Cecil" | "cecil@private.se"
| "Daniel" | "daniel@company.com"
| "Eskil" | "eskil@company.se"

2+d|Rows: 4
|===

=====

[[chaining-comparison-oeprators]]
=== Chaining comparison operators

There is no limit on how many comparisons can be chained together.
If chaining two or more comparison operators, each comparison is effectively separated by an `AND` operator (though this `AND` is not required syntactically).
For example, if `a, b, c, ..., z` are expressions and `op1, op2, ..., opN` are comparison operators, then the following expressions are equivalent:

.Equivalent expressions
[source, syntax]
----
a op1 b op2 c ... y opN z;
a op1 b AND b op2 c AND ... y opN z
----

Note that `a op1 b op2 c` does not imply any kind of comparison between `a` and `c`.
For example, in `x < y > z`, `x` and `z` are not compared.

[[chaining-equality-operators]]
==== Chaining equality operators

Chains of `=` and `<>` are treated in a special way in Cypher.
Specifically, `1=1=true` is equivalent to `1=1 AND 1=true` and not to `(1=1)=true` or `1=(1=true)`.
For example, the following expressions are equivalent.

.Equivalent expressions
[source, syntax, role=noplay]
----
a < b = c <= d <> e;
a < b AND b = c AND c <= d AND d <> e
----

[[string-operators]]
== String operators

The string operators comprise:

* Prefix: `STARTS WITH` (case sensitive)
* Suffix: `ENDS WITH` (case sensitive)
* substring: `CONTAINS` (case sensitive)
* Regular expression: `=~`
* `IS NORMALIZED`
* `IS NOT NORMALIZED`

These operators perform _case-sensitive_ matching.
Attempting to use them on values which are not `STRING` values will return `NULL`.

.Prefix, suffix, and substring operators
=====

.`STARTS WITH` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.name STARTS WITH 'C'
RETURN n.name AS name
----


.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| name

| "Cecil"
| "Cecilia"
| "Charlie"

1+d|Rows: 3
|===

.`ENDS WITH` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.role ENDS WITH 'developer'
RETURN n.name AS name, n.role AS role
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | role

| "Cecil" | "Software developer"
| "Cecilia" | "Software developer"

2+d|Rows: 2
|===

.`CONTAINS` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.role CONTAINS 'eng'
RETURN n.name AS name, n.role AS role
----


.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | role

| "Charlie" | "Security engineer"

2+d|Rows: 1
|===

=====

[[regular-expressions]]
=== Regular expressions

Cypher supports filtering using regular expressions.
The regular expression syntax is inherited from the link:https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html[Java regular expressions].
This includes support for flags that change how `STRING` values are matched, including the case-insensitive `(?i)`, multiline `(?m)`, and dotall `(?s)` flags.
Flags are given at the beginning of the regular expression.

.Regular expressions
=====

.Regular expression (`=~`)
[source, cypher]
----
MATCH (n:Person)
WHERE n.email =~ '.*@company.com'
RETURN n.name AS name, n.email AS email
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | email

| "Alice" | "alice@company.com"
| "Daniel" | "daniel@company.com"
| "Eskil" | "eskil@company.com"

2+d|Rows: 3
|===

By pre-pending a regular expression with the flag `(?i)`, the whole expression becomes case-insensitive:

.Case-insensitive regular expression `(?i)` 
[source, cypher]
----
MATCH (n:Person)
WHERE n.name =~ '(?i)CEC.*'
RETURN n.name
----

The names of both `Cecil` and `Cecilia` are returned because their name starts with `'CEC'` regardless of casing:

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| name

| "Cecil"
| "Cecilia"

1+d|Rows: 2
|===


=====


[[escaping-in-regular-expressions]]
=== Escaping in regular expressions

Characters such as `.` or `*` have special meaning in a regular expression.
To use these as ordinary characters without special meaning, escape them.

.Escaped characters in a regular expression
[source, cypher]
----
MATCH (n:Person)
WHERE n.email =~ '.*\\.se'
RETURN n.name AS name, n.email AS email
----

`Cecil` is returned because his email ends with `'.se'`:

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | email

| "Cecil" | "cecil@private.se"

2+d|Rows: 1

|===

Note that the regular expression constructs in
link:https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html[Java regular expressions] are applied only after resolving the escaped character sequences in the given xref::expressions/expressions-overview.adoc#expressions-string-literals[string literal].
It is sometimes necessary to add additional backslashes to express regular expression constructs.
This list clarifies the combination of these two definitions, containing the original escape sequence and the resulting character in the regular expression:

[options="header", cols=">1,<2,<2"]
|===
|String literal sequence|Resulting Regex sequence|Regex match
|`\t`|Tab|Tab
|`\\t`|`\t`|Tab
|`\b`|Backspace|Backspace
|`\\b`|`\b`|Word boundary
|`\n`|Newline|NewLine
|`\\n`|`\n`|Newline
|`\r`|Carriage return|Carriage return
|`\\r`|`\r`|Carriage return
|`\f`|Form feed|Form feed
|`\\f`|`\f`|Form feed
|`\'`|Single quote|Single quote
|`\"`|Double quote|Double quote
|`\\`|Backslash|Backslash
|`\\\`|`\\`|Backslash
|`\uxxxx`|Unicode UTF-16 code point (4 hex digits must follow the `\u`)|Unicode UTF-16 code point (4 hex digits must follow the `\u`)
|`\\uxxxx`|`\uxxxx`|Unicode UTF-16 code point (4 hex digits must follow the `\u`)
|===

[NOTE]
====
Using regular expressions with unsanitized user input makes you vulnerable to Cypher injection.
Consider using xref:syntax/parameters.adoc[parameters] instead.
====

[[string-normalization-operators]]
=== String normalization operators

The `IS NORMALIZED` operator is used to check whether the given `STRING` is in the `NFC` Unicode normalization form:

[NOTE]
====
Unicode normalization is a process that transforms different representations of the same string into a standardized form.
For more information, see the documentation for link:https://unicode.org/reports/tr15/#Norm_Forms[Unicode normalization forms].
====

.`IS NORMALIZED` operator
[source, cypher]
----
RETURN 'the \u212B char' IS NORMALIZED AS normalized
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| normalized
| FALSE

1+|Rows: 1
|===

Because the given `STRING` contains a non-normalized Unicode character (`\u212B`), `FALSE` is returned.

To normalize a `STRING`, use the xref:functions/string.adoc#functions-normalize[normalize()] function.

Note that the `IS NORMALIZED` operator returns `NULL` when used on a non-`STRING` value.
For example, `RETURN 1 IS NORMALIZED` returns `NULL`.

The `IS NOT NORMALIZED` operator is used to check whether the given `STRING` is not in the `NFC` Unicode normalization form:

.`IS NOT NORMALIZED`
[source, cypher]
----
RETURN 'the \u212B char' IS NOT NORMALIZED AS notNormalized
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| notNormalized
| TRUE

1+|Rows: 1
|===

Because the given `STRING` contains a non-normalized Unicode character (`\u212B`), and is not normalized, `TRUE` is returned.

Note that the `IS NOT NORMALIZED` operator returns `NULL` when used on a non-`STRING` value.
For example, `RETURN 1 IS NOT NORMALIZED` returns `NULL`.


[[defining-normalization-forms]]
==== Using `IS NORMALIZED` with a specified normalization type

It is possible to define which Unicode normalization type is used (the default is `NFC`).

The available normalization types are:

* `NFC`
* `NFD`
* `NFKC`
* `NFKD`

.Query
[source, cypher]
----
WITH 'the \u00E4 char' as myString
RETURN myString IS NFC NORMALIZED AS nfcNormalized,
    myString IS NFD NORMALIZED AS nfdNormalized
----

The given `STRING` contains the Unicode character: `\u00E4`, which is considered normalized in `NFC` form, but not in `NFD` form.

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| nfcNormalized | nfdNormalized
| TRUE          | FALSE
2+|Rows: 2
|===

It is also possible to specify the normalization form when using the negated normalization operator.
For example, `RETURN "string" IS NOT NFD NORMALIZED`.

[[list-operators]]
== List operators

The list operators comprise:

* Membership: `IN`

To check if an element exists in a xref:values-and-types/lists.adoc[`LIST`], use the `IN` operator.

.`IN` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.role IN ['Software developer', 'Project manager']
RETURN n.name AS name, n.role AS role
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | role

| "Alice"   | "Project manager"
| "Cecil"   | "Software developer"
| "Cecilia" | "Software developer"

2+d|Rows: 3
|===

For additional list predicates, see:

* The following quantifier predicates: xref:functions/predicate.adoc#functions-all[`all()`], xref:functions/predicate.adoc#functions-any[`any()`], xref:functions/predicate.adoc#functions-none[`none()`], and xref:functions/predicate.adoc#functions-single[`single()`].
* The xref:functions/predicate.adoc#functions-isempty[`isEmpty()`] function.
