# graph-pattern

<graph pattern> ::= 
  [ <match mode> ] <path pattern list> [ <graph pattern where clause> ]

<path pattern list> ::= 
  <path pattern> [ { "," <path pattern> }... ]

<graph pattern where clause> ::= 
  "WHERE" <search condition>