<graph pattern> ::= [ xref:patterns/reference/match-modes-and-path-modes.adoc#path-modes[<match mode>] ] <path pattern list> [ xref:indexes/search-performance-indexes/index-hints.adoc[<hints>] ][ <graph pattern where and search clause> ] 
<graph pattern where and search clause> ::= <graph pattern where clause> [ xref:clauses/search.adoc[<search clause>] ]| xref:clauses/search.adoc[<search clause>] [ <graph pattern where clause> ] 
<path pattern list> ::= xref:patterns/reference/path-patterns-and-graph-patterns.adoc[<path pattern>] [{ "," xref:patterns/reference/path-patterns-and-graph-patterns.adoc[<path pattern>] }...] 
<graph pattern where clause> ::= xref:clauses/where.adoc[<where clause>]