<label expression> ::= <label term> | <label expression> "|" <label term> 
<label term> ::= <label factor> | <label term> <ampersand> <label factor> 
<label factor> ::= <label primary> | <label negation> 
<ampersand> ::= "&" 
<label primary> ::= xref:queries/concepts.adoc#core-concepts-nodes[<label name>] | <parenthesized label expression> | <wildcard label> | <dynamic label expression> 
<label negation> ::= <exclamation mark> <label primary> 
<parenthesized label expression> ::= "(" <label expression> ")" 
<wildcard label> ::= <percent> 
<dynamic label expression> ::= "$" [ <dynamic label expression quantifier> ] "(" xref:expressions/index.adoc[<value expression>] ")" 
<exclamation mark> ::= "!" 
<percent> ::= "%" 
<dynamic label expression quantifier> ::= "ALL" | "ANY"