<label expression> ::= 
    <label term>
  | <label expression> "|" <label term>

<label term> ::= 
    <label factor>
  | <label term> "&" <label factor>

<label factor> ::= 
    <label primary>
  | "!" <label primary>

<label primary> ::= 
    <label name>
  | "(" <label expression> ")"
  | "%"
  | <dynamic label expression>