<legacy shortest path pattern> ::= { "SHORTESTPATH" | "ALLSHORTESTPATHS" } "(" xref:patterns/reference/node-and-relationship-patterns.adoc#node-patterns[<node pattern>] xref:patterns/reference/node-and-relationship-patterns.adoc#relationship-patterns[<relationship pattern>] xref:patterns/reference/node-and-relationship-patterns.adoc#node-patterns[<node pattern>] ")"