<match mode> ::= <repeatable elements match mode> | <different edges match mode> 
<repeatable elements match mode> ::= "REPEATABLE" <element bindings or elements> 
<different edges match mode> ::= "DIFFERENT" <edge bindings or edges> 
<element bindings or elements> ::= "ELEMENT" [ "BINDINGS" ]| "ELEMENTS" 
<edge bindings or edges> ::= "RELATIONSHIP" [ "BINDINGS" ]| "RELATIONSHIPS"