# match-mode

<match mode> ::= 
    "REPEATABLE" <element bindings or elements>
  | "DIFFERENT" <edge bindings or edges>

<element bindings or elements> ::= 
    "ELEMENT" [ "BINDINGS" ]
  | "ELEMENTS"

<edge bindings or edges> ::= 
    "RELATIONSHIP" [ "BINDINGS" ]
  | "RELATIONSHIPS"