# nodes

<node pattern> ::= 
  "(" [ <node pattern filler> ] ")"

<node pattern filler> ::= 
    <binding variable> [ <label expression> ] [ <element pattern predicate> ]
  | <label expression> [ <element pattern predicate> ]
  | <element pattern predicate>

<element pattern predicate> ::= 
    "WHERE" <value expression>
  | "{" <property key value expression> "}"
  | "$" <parameter name>