<node pattern> ::= "(" [ <node pattern filler> ] ")" 
<node pattern filler> ::= xref:syntax/variables.adoc[<binding variable>] [ <is node label expression> ][ <element pattern predicate> ]| <is node label expression> [ <element pattern predicate> ]| <element pattern predicate> 
<is node label expression> ::= ":" xref:expressions/predicates/label-expression-predicates.adoc#label-expression-predicate-colon-syntax[<node label expression legacy>] | xref:expressions/predicates/label-expression-predicates.adoc#is-labeled-predicate[<is label expression>] 
<element pattern predicate> ::= <element pattern where clause> | xref:patterns/reference/node-and-relationship-patterns.adoc#properties[<element property specification>] | xref:syntax/parameters.adoc[<general parameter reference>] 
<element pattern where clause> ::= "WHERE" xref:expressions/index.adoc[<value expression>]