<path pattern> ::= [ <path variable declaration> ][ <path pattern prefix> ] <path pattern expression> 
<path variable declaration> ::= xref:syntax/variables.adoc[<binding variable>] "=" 
<path pattern prefix> ::= xref:patterns/reference/match-modes-and-path-modes.adoc#path-modes[<path mode prefix>] | xref:patterns/reference/shortest-paths.adoc#shortest-paths[<path search prefix>] 
<path pattern expression> ::= <path term> | xref:patterns/reference/shortest-paths.adoc#shortest-functions[<legacy shortest path pattern>] 
<path term> ::= <path factor> | <path term> <path factor> 
<path factor> ::= <path primary> | <quantified path primary> 
<path primary> ::= <element pattern> | <parenthesized path pattern expression> 
<quantified path primary> ::= <path primary> xref:patterns/reference/variable-length-paths.adoc#quantifiers[<graph pattern quantifier>] 
<element pattern> ::= xref:patterns/reference/node-and-relationship-patterns.adoc#node-patterns[<node pattern>] | xref:patterns/reference/node-and-relationship-patterns.adoc#relationship-patterns[<relationship pattern>] 
<parenthesized path pattern expression> ::= "(" [ <subpath variable declaration> ] <path pattern expression> [ <parenthesized path pattern where clause> ] ")" 
<subpath variable declaration> ::= xref:syntax/variables.adoc[<binding variable>] "=" 
<parenthesized path pattern where clause> ::= "WHERE" xref:expressions/index.adoc[<value expression>]