<relationship pattern> ::= 
    "<-" [ "[" [ <relationship pattern filler> ] "]" ] "-"
  | "-" [ "[" [ <relationship pattern filler> ] "]" ] "->"
  | "<-" [ "[" [ <relationship pattern filler> ] "]" ] "->"
  | "-" [ "[" [ <relationship pattern filler> ] "]" ] "-"

<relationship pattern filler> ::= 
    <binding variable> [ <type expression> ] [ <path length> ] [ <element pattern predicate> ]
  | <type expression> [ <path length> ] [ <element pattern predicate> ]
  | <path length> [ <element pattern predicate> ]
  | <element pattern predicate>

<path length> ::= 
  "*" [ <lower and upper bound path length> | <fixed path length> ]

<lower and upper bound path length> ::= 
  [ <lower bound path length> ] ".." [ <upper bound path length> ]

<lower bound path length> ::= 
  <unsigned decimal integer>

<upper bound path length> ::= 
  <unsigned decimal integer>

<fixed path length> ::= 
  <unsigned decimal integer>