<parenthesized path pattern expression> ::= 
  "(" [ <subpath variable declaration> ] <path pattern expression> [ <parenthesized path pattern where clause> ] ")"

<path pattern expression> ::= 
    <path term>
  | <legacy shortest path pattern>

<path term> ::= 
    <path factor>
  | <path term> <path factor>

<path factor> ::= 
    <path primary>
  | <quantified path primary>

<path primary> ::= 
    <node pattern>
  | <relationship pattern>
  | <parenthesized path pattern expression>

<subpath variable declaration> ::= 
  <binding variable> "="

<parenthesized path pattern where clause> ::= 
  "WHERE" <value expression>