# property key-value

<element property specification> ::= 
  "{" <property key value pair list> "}"

<property key value pair list> ::= 
  <property key value pair> [ { "," <property key value pair> }... ]

<property key value pair> ::= 
  <property name> ":" <value expression>