<element property specification> ::= <left brace> <property key value pair list> <right brace> 
<left brace> ::= "{" 
<property key value pair list> ::= <property key value pair> [{ "," <property key value pair> }...] 
<right brace> ::= "}" 
<property key value pair> ::= xref:syntax/naming.adoc[<property name>] ":" xref:expressions/index.adoc[<value expression>]