# qpp

<quantified path primary> ::= 
  <path primary> <graph pattern quantifier>

<path primary> ::= 
    <element pattern>
  | <parenthesized path pattern expression>

<element pattern> ::= 
    <node pattern>
  | <relationship pattern>