<quantified path primary> ::= <path primary> xref:patterns/reference/variable-length-paths.adoc#quantifiers[<graph pattern quantifier>] 
<path primary> ::= <element pattern> | xref:patterns/variable-length-paths.adoc#quantified-path-patterns[<parenthesized path pattern expression>] 
<element pattern> ::= xref:patterns/reference/node-and-relationship-patterns.adoc#node-patterns[<node pattern>] | xref:patterns/reference/node-and-relationship-patterns.adoc#relationship-patterns[<relationship pattern>]