# quantifiers

<graph pattern quantifier> ::= 
    "*"
  | "+"
  | <fixed quantifier>
  | <general quantifier>

<fixed quantifier> ::= 
  "{" <unsigned decimal integer> "}"

<general quantifier> ::= 
  "{" [ <lower bound path length> ] "," [ <upper bound path length> ] "}"

<lower bound path length> ::= 
  <unsigned decimal integer>

<upper bound path length> ::= 
  <unsigned decimal integer>