<graph pattern quantifier> ::= "*" | <plus sign> | <fixed quantifier> | <general quantifier> 
<plus sign> ::= "+" 
<fixed quantifier> ::= <left brace> xref:values-and-types/boolean-numeric-string.adoc#numerical[<unsigned decimal integer>] <right brace> 
<general quantifier> ::= <left brace> [ <lower bound path length> ] "," [ <upper bound path length> ] <right brace> 
<left brace> ::= "{" 
<right brace> ::= "}" 
<lower bound path length> ::= xref:values-and-types/boolean-numeric-string.adoc#numerical[<unsigned decimal integer>] 
<upper bound path length> ::= xref:values-and-types/boolean-numeric-string.adoc#numerical[<unsigned decimal integer>]