<relationship pattern> ::= 
    "<-" [ "[" [ <relationship pattern filler> ] "]" ] "-"
  | "-" [ "[" [ <relationship pattern filler> ] "]" ] "->"
  | "<-" [ "[" [ <relationship pattern filler> ] "]" ] "->"
  | "-" [ "[" [ <relationship pattern filler> ] "]" ] "-"

<element pattern predicate> ::= 
    "WHERE" <value expression>
  | "{" <property key value expression> "}"
  | "$" <parameter name>

<relationship pattern filler> ::= 
    <binding variable> [ <type expression> ] [ <path length> ] [ <element pattern predicate> ]
  | <type expression> [ <path length> ] [ <element pattern predicate> ]
  | <path length> [ <element pattern predicate> ]
  | <element pattern predicate>