<relationship pattern> ::= <full relationship pattern> 
<full relationship pattern> ::= <full relationship pointing left> | <full relationship pointing right> | <full relationship left or right> | <full relationship any direction> 
<full relationship pointing left> ::= <left arrowhead> <arrow line> [ "[" [ <relationship pattern filler> ] "]" ] <arrow line> 
<full relationship pointing right> ::= <arrow line> [ "[" [ <relationship pattern filler> ] "]" ] <arrow line> <right arrowhead> 
<full relationship left or right> ::= <left arrowhead> <arrow line> [ "[" [ <relationship pattern filler> ] "]" ] <arrow line> <right arrowhead> 
<full relationship any direction> ::= <arrow line> [ "[" [ <relationship pattern filler> ] "]" ] <arrow line> 
<relationship pattern filler> ::= xref:syntax/variables.adoc[<binding variable>] [ xref:expressions/predicates/label-expression-predicates.adoc#is-labeled-predicate[<is relationship label expression>] ][ xref:patterns/reference/variable-length-paths.adoc#variable-length-relationships.adoc[<path length>] ][ <element pattern predicate> ]| xref:expressions/predicates/label-expression-predicates.adoc#is-labeled-predicate[<is relationship label expression>] [ xref:patterns/reference/variable-length-paths.adoc#variable-length-relationships.adoc[<path length>] ][ <element pattern predicate> ]| xref:patterns/reference/variable-length-paths.adoc#variable-length-relationships.adoc[<path length>] [ <element pattern predicate> ]| <element pattern predicate> 
<left arrowhead> ::= "<" 
<arrow line> ::= "-" 
<right arrowhead> ::= ">" 
<element pattern predicate> ::= <element pattern where clause> | xref:patterns/reference/node-and-relationship-patterns.adoc#properties[<element property specification>] | xref:syntax/parameters.adoc[<general parameter reference>] 
<element pattern where clause> ::= "WHERE" xref:expressions/index.adoc[<value expression>]