# shortest-paths

<path search prefix> ::= 
    <all path search>
  | <any path search>
  | <shortest path search>

<all path search> ::= 
  "ALL" [ <path keywords> ]

<any path search> ::= 
  "ANY" [ <number of paths> ] [ <path keywords> ]

<shortest path search> ::= 
    <all shortest path search>
  | <any shortest path search>
  | <counted shortest path search>
  | <counted shortest group search>

<all shortest path search> ::= 
  "ALL SHORTEST" [ <path keywords> ]

<any shortest path search> ::= 
  "ANY SHORTEST" [ <path keywords> ]

<counted shortest path search> ::= 
  "SHORTEST" <number of paths> [ <path keywords> ]

<counted shortest group search> ::= 
  "SHORTEST" [ <number of groups> ] [ <path keywords> ] { "GROUP" | "GROUPS" }

<number of paths> ::= 
  <unsigned decimal integer specification>

<number of groups> ::= 
  <unsigned decimal integer specification>

<path keywords> ::= 
    "PATH"
  | "PATHS"