<path length> ::= "*" [ <lower and upper bound path length> | <fixed path length> ] 
<lower and upper bound path length> ::= [ <lower bound path length> ] <double period> [ <upper bound path length> ] 
<fixed path length> ::= xref:values-and-types/boolean-numeric-string.adoc#numerical[<unsigned decimal integer>] 
<lower bound path length> ::= xref:values-and-types/boolean-numeric-string.adoc#numerical[<unsigned decimal integer>] 
<upper bound path length> ::= xref:values-and-types/boolean-numeric-string.adoc#numerical[<unsigned decimal integer>] 
<double period> ::= ".."