:description: Information about setting an open schema in Neo4j using graph types.
:page-role: cypher-25-only new-neo4j-2025.xx enterprise-edition
= Graph types

.Preview Feature
[IMPORTANT]
====
The *graph types feature is offered AS-IS* as described in your agreement with Neo4j and should only be used for internal development purposes.

When this feature becomes generally available, you will need to upgrade to the latest Neo4j version (which may require downtime) to use the feature for non-development purposes.

*Enabling the preview feature (internal parameter):* +
In Aura, graph types are enabled by default.

In self-managed Neo4j, graph types are disabled by default.
Use the internal setting `internal.dbms.graph_types=true` to enable it.

During the Preview period, if you have any feedback, comments, or encounter any issues, we welcome them in our link:https://github.com/neo4j/neo4j/issues[public GitHub repository].
We will address them to the best of our ability.
Please include the term *Graph types* in the title of your issue so we can identify it more easily. +
Customers with active contracts may contact Neo4j Support through the standard support channels.
Please note that any cases related to the Preview feature will be classified as Severity 4 by default, in accordance with the link:https://neo4j.com/terms/support-terms/[Support Terms].
====

Graph types allow you to specify a graph schema for a database.

When a database is created, it has an empty graph type, meaning it is free from any constraints on what can be stored in a database.
Setting a graph type, typically done following the creation of a database, enables users to impose a schema on the nodes, relationships, and properties included in the graph type, thereby ensuring the integrity and quality of the data in a graph.

Cypher supports open graph types, meaning that a graph type only constrains the data included by the graph type.
It does not impose any constraints on nodes, relationships, and properties not included by the graph type.

For more information about working with graph types, see:

* xref:schema/graph-types/set-graph-types.adoc[]
* xref:schema/graph-types/extend-graph-types.adoc[]
* xref:schema/graph-types/alter-element-types.adoc[]
* xref:schema/graph-types/list-graph-types.adoc[]
* xref:schema/graph-types/drop-graph-type-elements.adoc[]

For reference material about the Cypher commands used to manage graph types, see xref:schema/syntax.adoc#graph-types[Syntax -> Graph types].
