:description: Information about setting an open schema in Neo4j using graph types.
:page-role: cypher-25-only new-neo4j-2025.xx enterprise-edition
= Graph types

Graph types allow you to specify a graph schema for a database.

When a database is created, it has an empty graph type, meaning it is free from any constraints on what can be stored in a database.
Creating a graph type, typically done following the creation of a database, enables users to impose a schema on the nodes, relationships, and properties included in the graph type, thereby ensuring the integrity and quality of the data in a graph.

Cypher supports open graph types, meaning that a graph type only constrains the data included by the graph type.
It does not impose any constraints on nodes, relationships, and properties not included by the graph type.

For more information about working with graph types, see:

* xref:schema/graph-types/set-graph-types.adoc[]
* xref:schema/graph-types/extend-graph-types.adoc[]
* xref:schema/graph-types/alter-graph-types.adoc[]
* xref:schema/graph-types/list-graph-types.adoc[]
* xref:schema/graph-types/drop-graph-type-elements.adoc[]

For reference material about the Cypher commands used to manage graph types, see xref:schema/syntax.adoc[].
