= Conditional queries (`WHEN`)
:page-role: new-2025.02

`WHEN`, together with `THEN` and `ELSE`, enables different branches of a query to execute based on specified conditions.
In this way, it performs similar a control-flow mechanism to the `IF` statements found in other programming languages.
`WHEN` constructs can be used as standalone branches, as part of subqueries, or combined `UNION` queries, but it cannot be used as a regular clause in a query.

[[example-graph]]
== Example graph

The following graph is used for the examples below:

image::conditionals_graph.svg[width="400",role="middle"]

To recreate the graph, run the following query against an empty Neo4j database:

[source, cypher, role=test-setup]
----
CREATE
  (alice:Person {name:'Alice', age: 65}),
  (bob:Person {name: 'Bob', age: 25}),
  (charlie:Person {name: 'Charlie', age: 61}),
  (daniel:Person {name: 'Daniel', age: 39}),
  (eskil:Person {name: 'Eskil', age: 39}),
  (bob)-[:WORKS_FOR]->(alice),
  (alice)-[:WORKS_FOR]->(daniel),
  (charlie)-[:WORKS_FOR]->(daniel),
  (bob)-[:LOVES]->(eskil),
  (charlie)-[:LOVES]->(alice)
----

== Standalone `WHEN` branches and basic logic

`WHEN` branches can be used independently of other clauses.
The first predicate that evaluates to `true` will be executed.
If no `WHEN` branches are executed and an `ELSE` branch exists, it is executed.
If no `WHEN` branches evaluates to `true` and no `ELSE` branch is present, no branches are executed and no rows are produced.
The following example demonstrates this basic logic:

.Basic `WHEN` logic
[source, cypher]
----
WHEN false THEN RETURN 1 AS x
WHEN true THEN RETURN 2 AS x
ELSE RETURN 3 AS x
----

Since the second `WHEN` branch is `true`, it will execute, while the preceding branch (which is `false`) and the succeeding `ELSE` branch will be skipped.

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| x
| 2

1+d| Rows: 1
|===

[[query-branches-column-rules]]
=== Branch consistency: column numbers and names

Similar to `UNION`, the number and names of the columns must be identical in all parts of a `WHEN`/`ELSE` construct.

.Not allowed: using different column names in different branches
[source, cypher, role=test-fail]
----
WHEN true THEN RETURN 2 AS x
ELSE RETURN 3 AS y
----

.Not allowed: returning different number of columns in different branches
[source, cypher, role=test-fail]
----
WHEN true THEN RETURN 2 AS x, 3 AS y
ELSE RETURN 3 AS x
----

== Conditional subqueries

`WHEN` can be used inside a xref:subqueries/index.adoc[subquery] to execute a set of operations only when a condition evaluates to `true`.

.Conditional `CALL` subquery
=====

In this example, `WHEN` is used to execute a xref:subqueries/call-subquery.adoc[`CALL` subquery] for each row that the condition (`m IS NULL`) evaluates to `true`. 

.Conditional `CALL` subquery
[source, cypher]
----
MATCH (n:Person)
OPTIONAL MATCH (n)-[:WORKS_FOR]->(m:Person)
CALL (*) {
 WHEN m IS NULL THEN {
   MERGE (f: Person {name: 'Peter', age: 36})
   MERGE (n)-[:WORKS_FOR]->(f)
   RETURN f, n.name AS newFriend
 }
}
RETURN f.name AS employer,
      collect(newFriend) AS employees
----

Because only `Daniel` and `Eskil` had no outgoing `KNOWS` relationships, they have now been connected as acquaintances with the new `Peter` node.

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| employeer | employees

| "Peter"
| ["Daniel", "Eskil"]

2+d| Rows: 1
|===
=====


.Conditional `EXISTS` subquery
=====

In this example, `WHEN` is used inside an xref:subqueries/existential.adoc[`EXISTS` subquery] to conditionally execute different branches based on the evaluation of the condition (`n.age > 40`).
If the condition evaluates to `true`, the subquery fetches people that the `person` knows; otherwise, it retrieves who the `person` is married to.

[NOTE]
Unlike `CALL` subqueries, variables returned in an `EXISTS` subquery is not available to the outer scope (the same is true for xref:subqueries/count.adoc[`COUNT`] and xref:subqueries/collect.adoc[`COLLECT` subqueries]).

.`WHEN` inside `EXISTS` subquery
[source, cypher]xxs
----
MATCH (n:Person)
WHERE EXISTS {
  WHEN n.age > 40 THEN {
    MATCH (n)-[:WORKS_FOR]->(x:Person)
    RETURN x
  }
  ELSE {
    MATCH (n)-[:LOVES]->(x:Person)
    RETURN x
  }
}
RETURN n.name AS name, n.age AS age, exists((n)-[:LOVES]->()) as hasLovesRel
----

Since each condition is satisfied by a distinct node, the query only returns two rows.

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| names | age | hasLovesRel

| "Alice" | 65 | FALSE
| "Charlie" | 61 | TRUE
| "Bob" | 25 | TRUE

3+d| Rows: 2
|===

=====

.Chaining conditional subqueries
=====

Disjointed conditional subqueries be chained in succession, each executing depending on a set of defined condition.

This example uses conditional logic to assign age groups to individuals.
It then collects the names of their managers (who they `WORK_FOR`), tagging them as "Older manager" or "Younger manager" based on their age relative to the individual.

.Combining several conditional `CALL` subqueries
[source, cypher]
----
MATCH (n:Person)-[r:WORKS_FOR]->(m:Person)
CALL (*) { 
  WHEN n.age > 60 THEN {
    SET n.ageGroup = 'Veteran'
    RETURN n.ageGroup AS ageGroup
  }
  WHEN n.age >= 35 AND n.age <= 59 THEN {
    SET n.ageGroup = 'Senior'
    RETURN n.ageGroup AS ageGroup
  }
  ELSE {
    SET n.ageGroup = 'Junior'
    RETURN n.ageGroup AS ageGroup
  }
}
CALL (*) {
  WHEN m.age > n.age THEN {
    RETURN collect([m.name, "Older manager"]) AS manager
  }
  ELSE {
    RETURN collect([m.name, "Younger manager"]) AS manager
  }
}
RETURN n.name AS name, ageGroup, manager
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| name  | ageGroup | manager

| "Alice"   | "Veteran" | [["Daniel", "Younger manager"]]
| "Bob"     | "Junior"  | [["Alice", "Older manager"]]
| "Charlie" | "Veteran" | [["Daniel", "Younger manager"]]
| "Daniel"  | "Senior"  | [["Peter", "Older manager"]]
| "Eskil"   | "Senior"  | [["Peter", "Younger manager"]]

3+d| Rows: 5
|===

=====


[[combined-conditional-queries]]
== Combining conditional queries with `UNION`

Conditional queries can also be combined using `UNION [DISTINCT]` or `UNION ALL` (the former alternative removes duplicates from the result set, the latter does not).

If the conditional query begins with `WHEN` and involves `UNION`, the `WHEN` branches must be enclosed within curly braces, `{}`.
(Such top-level braces can also be used to xref:queries/composed-queries/combined-queries.adoc[combine `UNION` and `UNION ALL`].)

.Combining conditional branches with `UNION` using `{}`
[source, cypher]
----
{
    WHEN true THEN RETURN 1 AS x
    WHEN false THEN RETURN 2 AS x
    ELSE RETURN 3 AS x
}
UNION
{
    WHEN false THEN RETURN 4 AS x
    WHEN false THEN RETURN 5 AS x
    ELSE RETURN 6 AS x
}
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| x

| 1
| 6

1+d| Rows: 2
|===

If the queries combined by the `UNION` does not begin with a `WHEN` branch, then top-level braces are not necessary.
In the example below, `UNION` is used to combine the results of two conditional subqueries (the first `CALL`, enclosing the whole query, is necessary to enable the collection for each `person` from each conditional subquery part in the final results).

.Combining conditional subqueries with `UNION`
[source, cypher]
----
MATCH (n:Person)
CALL (n) { 
  OPTIONAL MATCH (n)-[r:LOVES]->(m:Person)
  CALL (*) {
    WHEN r IS NULL THEN {
      RETURN n.name AS person, "Loves no one" AS message
    }
    ELSE {
      RETURN n.name AS person, "Loves somebody" AS message
    }
  }
  RETURN person, message
  UNION
  CALL (*) {
    WHEN n.age < 40 THEN {
       RETURN n.name AS person, "Younger person" AS message
    }
    ELSE {
       RETURN n.name AS person, "Older person" AS message
    }
  }
  RETURN person, message
}
RETURN person, collect(message) as status
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| person | status

| "Alice"   | ["Loves no one", "Older person"]
| "Charlie" | ["Loves no one", "Older person"]
| "Daniel"  | ["Loves no one", "Younger person"]
| "Eskil"   | ["Loves no one", "Younger person"]
| "Peter"   | ["Loves no one", "Younger person"]
| "Bob"     | ["Loves somebody", "Younger person"]

2+d| Rows: 7

|===

