= Conditional queries (`WHEN...THEN...ELSE`)
:page-role: new-2025.02

The `WHEN` clause in Cypher allows conditional execution of parts of a query, enabling different query branches or subqueries to run based on specified conditions.
Much like `UNION`, `WHEN` cannot be used as a regular clause in a query (though it can be used as standalone branches).
Instead, it encloses different query branches or subqueries as a condition for their execution.
In this way, it performs similar a control-flow structure to the `IF` statements of other programming languages.

[[example-graph]]
== Example graph

The following graph is used for the examples below:

image::conditionals_graph.svg[width="400",role="middle"]

To recreate the graph, run the following query against an empty Neo4j database:

[source, cypher, role=test-setup]
----
CREATE
  (alice:Person {name:'Alice', age: 38, eyes: 'brown'}),
  (bob:Person {name: 'Bob', age: 25, eyes: 'blue'}),
  (charlie:Person {name: 'Charlie', age: 53, eyes: 'green'}),
  (daniel:Person {name: 'Daniel', age: 32, eyes: 'brown'}),
  (eskil:Person {name: 'Eskil', age: 39, eyes: 'blue'}),
  (alice)-[:KNOWS]->(bob),
  (alice)-[:KNOWS]->(charlie),
  (bob)-[:KNOWS]->(daniel),
  (charlie)-[:KNOWS]->(daniel),
  (bob)-[:MARRIED]->(eskil)
----

== Standalone `WHEN` branches

`WHEN` branches can be used independently of other query parts.
The first predicate that evaluates to `true` will be executed.
If no `WHEN` branches were executed and an `ELSE` branch exists, it is executed.
If no `WHEN` branches evaluates to `true` and no `ELSE` branch is present, no rows are produced.
The following example demonstrates this basic logic:

.Basic `WHEN` logic
[source, cypher]
----
WHEN false THEN RETURN 1 AS x
WHEN true THEN RETURN 2 AS x
ELSE RETURN 3 AS x
----

Since the second `WHEN` branch is `true`, it will execute, while the preceding branch (which is `false`) and the succeeding `ELSE` branch will be skipped.

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| x
| 2

1+d| Rows: 1
|===

== Conditional subqueries

`WHEN` branches can be used inside a subquery to execute operations only when a condition evaluates to `true`.
For example, in a xref:subqueries/call-subquery.adoc[`CALL` subquery], you can use `WHEN` to ensure that particular actions are executed when a certain criteria is met.

.`WHEN` inside a `CALL` subquery
=====

In this example, `WHEN` is used to execute a `CALL` subquery for each row that the condition (`m IS NULL`) evaluates to `true`. 

.Conditional `CALL` subquery
[source, cypher]
----
MATCH (n:Person)
OPTIONAL MATCH (n)-[:KNOWS]->(m:Person)
CALL (*) {
  WHEN m IS NULL THEN {
    MERGE (f: Person {name: 'Peter', age: 36, eyes: 'green'})
    MERGE (n)-[:KNOWS]->(f)
    RETURN f, n.name AS newFriend
  }
}
RETURN f.name AS newNode,
       collect(newFriend) AS newFriends
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| newNode | newFriends

| "Peter"
| ["Daniel", "Eskil"]

2+d| Rows: 1
|===
=====


.Conditional `EXISTS` subquery
=====

Here `WHEN` is used inside an xref:subqueries/existential.adoc[`EXISTS` subquery] to conditionally execute different branches based on the evaluation of the condition (`n.age > 40`).
If the condition evaluates to `true`, the subquery fetches people that the `person` knows; otherwise, it retrieves who the `person` is married to.

.`WHEN` inside `EXISTS` subquery
[source, cypher]
----
MATCH (n:Person)
WHERE EXISTS {
  WHEN n.age > 40 THEN {
    MATCH (n)-[:KNOWS]->(x:Person)
    RETURN x
  }
  ELSE {
    MATCH (n)-[:MARRIED]->(x:Person)
    RETURN x
  }
}
RETURN n.name AS names
----

Since each condition is satisfied by a distinct node, the query only returns two rows.

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| names

| "Charlie"
| "Bob"

1+d| Rows: 2
|===

=====

== Conditional `UNION` queries

[source, cypher]
----
{
    WHEN true THEN RETURN 1 AS x
    WHEN false THEN RETURN 2 AS x
    ELSE RETURN 3 AS x
}
UNION
{
    WHEN false THEN RETURN 4 AS x
    WHEN false THEN RETURN 5 AS x
    ELSE RETURN 6 AS x
}
----

== Rules