= Sequential queries (`NEXT`)
:description: Information about how to use `NEXT` to construct sequential queries in Cypher.
:page-role: new-2025.06

`NEXT` allows for linear composition of queries into a sequence of smaller, self-contained segments while making return values from one segment available in the next.

`NEXT` has a number of benefits:

* `NEXT` can improve the modularity and readability of complex queries.
* `NEXT` reduces the need to rely on the xref:clauses/call.adoc[CALL] and xref:clauses/with.adoc[] clauses to construct complex queries.
* `NEXT` improves the usability of xref:queries/composed-queries/conditional-queries.adoc[conditional] and xref:queries/composed-queries/combined-queries.adoc[UNION] queries.

`NEXT` was introduced as part of Cypher's xref:appendix/gql-conformance/index.adoc[].



[[example-graph]]
== Example graph

The following graph is used for the examples on this page:

image::conditional_query_graph.svg[width="700",role="middle"]

To recreate the graph, run the following query against an empty Neo4j database:

[source, cypher, role=test-setup]
----
CREATE (alice:Person {name:'Alice', age: 65}),
       (bob:Person {name: 'Bob', age: 25}),
       (charlie:Person {name: 'Charlie', age: 61}),
       (daniel:Person {name: 'Daniel', age: 39}),
       (eskil:Person {name: 'Eskil', age: 39}),
       (bob)-[:WORKS_FOR]->(alice),
       (alice)-[:WORKS_FOR]->(daniel),
       (charlie)-[:WORKS_FOR]->(daniel),
       (bob)-[:LOVES]->(eskil),
       (charlie)-[:LOVES]->(alice)
----


[[sequential-syntax]]
== Syntax

Lorem ipsum.


[[sequential-rules]]
== Rules

Lorem ipsum.

.Not allowed: not aliasing returned expressions
[source, cypher, role=test-fail]
----
WHEN true THEN RETURN 2
ELSE RETURN 3
----


== Using `NEXT` instead of `CALL`

Lorem ipsum.


== Using `NEXT` instead of `WITH`

Lorem ipsum.


== Interactions with conditional queries

Lorem ipsum.


== Interactions with `UNION` queries

Lorem ipsum.