# create-constraint

<create constraint statement> ::= 
  "CREATE CONSTRAINT" [ <constraint name> | <general parameter reference> ] [ "IF NOT EXISTS" ] <constraint specification> [ <command options> ]

<command options> ::= 
  "OPTIONS" <map value or parameter specification>

<property names specification> ::= 
    <property name specification>
  | "(" <property name specification> [ { "," <property name specification> }... ] ")"

<property name specification> ::= 
  <binding variable> "." <property name>

<constraint specification> ::= 
    <node constraint specification>
  | <relationship constraint specification>

<node constraint specification> ::= 
    <node key constraint>
  | <node uniqueness constraint>
  | <node property existence constraint>
  | <node property type constraint>

<relationship constraint specification> ::= 
    <relationship key constraint>
  | <relationship uniqueness constraint>
  | <relationship property existence constraint>
  | <relationship property type constraint>

<node key constraint> ::= 
  "FOR" <command node pattern> "REQUIRE" <property names specification> "IS" [ "NODE" ] "KEY"

<node uniqueness constraint> ::= 
  "FOR" <command node pattern> "REQUIRE" <property names specification> "IS" [ "NODE" ] "UNIQUE"

<node property existence constraint> ::= 
  "FOR" <command node pattern> "REQUIRE" <property name specification> "IS NOT NULL"

<node property type constraint> ::= 
  "FOR" <command node pattern> "REQUIRE" <property name specification> { [ "IS" ] "::" | "IS TYPED" } <value type>

<relationship key constraint> ::= 
  "FOR" <command relationship pattern> "REQUIRE" <property names specification> "IS" [ "RELATIONSHIP" | "REL" ] "KEY"

<relationship uniqueness constraint> ::= 
  "FOR" <command relationship pattern> "REQUIRE" <property names specification> "IS" [ "RELATIONSHIP" | "REL" ] "UNIQUE"

<relationship property existence constraint> ::= 
  "FOR" <command relationship pattern> "REQUIRE" <property name specification> "IS NOT NULL"

<relationship property type constraint> ::= 
  "FOR" <command relationship pattern> "REQUIRE" <property name specification> { [ "IS" ] "::" | "IS TYPED" } <value type>

<command node pattern> ::= 
  "(" <binding variable> ":" <label name> ")"

<command relationship pattern> ::= 
  "()" { "<-[" <binding variable> ":" <label name> "]-" | "-[" <binding variable> ":" <label name> "]->" | "<-[" <binding variable> ":" <label name> "]->" | "-[" <binding variable> ":" <label name> "]-" } "()"

<map value or parameter specification> ::= 
    <map value constructor>
  | <general parameter reference>