# drop-constraint

<drop constraint statement> ::= 
  "DROP CONSTRAINT" <constraint name specification> [ "IF EXISTS" ]

<constraint name specification> ::= 
    <constraint name>
  | <general parameter reference>