<show constraints statement> ::= 
  "SHOW" [ <show constraint type> ] <constraint keywords> [ <show result clause> ]

<show constraint type> ::= 
    <show all constraints>
  | <show key constraints>
  | <show uniqueness constraints>
  | <show property existence constraints>
  | <show property type constraints>

<show all constraints> ::= 
  "ALL"

<show key constraints> ::= 
  [ "NODE" | "RELATIONSHIP" | "REL" ] "KEY"

<show uniqueness constraints> ::= 
  [ "NODE" | "RELATIONSHIP" | "REL" ] [ "PROPERTY" ] { "UNIQUENESS" | "UNIQUE" }

<show property existence constraints> ::= 
  [ "NODE" | "RELATIONSHIP" | "REL" ] [ "PROPERTY" ] { "EXISTENCE" | "EXIST" }

<show property type constraints> ::= 
  [ "NODE" | "RELATIONSHIP" | "REL" ] "PROPERTY TYPE"