<call procedure statement> ::= 
  [ "OPTIONAL" ] "CALL" { <inline procedure call> | <named procedure call> }

<named procedure call> ::= 
  <procedure reference> <explicit procedure arguments> [ "YIELD" <identifier> [ "AS" link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] ] [ { "," <identifier> [ "AS" link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] ] }... ] [ "WHERE" <search condition> ] ]