<create statement> ::= 
  "CREATE" <create path pattern> [ { "," <create path pattern> }... ]

<create path pattern> ::= 
  [ link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] "=" ] <create node pattern> [ { <create relationship pattern> <create node pattern> }... ]