<create statement> ::= "CREATE" <create graph pattern> 
<create graph pattern> ::= <create path pattern list> 
<create path pattern list> ::= <create path pattern> [{ "," <create path pattern> }...] 
<create path pattern> ::= [ <path variable declaration> ] xref:clauses/create.adoc#create-nodes[<create node pattern>] [{ xref:clauses/create.adoc#create-relationships[<create relationship pattern>] xref:clauses/create.adoc#create-nodes[<create node pattern>] }...] 
<path variable declaration> ::= xref:syntax/naming.adoc[<binding variable>] "="