<create statement> ::= "CREATE" <create graph pattern> 
<create graph pattern> ::= <create path pattern list> 
<create path pattern list> ::= <create path pattern> [{ "," <create path pattern> }...] 
<create path pattern> ::= [ <path variable declaration> ] <create node pattern> [{ <create relationship pattern> <create node pattern> }...] 
<path variable declaration> ::= xref:syntax/naming.adoc[<binding variable>] "="