<delete statement> ::= 
  [ "DETACH" | "NODETACH" ] "DELETE" link:https://neo4j.com/docs/cypher-manual/current/expressions/[<value expression>] [ { "," link:https://neo4j.com/docs/cypher-manual/current/expressions/[<value expression>] }... ]