<delete statement> ::= [ "DETACH" | "NODETACH" ] "DELETE" <delete item list> 
<delete item list> ::= <delete item> [{ "," <delete item> }...] 
<delete item> ::= xref:expressions/index.adoc[<value expression>]