<foreach statement> ::= 
  "FOREACH" "(" <foreach element source> <foreach action> ")"

<foreach element source> ::= 
  link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] "IN" link:https://neo4j.com/docs/cypher-manual/current/expressions/[<value expression>]

<foreach action> ::= 
  "|" { link:https://neo4j.com/docs/cypher-manual/current/clauses/create/[<create statement>] | link:https://neo4j.com/docs/cypher-manual/current/clauses/create/[<insert statement>] | link:https://neo4j.com/docs/cypher-manual/current/clauses/merge/[<merge statement>] | link:https://neo4j.com/docs/cypher-manual/current/clauses/set/[<set statement>] | link:https://neo4j.com/docs/cypher-manual/current/clauses/remove/[<remove statement>] | link:https://neo4j.com/docs/cypher-manual/current/clauses/delete/[<delete statement>] }...