<foreach statement> ::= 
  "FOREACH" "(" <foreach element source> <foreach action> ")"

<foreach element source> ::= 
  link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] "IN" link:https://neo4j.com/docs/cypher-manual/current/expressions/[<value expression>]

<foreach action> ::= 
  "|" { "CREATE" <create graph pattern> | "INSERT" <insert graph pattern> | "MERGE" <merge graph pattern> [ <merge action> ] | "SET" <set item list> | "REMOVE" <remove item list> | [ "DETACH" | "NODETACH" ] "DELETE" <delete item list> }...