<create or insert statement> ::= xref:clauses/create.adoc[<create statement>] | xref:clauses/create.adoc[<insert statement>] 
<foreach statement> ::= "FOREACH" "(" <foreach element source> <foreach action> ")" 
<foreach element source> ::= xref:syntax/naming.adoc[<binding variable reference>] "IN" xref:expressions/index.adoc[<value expression>] 
<foreach action> ::= "|" <foreach action statement> ... 
<foreach action statement> ::= <create or insert statement> | xref:clauses/merge.adoc[<merge statement>] | xref:clauses/set.adoc[<set statement>] | xref:clauses/remove.adoc[<remove statement>] | xref:clauses/delete.adoc[<delete statement>]