<group by clause> ::= "GROUP BY" <grouping element list> 
<grouping element list> ::= <grouping element> [{ "," <grouping element> }...]| <empty grouping set> | "ALL" 
<grouping element> ::= xref:expressions/index.adoc[<value expression>] 
<empty grouping set> ::= "(" ")"