<let statement> ::= "LET" <let variable definition list> 
<let variable definition list> ::= <let variable definition> [{ "," <let variable definition> }...] 
<let variable definition> ::= xref:syntax/variables.adoc[<binding variable>] "=" xref:expressions/index.adoc[<value expression>]