<load csv statement> ::= "LOAD CSV" [ <csv headers option> ] <csv source> [ <csv field terminator> ] 
<csv headers option> ::= "WITH HEADERS" 
<csv field terminator> ::= "FIELDTERMINATOR" xref:syntax/parsing.adoc[<character string literal>] 
<csv source> ::= "FROM" xref:expressions/index.adoc[<value expression>] "AS" xref:syntax/variables.adoc[<binding variable>]