<simple match statement> ::= 
  "MATCH" <graph pattern>

<limit clause> ::= 
  "LIMIT" <value expression>

<where clause> ::= 
  "WHERE" <search condition>

<graph pattern> ::= 
  [ <match mode> ] <path pattern> [ { "," <path pattern> }... ] [ <graph pattern where and search clause> ]

<graph pattern where and search clause> ::= 
    <graph pattern where clause> [ <search clause> ]
  | <search clause> [ <graph pattern where clause> ]

<match mode> ::= 
    "REPEATABLE" { "ELEMENT" [ "BINDINGS" ] | "ELEMENTS" }
  | "DIFFERENT" { "RELATIONSHIP" [ "BINDINGS" ] | "RELATIONSHIPS" }

<search clause> ::= 
  "SEARCH" <binding variable reference> "IN" "(" <index specification clause> <for clause> [ <where clause> ] <limit clause> ")" [ <score clause> ]

<index specification clause> ::= 
  "VECTOR INDEX" <index name specification>

<for clause> ::= 
  "FOR" <value expression>

<score clause> ::= 
  "SCORE AS" <identifier>

<path pattern> ::= 
  [ <identifier> "=" ] [ <path pattern prefix> ] <path pattern expression>

<node pattern> ::= 
  "(" [ <identifier> [ <is node label expression> ] [ <element pattern predicate> ] | <is node label expression> [ <element pattern predicate> ] | <element pattern predicate> ] ")"

<element pattern predicate> ::= 
    "WHERE" <value expression>
  | <element property specification>
  | "$" <parameter name>

<element property specification> ::= 
  "{" <property key value pair list> "}"

<property key value pair list> ::= 
  <property key value pair> [ { "," <property key value pair> }... ]

<property key value pair> ::= 
  <property name> ":" <value expression>

<relationship pattern> ::= 
    "<-" [ "[" [ <relationship pattern filler> ] "]" ] "-"
  | "-" [ "[" [ <relationship pattern filler> ] "]" ] "->"
  | "<-" [ "[" [ <relationship pattern filler> ] "]" ] "->"
  | "-" [ "[" [ <relationship pattern filler> ] "]" ] "-"

<relationship pattern filler> ::= 
    <identifier> [ <is relationship label expression> ] [ <path length> ] [ <element pattern predicate> ]
  | <is relationship label expression> [ <path length> ] [ <element pattern predicate> ]
  | <path length> [ <element pattern predicate> ]
  | <element pattern predicate>

<path length> ::= 
  "*" [ [ <unsigned decimal integer> ] ".." [ <unsigned decimal integer> ] | <unsigned decimal integer> ]

<is node label expression> ::= 
    ":" <node label expression legacy>
  | { ":" | "IS" } <label expression>

<is relationship label expression> ::= 
    ":" <relationship label expression legacy>
  | { ":" | "IS" } <label expression>

<label expression> ::= 
    <label term>
  | <label expression> "|" <label term>

<label term> ::= 
    <label factor>
  | <label term> "&" <label factor>

<label factor> ::= 
    <label primary>
  | <label negation>

<label negation> ::= 
  "!" <label primary>

<label primary> ::= 
    <label name>
  | "(" <label expression> ")"
  | "%"
  | "$" [ "ALL" | "ANY" ] "(" <value expression> ")"

<value expression> ::= 
  <boolean value expression>

<search condition> ::= 
  <boolean value expression>

<boolean value expression> ::= 
    <boolean term xor>
  | <boolean value expression> "OR" <boolean term xor>

<boolean term xor> ::= 
    <boolean term>
  | <boolean term xor> "XOR" <boolean term>

<boolean term> ::= 
    <boolean factor>
  | <boolean term> "AND" <boolean factor>

<boolean factor> ::= 
  [ { "NOT" }... ] <boolean primary>

<boolean primary> ::= 
    <pattern expression>
  | <predicate>

<pattern expression> ::= 
  <node pattern> { <relationship pattern> <node pattern> }...

<label name> ::= 
  <identifier>

<property name> ::= 
  <identifier>

<binding variable reference> ::= 
  <identifier>

<index name specification> ::= 
    <index name>
  | "$" <parameter name>

<index name> ::= 
  <identifier>