<simple match statement> ::= 
  "MATCH" <graph pattern>

<graph pattern> ::= 
  [ <match mode> ] <path pattern> [ { "," <path pattern> }... ] [ <graph pattern where clause> ]

<match mode> ::= 
    "REPEATABLE" { "ELEMENT" [ "BINDINGS" ] | "ELEMENTS" }
  | "DIFFERENT" { "RELATIONSHIP" [ "BINDINGS" ] | "RELATIONSHIPS" }

<path pattern> ::= 
  [ <identifier> "=" ] [ <path pattern prefix> ] <path pattern expression>