<simple match statement> ::= "MATCH" <graph pattern binding table> 
<graph pattern binding table> ::= <graph pattern> 
<graph pattern> ::= [ <match mode> ] <path pattern list> [ xref:indexes/search-performance-indexes/index-hints.adoc[<hints>] ][ <graph pattern where and search clause> ] 
<graph pattern where and search clause> ::= <graph pattern where clause> [ xref:clauses/search.adoc[<search clause>] ]| xref:clauses/search.adoc[<search clause>] [ <graph pattern where clause> ] 
<match mode> ::= <repeatable elements match mode> | <different edges match mode> 
<repeatable elements match mode> ::= "REPEATABLE" <element bindings or elements> 
<different edges match mode> ::= "DIFFERENT" <edge bindings or edges> 
<element bindings or elements> ::= "ELEMENT" [ "BINDINGS" ]| "ELEMENTS" 
<edge bindings or edges> ::= "RELATIONSHIP" [ "BINDINGS" ]| "RELATIONSHIPS" 
<path pattern list> ::= xref:patterns/reference/path-patterns-and-graph-patterns.adoc[<path pattern>] [{ "," xref:patterns/reference/path-patterns-and-graph-patterns.adoc[<path pattern>] }...] 
<graph pattern where clause> ::= xref:clauses/where.adoc[<where clause>]