<merge statement> ::= "MERGE" <merge graph pattern> [ <merge action> ] 
<merge action> ::= "ON" { "MATCH" | "CREATE" } xref:clauses/set.adoc[<set statement>] 
<merge graph pattern> ::= <merge path pattern> 
<merge path pattern> ::= [ <path variable declaration> ] xref:clauses/merge.adoc#merge-existing-patterns[<merge node pattern>] [{ xref:clauses/merge.adoc#merge-existing-patterns[<merge relationship pattern>] xref:clauses/merge.adoc#merge-existing-patterns[<merge node pattern>] }...] 
<path variable declaration> ::= xref:syntax/variables.adoc[<binding variable>] "="