<merge statement> ::= 
  "MERGE" [ link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] "=" ] <merge node pattern> [ { <merge relationship pattern> <merge node pattern> }... ] [ "ON" { "MATCH" | "CREATE" } "SET" <set item> [ { "," <set item> }... ] ]