<merge statement> ::= 
  "MERGE" [ link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] "=" ] <merge node pattern> [ { <merge relationship pattern> <merge node pattern> }... ] [ <merge action> ]

<merge action> ::= 
  "ON" { "MATCH" | "CREATE" } link:https://neo4j.com/docs/cypher-manual/current/clauses/set/[<set statement>]