<order by clause> ::= "ORDER BY" <sort specification list> 
<sort specification list> ::= <sort specification> [{ "," <sort specification> }...] 
<sort specification> ::= <sort key> [ <ordering specification> ] 
<sort key> ::= xref:expressions/index.adoc[<value expression>] 
<ordering specification> ::= <ascending order> | <descending order> 
<ascending order> ::= "ASC" | "ASCENDING" 
<descending order> ::= "DESC" | "DESCENDING"