<order by clause> ::= 
  "ORDER BY" <sort specification> [ { "," <sort specification> }... ]

<sort specification> ::= 
  link:https://neo4j.com/docs/cypher-manual/current/expressions/[<value expression>] [ "ASC" | "ASCENDING" | "DESC" | "DESCENDING" ]