<remove statement> ::= 
  "REMOVE" <remove item> [ { "," <remove item> }... ]

<remove item> ::= 
    <remove labels item>
  | <remove property item>

<remove labels item> ::= 
  link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] { ":" <label> { ":" <label> }... | { "IS" | ":" } <label> }

<remove property item> ::= 
  link:https://neo4j.com/docs/cypher-manual/current/expressions/[<postfix expression>]