<remove statement> ::= "REMOVE" <remove item list> 
<remove item list> ::= <remove item> [{ "," <remove item> }...] 
<remove item> ::= <remove labels item> | <remove property item> 
<remove labels item> ::= xref:syntax/naming.adoc[<binding variable reference>] <node label set specification for set and remove> 
<remove property item> ::= xref:expressions/index.adoc[<postfix expression>] 
<node label set specification for set and remove> ::= <dynamic node label set specification with colon> | <dynamic node label set single specification> 
<dynamic node label set specification with colon> ::= ":" <dynamic label specification> { ":" <dynamic label specification> }... 
<dynamic node label set single specification> ::= { "IS" | ":" } <dynamic label specification>