<return statement> ::= 
  "RETURN" [ "ALL" | "DISTINCT" ] { "*" | <return item> } [ { "," <return item> }... ] [ <order by and page clause> ]

<return item> ::= 
  link:https://neo4j.com/docs/cypher-manual/current/expressions/[<value expression>] [ "AS" <identifier> ]

<order by and page clause> ::= 
    <order by clause> [ <offset clause> ] [ <limit clause> ]
  | <offset clause> [ <limit clause> ]
  | <limit clause>