<return statement> ::= 
  "RETURN" [ "ALL" | "DISTINCT" ] { "*" | <return item> } [ { "," <return item> }... ] [ <order by and page clause> ]

<return item> ::= 
  link:https://neo4j.com/docs/cypher-manual/current/expressions/[<value expression>] [ "AS" link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<identifier>] ]

<order by and page clause> ::= 
    link:https://neo4j.com/docs/cypher-manual/current/clauses/order-by/[<order by clause>] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/skip/[<offset clause>] ] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/limit/[<limit clause>] ]
  | link:https://neo4j.com/docs/cypher-manual/current/clauses/skip/[<offset clause>] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/limit/[<limit clause>] ]
  | link:https://neo4j.com/docs/cypher-manual/current/clauses/limit/[<limit clause>]