<return statement> ::= "RETURN" <return statement body> [ <order by and page clause> ] 
<order by and page clause> ::= xref:clauses/order-by.adoc[<order by clause>] [ xref:clauses/skip.adoc[<offset clause>] ][ xref:clauses/limit.adoc[<limit clause>] ]| xref:clauses/skip.adoc[<offset clause>] [ xref:clauses/limit.adoc[<limit clause>] ]| xref:clauses/limit.adoc[<limit clause>] 
<return statement body> ::= [ <set quantifier> ] <return item list> [ <group by clause> ] 
<set quantifier> ::= "ALL" | "DISTINCT" 
<group by clause> ::= "GROUP BY" <grouping element list> 
<return item list> ::= { "*" | <return item> }[{ "," <return item> }...] 
<grouping element list> ::= <grouping element> [{ "," <grouping element> }...]| <empty grouping set> | "ALL" 
<return item> ::= xref:expressions/index.adoc[<value expression>] [ <return item alias> ] 
<grouping element> ::= xref:expressions/index.adoc[<value expression>] 
<empty grouping set> ::= "(" ")" 
<return item alias> ::= "AS" xref:syntax/naming.adoc[<identifier>]