<search clause> ::= 
  "SEARCH" link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] "IN" "(" "VECTOR INDEX" link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<identifier>] "FOR" link:https://neo4j.com/docs/cypher-manual/current/expressions/[<value expression>] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/where/[<where clause>] ] link:https://neo4j.com/docs/cypher-manual/current/clauses/limit/[<limit clause>] ")" [ "SCORE AS" link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] ]