<search clause> ::= "SEARCH" xref:syntax/naming.adoc[<binding variable reference>] "IN" "(" <index specification clause> <for clause> [ xref:clauses/where.adoc[<where clause>] ] xref:clauses/limit.adoc[<limit clause>] ")" [ <score clause> ] 
<index specification clause> ::= "VECTOR INDEX" <index name specification> 
<for clause> ::= "FOR" xref:expressions/index.adoc[<value expression>] 
<score clause> ::= "SCORE AS" xref:syntax/naming.adoc[<binding variable>] 
<index name specification> ::= <index name> | <general parameter reference> 
<index name> ::= xref:syntax/naming.adoc[<identifier>] 
<general parameter reference> ::= "$" xref:syntax/parameters.adoc[<parameter name>]