<search clause> ::= 
  "SEARCH" <binding variable> "IN" "(" "VECTOR INDEX" <index name> "FOR" <value expression> [ "WHERE" <search condition> ] "LIMIT" <value expression> ")" [ "SCORE AS" <binding variable> ]