<set statement> ::= "SET" <set item list> 
<set item list> ::= <set item> [{ "," <set item> }...] 
<set item> ::= <set all properties item> | <add all properties item> | <set labels item> | <set property item> 
<set all properties item> ::= xref:syntax/naming.adoc[<binding variable reference>] "=" xref:expressions/index.adoc[<value expression>] 
<add all properties item> ::= xref:syntax/naming.adoc[<binding variable reference>] "+=" xref:expressions/index.adoc[<value expression>] 
<set labels item> ::= xref:syntax/naming.adoc[<binding variable reference>] <node label set specification for set and remove> 
<set property item> ::= xref:expressions/index.adoc[<postfix expression>] "=" xref:expressions/index.adoc[<value expression>] 
<node label set specification for set and remove> ::= <dynamic node label set specification with colon> | <dynamic node label set single specification> 
<dynamic node label set specification with colon> ::= ":" xref:clauses/match.adoc#dynamic-match[<dynamic label specification>] { ":" xref:clauses/match.adoc#dynamic-match[<dynamic label specification>] }... 
<dynamic node label set single specification> ::= { "IS" | ":" } xref:clauses/match.adoc#dynamic-match[<dynamic label specification>]