<set statement> ::= 
  "SET" <set item> [ { "," <set item> }... ]

<set item> ::= 
    <set all properties item>
  | <add all properties item>
  | <set labels item>
  | <set property item>

<set all properties item> ::= 
  link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] "=" link:https://neo4j.com/docs/cypher-manual/current/expressions/[<value expression>]

<add all properties item> ::= 
  link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] "+=" link:https://neo4j.com/docs/cypher-manual/current/expressions/[<value expression>]

<set labels item> ::= 
  link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] { ":" <label> { ":" <label> }... | { "IS" | ":" } <label> }

<set property item> ::= 
  <postfix expression> "=" link:https://neo4j.com/docs/cypher-manual/current/expressions/[<value expression>]