<standalone catalog show statement> ::= <show aliases statement> | <show auth rules statement> | <show current user statement> | <show privileges statement> | <show roles statement> | <show servers statement> | <show users statement>