<show transactions statement> ::= 
  "SHOW" { "TRANSACTION" | "TRANSACTIONS" } [ <transaction-id> ] [ <show result clause> ]

<show result clause> ::= 
    "YIELD" <yield item list> [ <order by clause> ] [ <offset clause> ] [ <limit clause> ] [ <where clause> ] [ <return statement> ]
  | <where clause>