<primitive catalog show statement> ::= <show constraints statement> | <show current graph type statement> | <show indexes statement> | <show functions statement> | <show procedures statement> | <show settings statement> | <show transactions statement> | <show databases statement>