<show statement> ::=
"SHOW" <show target> [ <show result clause> ]

<show target> ::=
"FUNCTIONS" | "PROCEDURES" | "INDEXES" | "CONSTRAINTS" | "SETTINGS" | "TRANSACTIONS" | "DATABASES" | "ALIASES" | "SERVERS" | "USERS" | "ROLES" | "PRIVILEGES" | "AUTH RULES" | "CURRENT GRAPH TYPE"

<show result clause> ::=
[ "YIELD" { "*" | <yield item> { "," <yield item> }... } ]
[ link:https://neo4j.com/docs/cypher-manual/current/clauses/where/[<where clause>] ]
[ link:https://neo4j.com/docs/cypher-manual/current/clauses/return/[<return statement>] ]