<show procedures statement> ::= 
  "SHOW" { "PROCEDURE" | "PROCEDURES" } [ <executable by> ] [ <show result clause> ]

<executable by> ::= 
  "EXECUTABLE" [ "BY CURRENT USER" | "BY" <user name> ]

<show result clause> ::= 
    "YIELD" <yield item list> [ <order by clause> ] [ <offset clause> ] [ <limit clause> ] [ <where clause> ] [ <return statement> ]
  | <where clause>

<user name> ::= 
  <identifier>