<primitive catalog show statement> ::= xref:schema/constraints/list-constraints.adoc[<show constraints statement>] | xref:schema/graph-types/list-graph-types.adoc[<show current graph type statement>] | xref:indexes/search-performance-indexes/list-indexes.adoc[<show indexes statement>] | xref:functions/show-functions.adoc[<show functions statement>] | link:https://neo4j.com/docs/operations-manual/current/procedures/show-procedures/[<show procedures statement>] | link:https://neo4j.com/docs/operations-manual/current/configuration/show-settings/[<show settings statement>] | link:https://neo4j.com/docs/operations-manual/current/database-internals/show-and-terminate-transactions/#show-transactions[<show transactions statement>] | link:https://neo4j.com/docs/operations-manual/current/database-administration/standard-databases/listing-databases/[<show databases statement>]