<show procedures statement> ::= 
  "SHOW" { "PROCEDURE" | "PROCEDURES" } [ <executable by> ] [ <show result clause> ]

<executable by> ::= 
  "EXECUTABLE" [ "BY CURRENT USER" | "BY" <user name> ]

<show result clause> ::= 
    "YIELD" <yield item list> [ link:https://neo4j.com/docs/cypher-manual/current/clauses/order-by/[<order by clause>] ] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/skip/[<offset clause>] ] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/limit/[<limit clause>] ] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/where/[<where clause>] ] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/return/[<return statement>] ]
  | link:https://neo4j.com/docs/cypher-manual/current/clauses/where/[<where clause>]

<user name> ::= 
  link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<identifier>]