<show functions statement> ::= 
  "SHOW" [ "ALL" | "BUILT IN" | "USER DEFINED" ] { "FUNCTION" | "FUNCTIONS" } [ <executable by> ] [ <show result clause> ]

<executable by> ::= 
  "EXECUTABLE" [ "BY CURRENT USER" | "BY" <user name> ]

<show result clause> ::= 
    "YIELD" <yield item list> [ <order by clause> ] [ <offset clause> ] [ <limit clause> ] [ <where clause> ] [ <return statement> ]
  | <where clause>