<terminate transaction statement> ::= 
  "TERMINATE" { "TRANSACTION" | "TRANSACTIONS" } <character string list element list or expression> [ <show yield result clause> ]

<show yield result clause> ::= 
  "YIELD" <yield item list> [ link:https://neo4j.com/docs/cypher-manual/current/clauses/order-by/[<order by clause>] ] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/skip/[<offset clause>] ] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/limit/[<limit clause>] ] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/where/[<where clause>] ] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/return/[<return statement>] ]