<terminate transaction statement> ::= 
  "TERMINATE" { "TRANSACTION" | "TRANSACTIONS" } <character string list element list or expression> [ "YIELD" link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<identifier>] [ "AS" link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] ] [ { "," link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<identifier>] [ "AS" link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>] ] }... ] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/order-by/[<order by clause>] ] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/skip/[<offset clause>] ] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/limit/[<limit clause>] ] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/where/[<where clause>] ] [ link:https://neo4j.com/docs/cypher-manual/current/clauses/return/[<return statement>] ] ]

<character string list element list or expression> ::= 
    link:https://neo4j.com/docs/cypher-manual/current/syntax/parsing/[<character string literal>] [ { "," link:https://neo4j.com/docs/cypher-manual/current/syntax/parsing/[<character string literal>] }... ]
  | link:https://neo4j.com/docs/cypher-manual/current/expressions/[<value expression>]