<unwind statement> ::= 
  "UNWIND" link:https://neo4j.com/docs/cypher-manual/current/expressions/[<value expression>] "AS" link:https://neo4j.com/docs/cypher-manual/current/syntax/naming/[<binding variable>]