<use graph clause> ::= "USE" <graph expression> 
<graph expression> ::= "(" <graph expression> ")" | <graph reference> | <function invocation> 
<graph reference> ::= [ <regular catalog object parent reference> ] <regular graph name> | <graph name> 
<function invocation> ::= <function reference> "(" [ <set quantifier> ][ <function argument list> ] ")" 
<regular catalog object parent reference> ::= { <regular object name> "." }... 
<set quantifier> ::= "ALL" | "DISTINCT" 
<function argument list> ::= <function argument> [{ "," <function argument> }...] 
<function reference> ::= [ <catalog object parent reference> ] <function name> 
<function argument> ::= xref:expressions/index.adoc[<value expression>] 
<catalog object parent reference> ::= { <object name> "." }... 
<function name> ::= xref:syntax/naming.adoc[<identifier>]