<use graph clause> ::= "USE" <graph expression> 
<graph expression> ::= "(" <graph expression> ")" | xref:values-and-types/graph-references.adoc[<graph reference>] | xref:functions/graph.adoc[<function invocation>]