<with statement> ::= "WITH" <return statement body> [ <order by and page clause> ][ xref:clauses/where.adoc[<where clause>] ] 
<order by and page clause> ::= xref:clauses/order-by.adoc[<order by clause>] [ <offset clause> ][ xref:clauses/limit.adoc[<limit clause>] ]| <offset clause> [ xref:clauses/limit.adoc[<limit clause>] ]| xref:clauses/limit.adoc[<limit clause>] 
<return statement body> ::= [ <set quantifier> ] <return item list> [ xref:clauses/group-by.adoc[<group by clause>] ] 
<offset clause> ::= <offset synonym> xref:expressions/index.adoc[<value expression>] 
<set quantifier> ::= "ALL" | "DISTINCT" 
<return item list> ::= { "*" | <return item> }[{ "," <return item> }...] 
<offset synonym> ::= "SKIP" | "OFFSET" 
<return item> ::= xref:expressions/index.adoc[<value expression>] [ <return item alias> ] 
<return item alias> ::= "AS" xref:syntax/naming.adoc[<identifier>]