= Numeric, string, and boolean literals

This page describes the literal forms of numerical (`INTEGER` and `FLOAT`), `STRING`, and `BOOLEAN` values in xref:expressions/index.adoc[expressions].

[[numerical]]
== Numerical

Numerical literals can represent `INTEGER` or `FLOAT` values.

A numerical literal may be written as:

* A numeric (`INTEGER` or `FLOAT`) literal: `13`, `-40000`, `3.14`.
* * A numeric (`INTEGER` or `FLOAT`) literal in scientific notation: `6.022E23`, `1e-9`
* A hexadecimal `INTEGER` literal (prefix `0x`): `0x13af`, `0xFC3A9`, `-0x66eff`
* An octal `INTEGER` literal (prefix `0o`): `0o1372`, `-0o5671`
* A `FLOAT` literal: `Inf`, `Infinity`, `NaN`.
* `NULL`.

[NOTE]
Any numeric literal may contain an underscore `_` between digits.
There may be an underscore between the `0x` or `0o` and the digits for hexadecimal and octal literals.
For example: `1_000_000`, `0x_FC3A9`, and `0o_1372`.

[[string]]
== String

String literals represent `STRING` values.
They are written using single(`'`) or double quotes (`"`) and may contain escape sequences using a backslash (`\`).
A string literal may be written as:

* A quoted `STRING` using single quotes: `'Hello, 42'`
* A quoted `STRING` using double quotes: `"Hello, 42"`
* A `STRING` with whitespace: `'    hello   '`
* A `STRING` with escape sequences: `'Line 1\nLine 2'`, `'Tab\tseparated'`
* A `STRING` using Unicode code point: `'Name: \u004Aohn'` (produces `'Name: John'`)
* `NULL`.

[[string-literal-escape-sequences]]
=== String literal escape sequences

String literals can contain the following escape sequences:

[options="header", cols=">1,<2"]
|===
|Escape sequence|Character
|`\t`|Tab
|`\b`|Backspace
|`\n`|Newline
|`\r`|Carriage return
|`\f`|Form feed
|`\'`|Single quote
|`\"`|Double quote
|`\\`|Backslash
|`\uxxxx`|Unicode UTF-16 code point (4 hex digits must follow the `\u`)
|===

[[boolean]]
== Boolean

Boolean literals represent `BOOLEAN` values.

A boolean literal may be written as:

* The literal `true`
* The literal `false`
* `NULL`.