:description: This section provides an overview of the property, structural, and constructed data types supported by Cypher.

[[cypher-values]]
= Property, structural, and constructed values


Cypher provides first class support for a number of data value types.
These fall into the following three categories: *property*, *structural*, and *constructed*.
This section will first provide a brief overview of each type, and then go into more detail about the property data type. 

== Property types

A property type value is one that can be stored as a node or relationship property.

The following data types are included in the property types category: `BOOLEAN`, `DATE`, `DURATION`, `FLOAT`, `INTEGER`, `LIST`, `LOCAL DATETIME`, `LOCAL TIME`, `POINT`, `STRING`, `ZONED DATETIME`, and `ZONED TIME`.

* Property types can be returned from Cypher queries.
* Property types can be used as xref::syntax/parameters.adoc[parameters].
* Property types can be stored as properties.
* Property types can be constructed with xref::syntax/expressions.adoc[Cypher literals].

Homogeneous lists of simple types can be stored as properties, although lists in general (see xref::values-and-types/property-structural-constructed.adoc#constructed-types[Constructed types]) cannot be stored as properties.

Cypher also provides pass-through support for byte arrays, which can be stored as property values.
Byte arrays are supported for performance reasons, since using Cypher's generic data type, `LIST<INTEGER>` (where each `INTEGER` has a 64-bit representation), would be too costly.
However, byte arrays are _not_ considered a first class data type by Cypher, so they do not have a literal representation.


[[structural-types]]
== Structural types

The following data types are included in the structural types category: `NODE`, `RELATIONSHIP`, and `PATH`.

* Structural types can be returned from Cypher queries.
* Structural types cannot be used as xref::syntax/parameters.adoc[parameters].
* Structural types cannot be stored as properties.
* Structural types cannot be constructed with xref::syntax/expressions.adoc[Cypher literals].

The `NODE` data type includes: id, label(s), and a map of properties.
Note that labels are not values, but a form of pattern syntax. 

The `RELATIONSHIP` data type includes: id, relationship type, a map of properties, start node id, and end node id.

The `PATH` data type is an alternating sequence of nodes and relationships.

[NOTE]
====
Nodes, relationships, and paths are returned as a result of pattern matching.
In Neo4j, all relationships have a direction.
However, you can have the notion of undirected relationships at query time.
====

[[constructed-types]]
== Constructed types

The following data types are included in the constructed types category: `LIST` and `MAP`.

* Constructed types can be returned from Cypher queries.
* Constructed types can be used as xref::syntax/parameters.adoc[parameters].
* Constructed types cannot be stored as properties (with the exception of homogenous lists).
* Constructed types can be constructed with xref::syntax/expressions.adoc[Cypher literals].

The `LIST` data type can be either a homogenous collection of simple values, or a heterogeneous, ordered collection of values, each of which can have any property, structural or constructed type.

The `MAP` data type is a heterogeneous, unordered collection of (_Key_, _Value_) pairs, where _Key_ is a literal and  _Value_ can have any property, structural, or constructed type.

Constructed type values can also contain `null`.
For more details, see xref::values-and-types/working-with-null.adoc[working with null].

[[types-synonyms]]
== Types and their synonyms

The table below shows the types and their syntactic synonyms.
These types (and their synonyms) can be used in xref::syntax/expressions.adoc#type-predicate-expressions[type predicate expressions] and in xref::constraints/examples.adoc#constraints-examples-node-property-type[node] and xref::constraints/examples.adoc#constraints-examples-relationship-property-type[relationship] property type constraints.
However, not all types can be used in all places.
Some of these types are not yet supported in either type predicate expressions or property type constraints.
// TODO: Remove sentence about type not being supported once all types are allowed

[.synonyms, opts="header", cols="2a,2a"]
|===
| Type | Synonyms
| `BOOLEAN` | `BOOL`
| `DATE` |
| `DURATION` |
| `FLOAT` |
| `INTEGER` | `INT`, `SIGNED INTEGER`
| `LIST<INNER_TYPE>` | `ARRAY<INNER_TYPE>`, `INNER_TYPE LIST`, `INNER_TYPE ARRAY`
| `LOCAL DATETIME` | `TIMESTAMP WITHOUT TIMEZONE`
| `LOCAL TIME` | `TIME WITHOUT TIMEZONE`
| `MAP` |
| `NODE` | `VERTEX`
| `PATH` |
| `POINT` |
| `RELATIONSHIP` | `EDGE`
| `STRING` | `VARCHAR`
| `ZONED DATETIME` | `TIMESTAMP WITH TIMEZONE`
| `ZONED TIME` | `TIME WITH TIMEZONE`
|===

== Property type details

The below table provides more detailed information about the various property types that Cypher supports. 
Note that Cypher types are implemented using Java, and that below table references Java value constants. 

[.types, opts="header", cols="2,2,2,1"]
|===
| Type | Min. value | Max. value | Precision

| `BOOLEAN`
| `False`
| `True`
| -

| `DATE`
| `-999_999_999-01-01`
| `+999_999_999-12-31`
| Days

| `DURATION`
| `P-292471208677Y-6M-15DT-15H-36M-32S`
| `P292471208677Y6M15DT15H36M32.999999999S`
| Nanoseconds

| `FLOAT`
| `Double.MIN_VALUE` footnote:[The minimum value represents the minimum positive value of a `FLOAT`, i.e. the closest value to zero.
It is also possible to have a negative float.]
| `Double.MAX_VALUE`
| 64 bit

| `INTEGER`
| `Long.MIN_VALUE`
| `Long.MAX_VALUE`
| 64 bit

| `LOCAL DATETIME`
| `-999_999_999-01-01T00:00:00`
| `+999_999_999-12-31T23:59:59.999999999`
| Nanoseconds

| `LOCAL TIME`
| `00:00:00`
| `23:59:59.999999999`
| Nanoseconds

| `POINT`
| *Cartesian*: (`-Double.MAX_VALUE`, `-Double.MAX_VALUE`)

*Cartesian_3D*: (`-Double.MAX_VALUE`, `-Double.MAX_VALUE`, `-Double.MAX_VALUE`)

*WGS_84*: (`-180`, `-90`)

*WGS_84_3D*: (`-180`, `-90`, `-Double.MAX_VALUE`)

| *Cartesian*: (`Double.MAX_VALUE`, `Double.MAX_VALUE`)

*Cartesian_3D*: (`Double.MAX_VALUE`, `Double.MAX_VALUE`, `Double.MAX_VALUE`)

*WGS_84*: (`180`, `90`)

*WGS_84_3D*: (`180`, `90`, `Double.MAX_VALUE`)

| The precision of each coordinate of the `POINT` is 64 bit as they are floats.

| `STRING`
| -
| -
| -

| `ZONED DATETIME`
| `-999_999_999-01-01T00:00:00+18:00`
| `+999_999_999-12-31T23:59:59.999999999-18:00`
| Nanoseconds

| `ZONED TIME`
| `00:00:00+18:00`
| `23:59:59.999999999-18:00`
| Nanoseconds
|===

=== Java value details

[.values, opts="header", width=75%, cols="1,3"]
|===
| Name | Value

| `Double.MAX_VALUE`
| 1.7976931348623157e+308 

| `Double.MIN_VALUE` 
| 4.9e-324 

| `Long.MAX_VALUE` 
| 2^63-1 

| `Long.MIN_VALUE`
| -2^63 
|===

