= UUIDs
:description: Information for working with uuids in Cypher 5.
:page-role: new-neo4j-2026.08 enterprise-edition

`UUID` values can be created and stored as properties on nodes and relationships.

[IMPORTANT]
====
Only the `UUID` _type_ is present in Cypher 5.
Although `UUID` values can still be inserted in and retrieved from the database with Cypher 5 queries using a link:https://neo4j.com/docs/create-applications/[Neo4j client library] version >= 6.2, the Cypher functions to create and store `UUID` type properties are only available using link:https://neo4j.com/docs/cypher-manual/25/values-and-types/uuid/[Cypher 25].
If you wish to use `UUID` values, Cypher 25 is recommended.
====

[[uuid-type]]
== The UUID type

The `UUID` type is a 128-bit identifier, commonly used to uniquely identify objects within a distributed system. 
In Cypher, `UUID` values are stored as a dedicated type and can be represented as a hexadecimal string in the format `8-4-4-4-12` (e.g., `550e8400-e29b-41d4-a716-446655440000`).

.An example `UUID` value
[source]
----
uuid("550e8400-e29b-41d4-a716-446655440000")
----

In this example, the string `"550e8400-e29b-41d4-a716-446655440000"` is a valid representation of a UUID.

[NOTE]
Cypher's `UUID` type does not guarantee a specific UUID version.
See the link:https://www.rfc-editor.org/rfc/rfc9562.html[RFC 9562 Universally Unique IDentifiers (UUIDs)  documentation] for details on the different UUID versions.

[valid-values]]
=== Valid values

A `UUID` value must follow the standard representation of 32 hexadecimal digits, displayed in five groups separated by hyphens (e.g., `8-4-4-4-12`).
