= Vectors
:description: Information about Cypher's `VECTOR` type.
:page-role: new-2025.xx

Cypher's supports the construction of a `VECTOR` type that can be stored as xref:indexes/semantic-indexes/vector-indexes.adoc#embeddings[embedding] properties on nodes and relationships and utilized for efficient semantic retrieval using Neo4j's xref:indexes/semantic-indexes/vector-indexes.adoc[vector indexes] and xref:genai-integrations.adoc[GenAI plugin].

[[vector-type]]
== The vector type

The `VECTOR` type is a fixed-length list of numeric coordinate values (`INTEGER` or `FLOAT`) stored as a single unit.
It is defined by its dimension, which sets how many numeric values it holds, and its coordinate type, which specifies the specific numeric data type for those numbers.
Each numeric value in the list represents a coordinate along one of the vector’s defined dimensions.
The coordinate type controls the kind of number stored at each position, influencing precision and storage size.

In the below example, `[1.05, 0.123, 5]` is the list of numeric values (or coordinates), defining a three dimensional `VECTOR` with the coordinate type `FLOAT32`. 

.Example `VECTOR` type
[source]
----
VECTOR([1.05, 0.123, 5], 3, FLOAT32 NOT NULL)
----

.`VECTOR` and `LIST` values
[NOTE]
The dimensions and the formatting of a `VECTOR` is similar to a xref:values-and-types/lists.adoc[`LIST`] value.
However, unlike `LIST` values which contain elements that can be accessed individually with xref:expressions/list-expressions.adoc[list expressions], all operations on a `VECTOR` must operate on the entire `VECTOR`; it is not possible to access or slice individual dimensions of a `VECTOR` value.
Additionally, a `LIST` cannot contain `VECTOR` values.

The dimension of a `VECTOR` value must be larger than `0` and less than or equal to `4096`. 

The following coordinate types are supported:

.Vector coordinate types
[options="header",cols="2*<m"]
|===
| Default name | Alias

| `FLOAT` | `FLOAT64`
| `FLOAT32` | 
| `INTEGER` | `INT`, `INT64`, `SIGNED INTEGER`, `INTEGER64`
| `INTEGER8` | `INT8`
| `INTEGER16`| `INT16`
| `INTEGER32` | `INT8`

|===

A `VECTOR` value must have a dimension and a coordinate type.
As such, `VECTOR` should be considered a supertype (which can be checked for in a xref:expressions/predicates/type-predicate-expressions.adoc#type-predicate-vector[type predicate expressions]) of which all combinations of `VECTOR<TYPE>(DIMENSION)` are a part.

This logic continues for `VECTOR` values that define only a coordinate type or a dimension.
A `VECTOR` with only a dimension represents all vectors of that dimension regardless of the coordinate type, and a `VECTOR` with only a coordinate type represents all vectors of that coordinate type regardless of the `dimension`.

[[ordering-vector]]
== Ordering vector values

`VECTOR` values with a defined coordinate type and no dimension are ordered before values with only a defined dimension.
Values with both a defined coordinate type and dimension are ordered according to the ordering of the vector coordinate types, listed in ascending order below:

* `INTEGER8`
* `INTEGER16`
* `INTEGER32`
* `INTEGER64`
* `FLOAT32`
* `FLOAT64`

Within the same coordinate type, `VECTOR` values are ordered by their dimension, with smaller values first.
`VECTOR` values of the same coordinate type and dimension are then ordered pairwise, similar to how `LIST` values are ordered.

.Ordering rules for `VECTOR` values
[cols="3,3,2,6", options="header"]
|===
| A | B | Ordered As | Reason

| `VECTOR<FLOAT32>(12345)`
| `VECTOR<FLOAT32>(123456)`
| A < B
| Same coordinate type, compare by dimension ascending.

| `VECTOR<INTEGER32>(1234)`
| `VECTOR<FLOAT32>(1234)`
| A < B
| Coordinate type order: `INTEGER32` < `FLOAT32`

| `VECTOR<INTEGER8>`
| `VECTOR(3)`
| A < B
| Coordinate type defined and no dimension < dimension defined and no coordinate type

| `VECTOR<INTEGER64>(123456)`
| `VECTOR<FLOAT32>(3)`
| A < B
| Coordinate type order: `INTEGER64` < `FLOAT32`, compare coordinate type first.

| `VECTOR<FLOAT64>(1234)`
| `VECTOR<FLOAT32>(1234)`
| B < A
| Coordinate type order: `FLOAT32` < `FLOAT64`

| `VECTOR<FLOAT32>([1, 2])`
| `VECTOR<FLOAT32>([2, 1])`
| A < B
| Same coordinate type and dimension, pairwise value comparison.

| `VECTOR<INTEGER16>(1234)`
| `LIST<INTEGER>`
| A < B
| `VECTOR` values are ordered before `LIST` values

|===

== Vector normalization 

A `VECTOR` without a coordinate type or dimension encompasses any other `VECTOR`.
A `VECTOR` with a coordinate type but no dimension encompasses a vector with the same coordinate type and a defined dimension. A VECTOR with a dimension but no coordinate type encompasses a vector with the same dimension and any coordinate type. Vectors cannot be normalized together if their coordinate types differ, or if their dimensions differ.

[[construct-vector-values]]
== Construct vector values

To construct a `VECTOR` value, use the xref:functions/vector.adoc#functions-vector[`vector()`] function.

The following query constructs a three-dimensional vector with `INTEGER` values.
It returns the `VECTOR` itself, and the xref:functions/scalar.adoc#functions-valuetype[`valueType()`] function is used to information about its type.

.Construct a `VECTOR` value
[source, cypher]
----
WITH vector([1, 2, 3], 3, INTEGER) AS vector
RETURN vector, valueType(vector) AS vectorType
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| vector | vectorType

| [1, 2, 3] | "VECTOR<INTEGER64 NOT NULL>(3) NOT NULL"

2+d|Rows: 1
|===

The following example uses a parameter containing a `LIST<INTEGER>` as input to `vectorValue`.

.Parameters
[source, parameters]
----
{
  "integerList": [1, 2, 3, 4, 5]
}
----

.Construct a `VECTOR` value with using a parameter for `vectorValue`
[source, cypher]
----
WITH vector($integerList, 5, INTEGER8) as vector
RETURN vector, valueType(vector) AS vectorType
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| vector | vectorType

| [1, 2, 3, 4, 5] | "VECTOR<INTEGER8 NOT NULL>(5) NOT NULL"

2+d|Rows: 1
|===

[[calculate-vector-size]]
== Calculate vector size

To calculate the size (i.e. the number of dimensions) of a `VECTOR` value, use either the xref:functions/scalar.adoc#functions-size[`size()`] function or the xref:functions/vector.adoc#functions-vector_dimension_count[`vector_dimension_count()`] function.footnote:[`size()` can calculate the sizes of non-`VECTOR` values. `vector_dimension_count()` will throw an error for any non-`VECTOR` values.]

.Calculate `VECTOR` size with `size()`
[source, cypher]
----
RETURN size(vector([1, 2, 3], 3, INTEGER)) AS size
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| size

| 3

1+d|Rows: 1
|===

.Calculate `VECTOR` size with `vector_dimension_count()`
[source, cypher]
----
RETURN vector_dimension_count(vector([1, 2, 3], 3, INTEGER)) AS size
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| size

| 3

1+d|Rows: 1
|===

[role=label--enterprise-edition]
[[store-vector-properties]]
== Store vector values as properties

To store a `VECTOR` value as a node or relationship property, use the `vector()` function together with a write clause.

.Create a node and assign a `VECTOR` property
[source, cypher]
----
CREATE (n:Label {vectorProp = vector([1,2,3], 3, INTEGER))
RETURN n.vectorProp AS vectorProp
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| vectorProp

| 

1+d|Rows: 1
|===

.Parameters
[source, parameters]
----
{
  "floatList": [1.3, 2.4, 3.1, 4.4, 5.9]
}
----

.Set a `VECTOR` property using a parameter
[source, cypher]
----
CREATE (n:Label)
SET n.vectorProp = vector($floatList, 5, FLOAT)
RETURN n.vectorProp AS vectorProp
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| vectorProp

| 

1+d|Rows: 1
|===

[[genai-plugin-vector-indexes]]
== Vector values, the GenAI plugin, and vector indexes

Neo4j previously stored vector embeddings as `LIST<FLOAT64>` property values.
Storing vectors embeddings as `VECTOR` property values with a specified dimension and coordinate type allows for a more efficient storage of embeddings.

For information about how to store embeddings generated by Neo4j xref:genai-integrations.adoc[GenAI plugin] see:

* xref:genai-integrations.adoc#store-single-embedding-vector[Store a single embedding as a `VECTOR` property]
* xref:genai-integrations.adoc#store-multiple-embeddings-vector[Store multiple embeddings as a `VECTOR` properties]

[NOTE]
The GenAI plugin requires an account and API credentials from a supported GenAI provider.
For more information, see xref:genai-integrations.adoc#ai-providers[AI providers].

Embeddings stored as `VECTOR` property values can be indexed and searched semantically using a xref:indexes/semantic-indexes/vector-indexes.adoc[vector index].
