= Vectors
:description: Information about Cypher's `VECTOR` type.
:page-role: new-neo4j-2025.10

Cypher supports the construction of a `VECTOR` value that can be stored as xref:indexes/semantic-indexes/vector-indexes.adoc#embeddings[embedding] properties on nodes and relationships and used for efficient semantic retrieval using Neo4j's xref:indexes/semantic-indexes/vector-indexes.adoc[vector indexes] and xref:genai-integrations.adoc[GenAI plugin].
`VECTOR` values can also be measured and compared (in terms of similarity, distance, and norm) using Cypher's xref:functions/vector.adoc[vector functions].

[[vector-type]]
== The vector type

The `VECTOR` type is a fixed-length, ordered collection of numeric coordinate values (`INTEGER` or `FLOAT`) stored as a single unit.
It is defined by its dimension, which sets how many numeric values it holds, and its coordinate type, which specifies the specific numeric data type for those numbers.
Each numeric value in the list represents a coordinate along one of the vector’s defined dimensions.
The coordinate type controls the type of each coordinate in the `VECTOR`, influencing precision and storage size.
A `VECTOR` value must have a dimension and a coordinate type.

.Example `VECTOR` type
[source]
----
VECTOR([1.05, 0.123, 5], 3, FLOAT32 NOT NULL)
----

In this example, `[1.05, 0.123, 5]` is the coordinates of the `VECTOR`, `3` its dimensionality, and `FLOAT32` the data type for each coordinate value.

.`VECTOR` and `LIST` values
[NOTE]
The dimensions and the formatting of a `VECTOR` is similar to a xref:values-and-types/lists.adoc[`LIST`] value.
However, whereas elements in `LIST` values can be accessed individually with xref:expressions/list-expressions.adoc[list expressions], operations on a `VECTOR` must operate on the entire `VECTOR`: it is not possible to access or slice individual elements of a `VECTOR` value.
Additionally, Neo4j cannot store lists containing `VECTOR` values.

The dimension of a `VECTOR` value must be larger than `0` and less than or equal to `4096`.

The following coordinate types are supported:

.Vector coordinate types
[options="header",cols="2*<m"]
|===
| Default name | Alias

| `FLOAT` | `FLOAT64`
| `FLOAT32` |
| `INTEGER` | `INT`, `INT64`, `SIGNED INTEGER`, `INTEGER64`
| `INTEGER8` | `INT8`
| `INTEGER16`| `INT16`
| `INTEGER32` | `INT8`

|===

`VECTOR` is a supertype of `VECTOR<TYPE>(DIMENSION)` types.
The same applies for `VECTOR` types that define only a coordinate type or a dimension:

- `VECTOR` with only a defined dimension is a supertype of all `VECTOR` values of that dimension regardless of the coordinate type.
For example, `VECTOR(4)` is a supertype of `VECTOR<FLOAT>(4)` and `VECTOR<INT8>(4)`.
- `VECTOR` with only a defined coordinate type is a supertype of all `VECTOR` values with that coordinate type regardless of the dimension.
For example, `VECTOR<INT>` is a supertype of `VECTOR<INT>(3)` and `VECTOR<INT>(1024)`.

All of these supertypes can be used in xref:expressions/predicates/type-predicate-expressions.adoc#type-predicate-vector[type predicate expressions] to verify `VECTOR` type values.

See also:

* xref:values-and-types/ordering-equality-comparison.adoc#ordering-and-comparison[Equality, ordering, and comparison of value types -> Ordering vector types]
* xref:values-and-types/property-structural-constructed.adoc#vector-type-normalization[Property, structural, and constructed values -> Vector type normalization]

[[construct-vector-values]]
== Construct vector values

To construct a `VECTOR` value, use the xref:functions/vector.adoc#functions-vector[`vector()`] function.

.Create a three-dimensional vector with `INTEGER` values
====

.Query
[source, cypher]
----
WITH vector([1, 2, 3], 3, INTEGER) AS vector
RETURN vector
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| vector

| vector([1, 2, 3], 3, INTEGER NOT NULL)

1+d|Rows: 1
|===

====


[IMPORTANT]
====
Running a query that returns a `VECTOR` value via a link:{neo4j-docs-base-uri}/create-applications/[driver] version < 6.0 does not yield a `VECTOR`, but rather a placeholder `MAP` value.
A warning will also be attached.

.Result of returning a `VECTOR` with a driver older than 6.0
[source]
----
+----------------------------------------------------------------+
| n.vector                                                      |
+----------------------------------------------------------------+
| {originalType: "VECTOR(1, INTEGER64)", reason: "UNKNOWN_TYPE"} |
+----------------------------------------------------------------+
warn: One or more values returned could not be handled by this version of the driver and were replaced with placeholder map values. Please upgrade your driver!
03N95 (Neo.ClientNotification.UnknownType)
----
====


.Create a `VECTOR` value using parameters
====

.Parameters (`LIST<INTEGER>`)
[source, parameters]
----
{
  "integerList": [1, 2, 3, 4, 5]
}
----

.Query
[source, cypher]
----
WITH vector($integerList, 5, INTEGER8) as vector
RETURN vector
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| vector

| vector([1, 2, 3, 4, 5], 5, INTEGER8 NOT NULL)

1+d|Rows: 1
|===

====


[role=label--enterprise-edition]
[[store-vector-properties]]
== Store vector values as properties

To store a `VECTOR` value as a node or relationship property, use the `vector()` function together with a write clause.

[NOTE]
Storing `VECTOR` values on an on-prem instance requires the database to be on link:{neo4j-docs-base-uri}/operations-manual/current/database-internals/store-formats/#store-format-overview[block format].

.Create a node and a `VECTOR` property
====

.Query
[source, cypher]
----
CREATE (n:Label {vectorProp: vector([1,2,3], 3, INTEGER)})
RETURN n.vectorProp AS vectorProp
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| vectorProp

| vector([1, 2, 3], 3, INTEGER NOT NULL)

1+d|Rows: 1
|===

====

.Create a node and a `VECTOR` property using parameters
====

.Parameters
[source, parameters]
----
{
  "floatList": [1.3, 2.4, 3.1, 4.4, 5.9]
}
----

.Query
[source, cypher]
----
CREATE (n:Label {vectorProp: $floatList})
RETURN n.vectorProp AS vectorProp
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| vectorProp

| vector([1.3, 2.4, 3.1, 4.4, 5.9], 5, FLOAT NOT NULL)

1+d|Rows: 1
|===

====

[NOTE]
It is not possible to store lists of `VECTOR` values.


[[genai-plugin-vector-indexes]]
== Vector embeddings, the GenAI plugin, and vector indexes

Storing vector embeddings as `VECTOR` properties with a defined coordinate type has the following benefits:

* `VECTOR` values are stored on Neo4j's link:{neo4j-docs-base-uri}/operations-manual/current/database-internals/store-formats/#store-format-overview[block format], ensuring efficient retrieval and computation for operations like similarity search or distance calculations.
* Defining a coordinate type with the `vector()` function allows `VECTOR` values to be stored more efficiently.
Additionally, reducing a vectors coordinate type (e.g., from `INTEGER16` to `INTEGER8`) reduces storage requirements and improves performance, provided all values remain within the range supported by the smaller type.

For information about how to store embeddings generated by Neo4j as `VECTOR` values with the xref:genai-integrations.adoc[GenAI plugin], see:

* xref:genai-integrations.adoc#single-embedding[Generate a single embedding and store it]
* xref:genai-integrations.adoc#multiple-embeddings[Generate multiple embeddings and store them]

Embeddings stored as `VECTOR` properties can be indexed and searched semantically using xref:indexes/semantic-indexes/vector-indexes.adoc[vector indexes].
