= Vectors
:description: Information about Cypher's `VECTOR` type.
:page-role: new-2025.xx

Cypher's supports a `VECTOR` type that can be stored as properties on nodes and relationships.
`VECTOR` properties can be utilized for efficient semantic retrieval with the Neo4j's xref:indexes/semantic-indexes/vector-indexes.adoc[vector indexes] and xref:genai-integrations.adoc[GenAI plugin].


== Construct vector type values

To construct a `VECTOR` type value, use the xref:functions/vector.adoc#functions-vector[`vector()`] function.

.`vector()` function signature
[source]
----
vector(vectorValue :: STRING | LIST<INTEGER | FLOAT>, dimension :: INTEGER, coordinateType :: [INTEGER64, INTEGER32, INTEGER16, INTEGER8, FLOAT64, FLOAT32]) :: VECTOR
----

* `vectorValue`: a `LIST` of either `INTEGER` or `FLOAT` values, or a `STRING` (the `STRING` must start and end with square brackets (`[]`).
The values inside the brackets must be a number represented in either decimal or scientific notation and must be comma separated).
The `vectorValue` must be of the same length as the given `dimension` and contain values of the corresponding `coordinateType`.
`null`, NaN, and infinity values are not allowed.
* `dimension`: an `INTEGER` (with a value greater than `0 and less than or equal to `4096`) specifying the number of coordinates the `VECTOR` value contains.
For example a `VECTOR` with a dimension of `3` has three values, which might represent vector embeddings.
* `coordinateType`: a vector-only coordinate `INTEGER` or `FLOAT` type, determining the data type for each of the values in `vectorValue`.
If `vectorValue` contain elements that are not of the specified coordinate type, they will be coerced to that coordinate type if possible.
This includes the potential of lossy conversion in cases where a larger type, e.g. `INTEGER64` does not fit into the specified type, e.g. `FLOAT32`. 

The following expression constructs a three-dimensional vector with integer values:

.Construct a `VECTOR` value
[source, cypher]
----
WITH vector([1,2,3], 3, INTEGER) AS vector
RETURN vector, valueType(vector)
----


[role=label-enterprise-edition]
== Store vector values as properties



== Vector types, the GenAI plugin, and vector indexes


== Vectors and lists


Since Vectors are described as having multiple dimensions, they look a bit like the constructed value type LIST<...>. However, all vector operations operate on the entire vector. Operations on individual components of a vector instance are not defined. We therefore conclude that vectors are predefined value types.




== Vector supertype and vector coordinate types

Whilst it is not possible to store a typeless, dimensionless vector, it is possible to use that type in a type predicate expression for example; RETURN x IS :: VECTOR which should evaluate to true as long as x is a vector, regardless of its coordinate type or dimension. Due to this, we consider VECTOR to be a supertype of all VECTOR types. This logic continues for vectors that define only a type or a dimension, a VECTOR with only a dimension represents all vectors of that dimension regardless of the type, and a VECTOR with only a type represents all vectors of that type regardless of the dimension.