:description: Overview of the performance indexes available in Neo4j.
include::https://raw.githubusercontent.com/neo4j-graphacademy/courses/main/asciidoc/courses/cypher-indexes-constraints/ad.adoc[]
:page-aliases: indexes-for-search-performance.adoc, indexes/search-performance-indexes/index.adoc
= Performance indexes

Performance indexes allow the Cypher planner to evaluate predicates more efficiently without changing what those predicates mean.
There are four different performance indexes available in Neo4j:

* xref:indexes/performance-indexes/create-indexes.adoc#create-range-index[*Range indexes*]: Neo4j’s default index.
Supports most types of predicates.

* xref:indexes/performance-indexes/create-indexes.adoc#create-text-index[*Text indexes*]: solves predicates operating on `STRING` values.
Optimized for queries filtering with the `STRING` operators `CONTAINS` and `ENDS WITH`.

* xref:indexes/performance-indexes/create-indexes.adoc#create-point-index[*Point indexes*]: solves predicates on spatial `POINT` values.
Optimized for queries filtering on distance or within bounding boxes.

* xref:indexes/performance-indexes/create-indexes.adoc#create-lookup-index[*Token lookup indexes*]: only solves node label and relationship type predicates (i.e. they cannot solve any predicates filtering on properties).
Two token lookup indexes (one for node labels and one for relationship types) are present when a database is created in Neo4j.

To learn more about creating, listing, and deleting these indexes, as well as more details about the predicates supported by each index type, see xref:indexes/performance-indexes/create-indexes.adoc[], xref:indexes/performance-indexes/list-indexes.adoc[] and xref:indexes/performance-indexes/drop-indexes.adoc[].

For information about how performance indexes are used in Cypher queries, how they impact their performance, as well as some heuristics for when to use (and not to use) a performance index, see xref:indexes/performance-indexes/using-indexes.adoc[].

Performance indexes are used automatically, and if several indexes are available, the xref:planning-and-tuning/execution-plans.adoc[Cypher planner] tries to use the index (or indexes) that can most efficiently solve a particular predicate.
It is, however, possible to explicitly force a query to use a particular index with the `USING` keyword. For more information, see xref:indexes/performance-indexes/index-hints.adoc[].
