:description: How to use Cypher to manage Neo4j database administrative privileges.

////
[source, cypher, role=test-setup]
----
CREATE ROLE regularUsers;
CREATE ROLE databaseAdminUsers;
CREATE DATABASE `remote-db`;
CREATE USER jake SET PASSWORD 'abcd1234' CHANGE NOT REQUIRED;
----
////

[role=enterprise-edition aura-db-enterprise]
[[access-control-database-administration]]
= Database administration

[abstract]
--
This section explains how to use Cypher to manage Neo4j database administrative privileges.
--

Administrators can use the following Cypher commands to manage Neo4j database administrative rights.

The components of the database privilege commands are:

* _command_:
** `GRANT` – gives privileges to roles.
** `DENY` – denies privileges to roles.
** `REVOKE` – removes granted or denied privileges from roles.

* _mutability_:
** `IMMUTABLE` - When used in conjunction with `GRANT` or `DENY`, specifies that a privilege cannot subsequently be removed unless auth is disabled.
Contrastingly, when `IMMUTABLE` is specified in conjunction with a `REVOKE` command, it will act as a filter and only remove matching _immutable_ privileges.
See also xref:administration/access-control/index.adoc#access-control-privileges-immutable[immutable privileges].

* _database-privilege_
** `ACCESS` - allows access to a specific database or remote database alias.
** `START` - allows the specified database to be started.
** `STOP` - allows the specified database to be stopped.
** `CREATE INDEX` - allows indexes to be created on the specified database.
** `DROP INDEX` - allows indexes to be deleted on the specified database.
** `SHOW INDEX` - allows indexes to be listed on the specified database.
** `INDEX [MANAGEMENT]` - allows indexes to be created, deleted, and listed on the specified database.
** `CREATE CONSTRAINT` - allows constraints to be created on the specified database.
** `DROP CONSTRAINT` - allows constraints to be deleted on the specified database.
** `SHOW CONSTRAINT` - allows constraints to be listed on the specified database.
** `CONSTRAINT [MANAGEMENT]` - allows constraints to be created, deleted, and listed on the specified database.
** `CREATE NEW [NODE] LABEL` - allows new node labels to be created.
** `CREATE NEW [RELATIONSHIP] TYPE` - allows new relationship types to be created.
** `CREATE NEW [PROPERTY] NAME` - allows property names to be created, so that nodes and relationships can have properties assigned with these names.
** `NAME [MANAGEMENT]` - allows all of the name management capabilities: node labels, relationship types, and property names.
** `ALL [[DATABASE] PRIVILEGES]` - allows access, index, constraint, and name management for the specified database or remote database alias.
** `SHOW TRANSACTION` -  allows listing transactions and queries for the specified users on the specified database.
** `TERMINATE TRANSACTION` - allows ending transactions and queries for the specified users on the specified database.
** `TRANSACTION [MANAGEMENT]` - allows listing and ending transactions and queries for the specified users on the specified database.

* _name_
** The database to associate the privilege with.
+
[NOTE]
====
If you delete a database and create a new one with the same name, the new one will NOT have the same privileges previously assigned to the deleted one.
====
** The _name_ component can be `+*+`, which means all databases.
Databases created after this command execution will also be associated with these privileges.
** The `DATABASE[S] _name_` part of the command can be replaced by `HOME DATABASE`.
This refers to the home database configured for a user or, if that user does not have a home database configured, the default database.
If the user's home database changes for any reason after this command execution, the new one will be associated with these privileges.
This can be quite powerful as it allows permissions to be switched from one database to another simply by changing a user's home database.

* _role[, ...]_
** The role or roles to associate the privilege with, comma-separated.

[NOTE]
====
More details about the syntax descriptions can be found xref:administration/index.adoc#administration-syntax[here].
====

.General grant +ON DATABASE+ privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT ... ON ... TO ...+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] database-privilege ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } } TO role[, ...]
----

| Description
| Grants a privilege to one or multiple roles.

|===


.General deny +ON DATABASE+ privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +DENY ... ON ... TO ...+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
DENY [IMMUTABLE] database-privilege ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } } TO role[, ...]
----

| Description
| Denies a privilege to one or multiple roles.

|===


.General revoke +ON DATABASE+ privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +REVOKE GRANT ... ON ... FROM ...+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
REVOKE [IMMUTABLE] GRANT database-privilege ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } } FROM role[, ...]
----

| Description
| Revoke a granted privilege from one or multiple roles.

|===


.General revoke +ON DATABASE+ privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +REVOKE DENY ... ON ... FROM ...+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
REVOKE [IMMUTABLE] DENY database-privilege ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } } FROM role[, ...]
----

| Description
| Revokes a denied privilege from one or multiple roles.

|===


.General revoke +ON DATABASE+ privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +REVOKE ... ON ... FROM ...+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
REVOKE [IMMUTABLE] database-privilege ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } } FROM role[, ...]
----

| Description
| Revokes a granted or denied privilege from one or multiple roles.

|===


[NOTE]
====
`DENY` does *not* erase a granted privilege.
Use `REVOKE` if you want to remove a privilege.
====

Common errors, such as misspellings or attempts to revoke privileges that have not been granted or denied, will lead to notifications.
Some of these notifications may be replaced with errors in a future major version of Neo4j.
See link:{neo4j-docs-base-uri}/status-codes/{page-version}/notifications/all-notifications[Status Codes -> Notification codes] for details on notifications.

The hierarchy between the different database privileges is shown in the image below.

image::privileges_hierarchy_database.svg[title="Database privileges hierarchy"]




.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT ACCESS+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] ACCESS
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
a|
Grants the specified roles the privilege to access:

* The home database.
* Specific database(s) or remote database alias(es).
* All databases and remote database aliases.

|===


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT { START \| STOP }+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] { START \| STOP }
  ON { HOME DATABASE \| DATABASE[S] {* \| name[, ...] } }
  TO role[, ...]
----

| Description
| Grants the specified roles the privilege to start or stop the home database, specific database(s), or all databases.

|===


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT { CREATE \| DROP \| SHOW } INDEX+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] { CREATE \| DROP \| SHOW } INDEX[ES]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Grants the specified roles the privilege to create, delete, or show indexes on the home database, specific database(s), or all databases.

|===


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT INDEX+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] INDEX[ES] [MANAGEMENT]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Grants the specified roles the privilege to manage indexes on the home database, specific database(s), or all databases.

|===


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT { CREATE \| DROP \| SHOW } CONSTRAINT+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] { CREATE \| DROP \| SHOW } CONSTRAINT[S]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Grants the specified roles the privilege to create, delete, or show constraints on the home database, specific database(s), or all databases.

|===


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT CONSTRAINT+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] CONSTRAINT[S] [MANAGEMENT]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Grants the specified roles the privilege to manage constraints on the home database, specific database(s), or all databases.

|===


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT CREATE NEW LABEL+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] CREATE NEW [NODE] LABEL[S]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Grants the specified roles the privilege to create new node labels in the home database, specific database(s), or all databases.

|===


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT CREATE NEW TYPE+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] CREATE NEW [RELATIONSHIP] TYPE[S]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Grants the specified roles the privilege to create new relationship types in the home database, specific database(s), or all databases.

|===


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT CREATE NEW NAME+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] CREATE NEW [PROPERTY] NAME[S]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Grants the specified roles the privilege to create new property names in the home database, specific database(s), or all databases.

|===


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT NAME+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] NAME [MANAGEMENT]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Grants the specified roles the privilege to manage new labels, relationship types, and property names in the home database, specific database(s), or all databases.

|===


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT ALL+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] ALL [[DATABASE] PRIVILEGES]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Grants the specified roles all privileges for the home, a specific, or all databases and remote database aliases.

|===


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT { SHOW \| TERMINATE } TRANSACTION+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] { SHOW \| TERMINATE } TRANSACTION[S] [( { * \| user[, ...] } )]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Grants the specified roles the privilege to list and end the transactions and queries of all users or a particular user(s) in the home database, specific database(s), or all databases.

|===


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT TRANSACTION+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] TRANSACTION [MANAGEMENT] [( { * \| user[, ...] } )]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Grants the specified roles the privilege to manage the transactions and queries of all users or a particular user(s) in the home database, specific database(s), or all databases.

|===


image::privileges_grant_and_deny_syntax_database_privileges.svg[title="Syntax of GRANT and DENY Database Privileges"]


[[access-control-database-administration-access]]
== The database `ACCESS` privilege

The `ACCESS` privilege enables users to connect to a database or a remote database alias.
With `ACCESS` you can run calculations, for example, `+RETURN 2 * 5 AS answer+` or call functions `RETURN timestamp() AS time`.

[source, syntax, role="noheader"]
----
GRANT [IMMUTABLE] ACCESS
  ON { HOME DATABASE | DATABASE[S] { * | name[, ...] } }
  TO role[, ...]
----

For example, to grant the role `regularUsers` the ability to access the database `neo4j`, use:

[source, cypher, role=noplay]
----
GRANT ACCESS ON DATABASE neo4j TO regularUsers
----

The `ACCESS` privilege can also be denied:

[source, syntax, role="noheader"]
----
DENY [IMMUTABLE] ACCESS
  ON { HOME DATABASE | DATABASE[S] { * | name[, ...] } }
  TO role[, ...]
----

For example, to deny the role `regularUsers` the ability to access to the remote database alias `remote-db`, use:

[source, cypher, role=noplay]
----
DENY ACCESS ON DATABASE `remote-db` TO regularUsers
----

The privileges granted can be seen using the `SHOW PRIVILEGES` command:

[source, cypher, role=noplay]
----
SHOW ROLE regularUsers PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"DENY ACCESS ON DATABASE `remote-db` TO `regularUsers`"
|"GRANT ACCESS ON DATABASE `neo4j` TO `regularUsers`"
a|Rows: 2
|===


[[access-control-database-administration-startstop]]
== The database `START`/`STOP` privileges

The `START` privilege can be used to enable the ability to start a database:

[source, syntax, role="noheader"]
----
GRANT [IMMUTABLE] START
  ON { HOME DATABASE | DATABASE[S] { * | name[, ...] } }
  TO role[, ...]
----

For example, to grant the role `regularUsers` the ability to start the database `neo4j`, use:

[source, cypher, role=noplay]
----
GRANT START ON DATABASE neo4j TO regularUsers
----

The `START` privilege can also be denied:

[source, syntax, role="noheader"]
----
DENY [IMMUTABLE] START
  ON { HOME DATABASE | DATABASE[S] { * | name[, ...] } }
  TO role[, ...]
----

For example, to deny the role `regularUsers` the ability to start to the database `neo4j`, use:

[source, cypher, role=noplay]
----
DENY START ON DATABASE system TO regularUsers
----

The `STOP` privilege can be used to enable the ability to stop a database:

[source, syntax, role="noheader"]
----
GRANT [IMMUTABLE] STOP
  ON { HOME DATABASE | DATABASE[S] { * | name[, ...] } }
  TO role[, ...]
----

For example, to grant the role `regularUsers` the ability to stop the database `neo4j`, use:

[source, cypher, role=noplay]
----
GRANT STOP ON DATABASE neo4j TO regularUsers
----

The `STOP` privilege can also be denied:

[source, syntax, role="noheader"]
----
DENY [IMMUTABLE] STOP
  ON { HOME DATABASE | DATABASE[S] { * | name[, ...] } }
  TO role[, ...]
----

For example, to deny the role `regularUsers` the ability to stop the database `neo4j`, use:

[source, cypher, role=noplay]
----
DENY STOP ON DATABASE system TO regularUsers
----

The privileges granted can be seen using the `SHOW PRIVILEGES` command:

[source, cypher, role=noplay]
----
SHOW ROLE regularUsers PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"DENY ACCESS ON DATABASE `remote-db` TO `regularUsers`"
|"DENY START ON DATABASE `system` TO `regularUsers`"
|"DENY STOP ON DATABASE `system` TO `regularUsers`"
|"GRANT ACCESS ON DATABASE `neo4j` TO `regularUsers`"
|"GRANT START ON DATABASE `neo4j` TO `regularUsers`"
|"GRANT STOP ON DATABASE `neo4j` TO `regularUsers`"
a|Rows: 6
|===

[NOTE]
====
Note that `START` and `STOP` privileges are not included in the xref::administration/access-control/database-administration.adoc#access-control-database-administration-all[`ALL DATABASE PRIVILEGES`].
====


[[access-control-database-administration-index]]
== The `INDEX MANAGEMENT` privileges

Indexes can be created, deleted, or listed with the `CREATE INDEX`, `DROP INDEX`, and `SHOW INDEXES` commands.
The privilege to do this can be granted with `GRANT CREATE INDEX`, `GRANT DROP INDEX`, and `GRANT SHOW INDEX` commands.
The privilege to do all three can be granted with `GRANT INDEX MANAGEMENT` command.




.Index management privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT { CREATE \| DROP \| SHOW } INDEX+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] { CREATE \| DROP \| SHOW } INDEX[ES]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Enables the specified roles to create, delete, or show indexes in the home database, specific database(s), or all databases.

|===



.Index management privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT INDEX+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] INDEX[ES] [MANAGEMENT]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Enables the specified roles to manage indexes in the home database, specific database(s), or all databases.

|===


For example, to grant the role `regularUsers` the ability to create indexes on the database `neo4j`, use:

[source, cypher, role=noplay]
----
GRANT CREATE INDEX ON DATABASE neo4j TO regularUsers
----


[[access-control-database-administration-constraints]]
== The `CONSTRAINT MANAGEMENT` privileges

Constraints can be created, deleted, or listed with the `CREATE CONSTRAINT`, `DROP CONSTRAINT` and `SHOW CONSTRAINTS` commands.
The privilege to do this can be granted with `GRANT CREATE CONSTRAINT`, `GRANT DROP CONSTRAINT`, `GRANT SHOW CONSTRAINT` commands.
The privilege to do all three can be granted with `GRANT CONSTRAINT MANAGEMENT` command.


.Constraint management privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT { CREATE \| DROP \| SHOW } CONSTRAINT+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] { CREATE \| DROP \| SHOW } CONSTRAINT[S]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Enables the specified roles to create, delete, or show constraints on the home database, specific database(s), or all databases.

|===


.Constraint management privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT CONSTRAINT+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] CONSTRAINT[S] [MANAGEMENT]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Enable the specified roles to manage constraints on the home database, specific database(s), or all databases.

|===


For example, to grant the role `regularUsers` the ability to create constraints on the database `neo4j`, use:

[source, cypher, role=noplay]
----
GRANT CREATE CONSTRAINT ON DATABASE neo4j TO regularUsers
----


[[access-control-database-administration-tokens]]
== The `NAME MANAGEMENT` privileges

The right to create new labels, relationship types, and property names is different from the right to create nodes, relationships, and properties.
The latter is managed using database `WRITE` privileges, while the former is managed using specific `+GRANT/DENY CREATE NEW ...+` commands for each type.


.Node label management privileges syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT CREATE NEW LABEL+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] CREATE NEW [NODE] LABEL[S]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Enables the specified roles to create new node labels in the home database, specific database(s), or all databases.

|===


.Relationship type management privileges syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT CREATE NEW TYPE+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] CREATE NEW [RELATIONSHIP] TYPE[S]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Enables the specified roles to create new relationship types in the home database, specific database(s), or all databases.

|===


.Property name management privileges syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT CREATE NEW NAME+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] CREATE NEW [PROPERTY] NAME[S]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Enables the specified roles to create new property names in the home database, specific database(s), or all databases.

|===


.Node label, relationship type, and property name privileges management syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT NAME+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] NAME [MANAGEMENT]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Enables the specified roles to create new labels, relationship types, and property names in the home database, specific database(s), or all databases.

|===


For example, to grant the role `regularUsers` the ability to create new properties on nodes or relationships on the database `neo4j`, use:

[source, cypher, role=noplay]
----
GRANT CREATE NEW PROPERTY NAME ON DATABASE neo4j TO regularUsers
----


[[access-control-database-administration-all]]
== Granting `ALL DATABASE PRIVILEGES`

The right to access a database, create and drop indexes and constraints and create new labels, relationship types or property names can be achieved with a single command:

[source, syntax, role="noheader"]
----
GRANT [IMMUTABLE] ALL [[DATABASE] PRIVILEGES]
  ON { HOME DATABASE | DATABASE[S] { * | name[, ...] } }
  TO role[, ...]
----

[NOTE]
====
Note that the privileges for starting and stopping all databases, and transaction management, are not included in the `ALL DATABASE PRIVILEGES` grant.
These privileges are associated with administrators while other database privileges are of use to domain and application developers.
====

For example, granting the abilities above on the database `neo4j` to the role `databaseAdminUsers` is done using the following query.

[source, cypher, role=noplay]
----
GRANT ALL DATABASE PRIVILEGES ON DATABASE neo4j TO databaseAdminUsers
----

The privileges granted can be seen using the `SHOW PRIVILEGES` command:

[source, cypher, role=noplay]
----
SHOW ROLE databaseAdminUsers PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ALL DATABASE PRIVILEGES ON DATABASE `neo4j` TO `databaseAdminUsers`"
a|Rows: 1
|===


[[access-control-database-administration-transaction]]
== Granting `TRANSACTION MANAGEMENT` privileges

The right to run the commands `SHOW TRANSACTIONS`, `TERMINATE TRANSACTIONS`, and the deprecated procedures `dbms.listTransactions`, `dbms.listQueries`, `dbms.killQuery`, `dbms.killQueries`, `dbms.killTransaction` and `dbms.killTransactions` is now managed through the `SHOW TRANSACTION` and `TERMINATE TRANSACTION` privileges.


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT SHOW TRANSACTION+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] SHOW TRANSACTION[S] [( { * \| user[, ...] } )]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Enables the specified roles to list transactions and queries for user(s) or all users in the home database, specific database(s), or all databases.

|===


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT TERMINATE TRANSACTION+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] TERMINATE TRANSACTION[S] [( { * \| user[, ...] } )]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Enables the specified roles to end running transactions and queries for user(s) or all users in the home database, specific database(s), or all databases.

|===


.Database privilege syntax
[cols="<15s,<85"]
|===

| Command
m| +GRANT TRANSACTION+

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT [IMMUTABLE] TRANSACTION [MANAGEMENT] [( { * \| user[, ...] } )]
  ON { HOME DATABASE \| DATABASE[S] { * \| name[, ...] } }
  TO role[, ...]
----

| Description
| Enables the specified roles to manage transactions and queries for user(s) or all users in the home database, specific database(s), or all databases.

|===


[NOTE]
====
Note that the `TRANSACTION MANAGEMENT` privileges are not included in the xref::administration/access-control/database-administration.adoc#access-control-database-administration-all[`ALL DATABASE PRIVILEGES`].
====

For example, to grant the role `regularUsers` the ability to list transactions for user `jake` on the database `neo4j`, use:

[source, cypher, role=noplay]
----
GRANT SHOW TRANSACTION (jake) ON DATABASE neo4j TO regularUsers
----
