:description: How to use Cypher to manage Neo4j DBMS administrative privileges.

////
[source, cypher, role=test-setup]
----
CREATE USER jake SET PASSWORD 'abcd1234' CHANGE NOT REQUIRED;
CREATE ROLE roleAdder IF NOT EXISTS;
CREATE ROLE roleNameModifier IF NOT EXISTS;
CREATE ROLE roleDropper IF NOT EXISTS;
CREATE ROLE roleAssigner IF NOT EXISTS;
CREATE ROLE roleRemover IF NOT EXISTS;
CREATE ROLE roleShower IF NOT EXISTS;
CREATE ROLE roleManager IF NOT EXISTS;
CREATE ROLE userAdder IF NOT EXISTS;
CREATE ROLE userNameModifier IF NOT EXISTS;
CREATE ROLE userModifier IF NOT EXISTS;
CREATE ROLE passwordModifier IF NOT EXISTS;
CREATE ROLE statusModifier IF NOT EXISTS;
CREATE ROLE userDropper IF NOT EXISTS;
CREATE ROLE userShower IF NOT EXISTS;
CREATE ROLE userManager IF NOT EXISTS;
CREATE ROLE userImpersonator IF NOT EXISTS;
CREATE ROLE databaseAdder IF NOT EXISTS;
CREATE ROLE compositeDatabaseAdder IF NOT EXISTS;
CREATE ROLE databaseDropper IF NOT EXISTS;
CREATE ROLE compositeDatabaseDropper IF NOT EXISTS;
CREATE ROLE databaseModifier IF NOT EXISTS;
CREATE ROLE accessModifier IF NOT EXISTS;
CREATE ROLE compositeDatabaseManager IF NOT EXISTS;
CREATE ROLE databaseManager IF NOT EXISTS;
CREATE ROLE aliasAdder IF NOT EXISTS;
CREATE ROLE aliasDropper IF NOT EXISTS;
CREATE ROLE aliasModifier IF NOT EXISTS;
CREATE ROLE aliasLister IF NOT EXISTS;
CREATE ROLE aliasManager IF NOT EXISTS;
CREATE ROLE privilegeShower IF NOT EXISTS;
CREATE ROLE privilegeAssigner IF NOT EXISTS;
CREATE ROLE privilegeRemover IF NOT EXISTS;
CREATE ROLE privilegeManager IF NOT EXISTS;
CREATE ROLE procedureExecutor IF NOT EXISTS;
CREATE ROLE deniedProcedureExecutor IF NOT EXISTS;
CREATE ROLE boostedProcedureExecutor IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor1 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor2 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor3 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor4 IF NOT EXISTS;
CREATE ROLE adminProcedureExecutor IF NOT EXISTS;
CREATE ROLE functionExecutor IF NOT EXISTS;
CREATE ROLE deniedFunctionExecutor IF NOT EXISTS;
CREATE ROLE boostedFunctionExecutor IF NOT EXISTS;
CREATE ROLE globbing1 IF NOT EXISTS;
CREATE ROLE globbing2 IF NOT EXISTS;
CREATE ROLE globbing3 IF NOT EXISTS;
CREATE ROLE globbing4 IF NOT EXISTS;
CREATE ROLE globbing5 IF NOT EXISTS;
CREATE ROLE globbing6 IF NOT EXISTS;
CREATE ROLE dbmsManager IF NOT EXISTS;
CREATE ROLE configurationViewer IF NOT EXISTS;
CREATE ROLE deniedConfigurationViewer IF NOT EXISTS;
----
////

[role=enterprise-edition aura-db-enterprise]
[[access-control-dbms-administration]]
= DBMS administration

[abstract]
--
This section explains how to use Cypher to manage Neo4j DBMS administrative privileges.
--

All DBMS privileges are relevant system-wide.
Like user management, they do not belong to one specific database or graph.
For more details on the differences between graphs, databases and the DBMS, refer to xref::introduction/cypher_neo4j.adoc[].

image::privileges_grant_and_deny_syntax_dbms_privileges.svg[title="Syntax of GRANT and DENY DBMS Privileges"]

image::privileges_hierarchy_dbms.svg[title="DBMS privileges hierarchy"]

The xref::administration/access-control/built-in-roles.adoc#access-control-built-in-roles-admin[`admin` role] has a number of built-in privileges.
These include:

* Create, delete, and modify databases and aliases.
* Change configuration parameters.
* Manage transactions.
* Manage users and roles.
* Manage sub-graph privileges.
* Manage procedure security.

To enable a user to perform these tasks, you can grant them the `admin` role, but it is also possible to make a custom role with a subset of these privileges.
All privileges are also assignable using Cypher commands.
For more details, see the following sections:

* xref::administration/access-control/dbms-administration.adoc#access-control-dbms-administration-role-management[Role management]
* xref::administration/access-control/dbms-administration.adoc#access-control-dbms-administration-user-management[User management]
* xref::administration/access-control/dbms-administration.adoc#access-control-dbms-administration-impersonation[Impersonation privileges management]
* xref::administration/access-control/dbms-administration.adoc#access-control-dbms-administration-database-management[Database management]
* xref::administration/access-control/dbms-administration.adoc#access-control-dbms-administration-alias-management[Alias management]
* xref::administration/access-control/dbms-administration.adoc#access-control-dbms-administration-privilege-management[Privilege management]
* xref::administration/access-control/database-administration.adoc#access-control-database-administration-transaction[Transaction management]
* xref::administration/access-control/dbms-administration.adoc#access-control-dbms-administration-execute[Procedure and user-defined function security]

[[access-control-dbms-administration-custom]]
== Using a custom role to manage DBMS privileges

In order to have an administrator role with a subset of privileges that includes all DBMS privileges, but not all database privileges, you can copy the `admin` role and revoke or deny the unwanted privileges.
A second option is to build a custom administrator from scratch by granting the wanted privileges instead.

As an example, an administrator role can be created to only manage users and roles by using the second option:

. First, create the new role:
+
[source, cypher, role=noplay]
----
CREATE ROLE usermanager
----
. Then grant the privilege to manage users:
+
[source, cypher, role=noplay]
----
GRANT USER MANAGEMENT ON DBMS TO usermanager
----
. And to manage roles:
+
[source, cypher, role=noplay]
----
GRANT ROLE MANAGEMENT ON DBMS TO usermanager
----

The resulting role has privileges that only allow user and role management.
To list all privileges for the role `usermanager` as commands, run this query:

[source, cypher, role=noplay]
----
SHOW ROLE usermanager PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ROLE MANAGEMENT ON DBMS TO `usermanager`"
|"GRANT USER MANAGEMENT ON DBMS TO `usermanager`"
a|Rows: 2
|===

Note that this role does not allow all DBMS capabilities.
For example, the role is missing privileges for management, creation and drop of databases as well as execution of `admin` procedures.
To create a more powerful administrator, you can grant a different set of privileges.

In the following example, a new administrator role is created to perform almost all DBMS capabilities, excluding database management.
However, the role still has some limited database capabilities, such as managing transactions:

. Again, start by creating a new role:
+
[source, cypher, role=noplay]
----
CREATE ROLE customAdministrator
----
. Then grant the privilege for all DBMS capabilities:
+
[source, cypher, role=noplay]
----
GRANT ALL DBMS PRIVILEGES ON DBMS TO customAdministrator
----
. And explicitly deny the privilege to manage databases and aliases:
+
[source, cypher, role=noplay]
----
DENY DATABASE MANAGEMENT ON DBMS TO customAdministrator
----
. Next, grant the transaction management privilege:
+
[source, cypher, role=noplay]
----
GRANT TRANSACTION MANAGEMENT (*) ON DATABASE * TO customAdministrator
----

The resulting role has privileges that include all DBMS privileges except creating, dropping, and modifying databases and aliases, as well as managing transactions.
Use the following query to list all privileges for the role `customAdministrator` as commands:

[source, cypher, role=noplay]
----
SHOW ROLE customAdministrator PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"DENY DATABASE MANAGEMENT ON DBMS TO `customAdministrator`"
|"GRANT ALL DBMS PRIVILEGES ON DBMS TO `customAdministrator`"
|"GRANT TRANSACTION MANAGEMENT (*) ON DATABASE * TO `customAdministrator`"
a|Rows: 3
|===


[[access-control-dbms-administration-role-management]]
== The DBMS `ROLE MANAGEMENT` privileges

The DBMS privileges for role management are assignable using Cypher administrative commands.
They can be granted, denied and revoked like other privileges.

[NOTE]
====
More details about the syntax descriptions can be found xref:administration/index.adoc#administration-syntax[here].
====

.Role management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] CREATE ROLE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create new roles.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] RENAME ROLE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to change the name of roles.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] DROP ROLE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to delete roles.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ASSIGN ROLE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to assign roles to users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] REMOVE ROLE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to remove roles from users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SHOW ROLE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to list roles.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ROLE MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create, delete, assign, remove, and list roles.

|===

The ability to add roles can be granted via the `CREATE ROLE` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT CREATE ROLE ON DBMS TO roleAdder
----

The resulting role has privileges that only allow adding roles.
List all privileges for the role `roleAdder` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE roleAdder PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT CREATE ROLE ON DBMS TO `roleAdder`"
a|Rows: 1
|===

The ability to rename roles can be granted via the `RENAME ROLE` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT RENAME ROLE ON DBMS TO roleNameModifier
----

The resulting role has privileges that only allow renaming roles.
List all privileges for the role `roleNameModifier` using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE roleNameModifier PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT RENAME ROLE ON DBMS TO `roleNameModifier`"
a|Rows: 1
|===

The ability to delete roles can be granted via the `DROP ROLE` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT DROP ROLE ON DBMS TO roleDropper
----

The resulting role has privileges that only allow deleting roles.
List all privileges for the role `roleDropper` by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE roleDropper PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT DROP ROLE ON DBMS TO `roleDropper`"
a|Rows: 1
|===

The ability to assign roles to users can be granted via the `ASSIGN ROLE` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT ASSIGN ROLE ON DBMS TO roleAssigner
----

The resulting role has privileges that only allow assigning/granting roles.
List all privileges for the role `roleAssigner` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE roleAssigner PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ASSIGN ROLE ON DBMS TO `roleAssigner`"
a|Rows: 1
|===

The ability to remove roles from users can be granted via the `REMOVE ROLE` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT REMOVE ROLE ON DBMS TO roleRemover
----

The resulting role has privileges that only allow removing/revoking roles.
List all privileges for the role `roleRemover` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE roleRemover PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT REMOVE ROLE ON DBMS TO `roleRemover`"
a|Rows: 1
|===

The ability to show roles can be granted via the `SHOW ROLE` privilege.
A role with this privilege is allowed to execute the `SHOW ROLES` and `SHOW POPULATED ROLES` administration commands.
For the `SHOW ROLES WITH USERS` and `SHOW POPULATED ROLES WITH USERS` administration commands, both this privilege and the `SHOW USER` privilege are required.
The following query shows an example of how to grant the `SHOW ROLE` privilege:

In order to use `SHOW ROLES WITH USERS` and `SHOW POPULATED ROLES WITH USERS` administration commands, both the `SHOW ROLE` and the `SHOW USER` privileges are required.
See an example of how to grant the `SHOW ROLE` privilege:

[source, cypher, role=noplay]
----
GRANT SHOW ROLE ON DBMS TO roleShower
----

The resulting role has privileges that only allow showing roles.
List all privileges for the role `roleShower` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE roleShower PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW ROLE ON DBMS TO `roleShower`"
a|Rows: 1
|===

The privileges to create, rename, delete, assign, remove, and list roles can be granted via the `ROLE MANAGEMENT` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT ROLE MANAGEMENT ON DBMS TO roleManager
----

The resulting role has all privileges to manage roles.
List all privileges for the role `roleManager` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE roleManager PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ROLE MANAGEMENT ON DBMS TO `roleManager`"
a|Rows: 1
|===


[[access-control-dbms-administration-user-management]]
== The DBMS `USER MANAGEMENT` privileges

The DBMS privileges for user management can be assigned using Cypher administrative commands.
They can be granted, denied and revoked like other privileges.

[NOTE]
====
More details about the syntax descriptions can be found xref:administration/index.adoc#administration-syntax[here].
====

.User management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] CREATE USER
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create new users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] RENAME USER
  ON DBMS
  TO role[, ...]
| Enables the specified roles to change the name of users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ALTER USER
  ON DBMS
  TO role[, ...]
| Enables the specified roles to modify users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SET PASSWORD[S]
  ON DBMS
  TO role[, ...]
| Enables the specified roles to modify users' passwords and whether those passwords must be changed upon first login.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SET USER HOME DATABASE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to modify users' home database.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SET USER STATUS
  ON DBMS
  TO role[, ...]
| Enables the specified roles to modify the account status of users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] DROP USER
  ON DBMS
  TO role[, ...]
| Enables the specified roles to delete users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SHOW USER
  ON DBMS
  TO role[, ...]
| Enables the specified roles to list users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] USER MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create, delete, modify, and list users.

|===

The ability to add users can be granted via the `CREATE USER` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT CREATE USER ON DBMS TO userAdder
----

The resulting role has privileges that only allow adding users.
List all privileges for the role `userAdder` as commands by using this query:

[source, cypher, role=noplay]
----
SHOW ROLE userAdder PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT CREATE USER ON DBMS TO `userAdder`"
a|Rows: 1
|===

The ability to rename users can be granted via the `RENAME USER` privilege.
The following query shows an example of this:

[source, cypher, role=noplay]
----
GRANT RENAME USER ON DBMS TO userNameModifier
----

The resulting role has privileges that only allow renaming users:

[source, cypher, role=noplay]
----
SHOW ROLE userNameModifier PRIVILEGES AS COMMANDS
----

Lists all privileges for role `userNameModifier`:

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT RENAME USER ON DBMS TO `userNameModifier`"
a|Rows: 1
|===

The ability to modify users can be granted via the `ALTER USER` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT ALTER USER ON DBMS TO userModifier
----

The resulting role has privileges that only allow modifying users.
List all privileges for the role `userModifier` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE userModifier PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ALTER USER ON DBMS TO `userModifier`"
a|Rows: 1
|===

A user that is granted the `ALTER USER` privilege is allowed to run the `ALTER USER` administration command with one or several of the `SET PASSWORD`, `SET PASSWORD CHANGE [NOT] REQUIRED` and `SET STATUS` parts:

[source, cypher, role=noplay]
----
ALTER USER jake SET PASSWORD 'verysecret' SET STATUS SUSPENDED
----

The ability to modify users' passwords and whether those passwords must be changed upon first login can be granted via the `SET PASSWORDS` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT SET PASSWORDS ON DBMS TO passwordModifier
----

The resulting role has privileges that only allow modifying users' passwords and whether those passwords must be changed upon first login.
List all privileges for the role `passwordModifier` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE passwordModifier PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SET PASSWORD ON DBMS TO `passwordModifier`"
a|Rows: 1
|===

A user that is granted the `SET PASSWORDS` privilege is allowed to run the `ALTER USER` administration command with one or both of the `SET PASSWORD` and `SET PASSWORD CHANGE [NOT] REQUIRED` parts:

[source, cypher, role=noplay]
----
ALTER USER jake SET PASSWORD 'abcd5678' CHANGE NOT REQUIRED
----

The ability to modify the account status of users can be granted via the `SET USER STATUS` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT SET USER STATUS ON DBMS TO statusModifier
----

The resulting role has privileges that only allow modifying the account status of users.
List all privileges for the role `statusModifier` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE statusModifier PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SET USER STATUS ON DBMS TO `statusModifier`"
a|Rows: 1
|===

A user that is granted the `SET USER STATUS` privilege is allowed to run the `ALTER USER` administration command with only the `SET STATUS` part:

[source, cypher, role=noplay]
----
ALTER USER jake SET STATUS ACTIVE
----

In order to be able to modify the home database of users, grant the `SET USER HOME DATABASE` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT SET USER HOME DATABASE ON DBMS TO statusModifier
----

The resulting role has privileges that only allow modifying the home database of users.
List all privileges for the role `statusModifier` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE statusModifier PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SET USER HOME DATABASE ON DBMS TO `statusModifier`"
|"GRANT SET USER STATUS ON DBMS TO `statusModifier`"
a|Rows: 2
|===

A user that is granted the `SET USER HOME DATABASE` privilege is allowed to run the `ALTER USER` administration command with only the `SET HOME DATABASE` or `REMOVE HOME DATABASE` part:

[source, cypher, role=noplay]
----
ALTER USER jake SET HOME DATABASE otherDb
----

[source, cypher, role=noplay]
----
ALTER USER jake REMOVE HOME DATABASE
----

[NOTE]
====
Note that the combination of the `SET PASSWORDS`, `SET USER STATUS`, and the `SET USER HOME DATABASE` privilege actions is equivalent to the `ALTER USER` privilege action.
====

The ability to delete users can be granted via the `DROP USER` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT DROP USER ON DBMS TO userDropper
----

The resulting role has privileges that only allow deleting users.
List all privileges for the role `userDropper` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE userDropper PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT DROP USER ON DBMS TO `userDropper`"
a|Rows: 1
|===

The ability to show users can be granted via the `SHOW USER` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT SHOW USER ON DBMS TO userShower
----

The resulting role has privileges that only allow showing users.
List all privileges for the role `userShower` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE userShower PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW USER ON DBMS TO `userShower`"
a|Rows: 1
|===

The privileges to create, rename, modify, delete, and list users can be granted via the `USER MANAGEMENT` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT USER MANAGEMENT ON DBMS TO userManager
----

The resulting role has all privileges to manage users.
List all privileges for the role `userManager` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE userManager PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW USER ON DBMS TO `userManager`"
a|Rows: 1
|===

[[access-control-dbms-administration-impersonation]]
== The DBMS `IMPERSONATE` privileges

The DBMS privileges for impersonation can be assigned through Cypher administrative commands.
They can be granted, denied, and revoked like other privileges.

Impersonation is the ability of a user to assume another user's roles (and therefore privileges), with the restriction of not being able to execute updating `admin` commands as the impersonated user (i.e. they would still be able to use `SHOW` commands).

The ability to impersonate users can be granted via the `IMPERSONATE` privilege.

[NOTE]
====
More details about the syntax descriptions can be found xref:administration/index.adoc#administration-syntax[here].
====

.Impersonation privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] IMPERSONATE [(*)]
    ON DBMS
    TO role[, ...]
| Enables the specified roles to impersonate any user.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] IMPERSONATE (user[, ...])
    ON DBMS
    TO role[, ...]
| Enables the specified roles to impersonate the specified users.

|===

The following query shows an example of this.
Note that `userImpersonator` must be an existing role in order to make this query work:

.Query
[source, cypher, role=noplay]
----
GRANT IMPERSONATE (*) ON DBMS TO userImpersonator
----

The resulting role has privileges that allow impersonating all users:

.Query
[source, cypher, role=noplay]
----
SHOW ROLE userImpersonator PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
| command
| "GRANT IMPERSONATE (*) ON DBMS TO `userImpersonator`"
a|Rows: 1
|===

It is also possible to deny and revoke that privilege.
See an example which shows of how the `userImpersonator` user would be able to impersonate all users, except `alice`:

.Query
[source, cypher, role=noplay]
----
DENY IMPERSONATE (alice) ON DBMS TO userImpersonator
----

To grant (or revoke) the permissions to impersonate a specific user or a subset of users, you can first list them with this query:

.Query
[source, cypher, role=noplay]
----
GRANT IMPERSONATE (alice, bob) ON DBMS TO userImpersonator
----


[[access-control-dbms-administration-database-management]]
== The DBMS `DATABASE MANAGEMENT` privileges

The DBMS privileges for database management can be assigned by using Cypher administrative commands.
They can be granted, denied and revoked like other privileges.

[NOTE]
====
More details about the syntax descriptions can be found xref:administration/index.adoc#administration-syntax[here].
====

.Database management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] CREATE DATABASE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create new standard databases and aliases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] DROP DATABASE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to delete standard databases and aliases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ALTER DATABASE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to modify standard databases and aliases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SET DATABASE ACCESS
  ON DBMS
  TO role[, ...]
| Enables the specified roles to modify access to standard databases.

| [source, syntax, role=noheader]
GRANT CREATE COMPOSITE DATABASE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create new composite databases.

| [source, syntax, role=noheader]
GRANT DROP COMPOSITE DATABASE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to delete composite databases.

| [source, syntax, role=noheader]
GRANT COMPOSITE DATABASE MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create and delete composite databases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] DATABASE MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create, delete, and modify databases and aliases.

|===


The ability to create standard databases and aliases can be granted via the `CREATE DATABASE` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT CREATE DATABASE ON DBMS TO databaseAdder
----

The resulting role has privileges that only allow creating standard databases and aliases.
List all privileges for the role `databaseAdder` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE databaseAdder PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT CREATE DATABASE ON DBMS TO `databaseAdder`"
a|Rows: 1
|===

The ability to create composite databases can be granted via the `CREATE COMPOSITE DATABASE` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT CREATE COMPOSITE DATABASE ON DBMS TO compositeDatabaseAdder
----

The resulting role has privileges that only allow creating composite databases.
List all privileges for the role `compositeDatabaseAdder` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE compositeDatabaseAdder PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT CREATE COMPOSITE DATABASE ON DBMS TO `compositeDatabaseAdder`"
a|Rows: 1
|===

The ability to delete standard databases and aliases can be granted via the `DROP DATABASE` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT DROP DATABASE ON DBMS TO databaseDropper
----

The resulting role has privileges that only allow deleting standard databases and aliases.
List all privileges for the role `databaseDropper` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE databaseDropper PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT DROP DATABASE ON DBMS TO `databaseDropper`"
a|Rows: 1
|===

The ability to delete composite databases can be granted via the `DROP COMPOSITE DATABASE` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT DROP COMPOSITE DATABASE ON DBMS TO compositeDatabaseDropper
----

The resulting role has privileges that only allow deleting composite databases.
List all privileges for the role `compositeDatabaseDropper` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE compositeDatabaseDropper PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT DROP COMPOSITE DATABASE ON DBMS TO `compositeDatabaseDropper`"
a|Rows: 1
|===

The ability to modify standard databases and aliases can be granted via the `ALTER DATABASE` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT ALTER DATABASE ON DBMS TO databaseModifier
----

The resulting role has privileges that only allow modifying standard databases and aliases.
List all privileges for the role `databaseModifier` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE databaseModifier PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ALTER DATABASE ON DBMS TO `databaseModifier`"
a|Rows: 1
|===

The ability to modify access to standard databases can be granted via the `SET DATABASE ACCESS` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT SET DATABASE ACCESS ON DBMS TO accessModifier
----

The resulting role has privileges that only allow modifying access to standard databases.
List all privileges for the role `accessModifier` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE accessModifier PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SET DATABASE ACCESS ON DBMS TO `accessModifier`"
a|Rows: 1
|===

The ability to create and delete composite databases can be granted via the `COMPOSITE DATABASE MANAGEMENT` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT COMPOSITE DATABASE MANAGEMENT ON DBMS TO compositeDatabaseManager
----

The resulting role has all privileges to manage composite databases.
List all privileges for the role `compositeDatabaseManager` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE compositeDatabaseManager PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT COMPOSITE DATABASE MANAGEMENT ON DBMS TO `compositeDatabaseManager`"
a|Rows: 1
|===

The ability to create, delete, and modify databases and aliases can be granted via the `DATABASE MANAGEMENT` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT DATABASE MANAGEMENT ON DBMS TO databaseManager
----

The resulting role has all privileges to manage standard and composite databases as well as aliases.
List all privileges for the role `databaseManager` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE databaseManager PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT DATABASE MANAGEMENT ON DBMS TO `databaseManager`"
a|Rows: 1
|===

[[access-control-dbms-administration-alias-management]]
== The DBMS `ALIAS MANAGEMENT` privileges

The DBMS privileges for alias management can be assigned by using Cypher administrative commands and can be applied to both local and remote aliases.
They can be granted, denied and revoked like other privileges.
It is also possible to manage aliases with xref::administration/access-control/dbms-administration.adoc#access-control-dbms-administration-database-management[database management commands].

[NOTE]
====
More details about the syntax descriptions can be found xref:administration/index.adoc#administration-syntax[here].
====

.Alias management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] CREATE ALIAS
ON DBMS
TO role[, ...]
| Enables the specified roles to create new aliases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] DROP ALIAS
ON DBMS
TO role[, ...]
| Enables the specified roles to delete aliases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ALTER ALIAS
ON DBMS
TO role[, ...]
| Enables the specified roles to modify aliases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SHOW ALIAS
ON DBMS
TO role[, ...]
| Enables the specified roles to list aliases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ALIAS MANAGEMENT
ON DBMS
TO role[, ...]
| Enables the specified roles to list, create, delete, and modify aliases.

|===

The ability to create aliases can be granted via the `CREATE ALIAS` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT CREATE ALIAS ON DBMS TO aliasAdder
----

The resulting role has privileges that only allow creating aliases.
List all privileges for the role `aliasAdder` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE aliasAdder PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT CREATE ALIAS ON DBMS TO `aliasAdder`"
a|Rows: 1
|===

The ability to delete aliases can be granted via the `DROP ALIAS` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT DROP ALIAS ON DBMS TO aliasDropper
----

The resulting role has privileges that only allow deleting aliases.
See all privileges for the role `aliasDropper` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE aliasDropper PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT DROP ALIAS ON DBMS TO `aliasDropper`"
a|Rows: 1
|===

The ability to modify aliases can be granted via the `ALTER ALIAS` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT ALTER ALIAS ON DBMS TO aliasModifier
----

The resulting role has privileges that only allow modifying aliases.
List all privileges for the role `aliasModifier` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE aliasModifier PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ALTER ALIAS ON DBMS TO `aliasModifier`"
a|Rows: 1
|===

The ability to list aliases can be granted via the `SHOW ALIAS` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT SHOW ALIAS ON DBMS TO aliasLister
----

The resulting role has privileges that only allow modifying aliases.
List all privileges for the role `aliasLister` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE aliasLister PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW ALIAS ON DBMS TO `aliasLister`"
a|Rows: 1
|===

The privileges to list, create, delete, and modify aliases can be granted via the `ALIAS MANAGEMENT` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT ALIAS MANAGEMENT ON DBMS TO aliasManager
----

The resulting role has all privileges to manage aliases.
List all privileges for the role `aliasManager` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE aliasManager PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ALIAS MANAGEMENT ON DBMS TO `aliasManager`"
a|Rows: 1
|===

[[access-control-dbms-administration-server-management]]
== The DBMS `SERVER MANAGEMENT` privileges

The DBMS privileges for server management can be assigned using Cypher administrative commands.
They can be granted, denied, and revoked like other privileges.

[NOTE]
====
More details about the syntax descriptions can be found xref:administration/index.adoc#administration-syntax[here].
====

.Server management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT SERVER MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to show, enable, rename, alter, reallocate, deallocate, and drop servers.

| [source, syntax, role=noheader]
GRANT SHOW SERVERS
  ON DBMS
  TO role[, ...]
| Enables the specfied roles to show servers.
|===


[[access-control-dbms-administration-privilege-management]]
== The DBMS `PRIVILEGE MANAGEMENT` privileges

The DBMS privileges for privilege management can be assigned by using Cypher administrative commands.
They can be granted, denied and revoked like other privileges.

[NOTE]
====
More details about the syntax descriptions can be found xref:administration/index.adoc#administration-syntax[here].
====

.Privilege management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SHOW PRIVILEGE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to list privileges.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ASSIGN PRIVILEGE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to assign privileges using the `GRANT` and `DENY` commands.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] REMOVE PRIVILEGE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to remove privileges using the `REVOKE` command.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] PRIVILEGE MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to list, assign, and remove privileges.
|===

The ability to list privileges can be granted via the `SHOW PRIVILEGE` privilege.

A user with this privilege is allowed to execute the `SHOW PRIVILEGES` and `SHOW ROLE roleName PRIVILEGES` administration commands.
To execute the `SHOW USER username PRIVILEGES` administration command, both this privilege and the `SHOW USER` privilege are required.
The following query shows an example of how to grant the `SHOW PRIVILEGE` privilege:

[source, cypher, role=noplay]
----
GRANT SHOW PRIVILEGE ON DBMS TO privilegeShower
----

The resulting role has privileges that only allow showing privileges.
List all privileges for the role `privilegeShower` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE privilegeShower PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW PRIVILEGE ON DBMS TO `privilegeShower`"
a|Rows: 1
|===

[NOTE]
====
Note that no specific privileges are required for showing the current user's privileges through the `SHOW USER _username_ PRIVILEGES` or `SHOW USER PRIVILEGES` commands.

In addition, note that if a non-native auth provider like LDAP is in use, `SHOW USER PRIVILEGES` will only work with a limited capacity by making it only possible for a user to show their own privileges.
Other users' privileges cannot be listed when using a non-native auth provider.
====

The ability to assign privileges to roles can be granted via the `ASSIGN PRIVILEGE` privilege.
A user with this privilege is allowed to execute `GRANT` and `DENY` administration commands.
See an example of how to grant this privilege:

[source, cypher, role=noplay]
----
GRANT ASSIGN PRIVILEGE ON DBMS TO privilegeAssigner
----

The resulting role has privileges that only allow assigning privileges.
List all privileges for the role `privilegeAssigner` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE privilegeAssigner PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ASSIGN PRIVILEGE ON DBMS TO `privilegeAssigner`"
a|Rows: 1
|===

The ability to remove privileges from roles can be granted via the `REMOVE PRIVILEGE` privilege.

A user with this privilege is allowed to execute `REVOKE` administration commands.
See an example of how to grant this privilege:

[source, cypher, role=noplay]
----
GRANT REMOVE PRIVILEGE ON DBMS TO privilegeRemover
----

The resulting role has privileges that only allow removing privileges.
List all privileges for the role `privilegeRemover` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE privilegeRemover PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT REMOVE PRIVILEGE ON DBMS TO `privilegeRemover`"
a|Rows: 1
|===

The privileges to list, assign, and remove privileges can be granted via the `PRIVILEGE MANAGEMENT` privilege.
See an example:

[source, cypher, role=noplay]
----
GRANT PRIVILEGE MANAGEMENT ON DBMS TO privilegeManager
----

The resulting role has all privileges to manage privileges.
List all privileges for the role `privilegeManager` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE privilegeManager PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT PRIVILEGE MANAGEMENT ON DBMS TO `privilegeManager`"
a|Rows: 1
|===


[[access-control-dbms-administration-execute]]
== The DBMS `EXECUTE` privileges

The DBMS privileges for procedure and user defined function execution can be assigned by using Cypher administrative commands.
They can be granted, denied and revoked like other privileges.

[NOTE]
====
More details about the syntax descriptions can be found xref:administration/index.adoc#administration-syntax[here].
====

.Execute privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command
| Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] EXECUTE PROCEDURE[S] name-globbing[, ...]
  ON DBMS
  TO role[, ...]
| Enables the specified roles to execute the given procedures.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] EXECUTE BOOSTED PROCEDURE[S] name-globbing[, ...]
  ON DBMS
  TO role[, ...]
| Enables the specified roles to execute the given procedures with elevated privileges.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] EXECUTE ADMIN[ISTRATOR] PROCEDURES
  ON DBMS
  TO role[, ...]
| Enables the specified roles to execute procedures annotated with `@Admin`. The procedures are executed with elevated privileges.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] EXECUTE [USER [DEFINED]] FUNCTION[S] name-globbing[, ...]
  ON DBMS
  TO role[, ...]
| Enables the specified roles to execute the given user defined functions.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] EXECUTE BOOSTED [USER [DEFINED]] FUNCTION[S] name-globbing[, ...]
  ON DBMS
  TO role[, ...]
| Enables the specified roles to execute the given user defined functions with elevated privileges.
|===

The `EXECUTE BOOSTED` privileges replace the `dbms.security.procedures.default_allowed` and `dbms.security.procedures.roles` configuration parameters for procedures and user defined functions.
The configuration parameters are still honored as a set of temporary privileges.
These cannot be revoked, but will be updated on each restart with the current configuration values.


[[access-control-execute-procedure]]
=== The `EXECUTE PROCEDURE` privilege

The ability to execute a procedure can be granted via the `EXECUTE PROCEDURE` privilege.
A role with this privilege is allowed to execute the procedures matched by the xref::administration/access-control/dbms-administration.adoc#access-control-name-globbing[name-globbing].
The following query shows an example of how to grant this privilege:

[source, cypher, role=noplay]
----
GRANT EXECUTE PROCEDURE db.schema.* ON DBMS TO procedureExecutor
----

Users with the role `procedureExecutor` can then run any procedure in the `db.schema` namespace.
The procedure is run using the user's own privileges.

The resulting role has privileges that only allow executing procedures in the `db.schema` namespace.
List all privileges for the role `procedureExecutor` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE procedureExecutor PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT EXECUTE PROCEDURE db.schema.* ON DBMS TO `procedureExecutor`"
a|Rows: 1
|===

In order to allow the execution of all but only a few procedures, you can grant `EXECUTE PROCEDURES *` and deny the unwanted procedures.
For example, the following queries allow the execution of all procedures, except those starting with `dbms.killTransaction`:

[source, cypher, role=noplay]
----
GRANT EXECUTE PROCEDURE * ON DBMS TO deniedProcedureExecutor
----

[source, cypher, role=noplay]
----
DENY EXECUTE PROCEDURE dbms.killTransaction* ON DBMS TO deniedProcedureExecutor
----

The resulting role has privileges that only allow executing all procedures except those starting with `dbms.killTransaction`.
List all privileges for the role `deniedProcedureExecutor` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE deniedProcedureExecutor PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"DENY EXECUTE PROCEDURE dbms.killTransaction* ON DBMS TO `deniedProcedureExecutor`"
|"GRANT EXECUTE PROCEDURE * ON DBMS TO `deniedProcedureExecutor`"
a|Rows: 2
|===

Both the `dbms.killTransaction` and the `dbms.killTransactions` procedures are blocked here, as well as any other procedures starting with `dbms.killTransaction`.


[[access-control-execute-boosted-procedure]]
=== The `EXECUTE BOOSTED PROCEDURE` privilege

The ability to execute a procedure with elevated privileges can be granted via the `EXECUTE BOOSTED PROCEDURE` privilege.
A user with this privilege is allowed to execute the procedures matched by the xref::administration/access-control/dbms-administration.adoc#access-control-name-globbing[name-globbing] without the execution being restricted to their other privileges.

There is no need to grant an individual `EXECUTE PROCEDURE` privilege for the procedures either, as granting the `EXECUTE BOOSTED PROCEDURE` includes an implicit `EXECUTE PROCEDURE` grant for them.
A denied `EXECUTE PROCEDURE` still denies executing the procedure.
The following query shows an example of how to grant this privilege:

[source, cypher, role=noplay]
----
GRANT EXECUTE PROCEDURE * ON DBMS TO boostedProcedureExecutor;
GRANT EXECUTE BOOSTED PROCEDURE db.labels, db.relationshipTypes ON DBMS TO boostedProcedureExecutor
----

Users with the role `boostedProcedureExecutor` can thus run the `db.labels` and the `db.relationshipTypes` procedures with full privileges.
Now they can see everything on the graph and not just the labels and types that the user has `TRAVERSE` privilege on.

The resulting role has privileges that only allow executing the `db.labels` and the `db.relationshipTypes` procedures, but with elevated execution.
List all privileges for the role `boostedProcedureExecutor` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE boostedProcedureExecutor PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT EXECUTE PROCEDURE * ON DBMS TO `boostedProcedureExecutor`"
|"GRANT EXECUTE BOOSTED PROCEDURE db.labels ON DBMS TO `boostedProcedureExecutor`"
|"GRANT EXECUTE BOOSTED PROCEDURE db.relationshipTypes ON DBMS TO `boostedProcedureExecutor`"
a|Rows: 3
|===

Granting the `EXECUTE BOOSTED PROCEDURE` privilege on its own allows the procedure to be both executed (due to the implicit `EXECUTE PROCEDURE` grant) and proceed with elevated privileges.
A denied `EXECUTE BOOSTED PROCEDURE` on its own behaves slightly differently: it only denies the elevation and not the execution of the procedure.
However, a role with both a granted `EXECUTE BOOSTED PROCEDURE` and a denied `EXECUTE BOOSTED PROCEDURE` will deny the execution as well.
This is explained through the following examples:

.Grant `EXECUTE PROCEDURE` and deny `EXECUTE BOOSTED PROCEDURE`
[example]
====
[source, cypher, role=noplay]
----
GRANT EXECUTE PROCEDURE * ON DBMS TO deniedBoostedProcedureExecutor1
----

[source, cypher, role=noplay]
----
DENY EXECUTE BOOSTED PROCEDURE db.labels ON DBMS TO deniedBoostedProcedureExecutor1
----

The resulting role has privileges that allow the execution of all procedures using the user's own privileges.
It also prevents the `db.labels` procedure from being elevated.
Still, the denied `EXECUTE BOOSTED PROCEDURE` does not block execution of `db.labels`.

To list all privileges for role `deniedBoostedProcedureExecutor1` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE deniedBoostedProcedureExecutor1 PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"DENY EXECUTE BOOSTED PROCEDURE db.labels ON DBMS TO `deniedBoostedProcedureExecutor1`"
|"GRANT EXECUTE PROCEDURE * ON DBMS TO `deniedBoostedProcedureExecutor1`"
a|Rows: 2
|===
====

.Grant `EXECUTE BOOSTED PROCEDURE` and deny `EXECUTE PROCEDURE`
[example]
====
[source, cypher, role=noplay]
----
GRANT EXECUTE BOOSTED PROCEDURE * ON DBMS TO deniedBoostedProcedureExecutor2
----

[source, cypher, role=noplay]
----
DENY EXECUTE PROCEDURE db.labels ON DBMS TO deniedBoostedProcedureExecutor2
----

The resulting role has privileges that allow executing all procedures with elevated privileges except `db.labels`, which is not allowed to be executed at all.
List all privileges for the role `deniedBoostedProcedureExecutor2` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE deniedBoostedProcedureExecutor2 PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"DENY EXECUTE PROCEDURE db.labels ON DBMS TO `deniedBoostedProcedureExecutor2`"
|"GRANT EXECUTE BOOSTED PROCEDURE * ON DBMS TO `deniedBoostedProcedureExecutor2`"
a|Rows: 2
|===
====

.Grant `EXECUTE BOOSTED PROCEDURE` and deny `EXECUTE BOOSTED PROCEDURE`
[example]
====
[source, cypher, role=noplay]
----
GRANT EXECUTE BOOSTED PROCEDURE * ON DBMS TO deniedBoostedProcedureExecutor3
----

[source, cypher, role=noplay]
----
DENY EXECUTE BOOSTED PROCEDURE db.labels ON DBMS TO deniedBoostedProcedureExecutor3
----

The resulting role has privileges that allow executing all procedures with elevated privileges except `db.labels`, which is not allowed to be executed at all.
List all privileges for the role `deniedBoostedProcedureExecutor3` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE deniedBoostedProcedureExecutor3 PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"DENY EXECUTE BOOSTED PROCEDURE db.labels ON DBMS TO `deniedBoostedProcedureExecutor3`"
|"GRANT EXECUTE BOOSTED PROCEDURE * ON DBMS TO `deniedBoostedProcedureExecutor3`"
a|Rows: 2
|===
====

.Grant `EXECUTE PROCEDURE` and `EXECUTE BOOSTED PROCEDURE` and deny `EXECUTE BOOSTED PROCEDURE`
[example]
====
[source, cypher, role=noplay]
----
GRANT EXECUTE PROCEDURE db.labels ON DBMS TO deniedBoostedProcedureExecutor4
----

[source, cypher, role=noplay]
----
GRANT EXECUTE BOOSTED PROCEDURE * ON DBMS TO deniedBoostedProcedureExecutor4
----

[source, cypher, role=noplay]
----
DENY EXECUTE BOOSTED PROCEDURE db.labels ON DBMS TO deniedBoostedProcedureExecutor4
----

The resulting role has privileges that allow executing all procedures with elevated privileges except the `db.labels` procedure, which is only allowed to execute using the user's own privileges.
List all privileges for the role `deniedBoostedProcedureExecutor4` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE deniedBoostedProcedureExecutor4 PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"DENY EXECUTE BOOSTED PROCEDURE db.labels ON DBMS TO `deniedBoostedProcedureExecutor4`"
|"GRANT EXECUTE BOOSTED PROCEDURE * ON DBMS TO `deniedBoostedProcedureExecutor4`"
|"GRANT EXECUTE PROCEDURE db.labels ON DBMS TO `deniedBoostedProcedureExecutor4`"
a|Rows: 3
|===
====

.How would the privileges from examples 1 to 4 affect the output of a procedure?
[example]
====
Assume there is a procedure called `myProc`.

This procedure gives the result `A` and `B` for a user with `EXECUTE PROCEDURE` privilege and `A`, `B` and `C` for a user with `EXECUTE BOOSTED PROCEDURE` privilege.

Now, adapt the privileges from examples 1 to 4 to be applied to this procedure and show what is returned.
With the privileges from example 1, granted `EXECUTE PROCEDURE *` and denied `EXECUTE BOOSTED PROCEDURE myProc`, the `myProc` procedure returns the result `A` and `B`.

With the privileges from example 2, granted `EXECUTE BOOSTED PROCEDURE *` and denied `EXECUTE PROCEDURE myProc`, execution of the `myProc` procedure is not allowed.

With the privileges from example 3, granted `EXECUTE BOOSTED PROCEDURE *` and denied `EXECUTE BOOSTED PROCEDURE myProc`, execution of the `myProc` procedure is not allowed.

For comparison, when granted:

* `EXECUTE PROCEDURE myProc`: the `myProc` procedure returns the result `A` and `B`.
* `EXECUTE BOOSTED PROCEDURE myProc`: execution of the `myProc` procedure is not allowed.
* `EXECUTE PROCEDURE myProc` and `EXECUTE BOOSTED PROCEDURE myProc`: the `myProc` procedure returns the result `A`, `B`, and `C`.

For comparison, when only `EXECUTE BOOSTED PROCEDURE myProc` is granted, the `myProc` procedure returns the result `A`, `B`, and `C`; without the need for granting of the `EXECUTE PROCEDURE myProc` privilege.
====


[[access-control-admin-procedure]]
=== The `EXECUTE ADMIN PROCEDURE` privilege

The ability to execute admin procedures (annotated with `@Admin`) can be granted via the `EXECUTE ADMIN PROCEDURES` privilege.
This privilege is equivalent to granting the xref::administration/access-control/dbms-administration.adoc#access-control-execute-boosted-procedure[`EXECUTE BOOSTED PROCEDURE` privilege] on each of the admin procedures.
Any newly added `admin` procedure is automatically included in this privilege.
The following query shows an example of how to grant this privilege:

[source, cypher, role=noplay]
----
GRANT EXECUTE ADMIN PROCEDURES ON DBMS TO adminProcedureExecutor
----

Users with the role `adminProcedureExecutor` can then run any `admin` procedure with elevated privileges.

The resulting role has privileges that allow executing all admin procedures.
List all privileges for the role `adminProcedureExecutor` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE adminProcedureExecutor PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT EXECUTE ADMIN PROCEDURES ON DBMS TO `adminProcedureExecutor`"
a|Rows: 1
|===

In order to compare this with the `EXECUTE PROCEDURE` and `EXECUTE BOOSTED PROCEDURE` privileges, revisit the `myProc` procedure, but this time as an `admin` procedure, which will give the result `A`, `B` and `C` when allowed to execute.

By starting with a user only granted with the `EXECUTE PROCEDURE myProc` privilege, execution of the `myProc` procedure is not allowed.

However, for a user granted with the `EXECUTE BOOSTED PROCEDURE myProc` or `EXECUTE ADMIN PROCEDURES` privileges, the `myProc` procedure returns the result `A`, `B` and `C`.

Any denied `EXECUTE` privilege results in the procedure not being allowed to be executed.
In this case, it does not matter whether `EXECUTE PROCEDURE`, `EXECUTE BOOSTED PROCEDURE` or `EXECUTE ADMIN PROCEDURES` is being denied.


[[access-control-execute-user-defined-function]]
=== The `EXECUTE USER DEFINED FUNCTION` privilege

//EXECUTE [USER [DEFINED]] FUNCTION[S]
The ability to execute a user-defined function (UDF) can be granted via the `EXECUTE USER DEFINED FUNCTION` privilege.
A role with this privilege is allowed to execute the UDFs matched by the xref::administration/access-control/dbms-administration.adoc#access-control-name-globbing[name-globbing].

[IMPORTANT]
====
The `EXECUTE USER DEFINED FUNCTION` privilege does not apply to built-in functions, which are always executable.
====

.Execute user-defined function
======
The following query shows an example of how to grant this privilege:

[source,cypher,role=noplay]
----
GRANT EXECUTE USER DEFINED FUNCTION apoc.coll.* ON DBMS TO functionExecutor
----

Or in short form:

[source,cypher,role=noplay]
----
GRANT EXECUTE FUNCTION apoc.coll.* ON DBMS TO functionExecutor
----

Users with the role `functionExecutor` can thus run any UDF in the `apoc.coll` namespace.
The function here is run using the user's own privileges.

The resulting role has privileges that only allow executing UDFs in the `apoc.coll` namespace.
List all privileges for the role `functionExecutor` as commands by using the following query:

[source,cypher,role=noplay]
----
SHOW ROLE functionExecutor PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT EXECUTE FUNCTION apoc.coll.* ON DBMS TO `functionExecutor`"
a|Rows: 1
|===
======

To allow the execution of all but a few UDFs, you can grant `+EXECUTE USER DEFINED FUNCTIONS *+` and deny the unwanted functions.

.Execute user-defined functions
======
The following queries allow the execution of all UDFs except those starting with `apoc.any.prop`:

[source, cypher, role=noplay]
----
GRANT EXECUTE USER DEFINED FUNCTIONS * ON DBMS TO deniedFunctionExecutor
----

[source, cypher, role=noplay]
----
DENY EXECUTE USER DEFINED FUNCTION apoc.any.prop* ON DBMS TO deniedFunctionExecutor
----

Or in short form:

[source, cypher, role=noplay]
----
GRANT EXECUTE FUNCTIONS * ON DBMS TO deniedFunctionExecutor
----

[source, cypher, role=noplay]
----
DENY EXECUTE FUNCTION apoc.any.prop* ON DBMS TO deniedFunctionExecutor
----

The resulting role has privileges that only allow the execution of all procedures except those starting with `apoc.any.prop`.
List all privileges for the role `deniedFunctionExecutor` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE deniedFunctionExecutor PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"DENY EXECUTE FUNCTION apoc.any.prop* ON DBMS TO `deniedFunctionExecutor`"
|"GRANT EXECUTE FUNCTION * ON DBMS TO `deniedFunctionExecutor`"
a|Rows: 2
|===

The `apoc.any.property` and `apoc.any.properties` are blocked, as well as any other procedures starting with `apoc.any.prop`.
======

[[access-control-execute-boosted-user-defined-function]]
=== The `EXECUTE BOOSTED USER DEFINED FUNCTION` privilege

//EXECUTE BOOSTED [USER [DEFINED]] FUNCTION[S]
The ability to execute a user-defined function (UDF) with elevated privileges can be granted via the `EXECUTE BOOSTED USER DEFINED FUNCTION` privilege.
A user with this privilege is allowed to execute the UDFs matched by the xref::administration/access-control/dbms-administration.adoc#access-control-name-globbing[name-globbing] without the execution being restricted to their other privileges.

There is no need to grant an individual `EXECUTE USER DEFINED FUNCTION` privilege for the functions, as granting `EXECUTE BOOSTED USER DEFINED FUNCTION` includes an implicit `EXECUTE USER DEFINED FUNCTION` grant.
However, a denied `EXECUTE USER DEFINED FUNCTION` still prevents the function to be executed.

[IMPORTANT]
====
The `EXECUTE BOOSTED USER DEFINED FUNCTION` privilege does not apply to built-in functions, as they have no concept of elevated privileges.
====

Granting `EXECUTE BOOSTED USER DEFINED FUNCTION` on its own allows the UDF to be both executed (because of the implicit `EXECUTE USER DEFINED FUNCTION` grant) and gives it elevated privileges during the execution.
A denied `EXECUTE BOOSTED USER DEFINED FUNCTION` on its own behaves slightly differently: it only denies the elevation and not the execution of the UDF.
However, a role with only a granted `EXECUTE BOOSTED USER DEFINED FUNCTION` and a denied `EXECUTE BOOSTED USER DEFINED FUNCTION` prevents the execution to be performed as well.
This is the same behavior as for the xref::administration/access-control/dbms-administration.adoc#access-control-execute-boosted-procedure[`EXECUTE BOOSTED PROCEDURE` privilege].

.Execute boosted user-defined function
======
The following query shows an example of how to grant the `EXECUTE BOOSTED USER DEFINED FUNCTION` privilege:

[source,cypher,role=noplay]
----
GRANT EXECUTE USER DEFINED FUNCTION * ON DBMS TO boostedFunctionExecutor
GRANT EXECUTE BOOSTED USER DEFINED FUNCTION apoc.any.properties ON DBMS TO boostedFunctionExecutor
----

Or in short form:

[source,cypher,role=noplay]
----
GRANT EXECUTE FUNCTION * ON DBMS TO boostedFunctionExecutor
GRANT EXECUTE BOOSTED FUNCTION apoc.any.properties ON DBMS TO boostedFunctionExecutor
----

Users with the role `boostedFunctionExecutor` can thus run `apoc.any.properties` with full privileges and see every property on the node/relationship, not just the properties that the user has `READ` privilege on.

The resulting role has privileges that only allow executing of the UDF `apoc.any.properties`, but with elevated execution.
List all privileges for the role `boostedFunctionExecutor` as commands by using the following query:

[source,cypher,role=noplay]
----
SHOW ROLE boostedFunctionExecutor PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer",width="100%",cols="m"]
|===
|command
|"GRANT EXECUTE FUNCTION * ON DBMS TO `boostedFunctionExecutor`"
|"GRANT EXECUTE BOOSTED FUNCTION apoc.any.properties ON DBMS TO `boostedFunctionExecutor`"
a|Rows: 2
|===
======


[[access-control-dbms-administration-setting]]
== The DBMS `SETTING` privileges

_This feature was introduced in Neo4j 5.6._

The ability to show configuration settings can be granted via the `SHOW SETTING` privilege.
A role with this privilege is allowed to query the configuration settings matched by the xref::administration/access-control/dbms-administration.adoc#access-control-name-globbing[name-globbing].


[NOTE]
====
More details about the syntax descriptions can be found xref:administration/index.adoc#administration-syntax[here].
====

.Setting privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command
| Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SHOW SETTING[S] name-globbing[, ...]
  ON DBMS
  TO role[, ...]
| Enables the specified roles to query given configuration settings.
|===

The following query shows an example of how to grant this privilege:

[source, cypher, role=noplay]
----
GRANT SHOW SETTING server.bolt.* ON DBMS TO configurationViewer
----

Users with the role `configurationViewer` can then query any setting in the `server.bolt` namespace.

The updated role `configurationViewer` has privileges that only allow querying settings in the `server.bolt` namespace.
List all privileges for the role `configurationViewer` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE configurationViewer PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW SETTING server.bolt.* ON DBMS TO `configurationViewer`"
a|Rows: 1
|===

To deny a specific setting from a role, first grant `SHOW SETTINGS *`, and then deny the unwanted setting.
For example, the following queries allow the querying of all settings, except those starting with `dbms.security`:

[source, cypher, role=noplay]
----
GRANT SHOW SETTINGS * ON DBMS TO deniedConfigurationViewer
----

[source, cypher, role=noplay]
----
DENY SHOW SETTING dbms.security* ON DBMS TO deniedConfigurationViewer
----

The resulting role has privileges that allow querying all settings except those starting with `dbms.security`.
List all privileges for the role `deniedConfigurationViewer` as commands by using the following query:

[source, cypher, role=noplay]
----
SHOW ROLE deniedConfigurationViewer PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"DENY SHOW SETTING dbms.security* ON DBMS TO `deniedConfigurationViewer`"
|"GRANT SHOW SETTING * ON DBMS TO `deniedConfigurationViewer`"
a|Rows: 2
|===

As the query result shows, access to any setting starting with `dbms.security` are blocked, but the rest can still be queried.


[[access-control-dbms-administration-all]]
== Granting `ALL DBMS PRIVILEGES`

The right to perform the following privileges can be achieved with a single command:

* Create, drop, assign, remove, and show roles.
* Create, alter, drop, show, and impersonate users.
* Create, alter, and drop databases and aliases.
* Enable, alter, rename, reallocate, deallocate, and drop servers
* Show, assign, and remove privileges.
* Execute all procedures with elevated privileges.
* Execute all user defined functions with elevated privileges.
* Show all configuration settings.

[NOTE]
====
More details about the syntax descriptions can be found xref:administration/index.adoc#administration-syntax[here].
====

[source, syntax, role=noheader]
----
GRANT [IMMUTABLE] ALL [[DBMS] PRIVILEGES]
    ON DBMS
    TO role[, ...]
----

For example, to grant the role `dbmsManager` the abilities above, use the following query:

[source, cypher, role=noplay]
----
GRANT ALL DBMS PRIVILEGES ON DBMS TO dbmsManager
----

The privileges granted can be seen using the `SHOW PRIVILEGES` command:

[source, cypher, role=noplay]
----
SHOW ROLE dbmsManager PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ALL DBMS PRIVILEGES ON DBMS TO `dbmsManager`"
a|Rows: 1
|===

[[access-control-name-globbing]]
== Name-globbing for procedures, user-defined functions, and settings

The name-globbing for procedure, user defined function, and setting names is a simplified version of globbing for filename expansions.
It only allows two wildcard characters: `+*+` and `?`, which are used for multiple and single character matches.
In this case, `+*+` means 0 or more characters and `?` matches exactly one character.

[NOTE]
====
The name-globbing is subject to the xref::syntax/naming.adoc[standard Cypher restrictions on valid identifiers],
with the exception that it may include dots, stars, and question marks without the need for escaping using backticks.

Each part of the name-globbing separated by dots may be individually escaped.
For example, `++mine.`procedureWith%`++` is allowed, but not `++mine.procedure`With%`++`.
Also, note that wildcard characters behave as wildcards even when escaped.
For example, using `++`*`++` is equivalent to using `+*+`, and thus allows executing all functions or procedures and not only the procedure or function named `+*+`.
====

Given the following list of procedures:

* `mine.public.exampleProcedure`
* `mine.public.exampleProcedure1`
* `mine.public.exampleProcedure2`
* `mine.public.with#SpecialCharacters`
* `mine.private.exampleProcedure`
* `mine.private.exampleProcedure1`
* `mine.private.exampleProcedure2`
* `mine.private.with#SpecialCharacters`
* `your.exampleProcedure`

The following examples demonstrate how name-globbing patterns can be used in controlling access to procedures.
Note that the same rules apply to user-defined functions and settings.

[source, cypher, role=noplay]
----
GRANT EXECUTE PROCEDURE * ON DBMS TO globbing1
----

Users with the role `globbing1` can run all the procedures.

[source, cypher, role=noplay]
----
GRANT EXECUTE PROCEDURE mine.*.exampleProcedure ON DBMS TO globbing2
----

Users with the role `globbing2` can run procedures `mine.public.exampleProcedure` and `mine.private.exampleProcedure`, but no other procedures.

[source, cypher, role=noplay]
----
GRANT EXECUTE PROCEDURE mine.*.exampleProcedure? ON DBMS TO globbing3
----

Users with the role `globbing3` can run procedures `mine.public.exampleProcedure1`, `mine.private.exampleProcedure1`, and `mine.private.exampleProcedure2`, but no other procedures.

[source, cypher, role=noplay]
----
GRANT EXECUTE PROCEDURE *.exampleProcedure ON DBMS TO globbing4
----

Users with the role `globbing4` can run procedures `your.exampleProcedure`, `mine.public.exampleProcedure`, and `mine.private.exampleProcedure`, but no other procedures.

[source, cypher, role=noplay]
----
GRANT EXECUTE PROCEDURE mine.public.exampleProcedure* ON DBMS TO globbing5
----

Users with the role `globbing5` can run procedures `mine.public.exampleProcedure`, `mine.public.exampleProcedure1` and `mine.public.exampleProcedure42`, but no other procedures.

[source, cypher, role=noplay]
----
GRANT EXECUTE PROCEDURE `mine.public.with#*Characters`, mine.private.`with#Spec???Characters` ON DBMS TO globbing6
----

Users with the role `globbing6` can run procedures `mine.public.with#SpecialCharacters`, and `mine.private.with#SpecialCharacters`, but no other procedures.

[NOTE]
====
The name-globbing may be fully or partially escaped.
Both `+*+` and `+?+` are interpreted as wildcards in both cases.
====

