:description: Neo4j role-based access control and fine-grained security.

[[access-control]]
= Access control

== Overview 

Neo4j has a complex security model stored in the system graph, which is maintained on a special database called the `system` database.
All administrative commands need to be executed against the `system` database.
When connected to the DBMS over link:{neo4j-docs-base-uri}/operations-manual/{page-version}/configuration/connectors[Bolt], administrative commands are automatically routed to the `system` database.
For more information on how to manage multiple databases, refer to the section on xref::administration/databases.adoc[administering databases].

_Role-based access control_ was introduced in Neo4j 3.1.
Since then, it has been possible to create users and assign them to roles to control whether users can read, write and administer the database.
In Neo4j 4.0 this model was enhanced significantly with the addition of _privileges_, which are the underlying access-control rules by which the users rights are defined.

The original built-in roles still exist with almost the exact same access rights, but they are no-longer statically defined (see xref::administration/access-control/built-in-roles.adoc[Built-in roles]).
Instead, they are defined in terms of their underlying _privileges_, and they can be modified by adding or removing these access rights.

In addition, any newly created roles can be assigned to any combination of _privileges_, so that you may set specific access controls for them.
Another new major capability is the _sub-graph_ access control, through which read access to the graph can be limited to specific combinations of labels, relationship types, and properties.

== Categories of access control

More details about specific categories of access control can be found in the following sections:

* xref:administration/access-control/manage-users.adoc[]
* xref:administration/access-control/manage-roles.adoc[]
* xref:administration/access-control/manage-privileges.adoc[]
* xref:administration/access-control/built-in-roles.adoc[]
* xref:administration/access-control/privileges-reads.adoc[]
* xref:administration/access-control/privileges-writes.adoc[]
* xref:administration/access-control/database-administration.adoc[]
* xref:administration/access-control/dbms-administration.adoc[]
* xref:administration/access-control/load-privileges.adoc[]
* xref:administration/access-control/limitations.adoc[]
* xref:administration/access-control/privileges-immutable.adoc[]

