[[cypher-lists]]
= Lists
:description: Cypher has comprehensive support for lists. 

* xref:syntax/lists.adoc#cypher-lists-general[Lists in general]
* xref:syntax/lists.adoc#cypher-list-comprehension[List comprehension]
* xref:syntax/lists.adoc#cypher-pattern-comprehension[Pattern comprehension]

[NOTE]
====
Information regarding operators such as list concatenation (`+`), element existence checking (`IN`) and access (`[]`) can be found xref:syntax/operators.adoc#query-operators-list[here].
The behavior of the `IN` and `[]` operators with respect to `null` is detailed xref:syntax/working-with-null.adoc[here].


====

[[cypher-lists-general]]
== Lists in general

A literal list is created by using brackets and separating the elements in the list with commas.


.Query
[source, cypher]
----
RETURN [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] AS list
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +list+
| +[0,1,2,3,4,5,6,7,8,9]+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE (keanu:Person {name: 'Keanu Reeves'}),
(johnnymnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
(somethingsgottagive:Movie {title: 'Somethings Gotta Give', released: 2003}),
(thematrixrevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
(thematrixreloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
(thereplacements:Movie {title: 'The Replacements', released: 2000}),
(thematrix:Movie {title: 'The Matrix', released: 1999}),
(thedevilsadvocate:Movie {title: 'The Devils Advocate', released: 1997}),

(keanu)-[:ACTED_IN]->(johnnymnemonic),
(keanu)-[:ACTED_IN]->(somethingsgottagive),
(keanu)-[:ACTED_IN]->(thematrixrevolutions),
(keanu)-[:ACTED_IN]->(thematrixreloaded),
(keanu)-[:ACTED_IN]->(thereplacements),
(keanu)-[:ACTED_IN]->(thematrix),
(keanu)-[:ACTED_IN]->(thedevilsadvocate)

      

]]></database><command><![CDATA[
RETURN [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] AS list
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

In our examples, we'll use the xref:functions/list.adoc#functions-range[`range`] function.
It gives you a list containing all numbers between given start and end numbers.
Range is inclusive in both ends.

To access individual elements in the list, we use the square brackets again.
This will extract from the start index and up to but not including the end index.


.Query
[source, cypher]
----
RETURN range(0, 10)[3]
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +range(0, 10)[3]+
| +3+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE (keanu:Person {name: 'Keanu Reeves'}),
(johnnymnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
(somethingsgottagive:Movie {title: 'Somethings Gotta Give', released: 2003}),
(thematrixrevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
(thematrixreloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
(thereplacements:Movie {title: 'The Replacements', released: 2000}),
(thematrix:Movie {title: 'The Matrix', released: 1999}),
(thedevilsadvocate:Movie {title: 'The Devils Advocate', released: 1997}),

(keanu)-[:ACTED_IN]->(johnnymnemonic),
(keanu)-[:ACTED_IN]->(somethingsgottagive),
(keanu)-[:ACTED_IN]->(thematrixrevolutions),
(keanu)-[:ACTED_IN]->(thematrixreloaded),
(keanu)-[:ACTED_IN]->(thereplacements),
(keanu)-[:ACTED_IN]->(thematrix),
(keanu)-[:ACTED_IN]->(thedevilsadvocate)

      

]]></database><command><![CDATA[
RETURN range(0, 10)[3]
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

You can also use negative numbers, to start from the end of the list instead.


.Query
[source, cypher]
----
RETURN range(0, 10)[-3]
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +range(0, 10)[-3]+
| +8+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE (keanu:Person {name: 'Keanu Reeves'}),
(johnnymnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
(somethingsgottagive:Movie {title: 'Somethings Gotta Give', released: 2003}),
(thematrixrevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
(thematrixreloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
(thereplacements:Movie {title: 'The Replacements', released: 2000}),
(thematrix:Movie {title: 'The Matrix', released: 1999}),
(thedevilsadvocate:Movie {title: 'The Devils Advocate', released: 1997}),

(keanu)-[:ACTED_IN]->(johnnymnemonic),
(keanu)-[:ACTED_IN]->(somethingsgottagive),
(keanu)-[:ACTED_IN]->(thematrixrevolutions),
(keanu)-[:ACTED_IN]->(thematrixreloaded),
(keanu)-[:ACTED_IN]->(thereplacements),
(keanu)-[:ACTED_IN]->(thematrix),
(keanu)-[:ACTED_IN]->(thedevilsadvocate)

      

]]></database><command><![CDATA[
RETURN range(0, 10)[-3]
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

Finally, you can use ranges inside the brackets to return ranges of the list.


.Query
[source, cypher]
----
RETURN range(0, 10)[0..3]
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +range(0, 10)[0..3]+
| +[0,1,2]+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE (keanu:Person {name: 'Keanu Reeves'}),
(johnnymnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
(somethingsgottagive:Movie {title: 'Somethings Gotta Give', released: 2003}),
(thematrixrevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
(thematrixreloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
(thereplacements:Movie {title: 'The Replacements', released: 2000}),
(thematrix:Movie {title: 'The Matrix', released: 1999}),
(thedevilsadvocate:Movie {title: 'The Devils Advocate', released: 1997}),

(keanu)-[:ACTED_IN]->(johnnymnemonic),
(keanu)-[:ACTED_IN]->(somethingsgottagive),
(keanu)-[:ACTED_IN]->(thematrixrevolutions),
(keanu)-[:ACTED_IN]->(thematrixreloaded),
(keanu)-[:ACTED_IN]->(thereplacements),
(keanu)-[:ACTED_IN]->(thematrix),
(keanu)-[:ACTED_IN]->(thedevilsadvocate)

      

]]></database><command><![CDATA[
RETURN range(0, 10)[0..3]
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
RETURN range(0, 10)[0..-5]
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +range(0, 10)[0..-5]+
| +[0,1,2,3,4,5]+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE (keanu:Person {name: 'Keanu Reeves'}),
(johnnymnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
(somethingsgottagive:Movie {title: 'Somethings Gotta Give', released: 2003}),
(thematrixrevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
(thematrixreloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
(thereplacements:Movie {title: 'The Replacements', released: 2000}),
(thematrix:Movie {title: 'The Matrix', released: 1999}),
(thedevilsadvocate:Movie {title: 'The Devils Advocate', released: 1997}),

(keanu)-[:ACTED_IN]->(johnnymnemonic),
(keanu)-[:ACTED_IN]->(somethingsgottagive),
(keanu)-[:ACTED_IN]->(thematrixrevolutions),
(keanu)-[:ACTED_IN]->(thematrixreloaded),
(keanu)-[:ACTED_IN]->(thereplacements),
(keanu)-[:ACTED_IN]->(thematrix),
(keanu)-[:ACTED_IN]->(thedevilsadvocate)

      

]]></database><command><![CDATA[
RETURN range(0, 10)[0..-5]
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
RETURN range(0, 10)[-5..]
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +range(0, 10)[-5..]+
| +[6,7,8,9,10]+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE (keanu:Person {name: 'Keanu Reeves'}),
(johnnymnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
(somethingsgottagive:Movie {title: 'Somethings Gotta Give', released: 2003}),
(thematrixrevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
(thematrixreloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
(thereplacements:Movie {title: 'The Replacements', released: 2000}),
(thematrix:Movie {title: 'The Matrix', released: 1999}),
(thedevilsadvocate:Movie {title: 'The Devils Advocate', released: 1997}),

(keanu)-[:ACTED_IN]->(johnnymnemonic),
(keanu)-[:ACTED_IN]->(somethingsgottagive),
(keanu)-[:ACTED_IN]->(thematrixrevolutions),
(keanu)-[:ACTED_IN]->(thematrixreloaded),
(keanu)-[:ACTED_IN]->(thereplacements),
(keanu)-[:ACTED_IN]->(thematrix),
(keanu)-[:ACTED_IN]->(thedevilsadvocate)

      

]]></database><command><![CDATA[
RETURN range(0, 10)[-5..]
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
RETURN range(0, 10)[..4]
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +range(0, 10)[..4]+
| +[0,1,2,3]+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE (keanu:Person {name: 'Keanu Reeves'}),
(johnnymnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
(somethingsgottagive:Movie {title: 'Somethings Gotta Give', released: 2003}),
(thematrixrevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
(thematrixreloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
(thereplacements:Movie {title: 'The Replacements', released: 2000}),
(thematrix:Movie {title: 'The Matrix', released: 1999}),
(thedevilsadvocate:Movie {title: 'The Devils Advocate', released: 1997}),

(keanu)-[:ACTED_IN]->(johnnymnemonic),
(keanu)-[:ACTED_IN]->(somethingsgottagive),
(keanu)-[:ACTED_IN]->(thematrixrevolutions),
(keanu)-[:ACTED_IN]->(thematrixreloaded),
(keanu)-[:ACTED_IN]->(thereplacements),
(keanu)-[:ACTED_IN]->(thematrix),
(keanu)-[:ACTED_IN]->(thedevilsadvocate)

      

]]></database><command><![CDATA[
RETURN range(0, 10)[..4]
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Out-of-bound slices are simply truncated, but out-of-bound single elements return `null`.


====


.Query
[source, cypher]
----
RETURN range(0, 10)[15]
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +range(0, 10)[15]+
| +<null>+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE (keanu:Person {name: 'Keanu Reeves'}),
(johnnymnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
(somethingsgottagive:Movie {title: 'Somethings Gotta Give', released: 2003}),
(thematrixrevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
(thematrixreloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
(thereplacements:Movie {title: 'The Replacements', released: 2000}),
(thematrix:Movie {title: 'The Matrix', released: 1999}),
(thedevilsadvocate:Movie {title: 'The Devils Advocate', released: 1997}),

(keanu)-[:ACTED_IN]->(johnnymnemonic),
(keanu)-[:ACTED_IN]->(somethingsgottagive),
(keanu)-[:ACTED_IN]->(thematrixrevolutions),
(keanu)-[:ACTED_IN]->(thematrixreloaded),
(keanu)-[:ACTED_IN]->(thereplacements),
(keanu)-[:ACTED_IN]->(thematrix),
(keanu)-[:ACTED_IN]->(thedevilsadvocate)

      

]]></database><command><![CDATA[
RETURN range(0, 10)[15]
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
RETURN range(0, 10)[5..15]
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +range(0, 10)[5..15]+
| +[5,6,7,8,9,10]+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE (keanu:Person {name: 'Keanu Reeves'}),
(johnnymnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
(somethingsgottagive:Movie {title: 'Somethings Gotta Give', released: 2003}),
(thematrixrevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
(thematrixreloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
(thereplacements:Movie {title: 'The Replacements', released: 2000}),
(thematrix:Movie {title: 'The Matrix', released: 1999}),
(thedevilsadvocate:Movie {title: 'The Devils Advocate', released: 1997}),

(keanu)-[:ACTED_IN]->(johnnymnemonic),
(keanu)-[:ACTED_IN]->(somethingsgottagive),
(keanu)-[:ACTED_IN]->(thematrixrevolutions),
(keanu)-[:ACTED_IN]->(thematrixreloaded),
(keanu)-[:ACTED_IN]->(thereplacements),
(keanu)-[:ACTED_IN]->(thematrix),
(keanu)-[:ACTED_IN]->(thedevilsadvocate)

      

]]></database><command><![CDATA[
RETURN range(0, 10)[5..15]
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

You can get the xref:functions/scalar.adoc#functions-size[`size`] of a list as follows:


.Query
[source, cypher]
----
RETURN size(range(0, 10)[0..3])
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +size(range(0, 10)[0..3])+
| +3+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE (keanu:Person {name: 'Keanu Reeves'}),
(johnnymnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
(somethingsgottagive:Movie {title: 'Somethings Gotta Give', released: 2003}),
(thematrixrevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
(thematrixreloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
(thereplacements:Movie {title: 'The Replacements', released: 2000}),
(thematrix:Movie {title: 'The Matrix', released: 1999}),
(thedevilsadvocate:Movie {title: 'The Devils Advocate', released: 1997}),

(keanu)-[:ACTED_IN]->(johnnymnemonic),
(keanu)-[:ACTED_IN]->(somethingsgottagive),
(keanu)-[:ACTED_IN]->(thematrixrevolutions),
(keanu)-[:ACTED_IN]->(thematrixreloaded),
(keanu)-[:ACTED_IN]->(thereplacements),
(keanu)-[:ACTED_IN]->(thematrix),
(keanu)-[:ACTED_IN]->(thedevilsadvocate)

      

]]></database><command><![CDATA[
RETURN size(range(0, 10)[0..3])
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[[cypher-list-comprehension]]
== List comprehension

List comprehension is a syntactic construct available in Cypher for creating a list based on existing lists.
It follows the form of the mathematical set-builder notation (set comprehension) instead of the use of map and filter functions.


.Query
[source, cypher]
----
RETURN [x IN range(0,10) WHERE x % 2 = 0 | x^3 ] AS result
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +result+
| +[0.0,8.0,64.0,216.0,512.0,1000.0]+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE (keanu:Person {name: 'Keanu Reeves'}),
(johnnymnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
(somethingsgottagive:Movie {title: 'Somethings Gotta Give', released: 2003}),
(thematrixrevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
(thematrixreloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
(thereplacements:Movie {title: 'The Replacements', released: 2000}),
(thematrix:Movie {title: 'The Matrix', released: 1999}),
(thedevilsadvocate:Movie {title: 'The Devils Advocate', released: 1997}),

(keanu)-[:ACTED_IN]->(johnnymnemonic),
(keanu)-[:ACTED_IN]->(somethingsgottagive),
(keanu)-[:ACTED_IN]->(thematrixrevolutions),
(keanu)-[:ACTED_IN]->(thematrixreloaded),
(keanu)-[:ACTED_IN]->(thereplacements),
(keanu)-[:ACTED_IN]->(thematrix),
(keanu)-[:ACTED_IN]->(thedevilsadvocate)

      

]]></database><command><![CDATA[
RETURN [x IN range(0,10) WHERE x % 2 = 0 | x^3 ] AS result
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

Either the `WHERE` part, or the expression, can be omitted, if you only want to filter or map respectively.


.Query
[source, cypher]
----
RETURN [x IN range(0,10) WHERE x % 2 = 0 ] AS result
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +result+
| +[0,2,4,6,8,10]+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE (keanu:Person {name: 'Keanu Reeves'}),
(johnnymnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
(somethingsgottagive:Movie {title: 'Somethings Gotta Give', released: 2003}),
(thematrixrevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
(thematrixreloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
(thereplacements:Movie {title: 'The Replacements', released: 2000}),
(thematrix:Movie {title: 'The Matrix', released: 1999}),
(thedevilsadvocate:Movie {title: 'The Devils Advocate', released: 1997}),

(keanu)-[:ACTED_IN]->(johnnymnemonic),
(keanu)-[:ACTED_IN]->(somethingsgottagive),
(keanu)-[:ACTED_IN]->(thematrixrevolutions),
(keanu)-[:ACTED_IN]->(thematrixreloaded),
(keanu)-[:ACTED_IN]->(thereplacements),
(keanu)-[:ACTED_IN]->(thematrix),
(keanu)-[:ACTED_IN]->(thedevilsadvocate)

      

]]></database><command><![CDATA[
RETURN [x IN range(0,10) WHERE x % 2 = 0 ] AS result
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
RETURN [x IN range(0,10) | x^3 ] AS result
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +result+
| +[0.0,1.0,8.0,27.0,64.0,125.0,216.0,343.0,512.0,729.0,1000.0]+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE (keanu:Person {name: 'Keanu Reeves'}),
(johnnymnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
(somethingsgottagive:Movie {title: 'Somethings Gotta Give', released: 2003}),
(thematrixrevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
(thematrixreloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
(thereplacements:Movie {title: 'The Replacements', released: 2000}),
(thematrix:Movie {title: 'The Matrix', released: 1999}),
(thedevilsadvocate:Movie {title: 'The Devils Advocate', released: 1997}),

(keanu)-[:ACTED_IN]->(johnnymnemonic),
(keanu)-[:ACTED_IN]->(somethingsgottagive),
(keanu)-[:ACTED_IN]->(thematrixrevolutions),
(keanu)-[:ACTED_IN]->(thematrixreloaded),
(keanu)-[:ACTED_IN]->(thereplacements),
(keanu)-[:ACTED_IN]->(thematrix),
(keanu)-[:ACTED_IN]->(thedevilsadvocate)

      

]]></database><command><![CDATA[
RETURN [x IN range(0,10) | x^3 ] AS result
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[[cypher-pattern-comprehension]]
== Pattern comprehension

Pattern comprehension is a syntactic construct available in Cypher for creating a list based on matchings of a pattern.
A pattern comprehension will match the specified pattern just like a normal `MATCH` clause, with predicates just
like a normal `WHERE` clause, but will yield a custom projection as specified.

The following graph is used for the example below:

.Graph
["dot", "Lists-1.svg", "neoviz", ""]
----
  N0 [
    label = "{Person|name = \'Keanu Reeves\'\l}"
  ]
  N0 -> N7 [
    color = "#2e3436"
    fontcolor = "#2e3436"
    label = "ACTED_IN\n"
  ]
  N0 -> N4 [
    color = "#2e3436"
    fontcolor = "#2e3436"
    label = "ACTED_IN\n"
  ]
  N0 -> N3 [
    color = "#2e3436"
    fontcolor = "#2e3436"
    label = "ACTED_IN\n"
  ]
  N0 -> N5 [
    color = "#2e3436"
    fontcolor = "#2e3436"
    label = "ACTED_IN\n"
  ]
  N0 -> N6 [
    color = "#2e3436"
    fontcolor = "#2e3436"
    label = "ACTED_IN\n"
  ]
  N0 -> N2 [
    color = "#2e3436"
    fontcolor = "#2e3436"
    label = "ACTED_IN\n"
  ]
  N0 -> N1 [
    color = "#2e3436"
    fontcolor = "#2e3436"
    label = "ACTED_IN\n"
  ]
  N1 [
    label = "{Movie|title = \'Johnny Mnemonic\'\lreleased = 1995\l}"
  ]
  N2 [
    label = "{Movie|title = \'Somethings Gotta Give\'\lreleased = 2003\l}"
  ]
  N3 [
    label = "{Movie|title = \'The Matrix Revolutions\'\lreleased = 2003\l}"
  ]
  N4 [
    label = "{Movie|title = \'The Matrix Reloaded\'\lreleased = 2003\l}"
  ]
  N5 [
    label = "{Movie|title = \'The Replacements\'\lreleased = 2000\l}"
  ]
  N6 [
    label = "{Movie|title = \'The Matrix\'\lreleased = 1999\l}"
  ]
  N7 [
    label = "{Movie|title = \'The Devils Advocate\'\lreleased = 1997\l}"
  ]

----
 


.Query
[source, cypher]
----
MATCH (a:Person {name: 'Keanu Reeves'})
RETURN [(a)-->(b) WHERE b:Movie | b.released] AS years 
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +years+
| +[1997,2003,2003,2000,1999,2003,1995]+
1+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE (keanu:Person {name: 'Keanu Reeves'}),
(johnnymnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
(somethingsgottagive:Movie {title: 'Somethings Gotta Give', released: 2003}),
(thematrixrevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
(thematrixreloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
(thereplacements:Movie {title: 'The Replacements', released: 2000}),
(thematrix:Movie {title: 'The Matrix', released: 1999}),
(thedevilsadvocate:Movie {title: 'The Devils Advocate', released: 1997}),

(keanu)-[:ACTED_IN]->(johnnymnemonic),
(keanu)-[:ACTED_IN]->(somethingsgottagive),
(keanu)-[:ACTED_IN]->(thematrixrevolutions),
(keanu)-[:ACTED_IN]->(thematrixreloaded),
(keanu)-[:ACTED_IN]->(thereplacements),
(keanu)-[:ACTED_IN]->(thematrix),
(keanu)-[:ACTED_IN]->(thedevilsadvocate)

      

]]></database><command><![CDATA[
MATCH (a:Person {name: 'Keanu Reeves'})
RETURN [(a)-->(b) WHERE b:Movie | b.released] AS years 
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The whole predicate, including the `WHERE` keyword, is optional and may be omitted.

