:description: This section describes whitespace in Cypher

[[parsing]]
= Parsing

This page provides a general overview of how Cypher parses an input `STRING`.

The Cypher parser takes an arbitrary input `STRING`.
While the syntax of Cypher is described in subsequent chapters, the following details the general rules on which characters are considered valid input.

== Using unicodes in Cypher
Unicodes can generally be escaped as `\uxxx`.

Additional documentation on escaping rules for `STRING` literals, names and regular expressions can be found here:

* xref::queries/expressions.adoc#expressions-string-literals[String literal escape sequences]
* xref::syntax/naming.adoc#symbolic-names-escaping-rules[Using special characters in names]
* xref::clauses/where.adoc#escaping-in-regular-expressions[Regular epxressions]

The following example escapes the unicode character `A` (`\u0041`) in the keyword `MATCH`:

[source, syntax]
----
M\u0041TCH (m) RETURN m;
----

[[cypher-whitespaces]]
== Supported whitespace

Whitespace can be used as a separator between keywords and has no semantic meaning.
The following unicode characters are considered as whitespace:

[options="header", cols="1,2"]
|===
| Description                       | List of included Unicode characters
| Unicode general gategory Zp       | `\u2029`
| Unicode general gategory Zs       | `\u0020` (space), `\u1680`, `\u2000-200A`, `\u202F`, `\u205F`, `\u3000`
| Unicode general gategory class Zl | `\u2028`
| Horizontal tabulation             | `\t`, `\u0009`
| Line feed                         | `\n`, `\u000A`
| Vertical tabulation               | `\u000B`
| Form feed                         | `\f`, `\u000C`
| Carriage return                   | `\r`, `\u000D`
| File separator                    | `\u001C`
| Group separator                   | `\u001D`
| Record separator                  | `\u001E`
| Unit separator                    | `\u001F`
|===

It is possible to have multiple whitespace characters in a row, and will have the same effect as using a single whitespace.

The following example query uses vertical tabulation (`\u000B`) as whitespace between the `RETURN` keyword and the variable `m`:

[source, syntax]
----
MATCH (m) RETURN\u000Bm;
----

[[cypher-newlines]]
== Supported newline characters

A newline character identifies a new line in the query and is also considered whitespace.
The supported newline characters in Cypher are:

[options="header", cols="1,2"]
|===
| Description                       | List of included Unicode characters
| Line feed                         | `\n`, `\u000A`
| Carriage return                   | `\r`, `\u000D`
| Carriage return + line feed       | `\r\n`, `\u000D\u000A`
|===