:description: This section provides an overview of data types in Cypher.

[[cypher-values]]
= Values and types

[abstract]
--
This section provides an overview of data types in Cypher.
--

Cypher provides first class support for a number of data types.
These fall into the following three types: property, structural, composite. 

== Property types

The following data types are included in the property types category: Integer, Float, String, Boolean, Point, Date, Time, LocalTime, DateTime, LocalDateTime, and Duration.

* Property types can be returned from Cypher queries
* Property types can be used as xref::syntax/parameters.adoc[parameters]
* Property types can be stored as properties
* Property types can be constructed with xref::syntax/expressions.adoc[Cypher literals]

The adjective _numeric_, when used in the context of describing  Cypher functions or expressions, indicates that any type of Number applies (Integer or Float).

Homogeneous lists of simple types can also be stored as properties, although lists in general (see xref::syntax/values.adoc#composite-types[Composite types]) cannot be stored.

Cypher also provides pass-through support for byte arrays, which can be stored as property values.
Byte arrays are _not_ considered a first class data type by Cypher, so do not have a literal representation.


[[structural-types]]
== Structural types

The following data types are included in the structural types category: Node, Relationship, and Path. 

* Structural types can be returned from Cypher queries
* Structural types cannot be used as xref::syntax/parameters.adoc[parameters]
* Structural types cannot be stored as properties
* Structural types cannot be constructed with xref::syntax/expressions.adoc[Cypher literals]

The Node data type includes: Id, Label(s), and Map (of properties).
Note that labels are not values but a form of pattern syntax. 

The Relationship data type includes: Id, Type, Map (of properties), Id of start node, and Id of end node. 

The Path data type is an alternating sequence of nodes and relationships. 

[[composite-types]]
== Composite types

The following data types are included in the composite types category: List and Map.


* Composite types can be returned from Cypher queries
* Composite types can be used as xref::syntax/parameters.adoc[parameters]
* Composite types cannot be stored as properties
* Composite types can be constructed with xref::syntax/expressions.adoc[Cypher literals]

The List data type is a heterogeneous, ordered collection of values, each of which has any property, structural or composite type.

The Map data type is a heterogeneous, unordered collection of (_Key_, _Value_) pairs where _Key_ is a string,  _Value_ can have any property, structural, or composite type. 

[NOTE]
====
Composite values can also contain `null`. 
For more on using `null`, see xref::syntax/working-with-null.adoc[working with null].
====


