:description: This section provides an overview of data types in Cypher.

[[cypher-values]]
= Values and types

[abstract]
--
This section provides an overview of data types in Cypher.
--

Cypher provides first class support for a number of data types.
These fall into the following three categories: *property*, *structural*, and *composite*. 
This chapter will first provide a brief overview of each type, and then go into more detail about the property data type. 

== Property types

The following data types are included in the property types category: `Integer`, `Float`, `String`, `Boolean`, `Point`, `Date`, `Time`, `LocalTime`, `DateTime`, `LocalDateTime`, and `Duration`.

* Property types can be returned from Cypher queries
* Property types can be used as xref::syntax/parameters.adoc[parameters]
* Property types can be stored as properties
* Property types can be constructed with xref::syntax/expressions.adoc[Cypher literals]

Homogeneous lists of simple types can also be stored as properties, although lists in general (see xref::syntax/values.adoc#composite-types[Composite types]) cannot be stored.

Cypher also provides pass-through support for byte lists, which can be stored as property values.
Byte lists are _not_ considered a first class data type by Cypher, so do not have a literal representation.


[[structural-types]]
== Structural types

The following data types are included in the structural types category: `Node`, `Relationship`, and `Path`. 

* Structural types can be returned from Cypher queries
* Structural types cannot be used as xref::syntax/parameters.adoc[parameters]
* Structural types cannot be stored as properties
* Structural types cannot be constructed with xref::syntax/expressions.adoc[Cypher literals]

The `Node` data type includes: Id, Label(s), and Map (of properties).
Note that labels are not values, but a form of pattern syntax. 

The `Relationship` data type includes: Id, Type, Map (of properties), Id of start node, and Id of end node. 

The `Path` data type is an alternating sequence of nodes and relationships. 

[[composite-types]]
== Composite types

The following data types are included in the composite types category: `List` and `Map`.

* Composite types can be returned from Cypher queries
* Composite types can be used as xref::syntax/parameters.adoc[parameters]
* Composite types cannot be stored as properties
* Composite types can be constructed with xref::syntax/expressions.adoc[Cypher literals]

The `List` data type is a heterogeneous, ordered collection of values, each of which can have any property, structural or composite type.

As noted above, homogeneous lists of simple types can be stored as properties.

The `Map` data type is a heterogeneous, unordered collection of (_Key_, _Value_) pairs, where _Key_ is a string and  _Value_ can have any property, structural, or composite type. 

Composite values can also contain `null`. 
For more details, see xref::syntax/working-with-null.adoc[working with null].

== Property type details

[.types, opts="header", cols="2,2,2,1"]
|===
| Type | Min. value | Max. value | Precision

| `Boolean`
| `False`
| `True`
| -

| `Date`
| `-999_999_999-01-01`
| `+999_999_999-12-31`
| Days

| `DateTime`
| `-999_999_999-01-01T00:00:00+18:00`
| `+999_999_999-12-31T23:59:59.999999999-18:00`
| Nanoseconds

| `Duration`
| `P-292471208677Y-6M-15DT-15H-36M-32S`
| `P292471208677Y6M15DT15H36M32.999999999S`
| Nanoseconds

| `Float`
| `Double.MIN_VALUE` footnote:[The minimum value represents the minimum positive value of a `Float`, i.e. the closest value to zero.
It is also possible to have a negative `Float`.]
| `Double.MAX_VALUE`
| 64 bit

| `Integer`
| `Long.MIN_VALUE`
| `Long.MAX_VALUE`
| 64 bit

| `LocalDateTime`
| `-999_999_999-01-01T00:00:00`
| `+999_999_999-12-31T23:59:59.999999999`
| Nanoseconds

| `LocalTime`
| `00:00:00`
| `23:59:59.999999999`
| Nanoseconds

| `Point`
| *Cartesian*: (`-Double.MAX_VALUE`, `-Double.MAX_VALUE`)

*Cartesian_3D*: (`-Double.MAX_VALUE`, `-Double.MAX_VALUE`, `-Double.MAX_VALUE`)

*WGS_84*: (`-180`, `-90`)

*WGS_84_3D*: (`-180`, `-90`, `-Double.MAX_VALUE`)

| *Cartesian*: (`Double.MAX_VALUE`, `Double.MAX_VALUE`)

*Cartesian_3D*: (`Double.MAX_VALUE`, `Double.MAX_VALUE`, `Double.MAX_VALUE`)

*WGS_84*: (`180`, `90`)

*WGS_84_3D*: (`180`, `90`, `Double.MAX_VALUE`)

| The precision of each coordinate of the `Point` is 64 bit as they are floats.

| `String`
| -
| -
| -

| `Time`
| `00:00:00+18:00`
| `23:59:59.999999999-18:00``
| Nanoseconds
|===

=== Java value details

[.values, opts="header", width=75%, cols="1,3"]
|===
| Name | Value

| `Double.MAX_VALUE`
| 1.7976931348623157e+308 

| `Double.MIN_VALUE` 
| 4.9e-324 

| `Long.MAX_VALUE` 
| 2^63-1 

| `Long.MIN_VALUE`
| -2^63 
|===

