= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/aggregating/[Aggregating functions^]


====
include::ROOT:functions/aggregating.adoc[tag=functions_aggregating_avg]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/aggregating/#functions-avg[`avg()`^] function returns the average of a set of `INTEGER` or `FLOAT` values.
====

====
include::ROOT:functions/aggregating.adoc[tag=functions_aggregating_duration_avg]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/aggregating/#functions-avg-duration[`avg()` duration^] function returns the average of a set of `DURATION` values.
====


====
include::ROOT:functions/aggregating.adoc[tag=functions_aggregating_collect]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/aggregating/#functions-collect[`collect()`^] function returns a single aggregated list containing the non-`null` values returned by an expression.
====


====
include::ROOT:functions/aggregating.adoc[tag=functions_aggregating_count]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/aggregating/#functions-count[`count()`^] function returns the number of values or rows.
When `count(*)` is used, the function returns the number of matching rows.
====


====
include::ROOT:functions/aggregating.adoc[tag=functions_aggregating_count_as_expression]

[.description]
The `count()` function can also be passed an expression.
If so, it returns the number of non-`null` values returned by the given expression.
====

====
include::ROOT:functions/aggregating.adoc[tag=functions_aggregating_max]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/aggregating/#functions-max[`max()`^] function returns the maximum value in a set of values.
====

====
include::ROOT:functions/aggregating.adoc[tag=functions_aggregating_min]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/aggregating/#functions-min[`min()`^] function returns the minimum value in a set of values.
====


====
include::ROOT:functions/aggregating.adoc[tag=functions_aggregating_percentile_cont]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/aggregating/#functions-percentilecont[`percentileCont()`^] function returns the percentile of the given value over a group, with a percentile from `0.0` to `1.0`.
It uses a linear interpolation method, calculating a weighted average between two values if the desired percentile lies between them. 
====


====
include::ROOT:functions/aggregating.adoc[tag=functions_aggregating_percentile_disc]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/aggregating/#functions-percentiledisc[`percentileDisc()`^] function returns the percentile of the given value over a group, with a percentile from `0.0` to `1.0`.
It uses a rounding method and calculates the nearest value to the percentile.
====

====
include::ROOT:functions/aggregating.adoc[tag=functions_aggregating_stdev]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/aggregating/#functions-stdev[`stDev()`^] function returns the standard deviation for the given value over a group.
It uses a standard two-pass method, with `N - 1` as the denominator, and should be used when taking a sample of the population for an unbiased estimate.
====


====
include::ROOT:functions/aggregating.adoc[tag=functions_aggregating_stdevp]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/aggregating/#functions-stdevp[`stDevP()`^] function returns the standard deviation for the given value over a group.
It uses a standard two-pass method, with `N` as the denominator, and should be used when calculating the standard deviation for an entire population.
====


====
include::ROOT:functions/aggregating.adoc[tag=functions_aggregating_sum]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/aggregating/#functions-sum[`sum()`^] function returns the sum of a set of numeric values.
====

====
include::ROOT:functions/aggregating.adoc[tag=functions_aggregating_sum_duration]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/aggregating/#functions-sum-duration[`sum()` duration^] function returns the sum of a set of durations.
====
