[role=label--enterprise-edition label--aura-db-enterprise label--aura-db-business-critical]
= link:{neo4j-docs-base-uri}/operations-manual/current/database-administration/aliases/manage-aliases-standard-databases/[ALIAS Management^]

////
[source, cypher, role=test-setup]
----
CREATE DATABASE `database-name`;
CREATE DATABASE `northwind-graph-2020`;
----
////

====
[source, cypher, role=noheader]
----
CREATE ALIAS `database-alias` IF NOT EXISTS
FOR DATABASE `database-name`
----

[.description]
Create a local alias named `database-alias` for the database named `database-name`.
====


====
[source, cypher, role=noheader]
----
CREATE OR REPLACE ALIAS `database-alias`
FOR DATABASE `database-name`
----

[.description]
Create or replace a local alias named `database-alias` for the database named `database-name`.
====


====
[source, cypher, role=noheader, role=test-skip]
----
CREATE ALIAS `database-alias`
FOR DATABASE `database-name`
PROPERTIES { property = $value }
----

[.description]
Database aliases can be given properties.
====


====
[source, cypher, role=noheader, role=test-skip]
----
CREATE ALIAS `database-alias`
FOR DATABASE `database-name`
AT $url
USER user_name
PASSWORD $password
----

[.description]
Create a remote alias named `database-alias` for the database named `database-name`.
====

====
[source, cypher, role=noheader, role=test-skip]
----
CREATE ALIAS `remote-with-default-language`
FOR DATABASE `northwind-graph-2020`
	AT "neo4j+s://location:7687"
	USER alice
	PASSWORD 'example_secret'
	DEFAULT LANGUAGE CYPHER 25
----

[.description]
Set the default Cypher version for a remote database alias when creating it. The available versions are `CYPHER 5` and `CYPHER 25`.
Local database aliases and database aliases in composite databases cannot be assigned a default Cypher version.
Local database aliases always have the Cypher version of their target database and database aliases in composite databases always have the Cypher version of the composite database they belong to.
====

====
[source, cypher, role=noheader, role=test-skip]
----
CREATE ALIAS `composite-database-name`.`alias-in-composite-name`
FOR DATABASE `database-name`
AT $url
USER user_name
PASSWORD $password

----

[.description]
Create a remote alias named `alias-in-composite-name` as a constituent alias in the composite database named `composite-database-name` for the database with name `database-name`.
====


====
[source, cypher, role=noheader]
----
ALTER ALIAS `database-alias` IF EXISTS
SET DATABASE TARGET `database-name`
----

[.description]
Alter the alias named `database-alias` to target the database named `database-name`.
====


====
[source, cypher, role=noheader]
----
ALTER ALIAS `remote-database-alias` IF EXISTS
SET DATABASE
USER user_name
PASSWORD $password
----

[.description]
Alter the remote alias named `remote-database-alias`, set the username (`user_name`) and the password.
====


====
[source, cypher, role=noheader]
----
ALTER ALIAS `database-alias`
SET DATABASE PROPERTIES { key: value }
----

[.description]
Update the properties for the database alias named `database-alias`.
====

====
[source, cypher, role=noheader]
----
ALTER ALIAS `remote-with-default-language` SET DATABASE DEFAULT LANGUAGE CYPHER 25
----

[.description]
Alter the default Cypher version of a remote database alias.
The available versions are `CYPHER 25` and `CYPHER 5`.
It is not possible to alter the default Cypher version of a local database alias or an alias belonging to a composite database.
Local database aliases always have the Cypher version of their target database and aliases belonging to composite databases always have the Cypher version of the composite database.
====

====
[source, cypher, role=noheader]
----
SHOW ALIASES FOR DATABASE
----

[.description]
List all database aliases in Neo4j DBMS and information about them, returns only the default outputs (`name`, `composite`, `database`, `location`, `url`, and `user`).
====


====
[source, cypher, role=noheader]
----
SHOW ALIASES `database-alias` FOR DATABASE
----

[.description]
List the database alias named `database-alias` and the information about it. Returns only the default outputs (`name`, `composite`, `database`, `location`, `url`, and `user`).
====


====
[source, cypher, role=noheader]
----
SHOW ALIASES FOR DATABASE YIELD *
----

[.description]
List all database aliases in Neo4j DBMS and information about them.
====

====
[source, cypher, role=noheader]
----
SHOW ALIAS `remote-with-default-language` FOR DATABASE YIELD name, defaultLanguage
----

[.description]
Show the default Cypher version of a remote database alias.
====

====
[source, cypher, role=noheader]
----
DROP ALIAS `database-alias` IF EXISTS FOR DATABASE
----

[.description]
Delete the alias named `database-alias`.
====