[.neo4j-ee.aura-dbe.aura-dbc]
= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/attribute-based-access-control/[AUTH Management^]
:test-skip: true

====
[source, cypher, role=noheader]
----
CREATE AUTH RULE salesRule
    SET CONDITION abac.oidc.user_attribute('department') = 'sales'
----

[.description]
Creates an auth rule named `salesRule`.
Users whose OIDC token contains `department = 'sales'` are granted the
roles assigned to this rule.
====

====
[source, cypher, role=noheader]
----
CREATE AUTH RULE ruleset_countries SET CONDITION
  any(country IN abac.oidc.user_attribute('citizenshipCountries')
    WHERE country IN ['c1', 'c5'])
----

[.description]
Create auth rules based on a list of values.
====


====
[source, cypher, role=noheader]
----
CREATE OR REPLACE AUTH RULE managementRule
    SET CONDITION abac.oidc.user_attribute('department') = 'management'
----

[.description]
Adding `OR REPLACE` to the command deletes any existing auth rule with the same name and creates a new auth rule with the same name. Any assigned roles associated with the old auth rule will not be associated to the new auth rule.
====

====
[source, cypher, role=noheader]
----
CREATE AUTH RULE managementRule IF NOT EXISTS
    SET CONDITION abac.oidc.user_attribute('department') = 'management'
----

[.description]
Appending `IF NOT EXISTS` to the command ensures that no error is returned and nothing happens should a rule with the same name already exists, and the command has no effect.
`OR REPLACE` and `IF NOT EXISTS` cannot be used at the same time.
====

====
[source, cypher, role=noheader]
----
CREATE AUTH RULE managementRule
    SET CONDITION abac.oidc.user_attribute('department') = 'sales'
    SET ENABLED false
----

[.description]
`SET ENABLED false` creates the rule in a disabled state so it is not
evaluated until explicitly enabled.
Default is `true`.
====


====
[source, cypher, role=noheader]
----
GRANT ROLE management TO AUTH RULE managementRule
----

[.description]
Assign a role to an auth rule.
====


====
[source, cypher, role=noheader]
----
REVOKE ROLE reader FROM AUTH RULE temporary_reader
----

[.description]
Revoke a role from an auth rule.
====


====
[source, cypher, role=noheader]
----
SHOW AUTH RULES
----

[.description]
Show all auth rules and return default columns (`name`, `condition`, `enabled`, `roles`)
For more information about specifying return columns and filtering, see the general xref:index.adoc#_show[`SHOW`] section.
====


====
[source, cypher, role=noheader]
----
SHOW AUTH RULES AS COMMANDS
----

[.description]
Show auth rules as Cypher commands.
====


====
[source, cypher, role=noheader]
----
RENAME AUTH RULE managementRule IF EXISTS TO managementRuleNew
----

[.description]
Rename an auth rule.
====


====
[source, cypher, role=noheader]
----
ALTER AUTH RULE ruleset_countries SET CONDITION any(country IN abac.oidc.user_attribute('citizenshipCountries')
WHERE country IN ['c1', 'c5', 'c6'])
----

[.description]
Modify the condition of an auth rule (this example adds `c6` to the list of allowed countries).
====


====
[source, cypher, role=noheader]
----
ALTER AUTH RULE ruleset_countries SET ENABLED false
----

[.description]
Disable an auth rule.
====


====
[source, cypher, role=noheader]
----
DROP AUTH RULE ruleset_countries IF EXISTS
----

[.description]
Drop an auth rule.
====

