= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/call/[CALL procedure^]


====
[source, cypher, role=noheader]
----
CALL db.labels() YIELD label
----

[.description]
Standalone call to the procedure link:{neo4j-docs-base-uri}/operations-manual/current/reference/procedures/#procedure_db_labels[`db.labels`^] to list all labels used in the database. Note that required procedure arguments are given explicitly in brackets after the procedure name.
====

====
[source, cypher, role=noheader]
----
MATCH (n)
OPTIONAL CALL apoc.neighbors.tohop(n, "KNOWS>", 1)
YIELD node
RETURN n.name AS name, collect(node.name) AS connections
----

[.description]
Optionally `CALL` a procedure.
Similar to `OPTIONAL MATCH`, any empty rows produced by the `OPTIONAL CALL` will return `null` and not affect the remainder of the procedure evaluation.
====


====
[source, cypher, role=noheader]
----
CALL db.labels() YIELD *
----

[.description]
Standalone calls may use `YIELD *` to return all columns.
====


====
[source, cypher, role=noheader]
----
CALL java.stored.procedureWithArgs
----

[.description]
Standalone calls may omit `YIELD` and also provide arguments implicitly via statement parameters, e.g. a standalone call requiring one argument input may be run by passing the parameter map `{input: 'foo'}`.
====


====
[source, cypher, role=noheader]
----
CALL db.labels() YIELD label
RETURN count(label) AS db_labels
----

[.description]
Calls the built-in procedure `db.labels` inside a larger query to count all labels used in the database. Calls inside a larger query always requires passing arguments and naming results explicitly with `YIELD`.
====