= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/expressions/conditional-expressions/[Conditional expressions(`CASE`)^] 

====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/expressions/conditional-expressions.adoc[tag=expressions_conditional_expressions_simple]

[.description]
The simple `CASE` form is used to compare a single expression against multiple values, and is analogous to the `switch` construct of programming languages.
The expressions are evaluated by the `WHEN` operator until a match is found.
If no match is found, the expression in the `ELSE` operator is returned.
If there is no `ELSE` case and no match is found, `null` will be returned.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/expressions/conditional-expressions.adoc[tag=expressions_conditional_expressions_extended_simple]

[.description]
The extended simple `CASE` can use comparison operators.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/expressions/conditional-expressions.adoc[tag=expressions_conditional_expressions_generic]

[.description]
The generic `CASE` expression supports multiple conditional statements, and is analogous to the `if-elseif-else` construct of programming languages.
Each row is evaluated in order until a `true` value is found.
If no match is found, the expression in the `ELSE` operator is returned.
If there is no `ELSE` case and no match is found, `null` will be returned.
====



====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/expressions/conditional-expressions.adoc[tag=expressions_conditional_expressions_properties]

[.description]
The results of a `CASE` expression can be used to set properties on a node or relationship.
====
