= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/queries/composed-queries/combined-queries/[Conditional queries (WHEN)^]

====
include::ROOT:queries/composed-queries/conditional-queries.adoc[tag=conditional_queries_logic]

[.description]
`WHEN`, together with `THEN` and `ELSE`, enables different branches of a query to execute based on certain conditions.
The first branch with a predicate that evaluates to `true` will be executed.
If no `WHEN` branches are executed and an `ELSE` branch exists, it is executed.
If no `WHEN` branches evaluates to `true` and no `ELSE` branch is present, no branches are executed and no rows are produced.
====


====
include::ROOT:queries/composed-queries/conditional-queries.adoc[tag=conditional_queries_standalone_when]

[.description]
Queries can be executed conditionally executed in standalone `WHEN` branches.
====


====
include::ROOT:queries/composed-queries/conditional-queries.adoc[tag=conditional_queries_call]

[.description]
`WHEN` can be used inside one or several `CALL` subqueries to execute a set of operations only when a specified condition evaluates to `true`.
====


====
include::ROOT:queries/composed-queries/conditional-queries.adoc[tag=conditional_queries_exists]

[.description]
`EXISTS`, `COLLECT`, and `COUNT` subquery expressions can also contain `WHEN` branches.
====


====
include::ROOT:queries/composed-queries/conditional-queries.adoc[tag=conditional_queries_union]

[.description]
The results of multiple conditional queries can also be combined using `UNION [DISTINCT]` or `UNION ALL`.
If the conditional query begins with `WHEN` and involves `UNION`, the `WHEN` branches *must* be enclosed within curly braces, `{}`.
====