= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/schema/constraints/[Constraints^]

====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_property_uniqueness]

[.description]
--
Create a node property uniqueness constraint.

Best practice is to always specify a sensible name when creating a constraint.
--
====

====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_if_not_exists]

[.description]
--
Create a relationship property uniqueness constraint.

Appending the keyword `IF NOT EXISTS` to any `CREATE CONSTRAINT` command makes the command idempotent, and no error will be thrown if an attempt is made to create the same constraint twice.Expand commentComment on line R21Resolved
--
====


====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_composite_property_uniqueness]

[.description]
Create a composite relationship property uniqueness constraint on several properties.
====

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_property_existence]

[.description]
Create a node property existence constraint.
====

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_property_type]

[.description]
Create a relationship property type constraint.
====

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_property_type_dynamic_union]

[.description]
Create a node property type constraint with dynamic union type, allowing the constrained property to be of more than one type.
====

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_key]

[.description]
Create a node key constraint.
====


[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_composite_key]

[.description]
Create a composite relationship key constraint on several properties.
====


[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_parameter]

[.description]
Create a constraint with a parameterized constraint name.
====


====
include::ROOT:schema/constraints/list-constraints.adoc[tag=schema_constraints_show]

[.description]
Show all constraints and return default columns (`id`, `name`, `type`, `entityType`, `labelsOrTypes`, `properties`, `ownedIndex`, and `propertyType`).
For more information about specifying return columns and filtering, see the general xref:index.adoc#_show[`SHOW`] section.
====


====
include::ROOT:schema/constraints/list-constraints.adoc[tag=schema_constraints_show_type_filter]

[.description]
`SHOW CONSTRAINTS` can be filtered on constraint type.
The available types are: `NODE PROPERTY UNIQUENESS`, `RELATIONSHIP PROPERTY UNIQUENESS`, `PROPERTY UNIQUENESS`, `NODE EXISTENCE`, `RELATIONSHIP EXISTENCE`, `EXISTENCE`, `NODE PROPERTY EXISTENCE`, `RELATIONSHIP PROPERTY EXISTENCE`, `PROPERTY EXISTENCE`, `NODE PROPERTY TYPE`, `RELATIONSHIP PROPERTY TYPE`, `PROPERTY TYPE`, `NODE KEY`, `RELATIONSHIP KEY`, and `KEY`.
====


====
include::ROOT:schema/constraints/drop-constraints.adoc[tag=schema_constraints_drop]

[.description]
Drop a constraint by its name.
====


====
include::ROOT:schema/constraints/drop-constraints.adoc[tag=schema_constraints_drop_parameter]

[.description]
Drop a constraint using a parameterized name.
====

====
include::ROOT:schema/constraints/drop-constraints.adoc[tag=schema_constraints_drop_if_exists]

[.description]
Appending `IF EXISTS` to `DROP CONSTRAINT` makes the command idempotent; if a constraint with the given name exists, it will be dropped; otherwise, no error will be thrown.
====