= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/schema/constraints/[Constraints^]


====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_property_uniqueness]

[.description]
--
Create a node property uniqueness constraint requiring `Book` nodes to have a unique `isbn` property.
An error will be thrown if an attempt is made to create the same constraint twice.
If any other node with that label is updated or created with an `isbn` property that already exists, the write operation will fail. 

Best practice is to always specify a sensible name when creating a constraint.

Property uniqueness constraints are backed by an index.
This means that creating a property uniqueness constraint will create a range index with the same name, node label/relationship type and property combination as its owning constraint.
--
====


====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_if_not_exists]

[.description]
To avoid failing on existing constraints, `IF NOT EXISTS` can be added to the `CREATE` command.
This will ensure that no error is thrown and that no constraint is created if any other constraint with the given name, or another constraint on the same constraint type and schema, or both, already exists.
====


====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_composite_property_uniqueness]

[.description]
Create a relationship composite property uniqueness constraint requiring `PREQUEL_OF` relationships to have unique combinations of `order` and `author` properties.
If any other relationship with that type is updated or created with the same combination of `order` and `author` properties, the write operation will fail.
====


[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_property_existence]

[.description]
Create a node property existence constraint requiring `Author` nodes to have a `name` property.
If a node with that label is created without a `name` property, the write operation will fail.
====


[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_property_type]

[.description]
Create a relationship property type constraint requiring `order` properties on `PART_OF` relationships to be of type `INTEGER`.
If an `order` property of a different type is created on a relationship with that type, the write operation will fail.
====


[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_property_type_dynamic_union]

[.description]
A closed dynamic union allows a node or relationship property to maintain some type flexibility whilst preventing unexpected values from being stored.
This example creates a node property type constraint requiring `tagline` properties on `Movie` nodes to be either of type `STRING` or `LIST<STRING NOT NULL>`.
====

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_key]

[.description]
--
Create a node key constraint requiring `Director` nodes to have a unique `imdbId` property as a node key.
Key constraints ensure that the property exist and the property value is unique for all nodes with a specific label or all relationships with a specific type.
For this example, if a node with that label without `imdbId` property that is unique, the write operation will fail.

Key constraints are backed by an index.
This means that creating a key constraint will create a range index with the same name, node label/relationship type and property combination as its owning constraint.
--
====


[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_key]

[.description]
Create a composite relationship key constraint requiring `KNOWS` relationships to have a unique combination of `since` and `how` properties .
====


====
include::ROOT:schema/constraints/create-constraints.adoc[tag=schema_constraints_create_parameter]

[.description]
Create a node property uniqueness constraint with a parameterized name.
All constraint types can be created in this way.
====


====
include::ROOT:schema/constraints/list-constraints.adoc[tag=schema_constraints_show]

[.description]
Show all constraints and return default columns (`id`, `name`, `type`, `entityType`, `labelsOrTypes`, `properties`, `ownedIndex`, and `propertyType`).
For more information about specifying return columns and filtering, see the general xref:index.adoc#_show[`SHOW`] section.
====


====
include::ROOT:schema/constraints/list-constraints.adoc[tag=schema_constraints_show_type_filter]

[.description]
`SHOW CONSTRAINTS` can be filtered on constraint type.
The available types are: `NODE PROPERTY UNIQUENESS`, `RELATIONSHIP PROPERTY UNIQUENESS`, `PROPERTY UNIQUENESS`, `NODE EXISTENCE`, `RELATIONSHIP EXISTENCE`, `EXISTENCE`, `NODE PROPERTY EXISTENCE`, `RELATIONSHIP PROPERTY EXISTENCE`, `PROPERTY EXISTENCE`, `NODE PROPERTY TYPE`, `RELATIONSHIP PROPERTY TYPE`, `PROPERTY TYPE`, `NODE KEY`, `RELATIONSHIP KEY`, and `KEY`.
====


====
include::ROOT:schema/constraints/drop-constraints.adoc[tag=schema_constraints_drop]

[.description]
Drop a constraint by name.
====


====
include::ROOT:schema/constraints/drop-constraints.adoc[tag=schema_constraints_drop_parameter]

[.description]
Drop a constraint with a parameterized name.
====

