= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/constraints/managing-constraints/[Constraints^]

====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT node_property_uniqueness_constraint IF NOT EXISTS
FOR (p:Person)
REQUIRE p.name IS UNIQUE
----

[.description]
--
Create a node property uniqueness constraint on the label `Person` and property `name`. Using the keyword `IF NOT EXISTS` makes the command idempotent, and no error will be thrown if an attempt is made to create the same constraint twice.  If any other node with that label is updated or created with a name that already exists, the write operation will fail. 

Best practice is to always specify a sensible name when creating a constraint.
--
====


====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT composite_uniqueness_constraint
FOR (p:Person)
REQUIRE (p.name, p.age) IS UNIQUE
----

[.description]
Create a node property uniqueness constraint on the label `Person` and properties `name` and `age`. An error will be thrown if an attempt is made to create the same constraint twice. If any node with that label is updated or created with a name and age combination that already exists, the write operation will fail.
====


====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT relationship_property_uniqueness_constraint
FOR ()-[r:LIKED]-()
REQUIRE r.when IS UNIQUE
----

[.description]
--
Create a relationship property uniqueness constraint on the relationship type `LIKED` and property `when`.
If any other relationship with that relationship type is updated or created with a `when` property value that already exists, the write operation will fail.

Best practice is to always specify a sensible name when creating a constraint.
--
====

////
.Parameters
[source, parameters]
----
{
  "nameParam": "parameterized_constraint_name"
}
----
////

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT $nameParam
FOR (p:Person)
REQUIRE p.name IS NOT NULL
----

[.description]
Create a node property existence constraint with the name given by the parameter `nameParam` on the label `Person` and property `name`. If a node with that label is created without a `name` property, or if the `name` property on the existing node with the label `Person` is removed, the write operation will fail.
====


[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT relationship_property_existence_constraint
FOR ()-[r:LIKED]-()
REQUIRE r.when IS NOT NULL
----

[.description]
Create a relationship property existence constraint on the type `LIKED` and property `when`. If a relationship with that type is created without a `when` property, or if the property `when` is removed from an existing relationship with the type `LIKED`, the write operation will fail.
====


[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT node_property_type_constraint
FOR (p:Person)
REQUIRE p.name IS :: STRING
----

[.description]
Create a node property type constraint on the label `Person` and property `name`, restricting the property to `STRING`.
If a node with that label is created with a `name` property of a different Cypher type, the write operation will fail.
====


[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT relationship_property_type_constraint
FOR ()-[r:LIKED]-()
REQUIRE r.when IS :: DATE
----

[.description]
Create a relationship property type constraint on the type `LIKED` and property `when`, restricting the property to `DATE`.
If a relationship with that type is created with a `when` property of a different Cypher type, the write operation will fail.
====


[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT node_key_constraint
FOR (p:Person)
REQUIRE (p.name, p.surname) IS NODE KEY
----

[.description]
Create a node key constraint on the label `Person` and properties `name` and `surname` with the name `constraint_name`.
If a node with that label is created without both the `name` and `surname` properties, or if the combination of the two is not unique, or if the `name` and/or `surname` properties on an existing node with the label `Person` is modified to violate these constraints, the write operation will fail.
====

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dsp.aura-dse]
====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT relationship_key_constraint
FOR ()-[r:KNOWS]-()
REQUIRE (r.since, r.isFriend) IS RELATIONSHIP KEY
----

[.description]
--
Create a relationship key constraint with the name `constraint_name` on the relationship type `KNOWS` and properties `since` and `isFriend`.
If a relationship with that relationship type is created without both the `since` and `isFriend` properties, or if the combination of the two is not unique, the write operation will fail.
The write operation will also fail if the `since` and/or `isFriend` properties on an existing relationship with the relationship type `KNOWS` is modified to violate these constraints.
--
====

====
[source, cypher, role=noheader]
----
SHOW CONSTRAINTS
----

[.description]
Show all constraints and return default columns (`id`, `name`, `type`, `entityType`, `labelsOrTypes`, `properties`, `ownedIndex`, and `propertyType`).
For more information about specifying return columns and filtering, see the general xref:index.adoc#_show[`SHOW`] section.
====

====
[source, cypher, role=noheader]
----
SHOW KEY CONSTRAINTS
----

[.description]
`SHOW CONSTRAINTS` can be filtered on constraint type.
The available types are: `NODE PROPERTY UNIQUENESS`, `RELATIONSHIP PROPERTY UNIQUENESS`, `PROPERTY UNIQUENESS`, `NODE EXISTENCE`, `RELATIONSHIP EXISTENCE`, `EXISTENCE`, `NODE PROPERTY EXISTENCE`, `RELATIONSHIP PROPERTY EXISTENCE`, `PROPERTY EXISTENCE`, `NODE PROPERTY TYPE`, `RELATIONSHIP PROPERTY TYPE`, `PROPERTY TYPE`, `NODE KEY`, `RELATIONSHIP KEY`, and `KEY`.
====

====
[source, cypher, role=noheader]
----
DROP CONSTRAINT relationship_key_constraint
----

[.description]
Drop the constraint with the name `constraint_name`, throws an error if the constraint does not exist.
====


====
[source, cypher, role=noheader, role=test-skip]
----
DROP CONSTRAINT $nameParam IF EXISTS
----

[.description]
Drop the constraint with the name given by the parameter `nameParam` if it exists, does nothing if it does not exist.
====
