= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/constraints/managing-constraints/[Constraints^]


====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT node_property_uniqueness_constraint IF NOT EXISTS
FOR (p:Person)
REQUIRE p.name IS UNIQUE
----

[.description]
--
Create a node property uniqueness constraint on the label `Person` and property `name`. Using the keyword `IF NOT EXISTS` makes the command idempotent, and no error will be thrown if an attempt is made to create the same constraint twice.  If any other node with that label is updated or created with a name that already exists, the write operation will fail. 

Best practice is to always specify a sensible name when creating a constraint.
--
====


====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT composite_constraint
FOR (p:Person)
REQUIRE (p.name, p.age) IS UNIQUE
----

[.description]
Create a node property uniqueness constraint on the label `Person` and properties `name` and `age`. An error will be thrown if an attempt is made to create the same constraint twice. If any node with that label is updated or created with a name and age combination that already exists, the write operation will fail.
====


====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT rel_property_uniqueness_constraint
FOR ()-[r:LIKED]-()
REQUIRE r.when IS UNIQUE
----

[.description]
--
Create a relationship property uniqueness constraint on the relationship type `LIKED` and property `when`.
If any other relationship with that relationship type is updated or created with a `when` property value that already exists, the write operation will fail.

Best practice is to always specify a sensible name when creating a constraint.
--
====


////
.Parameters
[source, parameters]
----
{
  "nameParam": "parameterized_constraint_name"
}
----
////

[role=label--enterprise-edition label--aura-db-free label--aura-db-professional label--aura-db-enterprise label--aura-db-business-critical label--aura-ds-professional label--aura-ds-enterprise]
====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT $nameParam
FOR (p:Person)
REQUIRE p.name IS NOT NULL
----

[.description]
Create a node property existence constraint with the name given by the parameter `nameParam` on the label `Person` and property `name`. If a node with that label is created without a `name` property, or if the `name` property on the existing node with the label `Person` is removed, the write operation will fail.
====


[role=label--enterprise-edition label--aura-db-free label--aura-db-professional label--aura-db-enterprise label--aura-db-business-critical label--aura-ds-professional label--aura-ds-enterprise]
====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT rel_property_existence_constraint
FOR ()-[r:LIKED]-()
REQUIRE r.when IS NOT NULL
----

[.description]
Create a relationship property existence constraint on the type `LIKED` and property `when`. If a relationship with that type is created without a `when` property, or if the property `when` is removed from an existing relationship with the type `LIKED`, the write operation will fail.
====


[role=label--enterprise-edition label--aura-db-free label--aura-db-professional label--aura-db-enterprise label--aura-db-business-critical label--aura-ds-professional label--aura-ds-enterprise]
====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT node_property_type_constraint
FOR (p:Person)
REQUIRE p.name IS :: STRING
----

[.description]
Create a node property type constraint on the label `Person` and property `name`, restricting the property to `STRING`.
If a node with that label is created with a `name` property of a different Cypher type, the write operation will fail.
====


[role=label--enterprise-edition label--aura-db-free label--aura-db-professional label--aura-db-enterprise label--aura-db-business-critical label--aura-ds-professional label--aura-ds-enterprise]
====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT rel_property_type_constraint
FOR ()-[r:LIKED]-()
REQUIRE r.when IS :: DATE
----

[.description]
Create a relationship property type constraint on the type `LIKED` and property `when`, restricting the property to `DATE`.
If a relationship with that type is created with a `when` property of a different Cypher type, the write operation will fail.
====


[role=label--enterprise-edition label--aura-db-free label--aura-db-professional label--aura-db-enterprise label--aura-db-business-critical label--aura-ds-professional label--aura-ds-enterprise]
====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT key_constraint
FOR (p:Person)
REQUIRE (p.name, p.surname) IS NODE KEY
----

[.description]
Create a node key constraint on the label `Person` and properties `name` and `surname` with the name `key_constraint`.
If a node with that label is created without both the `name` and `surname` properties, or if the combination of the two is not unique, or if the `name` and/or `surname` properties on an existing node with the label `Person` is modified to violate these constraints, the write operation will fail.
====

[role=label--enterprise-edition label--aura-db-free label--aura-db-professional label--aura-db-enterprise label--aura-db-business-critical label--aura-ds-professional label--aura-ds-enterprise]
====
[source, cypher, role=noheader]
----
CREATE CONSTRAINT rel_key_constraint
FOR ()-[r:KNOWS]-()
REQUIRE (r.since, r.isFriend) IS RELATIONSHIP KEY
----

[.description]
--
Create a relationship key constraint with the name `rel_key_constraint` on the relationship type `KNOWS` and properties `since` and `isFriend`.
If a relationship with that relationship type is created without both the `since` and `isFriend` properties, or if the combination of the two is not unique, the write operation will fail.
The write operation will also fail if the `since` and/or `isFriend` properties on an existing relationship with the relationship type `KNOWS` is modified to violate these constraints.
--
====

====
[source, cypher, role=noheader]
----
SHOW ALL CONSTRAINTS
----

[.description]
List all constraints, returns only the default outputs (`id`, `name`, `type`, `entityType`, `labelsOrTypes`, `properties`, `ownedIndex`, and `propertyType`).
Can also be filtered on `NODE UNIQUENESS`, `RELATIONSHIP UNIQUENESS`, `UNIQUENESS`, `NODE EXISTENCE`, `RELATIONSHIP EXISTENCE`, `EXISTENCE`, `NODE PROPERTY TYPE`, `RELATIONSHIP PROPERTY TYPE`, `PROPERTY TYPE`, `NODE KEY`, `RELATIONSHIP KEY`, and `KEY`.
For more information, see link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/constraints/syntax/#list-constraints[Constraints -> Syntax -> SHOW CONSTRAINTS^].
====


====
[source, cypher, role=noheader]
----
SHOW CONSTRAINTS YIELD *
----

[.description]
List all constraints. For more information, see link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/constraints/managing-constraints/#list-constraints[Constraints -> Create, show, and drop constraints -> SHOW CONSTRAINTS^].
====


====
[source, cypher, role=noheader]
----
DROP CONSTRAINT composite_constraint
----

[.description]
Drop the constraint with the name `composite_constraint`, throws an error if the constraint does not exist.
====


====
[source, cypher, role=noheader]
----
DROP CONSTRAINT $nameParam IF EXISTS
----

[.description]
Drop the constraint with the name given by the parameter `nameParam` if it exists, does nothing if it does not exist.
====


