= link:{neo4j-docs-base-uri}/operations-manual/current/database-administration/standard-databases/manage-databases/[DATABASE Management^]



====
[source, cypher, role=noheader]
----
dba
`db1`
`database-name`
`database-name-123`
`database.name`
`database.name.123`
----

[.description]
--
The naming rules for a database: 

* The character length of a database name must be at least `3` characters; and not more than `63` characters.
* The first character of a database name must be an ASCII alphabetic character.
* Subsequent characters must be ASCII alphabetic or numeric characters, dots or dashes; `[a..z][0..9].-`.
* Database names are case-insensitive and normalized to lowercase.
* Database names that begin with an underscore (`_`) or with the prefix `system` are reserved for internal use.

Database names may include dots (`.`) without being quoted with backticks, although this behavior is deprecated as it may introduce ambiguity when addressing composite databases.
Naming a database `foo.bar.baz` is valid, but deprecated. `++`foo.bar.baz`++` is valid.
--
====



====
[source, cypher, role=noheader]
----
SHOW DATABASES
----

[.description]
List all databases in Neo4j DBMS and information about them, returns only the default outputs (`name`, `type`, `aliases`, `access`, `address`, `role`, `writer`, `requestedStatus`, `currentStatus`, `statusMessage`, `default`, `home`, and `constituents`).
====


====
[source, cypher, role=noheader]
----
SHOW DATABASES YIELD *
----

[.description]
List all databases in Neo4j DBMS and information about them.
====


====
[source, cypher, role=noheader]
----
SHOW DATABASES
YIELD name, currentStatus
WHERE name CONTAINS 'my'
  AND currentStatus = 'online'
----

[.description]
List information about databases, filtered by `name` and `currentStatus` and further refined by conditions on these.
====


====
[source, cypher, role=noheader]
----
SHOW DATABASE `database-name` YIELD *
----

[.description]
List information about the database `database-name`.
====


====
[source, cypher, role=noheader]
----
SHOW DATABASES YIELD name, defaultLanguage
----

[.description]
List the default Cypher version of databases.
====


====
[source, cypher, role=noheader]
----
SHOW DEFAULT DATABASE
----

[.description]
List information about the default database, for the Neo4j DBMS.
====


====
[source, cypher, role=noheader]
----
SHOW HOME DATABASE
----

[.description]
List information about the current users home database.
====

[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
DROP DATABASE `database-name` IF EXISTS
----

[.description]
Delete the database `database-name`, if it exists. This command can delete both standard and composite databases.
====

[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
DROP COMPOSITE DATABASE `composite-database-name`
----

[.description]
Delete the database named `composite-database-name`. In case the given database name does not exist or is not composite, and error will be thrown.
====

[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
DROP DATABASE `database-name` CASCADE ALIASES
----

[.description]
Drop the database `database-name` and any database aliases referencing the database.
This command can drop both standard and composite databases.
For standard databases, the database aliases that will be dropped are any local database aliases targeting the database.
For composite databases, the database aliases that will be dropped are any constituent database aliases belonging to the composite database.

====

[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
CREATE DATABASE `database-name` IF NOT EXISTS
----

[.description]
Create a standard database named `database-name` if it does not already exist.
====

[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
CREATE OR REPLACE DATABASE `database-name`
----

[.description]
Create a standard database named `database-name`. If a database with that name exists, then the existing database is deleted and a new one created.
====

[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
CREATE DATABASE `topology-example` IF NOT EXISTS
TOPOLOGY 1 PRIMARY 0 SECONDARIES
----

[.description]
Create a standard database named `topology-example` in a cluster environment, to use 1 primary server and 0 secondary servers.
====

[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
CREATE COMPOSITE DATABASE `composite-database-name`
----

[.description]
Create a composite database named `composite-database-name`.
====

[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
CREATE [COMPOSITE] DATABASE actors SET DEFAULT LANGUAGE CYPHER 25
----

[.description]
--
Set the default Cypher version for a standard or composite database when creating it.
The available versions are `CYPHER 25` and `CYPHER 5`.
If not specified, the default language for the database is set to the default language of the DBMS.
--
====

[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
STOP DATABASE `database-name`
----

[.description]
Stop a database named `database-name`.
====

[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
START DATABASE `database-name`
----

[.description]
Start a database named `database-name`.
====

[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
ALTER DATABASE `database-name` IF EXISTS
SET ACCESS READ ONLY
----

[.description]
Modify a standard database named `database-name` to accept only read queries.
====

[role=label--enterprise-edition label--aura-db-free label--aura-db-professional label--aura-db-enterprise label--aura-db-business-critical label--aura-ds-professional label--aura-ds-enterprise]
====
[source, cypher, role=noheader]
----
ALTER DATABASE movies SET DEFAULT LANGUAGE CYPHER 25
----

[.description]
Alter the default Cypher version of an existing standard or composite database.
The available versions are `CYPHER 25` and `CYPHER 5`.
====


[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
ALTER DATABASE `database-name` IF EXISTS
SET ACCESS READ WRITE
----

[.description]
Modify a standard database named `database-name` to accept write and read queries.
====

[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
ALTER DATABASE `topology-example`
SET TOPOLOGY 1 PRIMARY 0 SECONDARIES
----

[.description]
Modify a standard database named `topology-example` in a cluster environment to use 1 primary server and 0 secondary servers.
====

[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
ALTER DATABASE `topology-example`
SET TOPOLOGY 1 PRIMARY
SET ACCESS READ ONLY
----

[.description]
Modify a standard database named `topology-example` in a cluster environment to use 1 primary servers and 0 secondary servers, and to only accept read queries.
====