= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/duration/[Duration functions^]



====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/duration.adoc[tag=functions_duration]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/duration/#functions-duration[`duration()`^] function can construct a `DURATION` from a `MAP` of its components.
====

====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/duration.adoc[tag=functions_duration_from_string]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/duration/#functions-duration-create-string[`duration()` from a string^] function returns the `DURATION` value obtained by parsing a `STRING` representation of a temporal amount.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/duration.adoc[tag=functions_duration_between]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/duration/#functions-duration-between[`duration.between()`^] function returns the `DURATION` value equal to the difference between the two given instants.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/duration.adoc[tag=functions_duration_in_days]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/duration/#functions-duration-indays[`duration.inDays()`^] function returns the `DURATION` value equal to the difference in whole days or weeks between the two given instants.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/duration.adoc[tag=functions_duration_in_months]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/duration/#functions-duration-inmonths[`duration.inMonths()`^] function returns the `DURATION` value equal to the difference in whole months between the two given instants.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/duration.adoc[tag=functions_duration_in_seconds]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/duration/#functions-duration-inseconds[`duration.inSeconds()`^] function returns the `DURATION` value equal to the difference in seconds and nanoseconds between the two given instants.
====
