= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/indexes/semantic-indexes/full-text-indexes/[Full-text indexes]


====
include::ROOT:indexes/semantic-indexes/full-text-indexes.adoc[tag=indexes_semantic_fulltext_create]

[.description]
--
Create a fulltext index.
With `IF NOT EXISTS`, no error is thrown and nothing happens should an index with the same name, schema or both already exist.

Best practice is to always specify a sensible name when creating an index.
--
====

====
include::ROOT:indexes/semantic-indexes/full-text-indexes.adoc[tag=indexes_semantic_fulltext_create_options]

[.description]
Create a fulltext index using the `OPTIONS` map to specify an `indexConfig`.
====


====
include::ROOT:indexes/semantic-indexes/full-text-indexes.adoc[tag=indexes_semantic_fulltext_query]

[.description]
Query a node fulltext index with the `db.index.fulltext.queryNodes()` procedure.
Fulltext indexes on relationships are queried using the `db.index.fulltext.queryRelationships()` procedure.
====


====
include::ROOT:indexes/semantic-indexes/full-text-indexes.adoc[tag=indexes_semantic_fulltext_show]

[.description]
Show all fulltext indexes.
For more information about specifying return columns and filtering, see the general xref:index.adoc#_show[`SHOW`] section.
====


====
include::ROOT:indexes/semantic-indexes/full-text-indexes.adoc[tag=indexes_semantic_fulltext_drop]

[.description]
Drop a fulltext index by name.
====






