= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/graph/[Graph functions^]


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/graph.adoc[tag=functions_graph_names]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/graph/#functions-graph-names[`graph.names()`^] function returns a list containing the names of all graphs on the current composite database.
It is only supported on link:{neo4j-docs-base-uri}/operations-manual/current/database-administration/composite-databases/concepts/[composite databases].
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/graph.adoc[tag=functions_graph_properties_by_name]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/graph/#functions-graph-propertiesbyname[`graph.propertiesByName()`^] function returns a map containing the properties associated with the given graph. The properties are set on the link:{neo4j-docs-base-uri}/operations-manual/current/database-administration/aliases/manage-aliases-standard-databases/[alias] that adds the graph as a constituent of a composite database.
It is only supported on link:{neo4j-docs-base-uri}/operations-manual/current/database-administration/composite-databases/concepts/[composite databases].
====

====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/graph.adoc[tag=functions_graph_by_name]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/graph/#functions-graph-byname[`graph.byName()`^] function resolves a constituent graph by name.
It is only supported in the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/use/[`USE`] clause on link:{neo4j-docs-base-uri}/operations-manual/current/database-administration/composite-databases/concepts/[composite databases].
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/graph.adoc[tag=functions_graph_by_element_id]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/graph/#functions-graph-by-elementid[`graph.byElementId()`^] function is used in the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/use/[`USE`] clause to resolve a constituent graph to which a given element id belongs.
If the constituent database is not a standard database in the DBMS, an error will be thrown.
====