= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/schema/graph-types/[Graph types^]

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/graph-types/extend-graph-types.adoc[tag=schema_graph_types_set]
// example taken from extend-graph-types.adoc as it does not include any <1> symbols.

[.description]
Graph types can be set with command `ALTER CURRENT GRAPH TYPE SET`.
A graph type enables users to impose a schema on the nodes, relationships, and properties included in the graph type.
Cypher supports open graph types, meaning that a graph type only constrains the data included by the graph type.
It does not impose any constraints on nodes, relationships, and properties not included by the graph type.
*Setting a graph type will replace any existing graph type/constraints in a database.*
====

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/graph-types/extend-graph-types.adoc[tag=schema_graph_types_add]

[.description]
Graph types can be extended with the command `ALTER CURRENT GRAPH TYPE ADD`.
====

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/graph-types/alter-element-types.adoc[tag=schema_graph_types_alter]

[.description]
The node element types and relationship element types in a graph type can be altered with the command `ALTER CURRENT GRAPH TYPE ALTER`.
*This replaces the previous definition of that element type with the new definition.*
====

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/graph-types/list-graph-types.adoc[tag=schema_graph_types_show]

[.description]
The graph type of a database can be shown using the command `SHOW CURRENT GRAPH TYPE`.
This command returns one column, `specification`, which is returned by default.
For more information about specifying return columns and filtering, see the general xref:index.adoc#_show[`SHOW`] section.
====

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/graph-types/list-graph-types.adoc[tag=schema_graph_types_show_as_graph]

[.description]
The graph type of a database can be shown as a virtual graph using the command `SHOW CURRENT GRAPH TYPE AS GRAPH`.
This command returns two columns, `nodes` and `relationships`.
Both are returned by default.
For more information about specifying return columns and filtering, see the general xref:index.adoc#_show[`SHOW`] section.
====

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/graph-types/drop-graph-type-elements.adoc[tag=schema_graph_types_drop_elements]

[.description]
Node element types and relationship element types can be dropped from a graph type with the command `ALTER CURRENT GRAPH TYPE DROP`.
====

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/graph-types/drop-graph-type-elements.adoc[tag=schema_graph_types_drop_constraints]

[.description]
Constraints in a graph type can be dropped using the `CONSTRAINT name` syntax inside the `ALTER CURRENT GRAPH TYPE DROP` command.
====

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
include::ROOT:schema/graph-types/drop-graph-type-elements.adoc[tag=schema_graph_types_drop_full]

[.description]
To drop a full graph type, use the `ALTER CURRENT GRAPH TYPE SET` command.
This will replace the existing graph type with a new (possibly empty) graph type.
====