= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/expressions/list-expressions[List expressions^]

====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_element_access]

[.description]
The subscript operator, `[]`, can be used to access specific elements in a `LIST`.
`[0]` refers to the first element in a `LIST`, `[1]` to the second, and so on.
`[-1]` refers to the last element in a `LIST`, `[-2]` to the penultimate element, and so on.
====


====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_nested_list_access]

[.description]
Access a `LIST` within a nested `LIST`.
====


====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_nested_list_specific_element_access]

[.description]
Access specific elements in a nested `LIST`.
====


====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_slicing]

[.description]
`LIST` values can be sliced if a range is provided within the subscript operator `[]`.
The bounds of the range are separated using two dots (`..`).
This allows for extracting a subset of a `LIST` rather than a single element.
List slicing is inclusive at the start of the range, but exclusive at the end (e.g. `list[start..end]` includes `start`, but excludes `end`).
====


====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_negative_slicing]

[.description]
Negative indexing in list slicing references elements from the end of the `LIST`; `..-1` excludes the last element, `..-2` excludes the last two elements, and so on.
====


====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_slice_inner_list]

[.description]
Slicing inner `LIST` values require two `[]` operators; the first `[]` accesses elements from the outer `LIST`, while the second slices or accesses elements from the inner `LIST`.
====


====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_concatenation]

[.description]
Cypher contains two list concatenation operators: `||` and `\+`.
They are functionally equivalent but `||` is GQL conformant and `+` is not.
====


====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_add_elements]

[.description]
The `+` operator can add elements to the beginning or end of a `LIST` value.
This is not possible using the `||` operator.
====


====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_comprehension]

[.description]
List comprehension is used to create new `LIST` values by iterating over existing `LIST` values and transforming the elements based on certain conditions or operations.
This process effectively maps each element in the original `LIST` to a new value.
The result is a new `LIST` that consists of the transformed elements.
====


====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_comprehension_properties]

[.description]
List comprehension using node properties.
====


====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_comprehension_where]

[.description]
List comprehension with a `WHERE` predicate.
====


====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_comprehension_concatenation_remove_null]

[.description]
List comprehension can be used to remove any unknown `NULL` values when concatenating `LIST` values.
====

====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_pattern_comprehension]

[.description]
Pattern comprehension is used to create new `LIST` values by matching graph patterns and applying conditions to the matched elements, returning custom projections.
====


====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_pattern_comprehension_where]

[.description]
Pattern comprehension with a `WHERE` predicate.
====


====
include::ROOT:expressions/list-expressions.adoc[tag=expressions_list_pattern_comprehension_var_length]

[.description]
Variable-length pattern comprehension.
====
