= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/[List functions^]

====
include::ROOT:functions/list.adoc[tag=functions_list_distinct]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-coll-distinct[`coll.distinct()`^] function returns a given list with all duplicate values removed.
====

====
include::ROOT:functions/list.adoc[tag=functions_list_flatten]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-coll-flatten[`coll.flatten()`^] function returns a list flattened to the given nesting depth, default is 1.
====

====
include::ROOT:functions/list.adoc[tag=functions_list_indexOf]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-coll-indexOf[`coll.indexOf()`^] function returns the index of the first match of a value in the given list or -1 if the value is not present.
====

====
include::ROOT:functions/list.adoc[tag=functions_list_insert]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-coll-insert[`coll.insert()`^] function returns a list with the given value inserted at the given index.
====

====
include::ROOT:functions/list.adoc[tag=functions_list_max]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-coll-max[`coll.max()`^] function returns the largest value present in the given list.
====

====
include::ROOT:functions/list.adoc[tag=functions_list_min]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-coll-min[`coll.min()`^] function returns the smallest value present in the given list.
====

====
include::ROOT:functions/list.adoc[tag=functions_list_remove]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-coll-remove[`coll.remove()`^] function returns a list with the value at the given index removed.
====

====
include::ROOT:functions/list.adoc[tag=functions_list_sort]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-coll-sort[`coll.sort()`^] function returns a sorted list.
====




====
include::ROOT:functions/list.adoc[tag=functions_list_keys]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-keys[`keys()`^] function returns a `LIST<STRING>` containing the `STRING` representations for all the property names of a `NODE`, `RELATIONSHIP`, or `MAP`.
====


====
include::ROOT:functions/list.adoc[tag=functions_list_labels]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-labels[`labels()`^] function returns a `LIST<STRING>` containing the `STRING` representations for all the labels of a `NODE`.
====


====
include::ROOT:functions/list.adoc[tag=functions_list_nodes]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-nodes[`nodes()`^] function returns a `LIST<NODE>` containing all the `NODE` values in a `PATH`.
====


====
include::ROOT:functions/list.adoc[tag=functions_list_range]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-range[`range()`^] function returns a `LIST<INTEGER>` comprising all `INTEGER` values within a range bounded by a start value and an end value, where the difference step between any two consecutive values is constant; i.e. an arithmetic progression.
====


====
include::ROOT:functions/list.adoc[tag=functions_list_reduce]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-reduce[`reduce()`^] function returns the value resulting from the application of an expression on each successive element in a list in conjunction with the result of the computation thus far.
====

====
include::ROOT:functions/list.adoc[tag=functions_list_relationships]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-relationships[`relationships()`^] function returns a `LIST<RELATIONSHIP>` containing all the `RELATIONSHIP` values in a `PATH`.
====

====
include::ROOT:functions/list.adoc[tag=functions_list_reverse]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-reverse-list[`reverse()`^] function returns a `LIST<ANY>` in which the order of all elements in the given `LIST<ANY>` have been reversed.
====

====
include::ROOT:functions/list.adoc[tag=functions_list_tail]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-tail[`tail()`^] function returns a `LIST<ANY>` containing all the elements, excluding the first one, from a given `LIST<ANY>`.
====


====
include::ROOT:functions/list.adoc[tag=functions_list_to_boolean_list]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-tobooleanlist[`toBooleanList()`^] converts a `LIST<ANY>` and returns a `LIST<BOOLEAN>`.
If any values are not convertible to `BOOLEAN` they will be `null` in the `LIST<BOOLEAN>` returned.
====


====
include::ROOT:functions/list.adoc[tag=functions_list_to_float_list]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-tofloatlist[`toFloatList()`^] converts a `LIST<ANY>` of values and returns a `LIST<FLOAT>`.
If any values are not convertible to `FLOAT` they will be `null` in the `LIST<FLOAT>` returned.
====


====
include::ROOT:functions/list.adoc[tag=functions_list_to_integer_list]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-tointegerlist[`toIntegerList()`^] converts a `LIST<ANY>` of values and returns a `LIST<INTEGER>`.
If any values are not convertible to `INTEGER` they will be `null` in the `LIST<INTEGER>` returned.
====


====
include::ROOT:functions/list.adoc[tag=functions_list_to_string_list]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/list/#functions-tostringlist[`toStringList()`^] converts a `LIST<ANY>` of values and returns a `LIST<STRING>`.
If any values are not convertible to `STRING` they will be `null` in the `LIST<STRING>` returned.
====
