= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/load-csv/[LOAD CSV^]


====
include::ROOT:clauses/load-csv.adoc[tag=clauses_load_csv_local_files]

[.description]
`LOAD CSV` is used to import data from CSV files into a Neo4j database.
This example imports the name and year information of artists from a local file.
====

====
include::ROOT:clauses/load-csv.adoc[tag=clauses_load_csv_remote_locations]

[.description]
Import artists name and year information from a remote file URL.
====

====
include::ROOT:clauses/load-csv.adoc[tag=clauses_load_csv_dynamic_columns]

[.description]
CSV columns can be referenced dynamically to map labels to nodes in the graph.
This enables flexible data handling, allowing labels to be be populated from CSV column values without manually specifying each entry.
====

====
include::ROOT:clauses/load-csv.adoc[tag=clauses_load_csv_transactions]

[.description]
Load a CSV file in several link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/subqueries/subqueries-in-transactions/[transactions].
This example uses a link:https://neo4j.com/docs/cypher-manual/current/subqueries/call-subquery/#variable-scope-clause[variable scope clause] (introduced in Neo4j 5.23) to import variables into the `CALL` subquery.
====

====
include::ROOT:clauses/load-csv.adoc[tag=clauses_load_csv_linenumber]

[.description]
Access line numbers in a CSV with the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/load-csv/#functions-linenumber[`linenumber()`] function.
====

====
include::ROOT:clauses/load-csv.adoc[tag=clauses_load_csv_file]

[.description]
Access the CSV file path with the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/load-csv/#functions-file[`file()`] function.
====

====
include::ROOT:clauses/load-csv.adoc[tag=clauses_load_csv_headers]

[.description]
Load CSV data with headers.
====

====
include::ROOT:clauses/load-csv.adoc[tag=clauses_load_csv_field_terminator]

[.description]
Import a CSV using `;` as field delimiter.
====