= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/patterns/match-modes/[Match modes^]

====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/patterns/match-modes.adoc[tag=patterns_match_modes_different_relationships]

[.description]
Cypher's default match mode is `DIFFERENT RELATIONSHIPS`.
This is a restrictive match mode, which requires that all relationships matched across all constituent path patterns in a graph pattern must be unique.
The match mode can be explicitly defined by adding `DIFFERENT RELATIONSHIPS` after `MATCH`.
Explicitly defining `DIFFERENT RELATIONSHIPS` is functionally equivalent to not specifying a match mode.
====

====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/patterns/match-modes.adoc[tag=patterns_match_modes_repeatable_elements]

[.description]
`REPEATABLE ELEMENTS` is a non-restrictive match mode, in which relationships matched across all constituent path patterns in a graph pattern can be repeatedly traversed.
Queries using `REPEATABLE ELEMENTS` must specify an upper bound to a pattern to ensure that a finite number of solutions are returned in a finite amount of time (i.e. quantifiers such as `*`, `+`, or `{1,}` are not allowed using `REPEATABLE ELEMENTS`).
====
