= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric[Mathematical Functions - trigonometric^]



====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_acos]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-acos[`acos()`^] function returns the arccosine of a `FLOAT` in radians.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_asin]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-asin[`asin()`^] function returns the arcsine of a `FLOAT` in radians.
====

====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_atan]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-atan[`atan()`^] function returns the arctangent of a `FLOAT` in radians.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_atan2]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-atan2[`atan2()`^] function returns the arctangent2 of a set of coordinates in radians.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_cos]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-cos[`cos()`^] function returns the cosine of a `FLOAT`.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_cosh]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-cosh[`cosh()`^] function returns the hyperbolic cosine of a `FLOAT`.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_cot]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-cot[`cot()`^] function returns the cotangent of a `FLOAT`.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_coth]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-coth[`coth()`^] function returns the hyperbolic cotangent of a `FLOAT`.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_degrees]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-degrees[`degrees()`^] function converts radians to degrees.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_haversin]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-haversin[`haversin()`^] function converts half the versine of a number.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_pi]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-pi[`pi()`^] function returns the mathematical constant _pi_.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_radians]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-radians[`radians()`^] function converts degrees to radians.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_sin]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-sin[`sin()`^] function returns the sine of a number.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_sinh]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-sinh[`sinh()`^] function returns the hyperbolic sine of a `FLOAT`.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_tan]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-tan[`tan()`^] function returns the tangent of a number.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-trigonometric.adoc[tag=functions_mathematical_trigonometric_tanh]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-trigonometric/#functions-tanh[`tanh()`^] function returns the hyperbolic tangent of a `FLOAT`.
====
