= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-logarithmic[Mathematical functions - logarithmic^]



====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-logarithmic.adoc[tag=functions_mathematical_logarithmic_e]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-logarithmic/#functions-e[`e()`^] function returns the base of the natural logarithm, _e_.
====

====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-logarithmic.adoc[tag=functions_mathematical_logarithmic_exp]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-logarithmic/#functions-exp[`exp()`^] function returns `e^n^`, where `e` is the base of the natural logarithm, and `n` is the value of the argument expression.
====

====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-logarithmic.adoc[tag=functions_mathematical_logarithmic_log]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-logarithmic/#functions-log[`log()`^] function returns the natural logarithm of a number.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-logarithmic.adoc[tag=functions_mathematical_logarithmic_log10]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-logarithmic/#functions-log10[`log10()`^] function returns the common logarithm (base 10) of a number.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/mathematical-logarithmic.adoc[tag=functions_mathematical_logarithmic_sqrt]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-logarithmic/#functions-sqrt[`sqrt()`^] function returns the square root of a number.
====
