= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-numeric[Mathematical functions - numerical^]



====
include::ROOT:functions/mathematical-numeric.adoc[tag=functions_mathematical_numeric_abs]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-numeric/#functions-abs[`abs()`^] function returns the absolute value of the given number.
====

====
include::ROOT:functions/mathematical-numeric.adoc[tag=functions_mathematical_numeric_ceil]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-numeric/#functions-ceil[`ceil()`^] function returns the smallest `FLOAT` that is greater than or equal to the given number and equal to an `INTEGER`.
====



====
include::ROOT:functions/mathematical-numeric.adoc[tag=functions_mathematical_numeric_floor]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-numeric/#functions-floor[`floor()`^] function returns the largest `FLOAT` that is less than or equal to the given number and equal to an `INTEGER`.
====

====
include::ROOT:functions/mathematical-numeric.adoc[tag=functions_mathematical_numeric_is_nan]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-numeric/#functions-isnan[`isNan()`^] function returns `true` if the given numeric value is `NaN` (Not a Number).
====


====
include::ROOT:functions/mathematical-numeric.adoc[tag=functions_mathematical_numeric_rand]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-numeric/#functions-rand[`rand()`^] function returns a random `FLOAT` in the range from 0 (inclusive) to 1 (exclusive).
The numbers returned follow an approximate uniform distribution.
====


====
include::ROOT:functions/mathematical-numeric.adoc[tag=functions_mathematical_numeric_round]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-numeric/#functions-round[`round()`^] function returns the value of the given number rounded to the nearest `INTEGER`, with ties always rounded towards positive infinity.
====


====
include::ROOT:functions/mathematical-numeric.adoc[tag=functions_mathematical_numeric_round_with_precision]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-numeric/#functions-round2[`round()` with precision^] function returns the value of the given number rounded to the closest value of given precision, with ties always being rounded away from zero (using rounding mode `HALF_UP`).
The exception is for precision 0, where ties are rounded towards positive infinity to align with `round()` without precision.
====

====
include::ROOT:functions/mathematical-numeric.adoc[tag=functions_mathematical_numeric_round_with_precision_and_rounding_mode]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-numeric/#functions-round3[`round()` with precision and rounding mode^] function returns the value of the given number rounded with the specified precision and the specified rounding mode.
====

====
include::ROOT:functions/mathematical-numeric.adoc[tag=functions_mathematical_numeric_sign]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/mathematical-numeric/#functions-sign[`sign()`^] function returns the signum of the given number: `0` if the number is 0, `-1` for any negative number, and `1` for any positive number.
====
