= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/patterns/fixed-length-paths/[Non-linear paths^]


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/patterns/non-linear-paths.adoc[tag=patterns_non_linear_paths_equijoin]

[.description]
An equijoin is an operation on paths that requires more than one of the nodes or relationships of the paths to be the same.
The equality between the nodes or relationships is specified by declaring a node variable or relationship variable more than once.
An equijoin on nodes allows cycles to be specified in a path pattern.
Due to link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/patterns/reference/#graph-patterns-rules-relationship-uniqueness[relationship uniqueness^], an equijoin on relationships yields no solutions.
====

====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/patterns/non-linear-paths.adoc[tag=patterns_non_linear_paths_graph_pattern]

[.description]
Multiple path patterns can be combined in a comma-separated list to form a graph pattern.
In a graph pattern, each path pattern is matched separately, and where node variables are repeated in the separate path patterns, the solutions are reduced via equijoins.
====