[.neo4j-ee.aura-dbe.aura-dbc]
= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/dbms-administration/dbms-role-management-privileges/[ON DBMS - ROLE MANAGEMENT Privileges^]

////
[source, cypher, role=test-setup]
----
CREATE ROLE role_name;
----
////

====
[source, cypher, role=noheader]
----
GRANT ROLE MANAGEMENT
ON DBMS TO role_name
----

[.description]
--
Grant `ROLE MANAGEMENT` privilege to manage roles to the specified role. 

* Allow creating roles - (`GRANT CREATE ROLE`).
* Allow renaming roles - (`GRANT RENAME ROLE`).
* Allow deleting roles - (`GRANT DROP ROLE`).
* Allow assigning (`GRANT`) roles to a user - (`GRANT ASSIGN ROLE`).
* Allow removing (`REVOKE`) roles from a user - (`GRANT REMOVE ROLE`).
* Allow listing roles - (`GRANT SHOW ROLE`).
--
====


====
[source, cypher, role=noheader]
----
GRANT CREATE ROLE
ON DBMS TO role_name
----

[.description]
Grant `CREATE ROLE` privilege to create roles to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT RENAME ROLE
ON DBMS TO role_name
----

[.description]
Grant `RENAME ROLE` privilege to rename roles to the specified role.
====


====
[source, cypher, role=noheader]
----
DENY DROP ROLE
ON DBMS TO role_name
----

[.description]
Deny `DROP ROLE` privilege to delete roles to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT ASSIGN ROLE
ON DBMS TO role_name
----

[.description]
Grant `ASSIGN ROLE` privilege to assign roles to users to the specified role.
====


====
[source, cypher, role=noheader]
----
DENY REMOVE ROLE
ON DBMS TO role_name
----

[.description]
Deny `REMOVE ROLE` privilege to remove roles from users to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT SHOW ROLE
ON DBMS TO role_name
----

[.description]
Grant `SHOW ROLE` privilege to list roles to the specified role.
====