[role=label--enterprise-edition label--aura-db-enterprise label--aura-db-business-critical]
= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-transaction[ON DATABASE - TRANSACTION MANAGEMENT Privileges^]

////
[source, cypher, role=test-setup]
----
CREATE ROLE role_name;
----
////


====
[source, cypher, role=noheader]
----
GRANT TRANSACTION MANAGEMENT (*)
ON DATABASE * TO role_name
----

[.description]
--
Grant `TRANSACTION MANAGEMENT` privilege to show and terminate transactions on all users, for all databases, to the specified role. 

* Allow listing transactions - (`GRANT SHOW TRANSACTION`).
* Allow terminate transactions - (`GRANT TERMINATE TRANSACTION`).
--
====


====
[source, cypher, role=noheader]
----
GRANT SHOW TRANSACTION (*)
ON DATABASE * TO role_name
----

[.description]
Grant `SHOW TRANSACTION` privilege to list transactions on all users on all databases to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT SHOW TRANSACTION (user_name1, user_name2)
ON HOME DATABASE TO role_name1, role_name2
----

[.description]
Grant `SHOW TRANSACTION` privilege to list transactions by the specified users on home database to the specified roles.
====


====
[source, cypher, role=noheader]
----
GRANT TERMINATE TRANSACTION (*)
ON DATABASE * TO role_name
----

[.description]
Grant `TERMINATE TRANSACTION` privilege to terminate transactions on all users on all databases to the specified role.
====