[.neo4j-ee.aura-dbe.aura-dbc]
= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/dbms-administration/#access-control-dbms-administration-privilege-management[ON DBMS - PRIVILEGE MANAGEMENT Privileges^]

////
[source, cypher, role=test-setup]
----
CREATE ROLE role_name;
----
////

====
[source, cypher, role=noheader]
----
GRANT PRIVILEGE MANAGEMENT
ON DBMS TO role_name
----

[.description]
--
Grant `PRIVILEGE MANAGEMENT` privilege to manage privileges for the Neo4j DBMS to the specified role. 

* Allow assigning (`GRANT|DENY`) privileges for a role - (`GRANT ASSIGN PRIVILEGE`).
* Allow removing (`REVOKE`) privileges for a role - (`GRANT REMOVE PRIVILEGE`).
* Allow listing privileges - (`GRANT SHOW PRIVILEGE`).
--
====


====
[source, cypher, role=noheader]
----
GRANT ASSIGN PRIVILEGE
ON DBMS TO role_name
----

[.description]
Grant `ASSIGN PRIVILEGE` privilege, allows the specified role to assign privileges for roles.
====


====
[source, cypher, role=noheader]
----
GRANT REMOVE PRIVILEGE
ON DBMS TO role_name
----

[.description]
Grant `REMOVE PRIVILEGE` privilege, allows the specified role to remove privileges for roles.
====


====
[source, cypher, role=noheader]
----
GRANT SHOW PRIVILEGE
ON DBMS TO role_name
----

[.description]
Grant `SHOW PRIVILEGE` privilege to list privileges to the specified role.
====