[role=label--enterprise-edition label--aura-db-enterprise label--aura-db-business-critical]
= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/dbms-administration/dbms-database-management-privileges/[ON DBMS - DATABASE MANAGEMENT Privileges^]

////
[source, cypher, role=test-setup]
----
CREATE ROLE role_name;
----
////

====
[source, cypher, role=noheader]
----
GRANT DATABASE MANAGEMENT
ON DBMS TO role_name
----

[.description]
--
Grant `DATABASE MANAGEMENT` privilege to manage databases to the specified role. 

* Allow creating standard databases - (`GRANT CREATE DATABASE`).
* Allow deleting standard databases - (`GRANT DROP DATABASE`).
* Allow modifying standard databases - (`GRANT ALTER DATABASE`).
* Allow managing composite databases - (`GRANT COMPOSITE DATABASE MANAGEMENT`).
--
====


====
[source, cypher, role=noheader]
----
GRANT CREATE DATABASE
ON DBMS TO role_name
----

[.description]
Grant `CREATE DATABASE` privilege to create standard databases to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT DROP DATABASE
ON DBMS TO role_name
----

[.description]
Grant `DROP DATABASE` privilege to delete standard databases to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT ALTER DATABASE
ON DBMS TO role_name
----

[.description]
--
Grant `ALTER DATABASE` privilege to alter standard databases the specified role.

* Allow modifying access mode for standard databases - (`GRANT SET DATABASE ACCESS`).
* Allow modifying topology settings for standard databases.
--
====


====
[source, cypher, role=noheader]
----
GRANT SET DATABASE ACCESS
ON DBMS TO role_name
----

[.description]
Grant `SET DATABASE ACCESS` privilege to set database access mode for standard databases to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT COMPOSITE DATABASE MANAGEMENT
ON DBMS TO role_name
----

[.description]
--
Grant all privileges to manage composite databases to the specified role. 

* Allow creating composite databases - (`CREATE COMPOSITE DATABASE`).
* Allow deleting composite databases - (`DROP COMPOSITE DATABASE`).
--
====


====
[source, cypher, role=noheader]
----
DENY CREATE COMPOSITE DATABASE
ON DBMS TO role_name
----

[.description]
Denies the specified role the privilege to create composite databases.
====


====
[source, cypher, role=noheader]
----
REVOKE DROP COMPOSITE DATABASE
ON DBMS FROM role_name
----

[.description]
Revokes the granted and denied privileges to delete composite databases from the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT SERVER MANAGEMENT
ON DBMS TO role_name
----

[.description]
Enables the specified role to show, enable, rename, alter, reallocate, deallocate, and drop servers.
====


====
[source, cypher, role=noheader]
----
DENY SHOW SERVERS
ON DBMS TO role_name
----

[.description]
Denies the specified role the privilege to show information about the serves.
====