[.neo4j-ee.aura-dbe.aura-dbc]
= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/dbms-administration/#access-control-dbms-administration-user-management[ON DBMS - USER MANAGEMENT Privileges^]

////
[source, cypher, role=test-setup]
----
CREATE ROLE role_name;
----
////

====
[source, cypher, role=noheader]
----
GRANT USER MANAGEMENT
ON DBMS TO role_name
----

[.description]
--
Grant `USER MANAGEMENT` privilege to manage users to the specified role. 

* Allow creating users - (`GRANT CREATE USER`).
* Allow renaming users - (`GRANT RENAME USER`).
* Allow modifying a user - (`GRANT ALTER USER`).
* Allow deleting users - (`GRANT DROP USER`).
* Allow listing users - (`GRANT SHOW USER`).
--
====


====
[source, cypher, role=noheader]
----
DENY CREATE USER
ON DBMS TO role_name
----

[.description]
Deny `CREATE USER` privilege to create users to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT RENAME USER
ON DBMS TO role_name
----

[.description]
Grant `RENAME USER` privilege to rename users to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT ALTER USER
ON DBMS TO role_name
----

[.description]
--
Grant `ALTER USER` privilege to alter users to the specified role. 

* Allow changing a user's password - (`GRANT SET PASSWORD`).
* Allow adding or removing a user's auth providers - (`GRANT SET AUTH`).
* Allow changing a user's home database - (`GRANT SET USER HOME DATABASE`).
* Allow changing a user's status - (`GRANT USER STATUS`).
--
====


====
[source, cypher, role=noheader]
----
DENY SET PASSWORD
ON DBMS TO role_name
----

[.description]
Deny `SET PASSWORD` privilege to alter a user password to the specified role.
====

====
[source, cypher, role=noheader]
----
GRANT SET AUTH
ON DBMS TO role_name
----

[.description]
Grant `SET AUTH` privilege to add/remove auth providers to the specified role.
====

====
[source, cypher, role=noheader]
----
GRANT SET USER HOME DATABASE
ON DBMS TO role_name
----

[.description]
Grant `SET USER HOME DATABASE` privilege to alter the home database of users to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT SET USER STATUS
ON DBMS TO role_name
----

[.description]
Grant `SET USER STATUS` privilege to alter user account status to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT DROP USER
ON DBMS TO role_name
----

[.description]
Grant `DROP USER` privilege to delete users to the specified role.
====


====
[source, cypher, role=noheader]
----
DENY SHOW USER
ON DBMS TO role_name
----

[.description]
Deny `SHOW USER` privilege to list users to the specified role.
====