[role=label--enterprise-edition label--aura-db-enterprise label--aura-db-business-critical]
= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/[ON DATABASE Privileges^]

////
[source, cypher, role=test-setup]
----
CREATE ROLE role_name;
----
////


====
[source, cypher, role=noheader]
----
GRANT ALL DATABASE PRIVILEGES
ON DATABASE * TO role_name
----

[.description]
--
Grant `ALL DATABASE PRIVILEGES` privilege for all databases to the specified role. 

* Allows access (`GRANT ACCESS`).
* Index management (`GRANT INDEX MANAGEMENT`).
* Constraint management (`GRANT CONSTRAINT MANAGEMENT`).
* Name management (`GRANT NAME MANAGEMENT`).

Note that the privileges for starting and stopping all databases, and transaction management, are not included.
--
====


====
[source, cypher, role=noheader]
----
GRANT ALL ON DATABASE * TO role_name
----

[.description]
--
Short form for grant `ALL DATABASE PRIVILEGES` privilege. 

* `GRANT` – gives privileges to roles.
* `DENY` – denies privileges to roles.

To remove a granted or denied privilege, prepend the privilege query with `REVOKE` and replace the `TO` with `FROM`; (`REVOKE GRANT ALL ON DATABASE * FROM role_name`).
--
====


====
[source, cypher, role=noheader]
----
REVOKE ACCESS
ON HOME DATABASE FROM role_name
----

[.description]
Revoke `ACCESS` privilege to access and run queries against the home database from the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT START
ON DATABASE * TO role_name
----

[.description]
Grant `START` privilege to start all databases to the specified role.
====


====
[source, cypher, role=noheader]
----
DENY STOP
ON HOME DATABASE TO role_name
----

[.description]
Deny `STOP` privilege to stop the home database to the specified role.
====