[role=label--enterprise-edition label--aura-db-enterprise label--aura-db-business-critical]
= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-tokens[ON DATABASE - NAME MANAGEMENT Privileges^]

////
[source, cypher, role=test-setup]
----
CREATE ROLE role_name;
----
////

====
[source, cypher, role=noheader]
----
GRANT NAME MANAGEMENT
ON DATABASE * TO role_name
----

[.description]
--
Grant `NAME MANAGEMENT` privilege to create new labels, new relationship types, and new property names for all databases to the specified role. 

* Allow creating a new label - (`GRANT CREATE NEW LABEL`).
* Allow creating a new relationship type - (`GRANT CREATE NEW TYPE`).
* Allow creating a new property name - (`GRANT CREATE NEW NAME`).
--
====


====
[source, cypher, role=noheader]
----
GRANT CREATE NEW LABEL
ON DATABASE * TO role_name
----

[.description]
Grant `CREATE NEW LABEL` privilege to create new labels on all databases to the specified role.
====


====
[source, cypher, role=noheader]
----
DENY CREATE NEW TYPE
ON DATABASE * TO role_name
----

[.description]
Deny `CREATE NEW TYPE` privilege to create new relationship types on all databases to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT CREATE NEW NAME
ON DATABASE * TO role_name
----

[.description]
Grant `CREATE NEW NAME` privilege to create new property names on all databases to the specified role.
====