[.neo4j-ee.aura-dbe.aura-dbc]
= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/dbms-administration/[ON DBMS Privileges^]

////
[source, cypher, role=test-setup]
----
CREATE ROLE role_name;
----
////

====
[source, cypher, role=noheader]
----
GRANT ALL DBMS PRIVILEGES
ON DBMS TO role_name
----

[.description]
--
Grant `ALL DBMS PRIVILEGES` privilege to perform management for roles, users, databases, aliases, and privileges to the specified role. Also privileges to execute procedures and user defined functions are granted. 

* Allow controlling roles - (`GRANT ROLE MANAGEMENT`).
* Allow controlling users - (`GRANT USER MANAGEMENT`).
* Allow controlling databases - (`GRANT DATABASE MANAGEMENT`).
* Allow controlling aliases - (`GRANT ALIAS MANAGEMENT`).
* Allow controlling privileges - (`GRANT PRIVILEGE MANAGEMENT`).
* Allow user impersonation - (`GRANT IMPERSONATE (*)`).
* Allow to execute all procedures with elevated privileges.
* Allow to execute all user defined functions with elevated privileges.
--
====


====
[source, cypher, role=noheader]
----
GRANT ALL
ON DBMS TO role_name
----

[.description]
--
Short form for grant `ALL DBMS PRIVILEGES` privilege. 

* `GRANT` – gives privileges to roles.
* `DENY` – denies privileges to roles.

To remove a granted or denied privilege, prepend the privilege query with `REVOKE` and replace the `TO` with `FROM`; (`REVOKE GRANT ALL ON DBMS FROM role_name`).
--
====


====
[source, cypher, role=noheader]
----
DENY IMPERSONATE (user_name1, user_name2)
ON DBMS TO role_name
----

[.description]
Deny `IMPERSONATE` privilege to impersonate the specified users (`user_name1` and `user_name2`) to the specified role.
====


====
[source, cypher, role=noheader]
----
REVOKE IMPERSONATE (*)
ON DBMS TO role_name
----

[.description]
Revoke `IMPERSONATE` privilege to impersonate all users from the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT EXECUTE PROCEDURE *
ON DBMS TO role_name
----

[.description]
Enables the specified role to execute all procedures.
====


====
[source, cypher, role=noheader]
----
GRANT EXECUTE BOOSTED PROCEDURE *
ON DBMS TO role_name
----

[.description]
Enables the specified role to use elevated privileges when executing all procedures.
====


====
[source, cypher, role=noheader]
----
GRANT EXECUTE ADMIN PROCEDURES
ON DBMS TO role_name
----

[.description]
Enables the specified role to execute procedures annotated with `@Admin`. The procedures are executed with elevated privileges.
====


====
[source, cypher, role=noheader]
----
GRANT EXECUTE FUNCTIONS *
ON DBMS TO role_name
----

[.description]
Enables the specified role to execute all user defined functions.
====


====
[source, cypher, role=noheader]
----
GRANT EXECUTE BOOSTED FUNCTIONS *
ON DBMS TO role_name
----

[.description]
Enables the specified role to use elevated privileges when executing all user defined functions.
====


[neo4j.ee]
====
[source, cypher, role=noheader]
----
GRANT SHOW SETTINGS *
ON DBMS TO role_name
----

[.description]
Enables the specified role to view all configuration settings.
====