[role=label--enterprise-edition label--aura-db-enterprise label--aura-db-business-critical]
= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-constraints[ON DATABASE - CONSTRAINT MANAGEMENT Privileges^]

////
[source, cypher, role=test-setup]
----
CREATE ROLE role_name;
CREATE DATABASE `database-name` IF NOT EXISTS;
----
////

====
[source, cypher, role=noheader]
----
GRANT CONSTRAINT MANAGEMENT
ON DATABASE * TO role_name
----

[.description]
--
Grant `CONSTRAINT MANAGEMENT` privilege to create, drop, and list constraints for all database to the specified role. 

* Allow creating a constraint - (`GRANT CREATE CONSTRAINT`).
* Allow removing a constraint - (`GRANT DROP CONSTRAINT`).
* Allow listing a constraint - (`GRANT SHOW CONSTRAINT`).
--
====


====
[source, cypher, role=noheader]
----
GRANT CREATE CONSTRAINT
ON DATABASE * TO role_name
----

[.description]
Grant `CREATE CONSTRAINT` privilege to create constraints on all databases to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT DROP CONSTRAINT
ON DATABASE * TO role_name
----

[.description]
Grant `DROP CONSTRAINT` privilege to create constraints on all databases to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT SHOW CONSTRAINT
ON DATABASE `database-name` TO role_name
----

[.description]
Grant `SHOW CONSTRAINT` privilege to list constraints on a specified database to the specified role.
====