[role=label--enterprise-edition label--aura-db-enterprise label--aura-db-business-critical]
= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/privileges-writes/[ON GRAPH Write Privileges^]


====
[source, cypher, role=noheader]
----
GRANT ALL GRAPH PRIVILEGES
ON GRAPH `database-name` TO role_name
----

[.description]
Grant `ALL GRAPH PRIVILEGES` privilege on a specified graph to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT ALL ON GRAPH `database-name` TO role_name
----

[.description]
--
Short form for grant `ALL GRAPH PRIVILEGES` privilege. 

* `GRANT` – gives privileges to roles.
* `DENY` – denies privileges to roles.

To remove a granted or denied privilege, prepend the privilege query with `REVOKE` and replace the `TO` with `FROM`; (`REVOKE GRANT ALL ON GRAPH `database-name` FROM role_name`).
--
====


====
[source, cypher, role=noheader]
----
DENY CREATE
ON GRAPH * NODES node_label TO role_name
----

[.description]
Deny `CREATE` privilege on all nodes with a specified label in all graphs to the specified role.
====


====
[source, cypher, role=noheader]
----
REVOKE DELETE
ON GRAPH `database-name` TO role_name
----

[.description]
Revoke `DELETE` privilege on all nodes and relationships in a specified graph from the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT SET LABEL node_label
ON GRAPH * TO role_name
----

[.description]
Grant `SET LABEL` privilege for the specified label on all graphs to the specified role.
====


====
[source, cypher, role=noheader]
----
DENY REMOVE LABEL *
ON GRAPH `database-name` TO role_name
----

[.description]
Deny `REMOVE LABEL` privilege for all labels on a specified graph to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT SET PROPERTY {prop_name}
ON GRAPH `database-name` RELATIONSHIPS rel_type TO role_name
----

[.description]
Grant `SET PROPERTY` privilege on a specified property, on all relationships with a specified type in a specified graph, to the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT MERGE {*}
ON GRAPH * NODES node_label TO role_name
----

[.description]
Grant `MERGE` privilege on all properties, on all nodes with a specified label in all graphs, to the specified role.
====


====
[source, cypher, role=noheader]
----
REVOKE WRITE
ON GRAPH * FROM role_name
----

[.description]
Revoke `WRITE` privilege on all graphs from the specified role.
====
