[.neo4j-ee.aura-dbe.aura-dbc]
= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/privileges-reads/[ON GRAPH Read Privileges^]


////
[source, cypher, role=test-setup]
----
CREATE ROLE role_name;
CREATE DATABASE `database-name`;
----
////

====
[source, cypher, role=noheader]
----
GRANT TRAVERSE
ON GRAPH * NODE * TO role_name
----

[.description]
--
Grant `TRAVERSE` privilege on all graphs and all nodes to the specified role. 

* `GRANT` – gives privileges to roles.
* `DENY` – denies privileges to roles.
--
====


====
[source, cypher, role=noheader]
----
REVOKE GRANT TRAVERSE
ON GRAPH * NODE * FROM role_name
----

[.description]
To remove a granted or denied privilege, prepend the privilege query with `REVOKE` and replace the `TO` with `FROM`.
====


====
[source, cypher, role=noheader]
----
GRANT TRAVERSE
ON GRAPH * RELATIONSHIP * TO role_name
----

[.description]
Grant `TRAVERSE` privilege on all graphs and all relationships to the specified role.
====


====
[source, cypher, role=noheader]
----
DENY READ {prop}
ON GRAPH `database-name` RELATIONSHIP rel_type TO role_name
----

[.description]
Deny `READ` privilege on a specified property, on all relationships with a specified type in a specified graph, to the specified role.
====


====
[source, cypher, role=noheader]
----
REVOKE READ {prop}
ON GRAPH `database-name` FROM role_name
----

[.description]
Revoke `READ` privilege on a specified property in a specified graph from the specified role.
====


====
[source, cypher, role=noheader]
----
GRANT MATCH {*}
ON HOME GRAPH ELEMENTS label_or_type TO role_name
----

[.description]
Grant `MATCH` privilege on all nodes and relationships with the specified label/type, on the home graph, to the specified role. This is semantically the same as having both `TRAVERSE` privilege and `READ {*}` privilege.
====


====
[source, cypher, role=noheader]
----
GRANT READ {*}
ON GRAPH *
FOR (n) WHERE n.secret = false
TO role_name
----

[.description]
Grant `READ` privilege on all graphs and all nodes with a `secret` property set to `false` to the specified role.
====


====
[source, cypher, role=noheader]
----
DENY TRAVERSE
ON GRAPH *
FOR (n:label) WHERE n.secret <> false
TO role_name
----

[.description]
Deny `TRAVERSE` privilege on all graphs and all nodes with the specified label and with a `secret` property not set to `false` to the specified role.
====


====
[source, cypher, role=noheader]
----
REVOKE MATCH {*}
ON GRAPH *
FOR (n:foo_label|bar_label) WHERE n.secret IS NULL
FROM role_name
----

[.description]
Revoke `MATCH` privilege on all graphs and all nodes with either `foo_label` or `bar_label` and with a `secret` property  that is `null` from the specified role.
====