= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/predicate/[Predicate functions^]


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/predicate.adoc[tag=functions_predicate_all]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/predicate/#functions-all[`all()`^] function returns `true` if the predicate holds for all elements in the given `LIST<ANY>`.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/predicate.adoc[tag=functions_predicate_any]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/predicate/#functions-any[`any()`^] function returns `true` if the predicate holds for at least one element in the given `LIST<ANY>`.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/predicate.adoc[tag=functions_predicate_exists]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/predicate/#functions-exists[`exists()`^] function returns `true` if a match for the given pattern exists in the graph.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/predicate.adoc[tag=functions_predicate_is_empty]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/predicate/#functions-isempty[`isEmpty()`^] function returns `true` if the given `LIST<ANY>` or `MAP` contains no elements, or if the given `STRING` contains no characters.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/predicate.adoc[tag=functions_predicate_none]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/predicate/#functions-none[`none()`^] function returns `true` if the predicate does not hold for any element in the given `LIST<ANY>`.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/predicate.adoc[tag=functions_predicate_single]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/predicate/#functions-single[`single()`^] function returns `true` if the predicate holds for exactly _one_ of the elements in the given `LIST<ANY>`.
====
