[.neo4j-ee.aura-dbe.aura-dbc]
= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/manage-roles/[ROLE Management^]

////
[source, cypher, role=test-setup]
----
CREATE USER user_name SET PASSWORD 'password' CHANGE NOT REQUIRED;
----
////


====
[source, cypher, role=noheader]
----
CREATE ROLE role_name IF NOT EXISTS
----

[.description]
Create a role, unless it already exists.
====


====
[source, cypher, role=noheader]
----
CREATE ROLE copy_role_name AS COPY OF role_name
----

[.description]
Create a role, as a copy of the existing `role_name`.
====


====
[source, cypher, role=noheader]
----
RENAME ROLE role_name TO renamed_role_name
----

[.description]
Rename a role.
====


====
[source, cypher, role=noheader]
----
GRANT ROLE renamed_role_name, copy_role_name TO user_name
----

[.description]
Assign roles to a user.
====


====
[source, cypher, role=noheader]
----
REVOKE ROLE renamed_role_name FROM user_name
----

[.description]
Remove the specified role from a user.
====

====
[source, cypher, role=noheader]
----
SHOW ROLES
----

[.description]
Show all roles in the system and return default column (`role`).
For more information about specifying return columns and filtering, see the general xref:index.adoc#_show[`SHOW`] section.
====


====
[source, cypher, role=noheader]
----
SHOW POPULATED ROLES
----

[.description]
Show all roles that are assigned to at least one user in the system.
====


====
[source, cypher, role=noheader]
----
SHOW POPULATED ROLES WITH USERS
----

[.description]
Show all roles that are assigned to at least one user in the system, and the users assigned to those roles. The returned outputs are `role` and `member`.
====


====
[source, cypher, role=noheader, role=test-skip]
----
SHOW POPULATED ROLES WITH USERS
YIELD member, role
WHERE member = $user
RETURN role
----

[.description]
Show all roles that are assigned to a `$user`.
// The explicit `YIELD member, role` must be present to be able to do a `RETURN role
====


====
[source, cypher, role=noheader]
----
DROP ROLE renamed_role_name
----

[.description]
Delete a role.
====

