= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/[Scalar functions^]


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_cardinality_list]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-cardinality[`cardinality()`^] function returns the number of keys in a `MAP`, the number of elements in a `LIST<ANY>`, or the number of nodes and relationships in a `PATH`.
====

====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_char_length]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-char_length[`char_length()`^] function returns the number of Unicode characters in a `STRING`.
This function is an alias of the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-size[`size()`^] function.
====

====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_character_length]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-character_length[`character_length()`^] function returns the number of Unicode characters in a `STRING`.
This function is an alias of the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-size[`size()`^] function.
====

====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_coalesce]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-coalesce[`coalesce()`^] function returns the first given non-null argument.
====

====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_element_id]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-elementid[`elementId()`^] function returns a `STRING` representation of a node or relationship identifier, unique within a specific transaction and DBMS.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_end_node]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-endnode[`endNode()`^] function returns the the end `NODE` of a `RELATIONSHIP`.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_head]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-head[`head()`^] function returns the first element of the list. Returns `null` for an empty list. Equivalent to the list indexing `$list[0]`.
====

====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_id]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-id[`id()`^] function returns an `INTEGER` (the internal ID of a node or relationship). Do not rely on the internal ID for your business domain; the internal ID can change between transactions. It is recommended to use `elementId` instead.
====

====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_last]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-last[`last()`^] function returns the last element of the list. Returns `null` for an empty list. Equivalent to the list indexing `$list[-1]`.
====

====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_length]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-length[`length()`^] function returns the length of a `PATH`.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_null_if]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-nullIf[`nullIf()`^] function returns `null` if the two given parameters are equivalent, otherwise it returns the value of the first parameter.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_properties]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-properties[`properties()`^] function returns a `MAP` containing all the properties of a node or relationship.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_random_uuid]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-randomuuid[`randomUUID()`^] function returns a `STRING`; a randomly-generated universally unique identifier (UUID).
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_size]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-size[`size()`^] function returns the number of elements in the list.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_start_node]

[.description]
The function link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-startnode[`startNode()`^] function returns the start `NODE` of a `RELATIONSHIP`.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_timestamp]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-timestamp[`timestamp()`^] function returns the time in milliseconds since `midnight, January 1, 1970 UTC.` and the current time.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_to_boolean]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-toboolean[`toBoolean()`^] function converts a `STRING`, `INTEGER` or `BOOLEAN` value to a `BOOLEAN` value.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_to_boolean_or_null]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-tobooleanornull[`toBooleanOrNull()`^] function converts a `STRING`, `INTEGER` or `BOOLEAN` value to a `BOOLEAN` value.
For any other input value, `null` will be returned.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_to_float]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-tofloat[`toFloat()`^] function converts an `INTEGER`, `FLOAT` or a `STRING` value to a `FLOAT`.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_to_float_or_null]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-tofloatornull[`toFloatOrNull()`^] function converts an `INTEGER`, `FLOAT` or a `STRING` value to a `FLOAT`.
For any other input value, `null` will be returned.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_to_integer]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-tointeger[`toInteger()`^] function converts a `BOOLEAN`, `INTEGER`, `FLOAT` or a `STRING` value to an `INTEGER` value.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_to_integer_or_null]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-tointegerornull[`toIntegerOrNull()`^] function converts a `BOOLEAN`, `INTEGER`, `FLOAT` or a `STRING` value to an `INTEGER` value.
For any other input value, `null` will be returned.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_type]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-type[`type()`^] function returns the `STRING` representation of the `RELATIONSHIP` type.
====


====
include::ROOT:functions/scalar.adoc[tag=functions_scalar_value_type]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/scalar/#functions-valueType[`valueType()`^] function returns a `STRING` representation of the most precise value type that the given expression evaluates to.
====
