= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/indexes/search-performance-indexes/[Search-performance indexes^]

Cypher includes four search-performance indexes: range (default), text, point, and token lookup.

====
include::ROOT:indexes/search-performance-indexes/create-indexes.adoc[tag=indexes_search_performance_create_range]

[.description]
--
The create syntax for creating indexes is: `CREATE [RANGE|TEXT|POINT|LOOKUP|FULLTEXT|VECTOR] INDEX …​`.
If no index type is specified, a range index will be created since it supports most types of predicates.
This example, therefore, creates a range index.

Best practice is to always specify a sensible name when creating a index.
--
====

====
include::ROOT:indexes/search-performance-indexes/create-indexes.adoc[tag=indexes_search_performance_create_if_not_exists]

[.description]
To avoid failing on existing indexes, `IF NOT EXISTS` can be added to the `CREATE` command.
This will ensure that no error is thrown and that no index is created if there already exists an index with the same schema and type, same name or both.
====


====
include::ROOT:indexes/search-performance-indexes/create-indexes.adoc[tag=indexes_search_performance_create_composite_range]

[.description]
Create a composite range index on multiple properties.
====


====
include::ROOT:indexes/search-performance-indexes/create-indexes.adoc[tag=indexes_search_performance_create_parameter]

[.description]
Create a range index with a parameterized name.
All index types can be created in this way. 
====


====
include::ROOT:indexes/search-performance-indexes/create-indexes.adoc[tag=indexes_search_performance_create_text]

[.description]
Create a text index.
Text indexes only solve predicates operating on `STRING` values.
====


====
include::ROOT:indexes/search-performance-indexes/create-indexes.adoc[tag=indexes_search_performance_create_point]

[.description]
Create a point index.
Point indexes only solve predicates operating on `POINT` values.
====

====
include::ROOT:indexes/search-performance-indexes/create-indexes.adoc[tag=indexes_search_performance_create_point_configuration]

[.description]
Create a point index with a specific configuration.
====


====
include::ROOT:indexes/search-performance-indexes/create-indexes.adoc[tag=indexes_search_performance_create_lookup]

[.description]
Create a node token lookup index.
Two token lookup indexes are present by default (node token lookup and relationship token lookup) and solve only node label and relationship type predicates.
It is not recommended to remove lookup indexes.
====


====
include::ROOT:indexes/search-performance-indexes/list-indexes.adoc[tag=indexes_search_performance_show]

[.description]
Show all indexes and return default columns(`id`, `name`, `state`, `populationPercent`, `type`, `entityType`, `labelsOrTypes`, `properties`, `indexProvider`, `owningConstraint`, `lastRead`, and `readCount`).
For more information about specifying return columns and filtering, see the general xref:index.adoc#_show[`SHOW`] section.
====


====
include::ROOT:indexes/search-performance-indexes/list-indexes.adoc[tag=indexes_search_performance_show_type_filter]

[.description]
`SHOW INDEXES` can be filtered on index type.
The available types are: `ALL`, `FULLTEXT`, `LOOKUP`, `POINT`, `RANGE`, `TEXT`, and `VECTOR`.
====


====
include::ROOT:indexes/search-performance-indexes/drop-indexes.adoc[tag=indexes_search_performance_drop]

[.description]
Drop an index by name.
====


====
include::ROOT:indexes/search-performance-indexes/drop-indexes.adoc[tag=indexes_search_performance_drop_parameter]

[.description]
Drop an index by parameterized name.
====


====
include::ROOT:indexes/search-performance-indexes/index-hints.adoc[tag=indexes_search_performance_hint]

[.description]
Index usage can be enforced when Cypher uses a suboptimal index, or when more than one index should be used.
====
