= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/indexes/search-performance-indexes/managing-indexes/[Search-performance indexes]

Cypher includes four search-performance indexes: range (default), text, point, and token lookup.

====
[source, cypher, role=noheader]
----
CREATE INDEX index_name
FOR (p:Person) ON (p.name)
----

[.description]
--
Create a range index with the name `index_name` on nodes with label `Person` and property `name`.

It is possible to omit the `index_name`, if not specified the index name will be decided by the DBMS. Best practice is to always specify a sensible name when creating an index. 

The create syntax is `CREATE [RANGE|TEXT|POINT|LOOKUP|FULLTEXT|VECTOR] INDEX ...`. Defaults to range if not explicitly stated.
--
====


====
[source, cypher, role=noheader]
----
CREATE RANGE INDEX range_index
FOR ()-[k:KNOWS]-() ON (k.since)
----

[.description]
Create a range index on relationships with type `KNOWS` and property `since` with the name `index_name`.
====

////
[source, parameters]
----
{
  "nameParam": ["param_index"]
}
----
////

====
[source, cypher, role=noheader]
----
CREATE INDEX $nameParam
FOR (p:Person) ON (p.name, p.age)
----

[.description]
Create a composite range index with the name given by the parameter `nameParam` on nodes with label `Person` and the properties `name` and `age`, throws an error if the index already exist.
====


====
[source, cypher, role=noheader]
----
CREATE INDEX index_name IF NOT EXISTS
FOR (p:Person) ON (p.name, p.age)
----

[.description]
Create a composite range index with the name `index_name` on nodes with label `Person` and the properties `name` and `age` if it does not already exist, does nothing if it did exist.
====


====
[source, cypher, role=noheader]
----
CREATE TEXT INDEX node_text_index
FOR (p:Person) ON (p.name)
----

[.description]
--
Create a text index on nodes with label `Person` and property `name`.
Text indexes only solve predicates involving `STRING` property values.
--
====


====
[source, cypher, role=noheader]
----
CREATE TEXT INDEX rel_text_index
FOR ()-[r:KNOWS]-() ON (r.city)
----

[.description]
Create a text index on relationships with type `KNOWS` and property `city`. 
Text indexes only solve predicates involving `STRING` property values.
====


====
[source, cypher, role=noheader]
----
CREATE POINT INDEX node_point_index
FOR (p:Person) ON (p.location)
OPTIONS {
  indexConfig: {
    `spatial.cartesian.min`: [-100.0, -100.0],
    `spatial.cartesian.max`: [100.0, 100.0]
  }
}
----

[.description]
Create a point index on nodes with label `Person` and property `location` with the name `index_name` and the given `spatial.cartesian` settings. The other index settings will have their default values.
Point indexes only solve predicates involving `POINT` property values.
====

////
[source, parameters]
----
{
  "pointNameParam": ["param_point_index"]
}
----
////

====
[source, cypher, role=noheader]
----
CREATE POINT INDEX $pointNameParam
FOR ()-[h:STREET]-() ON (h.intersection)
----

[.description]
Create a point index with the name given by the parameter `nameParam` on relationships with the type `STREET` and property `intersection`.
Point indexes only solve predicates involving `POINT` property values.
====


====
[source, cypher, role=noheader]
----
CREATE LOOKUP INDEX node_lookup_index
FOR (n) ON EACH labels(n)
----

[.description]
Create a token lookup index on nodes with any label.
====


====
[source, cypher, role=noheader]
----
CREATE LOOKUP INDEX rel_lookup_index
FOR ()-[r]-() ON EACH type(r)
----

[.description]
Create a token lookup index on relationships with any relationship type.
====


====
[source, cypher, role=noheader]
----
SHOW INDEXES
----

[.description]
List all indexes, returns only the default outputs (`id`, `name`, `state`, `populationPercent`, `type`, `entityType`, `labelsOrTypes`, `properties`, `indexProvider`, `owningConstraint`, `lastRead`, and `readCount`).
====


====
[source, cypher, role=noheader]
----
SHOW INDEXES YIELD *
----

[.description]
List all indexes and return all columns.
====

====
[source, cypher, role=noheader]
----
SHOW INDEX YIELD name, type, entityType, labelsOrTypes, properties
----

[.description]
List all indexes and return only specific columns.
====

====
[source, cypher, role=noheader]
----
SHOW INDEXES
YIELD name, type, options, createStatement
RETURN name, type, options.indexConfig AS config, createStatement
----

[.description]
List all indexes and return only specific columns using the `RETURN` clause.
Note that `YIELD` is mandatory if `RETURN` is used.
====


====
[source, cypher, role=noheader]
----
SHOW RANGE INDEXES
----

[.description]
List range indexes, can also be filtered on `ALL`, `FULLTEXT`, `LOOKUP`, `POINT`, `TEXT`, and `VECTOR`.
====


====
[source, cypher, role=noheader]
----
DROP INDEX index_name
----

[.description]
Drop the index named `index_name`, throws an error if the index does not exist.
====


====
[source, cypher, role=noheader]
----
DROP INDEX index_name IF EXISTS
----

[.description]
Drop the index named `index_name` if it exists, does nothing if it does not exist.
====

====
[source, cypher, role=noheader]
----
DROP INDEX $nameParam
----

[.description]
Drop an index using a parameter.
====

====
[source, cypher, role=noheader]
----
MATCH (n:Person)
USING INDEX n:Person(name)
WHERE n.name = $value
----

[.description]
Index usage can be enforced when Cypher uses a suboptimal index, or when more than one index should be used.
====
