= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/security/[Security functions^]

====
include::ROOT:functions/security.adoc[tag=functions_security_abac.native.user_tags]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/security/#functions-security-native-user-tags[`abac.native.user_tags()`^] function returns the list of tags for the native user.
`abac.native.user_tags()` cannot be called directly in queries. It can only be used in the condition of a `CREATE AUTH RULE` or `ALTER AUTH RULE` command.
====


====
include::ROOT:functions/security.adoc[tag=functions_security_abac.oidc.user_attribute]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/security/#functions-security-oidc-user-attribute[`abac.oidc.user_attribute()`^] function returns the value of the specified user attribute from the OIDC claims. Returns `null` if the attribute is not present.
`abac.oidc.user_attribute()` cannot be called directly in queries. It can only be used in the condition of a `CREATE AUTH RULE` or `ALTER AUTH RULE` command.
====