= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/set/[SET^]

====
include::ROOT:clauses/set.adoc[tag=clauses_set_property]

[.description]
Update a node property with `SET`.
====

====
include::ROOT:clauses/set.adoc[tag=clauses_set_with_expression]

[.description]
`SET` a property on a node or relationship using more complex expressions.
====


====
include::ROOT:clauses/set.adoc[tag=clauses_set_update]

[.description]
`SET` can be used to update a property on a node or relationship.
====


====
include::ROOT:clauses/set.adoc[tag=clauses_set_dynamic_property]

[.description]
`SET` can be used to set or update a property dynamically.
====


====
include::ROOT:clauses/set.adoc[tag=clauses_set_replace]

[.description]

The property replacement operator `=` can be used with `SET` to replace all existing properties on a node or relationship with properties provided by a map.
====

====
include::ROOT:clauses/set.adoc[tag=clauses_set_remove]

[.description]
All existing properties can be removed from a node or relationship by using `SET` with `=` and an empty map as the right operand.
====


====
include::ROOT:clauses/set.adoc[tag=clauses_set_mutate]

[.description]
The property mutation operator `+=` can be used with `SET` to update existing properties and add new properties from a map with fine-grained control.
====


====
include::ROOT:clauses/set.adoc[tag=clauses_set_parameter]

[.description]
Use a parameter to `SET` the value of a property.
====

====
include::ROOT:clauses/set.adoc[tag=clauses_set_parameter_all_properties]

[.description]
Update all existing properties on a node using a parameter.
====

====
include::ROOT:clauses/set.adoc[tag=clauses_set_label]

[.description]
`SET` a node label. 
====

====
include::ROOT:clauses/set.adoc[tag=clauses_set_dynamic_label]

[.description]
`SET` a node label dynamically.
====
