[.neo4j-ee.aura-dbe.aura-dbc]
= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/manage-privileges/#access-control-list-privileges[SHOW Privileges^]


====
[source, cypher, role=noheader]
----
SHOW PRIVILEGES
----

[.description]
Show all privileges in the system and return default columns (`access`, `action`, `resource`, `graph`, `segment`, `role`, and `immutable`).
For more information about specifying return columns and filtering, see the general xref:index.adoc#_show[`SHOW`] section.
====


====
[source, cypher, role=noheader]
----
SHOW PRIVILEGES AS COMMANDS
----

[.description]
Show all privileges in the system as Cypher commands, for example `GRANT ACCESS ON DATABASE * TO `admin``. Returns only the default output (`command`).
====


====
[source, cypher, role=noheader]
----
SHOW USER PRIVILEGES
----

[.description]
Show all privileges of the currently logged-in user, and the roles that they are assigned to. Outputs returned are: `access`, `action`, `resource`, `graph`, `segment`, `role`, `immutable`, and `user`.
====


====
[source, cypher, role=noheader]
----
SHOW USER PRIVILEGES AS COMMANDS
----

[.description]
Show all privileges of the currently logged-in user, and the roles that they are assigned to as Cypher commands, for example `GRANT ACCESS ON DATABASE * TO $role`. Returns only the default output (`command`).
====


====
[source, cypher, role=noheader]
----
SHOW USER user_name PRIVILEGES
----

[.description]
Show all privileges assigned to each of the specified users (multiple users can be specified separated by commas `n1, n2, n3`), and the roles that they are assigned to. Outputs returned are: `access`, `action`, `resource`, `graph`, `segment`, `role`, `immutable`, and `user`.
====


====
[source, cypher, role=noheader]
----
SHOW USER user_name PRIVILEGES AS COMMANDS YIELD *
----

[.description]
Show all privileges assigned to each of the specified users (multiple users can be specified separated by commas `n1, n2, n3`), as generic Cypher commands, for example `GRANT ACCESS ON DATABASE * TO $role`. Outputs returned are: `command` and `immutable`.
====


====
[source, cypher, role=noheader]
----
SHOW ROLE role_name PRIVILEGES
----

[.description]
Show all privileges assigned to each of the specified roles (multiple roles can be specified separated by commas `r1, r2, r3`). Outputs returned are: `access`, `action`, `resource`, `graph`, `segment`, `role`, and `immutable`.
====


====
[source, cypher, role=noheader]
----
SHOW ROLE role_name PRIVILEGES AS COMMANDS
----

[.description]
Show all privileges assigned to each of the specified roles (multiple roles can be specified separated by commas `r1, r2, r3`) as Cypher commands, for example `GRANT ACCESS ON DATABASE * TO `admin``. Returns only the default output (`command`).
====

====
[source, cypher, role=noheader]
----
SHOW SUPPORTED PRIVILEGES
----

[.description]
Show all privileges that are possible to grant or deny on a server.
Outputs returned are: `action`, `qualifier`, `target`, `scope`, and `description`.
====