= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/spatial/[Spatial functions^]


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/spatial.adoc[tag=functions_spatial_point_cartesian_2d]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/spatial/#functions-point-cartesian-2d[`point()` Cartesian 2D^] function returns a 2D `POINT` in the _Cartesian_ CRS corresponding to the given coordinate values.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/spatial.adoc[tag=functions_spatial_point_cartesian_3d]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/spatial/#functions-point-cartesian-3d[`point()` Cartesian 3D^] function returns a 3D `POINT` in the _Cartesian_ CRS corresponding to the given coordinate values.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/spatial.adoc[tag=functions_spatial_point_wgs_84_2d]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/spatial/#functions-point-wgs84-2d[`point()` WGS 84 2D^] function returns a 2D `POINT` in the _WGS 84 CRS_ corresponding to the given coordinate values.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/spatial.adoc[tag=functions_spatial_point_wgs_84_3d]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/spatial/#functions-point-wgs84-3d[`point()` WGS 84 3D^] function returns a 3D `POINT` in the _WGS 84 CRS_ corresponding to the given coordinate values.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/spatial.adoc[tag=functions_spatial_point_distance]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/spatial/#functions-distance[`point.distance()`^] function returns returns a `FLOAT` representing the geodesic distance between two points in the same Coordinate Reference System (CRS).
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/spatial.adoc[tag=functions_spatial_point_within_bbox]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/spatial/#functions-withinBBox[`point.withinBBox()`^] function takes the following arguments: the `POINT` to check, the lower-left (south-west) `POINT` of a bounding box, and the upper-right (or north-east) `POINT` of a bounding box.
The return value will be true if the provided point is contained in the bounding box (boundary included), otherwise the return value will be false.
====
