= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/[String functions^]

====
include::ROOT:functions/string.adoc[tag=functions_string_btrim]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-btrim[`btrim()`^] function returns the original `STRING` with leading and trailing `trimCharacterString` characters removed.
If `trimCharacterString` is not specified then all leading and trailing whitespace will be removed.
====

====
include::ROOT:functions/string.adoc[tag=functions_string_left]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-left[`left()`^] function returns a `STRING` containing the specified number of leftmost characters of the given `STRING`.
====

====
include::ROOT:functions/string.adoc[tag=functions_string_lower]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-lower[`lower()`^] function returns the given `STRING` in lowercase.
This function is an alias of the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-tolower[`toLower`^] function.
====


====
include::ROOT:functions/string.adoc[tag=functions_string_ltrim]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-ltrim[`ltrim()`^] function returns the original `STRING` with leading `trimCharacterString` characters removed.
If `trimCharacterString` is not specified then all leading whitespace will be removed.
====

====
include::ROOT:functions/string.adoc[tag=functions_string_normalize]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-normalize[`normalize()`^] function returns a given `STRING` normalized using the `NFC` Unicode normalization form.
====

====
include::ROOT:functions/string.adoc[tag=functions_string_replace]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-replace[`replace()`^] function returns a `STRING` in which all occurrences of a specified `STRING` in the given `STRING` have been replaced by another (specified) replacement `STRING`.
====


====
include::ROOT:functions/string.adoc[tag=functions_string_reverse]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-reverse[`reverse()`^] function returns a `STRING` in which the order of all characters in the given `STRING` have been reversed.
====


====
include::ROOT:functions/string.adoc[tag=functions_string_right]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-right[`right()`^] function returns a `STRING` containing the specified number of rightmost characters in the given `STRING`.
====


====
include::ROOT:functions/string.adoc[tag=functions_string_rtrim]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-rtrim[`rtrim()`^] function returns the given `STRING` with trailing `trimCharacterString` characters removed.
If `trimCharacterString` is not specified then all trailing whitespace will be removed.
====


====
include::ROOT:functions/string.adoc[tag=functions_string_split]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-split[`split()`^] function returns a `LIST<STRING>` resulting from the splitting of the given `STRING` around matches of the given delimiter.
====

====
include::ROOT:functions/string.adoc[tag=functions_string_indexof]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-string.indexof[`string.indexOf()`^] function returns the index of the first occurrence of the given `value` within the `input` `STRING`, or -1 if no match is found.
====

====
include::ROOT:functions/string.adoc[tag=functions_string_join]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-string.join[`string.join()`^] function concatenates the elements in the `input` `STRING`, inserting a `delimiter` between each element, and returns the resulting `STRING`.
====

====
include::ROOT:functions/string.adoc[tag=functions_string_regexreplace]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-string.regexreplace[`string.regexReplace()`^] function returns a `STRING` where all matches of `regex` in the `original` `STRING` are replaced with the `replacement` `STRING`.
====

====
include::ROOT:functions/string.adoc[tag=functions_string_substring]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-substring[`substring()`^] function returns a substring of the given `STRING`, beginning with a zero-based index start and length.
====


====
include::ROOT:functions/string.adoc[tag=functions_string_to_lower]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-tolower[`toLower()`^] function returns the given `STRING` in lowercase.
====


====
include::ROOT:functions/string.adoc[tag=functions_string_to_string]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-tostring[`toString()`^] function converts an `INTEGER`, `FLOAT`, `BOOLEAN`, `STRING`, `POINT`, `DURATION`, `DATE`, `ZONED TIME`, `LOCAL TIME`, `LOCAL DATETIME` or `ZONED DATETIME` value to a `STRING`.
====


====
include::ROOT:functions/string.adoc[tag=functions_string_to_string_or_null]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-tostringornull[`toStringOrNull()`^] function converts an `INTEGER`, `FLOAT`, `BOOLEAN`, `STRING`, `POINT`, `DURATION`, `DATE`, `ZONED TIME`, `LOCAL TIME`, `LOCAL DATETIME` or `ZONED DATETIME` value to a `STRING`.
For any other input value, `null` will be returned.
====


====
include::ROOT:functions/string.adoc[tag=functions_string_to_upper]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-toupper[`toUpper()`^] function returns the given `STRING` in uppercase.
====


====
include::ROOT:functions/string.adoc[tag=functions_string_trim]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-trim[`trim()`^] function returns the given `STRING` with leading and trailing whitespace removed.
====

====
include::ROOT:functions/string.adoc[tag=functions_string_upper]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-upper[`upper()`^] function returns the given `STRING` in uppercase.
This function is an alias of the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/string/#functions-toupper[`toUpper()`^] function.
====