= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/expressions/predicates/#string-operators[String operators^]

====
include::ROOT:expressions/predicates/string-operators.adoc[tag=expressions_predicates_string_operators_prefix]

[.description]
The `STARTS WITH` operator checks if a `STRING` value begins with a specified prefix.
====

====
include::ROOT:expressions/predicates/string-operators.adoc[tag=expressions_predicates_string_operators_suffix]

[.description]
The `ENDS WITH` operator checks if a `STRING` value ends with a specified suffix
====


====
include::ROOT:expressions/predicates/string-operators.adoc[tag=expressions_predicates_string_operators_substring]

[.description]
The `CONTAINS` operator checks if a `STRING` value contains a specified substring.
====


====
include::ROOT:expressions/predicates/string-operators.adoc[tag=expressions_predicates_string_operators_regex]

[.description]
The regular expression operator `=~` checks if a `STRING`value matches a regular expression.
====


====
include::ROOT:expressions/predicates/string-operators.adoc[tag=expressions_predicates_string_operators_regex_flag]

[.description]
The `=~` operator can be used with regular expression flags, such as `(?i)` for case-insensitive matching, to modify how the regex is applied.
====

====
include::ROOT:expressions/predicates/string-operators.adoc[tag=expressions_predicates_string_operators_is_normalized]

[.description]
The `IS NORMALIZED` operator is used to check whether the given `STRING` value is in the `NFC` Unicode normalization form.
====


====
include::ROOT:expressions/predicates/string-operators.adoc[tag=expressions_predicates_string_operators_is_not_normalized]

[.description]
The `IS NOT NORMALIZED` operator is used to check whether the given `STRING` value is not in the `NFC` Unicode normalization form.
====


====
include::ROOT:expressions/predicates/string-operators.adoc[tag=expressions_predicates_string_operators_is_normalized_normalization_type]

[.description]
It is possible to define which Unicode normalization type is used.
The available normalization types are: `NFC` (default), `NFD`, `NFKC`, and `NFKD`.
====
