= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/subqueries/subqueries-in-transactions/[CALL subqueries in transactions^]

====
include::ROOT:subqueries/subqueries-in-transactions.adoc[tag=subqueries_in_transactions_basic_example]

[.description]
`CALL` subqueries can execute in separate, inner transactions, producing intermediate commits.
====

====
include::ROOT:subqueries/subqueries-in-transactions.adoc[tag=subqueries_in_transactions_batching]

[.description]
Specify the number of rows processed in each transaction.
====

====
include::ROOT:subqueries/subqueries-in-transactions.adoc[tag=subqueries_in_transactions_error_behavior]

[.description]
--
There are four different option flags to control the behavior in case of an error occurring in any of the inner transactions:

* `ON ERROR CONTINUE` - ignores a recoverable error and continues the execution of subsequent inner transactions. The outer transaction succeeds.
* `ON ERROR BREAK` - ignores a recoverable error and stops the execution of subsequent inner transactions. The outer transaction succeeds.
* `ON ERROR FAIL` - acknowledges a recoverable error and stops the execution of subsequent inner transactions. The outer transaction fails.
* `ON ERROR RETRY` - uses an exponential delay between retry attempts for transaction batches that fail due to transient errors (i.e. errors where retrying a transaction can be expected to give a different result), with an optional maximum retry duration.
If the transaction still fails after the maximum duration, the failure is handled according to an optionally specified fallback error handling mode (`THEN CONTINUE`, `THEN BREAK`, `THEN FAIL` (default)).
--

====

====
include::ROOT:subqueries/subqueries-in-transactions.adoc[tag=subqueries_in_transactions_concurrent_transactions]

[.description]
`CALL` subqueries can execute batches in parallel by appending `IN [n] CONCURRENT TRANSACTIONS`, where `n` is an optional concurrency value used to set the maximum number of transactions that can be executed in parallel.
====

====
include::ROOT:subqueries/subqueries-in-transactions.adoc[tag=subqueries_in_transactions_deadlock_example]

[.description]
`ON ERROR RETRY ... THEN CONTINUE` can be used to retry the execution of a transaction for a specified maximum duration before continuing the execution of subsequent inner transactions by ignoring any recoverable errors. 
====