= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/[Temporal functions - instant^]

====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_date]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-date[`date`^] function returns the current `DATE` value.
If no time zone parameter is specified, the local time zone will be used.
====

====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_date_realtime]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-date-realtime[`date.realtime()`] function returns the current `DATE` instant using the realtime clock.
====

====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_date_statement]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-date-statement[`date.statement()`] function returns the current `DATE` instant using the statement clock.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_date_transaction]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-date-transaction[`date.transaction()`] function returns the current `DATE` instant using the transaction clock.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_date_truncate]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-date-truncate[`date.truncate()`] function truncates the given temporal value to a `DATE` instant using the specified unit.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_datetime]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-datetime[`datetime()`] function creates a `ZONED DATETIME` instant.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_datetime_fromepoch]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-datetime-fromepoch[`datetime.fromEpoch()`] function creates a `ZONED DATETIME` given the seconds and nanoseconds since the start of the epoch.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_datetime_fromepochmillis]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-datetime-fromepochmillis[`datetime.fromEpochMillis()`] function creates a `ZONED DATETIME` given the milliseconds since the start of the epoch.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_datetime_realtime]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-datetime-realtime[`datetime.realtime()`] function returns the current `ZONED DATETIME` instant using the realtime clock.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_datetime_statement]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-datetime-statement[`datetime.statement()`] function returns the current `ZONED DATETIME` instant using the statement clock.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_datetime_transaction]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-datetime-transaction[`datetime.transaction()`] function returns the current `ZONED DATETIME` instant using the transaction clock.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_datetime_truncate]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-datetime-truncate[`datetime.truncate()`] function truncates the given temporal value to a `ZONED DATETIME` instant using the specified unit.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_localdatetime]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-localdatetime[`localdatetime()`] function creates a `LOCAL DATETIME` instant.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_localdatetime_realtime]

[.description]
The  link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-localdatetime-realtime[`localdatetime.realtime()`]  function returns the current `LOCAL DATETIME` instant using the realtime clock.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_localdatetime_statement]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-localdatetime-statement[`localdatetime.statement()`] function returns the current `LOCAL DATETIME` instant using the statement clock.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_localdatetime_transaction]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-localdatetime-transaction[`localdatetime.transaction()`] function returns the current `LOCAL DATETIME` instant using the transaction clock.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_localdatetime_truncate]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-localdatetime-truncate[`localdatetime.truncate()`] function truncates the given temporal value to a `LOCAL DATETIME` instant using the specified unit.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_localtime]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-localtime[`localtime()`] function creates a `LOCAL TIME` instant.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_localtime_realtime]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-localtime-realtime[`localtime.realtime()`] function creates a `LOCAL TIME` instant. function returns the current `LOCAL TIME` instant using the realtime clock.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_localtime_statement]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-localtime-statement[`localtime.statement()`] function creates a `LOCAL TIME` instant. function returns the current `LOCAL TIME` instant using the statement clock.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_localtime_transaction]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-localtime-transaction[`localtime.transaction()`] function returns the current `LOCAL TIME` instant using the transaction clock.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_localtime_truncate]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-localtime-truncate[`localtime.truncate()`] function truncates the given temporal value to a `LOCAL TIME` instant using the specified unit.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_time]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-time[`time()`] function creates a `ZONED TIME` instant.
====

====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_time_realtime]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-time-realtime[`time.realtime()`] function returns the current `ZONED TIME` instant using the realtime clock.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_time_statement]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-time-statement[`time.statement()`] function returns the current `ZONED TIME` instant using the statement clock.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_time_transaction]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-time-transaction[`time.transaction()`] function returns the current `ZONED TIME` instant using the transaction clock.
====


====
include::{github-raw-page-uri}/docs-cypher/{query-include-branch}/modules/ROOT/pages/functions/temporal/index.adoc[tag=functions_temporal_time_truncate]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/temporal/#functions-time-truncate[`time.truncate()`] function truncates the given temporal value to a `ZONED TIME` instant using the specified unit.
====
