= link:{neo4j-docs-base-uri}/operations-manual/current/clauses/database-internals/show-and-terminate-transactions/[TRANSACTION management^]


====
[source, cypher, role=noheader]
----
SHOW TRANSACTIONS
----

[.description]
Show running transactions (within the instance) and return default columns (`database`, `transactionId`, `currentQueryId`, `connectionId`, `clientAddress`, `username`, `currentQuery`, `startTime`, `status`, and `elapsedTime`).
For more information about specifying return columns and filtering, see the general xref:index.adoc#_show[`SHOW`] section.
====


====
[source, cypher, role=noheader]
----
SHOW TRANSACTIONS 'transaction_id' YIELD *
----

[.description]
Show the running transaction (within the instance), with a specific `transaction_id`. 
As long as the transaction IDs evaluate to a string or a list of strings at runtime, they can be any expression.
====


====
[source, cypher, role=noheader, role=test-skip]
----
TERMINATE TRANSACTIONS 'transaction_id'
----

[.description]
Terminate a transaction with a specific `transaction_id`.
Returns the `transactionId`, `username`, and `message` columns.
As long as the transaction IDs evaluate to a string or a list of strings at runtime, they can be any expression.
====

====
[source, cypher, role=noheader, role=test-skip]
----
TERMINATE TRANSACTIONS "neo4j-transaction-1","neo4j-transaction-2"
YIELD transactionId, message
WHERE message <> "Transaction terminated."
----

[.description]
`TERMINATE TRANSACTIONS` can be filtered using `WHERE`.
If so, the `YIELD` clause is mandatory (in contrast to the `SHOW TRANSACTIONS` command, which does not require it).
====

====
[source, cypher, role=noheader]
----
SHOW TRANSACTIONS
YIELD transactionId AS txId, username AS user
WHERE user = "Alice"
TERMINATE TRANSACTIONS txId
YIELD message
RETURN txId, message
----

[.description]
`TERMINATE TRANSACTIONS` and `SHOW TRANSACTIONS` can be combined to identify and terminate transactions in the same statement.
Multiple `SHOW` and `TERMINATE` transactions can be included in a single statement.
This example shows all transactions run by user `Alice` and terminates them.
====