= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/expressions/predicates/type-predicate-expressions/[Type predicate expressions^]


====
include::ROOT:expressions/predicates/type-predicate-expressions.adoc[tag=expressions_predicates_type_predicate]

[.description]
A type predicate expression can be used to verify the type of a variable, literal, property or other Cypher expression.
====

====
include::ROOT:expressions/predicates/type-predicate-expressions.adoc[tag=expressions_predicates_type_predicate_not]

[.description]
It is possible to verify that a Cypher expression is not of a certain type, using the negated type predicate expression `IS NOT ::`.
====


====
include::ROOT:expressions/predicates/type-predicate-expressions.adoc[tag=expressions_predicates_type_predicate_null]

[.description]
All Cypher types includes the `NULL` value.
Type predicate expressions can be appended with `NOT NULL`.
This means that `IS ::` returns `TRUE` for all expressions evaluating to `NULL`, unless `NOT NULL` is appended.
====


====
include::ROOT:expressions/predicates/type-predicate-expressions.adoc[tag=expressions_predicates_type_predicate_properties]

[.description]
Type predicate expressions can also be used to filter out nodes or relationships with properties of a certain type.
====


====
include::ROOT:expressions/predicates/type-predicate-expressions.adoc[tag=expressions_predicates_type_predicate_closed_dynamic_union]

[.description]
Closed dynamic union types allow for the testing of multiple types in the same predicate.
====
