= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/manage-users/[USER Management^]

////
.Parameters
[source, parameters]
----
{
  "password": "verysecret"
}
----
////

====
[source, cypher, role=noheader]
----
CREATE USER user_name
SET PASSWORD $password
----

[.description]
Create a new user and set the password. This password must be changed on the first login.
====


====
[source, cypher, role=noheader]
----
CREATE USER new_user
SET AUTH 'native' {
  SET PASSWORD $password
  SET PASSWORD CHANGE REQUIRED
}
----
[.description]
Create a new user and set the password using the auth provider syntax. This password must be changed on the first login.
====


====
[source, cypher, role=noheader]
----
RENAME USER user_name TO renamed_user_name
----

[.description]
Rename the specified user.
====

////
.Parameters
[source, parameters]
----
{
  "oldPassword": "verysecret",
  "newPassword": "verysecret1"
}
----
////
====
[source, cypher, role=noheader]
----
ALTER CURRENT USER
SET PASSWORD FROM $oldPassword TO $newPassword
----

[.description]
Change the password of the logged-in user. The user will not be required to change this password on the next login.
====


====
[source, cypher, role=noheader]
----
ALTER USER renamed_user_name
SET PASSWORD $password
CHANGE NOT REQUIRED
----

[.description]
Set a new password (a String) for a user. This user will not be required to change this password on the next login.
====


====
[source, cypher, role=noheader]
----
ALTER USER renamed_user_name IF EXISTS
SET PASSWORD CHANGE REQUIRED
----

[.description]
If the specified user exists, force this user to change the password on the next login.
====

[.neo4j-ee]
====
[source, cypher, role=noheader, role=test-skip]
----
ALTER USER renamed_user_name
SET AUTH 'externalProviderName' {
  SET ID 'userIdForExternalProvider'
}
----
[.description]
Add another way for the user to authenticate and authorize using the external provider `externalProviderName`.
This provider needs to be defined in the configurations settings.
====

[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
[source, cypher, role=noheader]
----
ALTER USER renamed_user_name
SET STATUS SUSPENDED
----

[.description]
Change the status to `SUSPENDED`, for the specified user.
====


[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
[source, cypher, role=noheader]
----
ALTER USER renamed_user_name
SET STATUS ACTIVE
----

[.description]
Change the status to `ACTIVE`, for the specified user.
====


////
[source, cypher, role=test-setup]
----
CREATE DATABASE `database-name`;
----
////

[.neo4j-ee.aura-dbe.aura-dbc]
====
[source, cypher, role=noheader]
----
ALTER USER renamed_user_name
SET HOME DATABASE `database-name`
----

[.description]
Set the home database for the specified user. The home database can either be a database or an alias.
====


[.neo4j-ee.aura-dbe.aura-dbc]
====
[source, cypher, role=noheader]
----
ALTER USER renamed_user_name
REMOVE HOME DATABASE
----

[.description]
Unset the home database for the specified user and fallback to the default database.
====

====
[source, cypher, role=noheader]
----
SHOW USERS
----

[.description]
List all users in Neo4j DBMS, returns only the default outputs (`user`, `roles`, `passwordChangeRequired`, `suspended`, and `home`).
====


====
[source, cypher, role=noheader]
----
SHOW CURRENT USER
----

[.description]
List the currently logged-in user, returns only the default outputs (`user`, `roles`, `passwordChangeRequired`, `suspended`, and `home`).
====


[.neo4j-ee.aura-dbf.aura-dbp.aura-dbe.aura-dbc.aura-dsp.aura-dse]
====
[source, cypher, role=noheader]
----
SHOW USERS
WHERE suspended = true
----

[.description]
List users that are suspended.
====


====
[source, cypher, role=noheader]
----
SHOW USERS
WHERE passwordChangeRequired
----

[.description]
List users that must change their password at the next login.
====

====
[source, cypher, role=noheader]
----
SHOW USERS WITH AUTH
----

[.description]
List users with their auth providers. Will return one row per user per auth provider.
====

====
[source, cypher, role=noheader]
----
SHOW USERS WITH AUTH WHERE provider = 'oidc1'
----

[.description]
List users who have the `oidc1` auth provider.
====


====
[source, cypher, role=noheader]
----
DROP USER renamed_user_name
----

[.description]
Delete the specified user.
====


