= link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/manage-users/[USER Management^]



====
[source, cypher, role=noheader]
----
SHOW USERS
----

[.description]
List all users in Neo4j DBMS, returns only the default outputs (`user`, `roles`, `passwordChangeRequired`, `suspended`, and `home`).
====


====
[source, cypher, role=noheader]
----
SHOW CURRENT USER
----

[.description]
List the currently logged-in user, returns only the default outputs (`user`, `roles`, `passwordChangeRequired`, `suspended`, and `home`).
====


[role=label--enterprise-edition label--aura-db-free label--aura-db-professional label--aura-db-enterprise label--aura-db-business-critical label--aura-ds-professional label--aura-ds-enterprise]
====
[source, cypher, role=noheader]
----
SHOW USERS
WHERE suspended = true
----

[.description]
List users that are suspended.
====


====
[source, cypher, role=noheader]
----
SHOW USERS
WHERE passwordChangeRequired
----

[.description]
List users that must change their password at the next login.
====

====
[source, cypher, role=noheader]
----
SHOW USERS WITH AUTH
----

[.description]
List users with their auth providers. Will return one row per user per auth provider.
====

====
[source, cypher, role=noheader]
----
SHOW USERS WITH AUTH WHERE provider = 'oidc1'
----

[.description]
List users who have the `oidc1` auth provider.
====


====
[source, cypher, role=noheader]
----
DROP USER user_name
----

[.description]
Delete the specified user.
====


====
[source, cypher, role=noheader]
----
CREATE USER user_name
SET PASSWORD $password
----

[.description]
Create a new user and set the password. This password must be changed on the first login.
====


====
[source, cypher, role=noheader]
----
CREATE USER user_name
SET AUTH 'native' {
  SET PASSWORD $password
  SET PASSWORD CHANGE REQUIRED
}
----
[.description]
Create a new user and set the password using the auth provider syntax. This password must be changed on the first login.
====


====
[source, cypher, role=noheader]
----
RENAME USER user_name TO other_user_name
----

[.description]
Rename the specified user.
====


====
[source, cypher, role=noheader]
----
ALTER CURRENT USER
SET PASSWORD FROM $oldPassword TO $newPassword
----

[.description]
Change the password of the logged-in user. The user will not be required to change this password on the next login.
====


====
[source, cypher, role=noheader]
----
ALTER USER user_name
SET PASSWORD $password
CHANGE NOT REQUIRED
----

[.description]
Set a new password (a String) for a user. This user will not be required to change this password on the next login.
====


====
[source, cypher, role=noheader]
----
ALTER USER user_name IF EXISTS
SET PASSWORD CHANGE REQUIRED
----

[.description]
If the specified user exists, force this user to change the password on the next login.
====

[role=label--enterprise-edition]
====
[source, cypher, role=noheader]
----
ALTER USER user_name
SET AUTH 'externalProviderName' {
  SET ID 'userIdForExternalProvider'
}
----
[.description]
Add another way for the user to authenticate and authorize using the external provider `externalProviderName`.
This provider needs to be defined in the configurations settings.
====

[role=label--enterprise-edition label--aura-db-free label--aura-db-professional label--aura-db-enterprise label--aura-db-business-critical label--aura-ds-professional label--aura-ds-enterprise]
====
[source, cypher, role=noheader]
----
ALTER USER user_name
SET STATUS SUSPENDED
----

[.description]
Change the status to `SUSPENDED`, for the specified user.
====


[role=label--enterprise-edition label--aura-db-free label--aura-db-professional label--aura-db-enterprise label--aura-db-business-critical label--aura-ds-professional label--aura-ds-enterprise]
====
[source, cypher, role=noheader]
----
ALTER USER user_name
SET STATUS ACTIVE
----

[.description]
Change the status to `ACTIVE`, for the specified user.
====


[role=label--enterprise-edition label--aura-db-enterprise label--aura-db-business-critical]
====
[source, cypher, role=noheader]
----
ALTER USER user_name
SET HOME DATABASE `database-name`
----

[.description]
Set the home database for the specified user. The home database can either be a database or an alias.
====


[role=label--enterprise-edition label--aura-db-enterprise label--aura-db-business-critical]
====
[source, cypher, role=noheader]
----
ALTER USER user_name
REMOVE HOME DATABASE
----

[.description]
Unset the home database for the specified user and fallback to the default database.
====