= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/uuid/[UUID functions^]

====
include::ROOT:functions/uuid.adoc[tag=functions_uuid_random]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/uuid/#functions-uuid[`uuid()`^] function can be used to generate a random `UUID` value.
====


====
include::ROOT:functions/uuid.adoc[tag=functions_uuid_from_string]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/uuid/#functions-uuid[`uuid()`^] function can be used to generate a `UUID` from a `STRING` value.
The `STRING` must be 32 hexadecimal digits displayed in 5 groups, separated by 4 hyphens.
====

====
include::ROOT:functions/uuid.adoc[tag=functions_uuid_from_integers]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/uuid/#functions-uuid[`uuid()`^] function can be used to generate a `UUID` from two `INTEGER` values.
====


====
include::ROOT:functions/uuid.adoc[tag=functions_uuid_leastsignificantbits]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/uuid/#functions-leastsignificantbits[`uuid.leastSignifcantBits()`^] function returns the least significant bits from the given `UUID`.
====


====
include::ROOT:functions/uuid.adoc[tag=functions_uuid_mostsignificantbits]

[.description]
The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/uuid/#functions-mostsignificantbits[`uuid.mostSignifcantBits()`^] function returns the most significant bits from the given `UUID`.
====
