= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/indexes/semantic-indexes/vector-indexes/[Vector indexes]

====
[source, cypher, role=noheader]
----
CREATE VECTOR INDEX `abstract-embeddings`
FOR (a:Abstract) ON (a.embedding)
OPTIONS {
  indexConfig: {
    `vector.dimensions`: 1536,
    `vector.similarity_function`: 'cosine'
  }
}
----

[.description]
Create a vector index on nodes with label `Abstract`, property `embedding`, and a vector dimension of `1536` using the `cosine` similarity function and the name `abstract-embeddings`.
====

====
[source, cypher, role=noheader]
----
CREATE VECTOR INDEX `review-embeddings`
FOR ()-[r:REVIEWED]-() ON (r.embedding)
OPTIONS {
  indexConfig: {
    `vector.dimensions`: 256,
    `vector.similarity_function`: 'cosine'
  }
}
----

[.description]
Create a vector index on relationships with relationship type `REVIEWED`, property `embedding`, and a vector dimension of `256` using the `cosine` similarity function and the name `review-embeddings`.
====

====
[source, cypher, role=noheader]
----
CREATE VECTOR INDEX `multi-label-index`
FOR (a:Abstract|Summary) ON (a.embedding)
----

[.description]
Create a vector index on nodes with label `Abstract` or `Summary`, property `embedding`, and the name `multi-label-index`.
The index uses the default `cosine` similarity function and accepts any vector dimension since neither is specified.
====

====
[source, cypher, role=noheader]
----
CREATE VECTOR INDEX `additional-properties-index`
FOR ()-[r:REVIEWED]-()
ON (r.embedding)
WITH [r.date, r.grade]
----

[.description]
Create a vector index on relationships with relationship type `REVIEWED`, vector property `embedding`, additional properties for filtering `date` and `grade`, and the name `additional-properties-index`.
The index uses the default `cosine` similarity function and accepts any vector dimension since neither is specified.
====

====
[source, cypher, role=noheader, role=test-skip]
----
CALL db.index.vector.queryNodes('abstract-embeddings', 10, abstract.embedding)
----

[.description]
Query the node vector index `abstract-embeddings` for a neighborhood of `10` similar abstracts.
====

====
[source, cypher, role=noheader, role=test-skip]
----
CALL db.index.vector.queryRelationships('review-embeddings', 10, $query)
----

[.description]
Query the relationship vector index `review-embeddings` for a neighborhood of `10` similar reviews to the vector given by the `query` parameter.
====

////
.Parameters
[source, parameters]
----
{
  "id": "42",
  "vector": [1.0, 2.0, 3.0]
}
----
////

====
[source, cypher, role=noheader]
----
MATCH (n:Node {id: $id})
CALL db.create.setNodeVectorProperty(n, 'propertyKey', $vector)
----

[.description]
Set the vector properties of a node using `db.create.setNodeVectorProperty`.
====

////
.Parameters
[source, parameters]
----
{
  "relId": "42"
}
----
////

====
[source, cypher, role=noheader]
----
MATCH ()-[r:Relationship {id: $relId}]->()
CALL db.create.setRelationshipVectorProperty(r, 'propertyKey', $vector)
----

[.description]
Set the vector properties of a relationship using `db.create.setRelationshipVectorProperty`.
====

====
[source, cypher, role=noheader]
----
SHOW VECTOR INDEXES
----

[.description]
List all vector indexes.
====

====
[source, cypher, role=noheader]
----
DROP INDEX `abstract-embeddings`
----

[.description]
Drop a vector index.
====