= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/indexes/semantic-indexes/vector-indexes/[Vector indexes]

====
[source, cypher, role=noheader]
----
CREATE VECTOR INDEX `abstract-embeddings`
FOR (a:Abstract) ON (a.embedding)
OPTIONS {
  indexConfig: {
    `vector.dimensions`: 1536,
    `vector.similarity_function`: 'cosine'
  }
}
----

[.description]
Create a vector index on nodes with label `Abstract`, property `embedding`, and a vector dimension of `1536` using the `cosine` similarity function and the name `abstract-embeddings`.
====

====
[source, cypher, role=noheader]
----
CREATE VECTOR INDEX `review-embeddings`
FOR ()-[r:REVIEWED]-() ON (r.embedding)
OPTIONS {
  indexConfig: {
    `vector.dimensions`: 256,
    `vector.similarity_function`: 'cosine'
  }
}
----

[.description]
Create a vector index on relationships with relationship type `REVIEWED`, property `embedding`, and a vector dimension of `256` using the `cosine` similarity function and the name `review-embeddings`.
====

====
[source, cypher, role=noheader]
----
CREATE VECTOR INDEX `multi-label-index`
FOR (a:Abstract|Summary) ON (a.embedding)
----

[.description]
Create a vector index on nodes with label `Abstract` or `Summary`, property `embedding`, and the name `multi-label-index`.
The index uses the default `cosine` similarity function and accepts any vector dimension since neither is specified.
====

====
[source, cypher, role=noheader]
----
CREATE VECTOR INDEX `additional-properties-index`
FOR ()-[r:REVIEWED]-()
ON (r.embedding)
WITH [r.date, r.grade]
----

[.description]
Create a vector index on relationships with relationship type `REVIEWED`, vector property `embedding`, additional properties for filtering `date` and `grade`, and the name `additional-properties-index`.
The index uses the default `cosine` similarity function and accepts any vector dimension since neither is specified.
====


====
[source, cypher, role=noheader]
----
MATCH (abstract:Abstract {id: 'specific-document-id'})
MATCH (n:Abstract)
SEARCH n IN (
  VECTOR INDEX `abstract-embeddings`
  FOR abstract.embedding
  LIMIT 10
) SCORE AS myScore
RETURN n, myScore
----

[.description]
Query the node vector index `abstract-embeddings` using `SEARCH` for a neighborhood of `10` similar abstracts.
====

====
[source, cypher, role=noheader, role=test-skip]
----
MATCH (n:Node {id: $id})
SET n.propertyKey = vector($vector, 1536, FLOAT32)
----

[.description]
Set the vector properties of a node.
====

====
[source, cypher, role=noheader, role=test-skip]
----
MATCH ()-[r:Relationship {id: $id}]->()
SET r.propertyKey = vector($vector, 1536, FLOAT32)
----

[.description]
Set the vector properties of a relationship using `db.create.setRelationshipVectorProperty`.
====

====
[source, cypher, role=noheader]
----
SHOW VECTOR INDEXES
----

[.description]
List all vector indexes.
====

====
[source, cypher, role=noheader]
----
DROP INDEX `abstract-embeddings`
----

[.description]
Drop a vector index.
====