= link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/with/[WITH^]

====
include::ROOT:clauses/with.adoc[tag=clauses_with_new_variable]

[.description]
`WITH` can be used in combination with the `AS` keyword to bind new variables which can then be passed to subsequent clauses.
Any variables not explicitly referenced by `WITH` (or carried over by `WITH *`) are dropped from the scope of the query.
====

====
include::ROOT:clauses/with.adoc[tag=clauses_with_all_variables]

[.description]
Use the wildcard `*` to carry over all variables that are in scope.
====

====
include::ROOT:clauses/with.adoc[tag=clauses_with_subquery]

[.description]
`WITH` cannot de-scope variables imported to a `CALL` subquery, because variables imported to a subquery are considered global to its inner scope.
====

====
include::ROOT:clauses/with.adoc[tag=clauses_with_bind_values]

[.description]
`WITH` can be used to assign the values of expressions to variables.
====


====
include::ROOT:clauses/with.adoc[tag=clauses_with_chain_expressions]

[.description]
`WITH` can be used to chain expressions.
====

====
include::ROOT:clauses/with.adoc[tag=clauses_with_aggregations]

[.description]
`WITH` can be used to perform aggregations and bind the results to new variables.
====

====
include::ROOT:clauses/with.adoc[tag=clauses_with_remove_duplicates]

[.description]
`WITH` can be used to remove duplicate values from the result set if appended with the modifier `DISTINCT`.
====


====
include::ROOT:clauses/with.adoc[tag=clauses_with_ordering_pagination]

[.description]
`WITH` can order and paginate results if used together with the `ORDER BY`, `LIMIT`, and `SKIP` subclauses.
====

====
include::ROOT:clauses/with.adoc[tag=clauses_with_filtering]

[.description]
`WITH` can be followed by the `WHERE` subclause to filter results.
====

====
include::ROOT:clauses/with.adoc[tag=clauses_with_combine_write_read]

[.description]
If a write clause is followed by a read clause, `WITH` must be used as a separator between the two.
====
