= Conditional queries (WHEN)
:page-role: new-2025.02

The `WHEN` clause in Cypher allows conditional execution of parts of a query, enabling different query branches or subqueries to run based on specified conditions.
Much like `UNION`, `WHEN` cannot be used as a regular clause in a query (though it can be used as a standalone clause).
Instead, it encloses different query branches or subqueries as a condition for their execution.
In this way, it performs similar a control-flow structure to the `IF` statements of other programming languages.

[[example-graph]]
== Example graph

The following graph is used for the examples below:

image::conditionals_graph.svg[width="400",role="middle"]

To recreate the graph, run the following query against an empty Neo4j database:

[source, cypher, role=test-setup]
----
CREATE
  (alice:Person {name:'Alice', age: 38, eyes: 'brown'}),
  (bob:Person {name: 'Bob', age: 25, eyes: 'blue'}),
  (charlie:Person {name: 'Charlie', age: 53, eyes: 'green'}),
  (daniel:Person {name: 'Daniel', eyes: 'brown'}),
  (eskil:Person {name: 'Eskil', age: 41, eyes: 'blue'}),
  (alice)-[:KNOWS]->(bob),
  (alice)-[:KNOWS]->(charlie),
  (bob)-[:KNOWS]->(daniel),
  (charlie)-[:KNOWS]->(daniel),
  (bob)-[:MARRIED]->(eskil)
----

== Standalone `WHEN` branches

`WHEN` branches can be used independently of other query parts.
The first predicate that evaluates to `true` will be executed.
If no `WHEN` branches were executed and an `ELSE` branch exists, it is executed.
If no `WHEN` branches evaluates to `true` and no `ELSE` branch is present, no rows are produced.
The following example demonstrates this basic logic:

.Basic `WHEN` logic
[source, cypher]
----
WHEN false THEN RETURN 1 AS x
WHEN true THEN RETURN 2 AS x
ELSE RETURN 3 AS x
----

Since the second `WHEN` branch is `true`, it will execute, while the preceding branch (which is `false`) and the succeeding `ELSE` branch will be skipped.

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| x
| 2

1+d| Rows: 1
|===

== Conditional subqueries

`WHEN` can be used inside a subquery to execute operations only when a condition evaluates to `true`.

In the below example, `WHEN` is used to execute a xref:subqueries/call-subquery.adoc[`CALL` subquery] for each row that the condition (`m IS NULL`) evaluates to `true`. 

.`WHEN` inside a `CALL` subquery
[source, cypher]
----
MATCH (n:Person)
OPTIONAL MATCH (n)-[:KNOWS]->(m)
CALL {
  WHEN m IS NULL THEN {
    MERGE (f: Person {name: 'Peter'}), (n)-[:KNOWS]->(f)
    RETURN f, collect(n.name) AS newFriends
  }
}
RETURN f.name AS newNode, newFriends
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| newNode | newFriends

| "Peter"
| ["Daniel", "Eskil"]

2+d| Rows: 1
|===


[source, cypher]
----
MATCH (n:Person)
WHERE EXISTS {
    WHEN n.age > 40 THEN {
      MATCH (n)<-[:MARRIED]-(x:Person)
      RETURN x
   }
   ELSE {
      MATCH (n)<-[:KNOWS]-(x:Person)
      RETURN x
   }
}
 RETURN n.name
----

== Conditional `UNION` queries

[source, cypher]
----
{
    WHEN true THEN RETURN 1 AS x
    WHEN false THEN RETURN 2 AS x
    ELSE RETURN 3 AS x
}
UNION
{
    WHEN false THEN RETURN 4 AS x
    WHEN false THEN RETURN 5 AS x
    ELSE RETURN 6 AS x
}
----

== Rules