[[administration-security-reads]]
= Read privileges
:description: This section explains how to use Cypher to manage read privileges on graphs. 


* xref:administration/security/reads.adoc#administration-security-reads-traverse[The `TRAVERSE` privilege]
* xref:administration/security/reads.adoc#administration-security-reads-read[The `READ` privilege]
* xref:administration/security/reads.adoc#administration-security-reads-match[The `MATCH` privilege]


There are three separate read privileges:

* `TRAVERSE` - enables the specified entities to be found.
* `READ` - enables the specified properties on the found entities to be read.
* `MATCH` - combines both `TRAVERSE` and `READ`, enabling an entity to be found and its properties read.


[role=enterprise-edition]
[[administration-security-reads-traverse]]
== The `TRAVERSE` privilege

Users can be granted the right to find nodes and relationships using the `GRANT TRAVERSE` privilege.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-traverse-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
GRANT TRAVERSE
    ON {DEFAULT GRAPH | GRAPH[S] { * | name[, ...] }}
        [
            ELEMENT[S] { * | label-or-rel-type[, ...] }
            | NODE[S] { * | label[, ...] }
            | RELATIONSHIP[S] { * | rel-type[, ...] }
        ]
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-traverse-syntax.asciidoc[]

For example, we can enable the user `jake`, who has role 'regularUsers' to find all nodes with the label `Post`.


.Query
[source, cypher]
----
GRANT TRAVERSE ON GRAPH neo4j NODES Post TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT TRAVERSE ON GRAPH neo4j NODES Post TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The `TRAVERSE` privilege can also be denied.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-traverse-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
DENY TRAVERSE
    ON {DEFAULT GRAPH | GRAPH[S] { * | name[, ...] }}
        [
            ELEMENT[S] { * | label-or-rel-type[, ...] }
            | NODE[S] { * | label[, ...] }
            | RELATIONSHIP[S] { * | rel-type[, ...] }
        ]
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-traverse-syntax.asciidoc[]

For example, we can disable the user `jake`, who has role 'regularUsers' from finding all nodes with the label `Payments`.


.Query
[source, cypher]
----
DENY TRAVERSE ON DEFAULT GRAPH NODES Payments TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY TRAVERSE ON DEFAULT GRAPH NODES Payments TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[role=enterprise-edition]
[[administration-security-reads-read]]
== The `READ` privilege

Users can be granted the right to do property reads on nodes and relationships using the `GRANT READ` privilege.
It is very important to note that users can only read properties on entities that they are enabled to find in the first place.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-read-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
GRANT READ
    "{" { * | property[, ...] } "}"
    ON {DEFAULT GRAPH | GRAPH[S] { * | name[, ...] }}
        [
            ELEMENT[S] { * | label-or-rel-type[, ...] }
            | NODE[S] { * | label[, ...] }
            | RELATIONSHIP[S] { * | rel-type[, ...] }
        ]
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-read-syntax.asciidoc[]

For example, we can enable the user `jake`, who has role 'regularUsers' to read all properties on nodes with the label `Post`.
The `*` implies that the ability to read all properties also extends to properties that might be added in the future.


.Query
[source, cypher]
----
GRANT READ { * } ON GRAPH neo4j NODES Post TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT READ { * } ON GRAPH neo4j NODES Post TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Granting property `READ` access does not imply that the entities with that property can be found.
For example, if there is also a `DENY TRAVERSE` present on the same entity as a `GRANT READ`, the entity will not be found by a Cypher `MATCH` statement.


====

The `READ` privilege can also be denied.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-read-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
DENY READ
    "{" { * | property[, ...] } "}"
    ON {DEFAULT GRAPH | GRAPH[S] { * | name[, ...] }}
        [
            ELEMENT[S] { * | label-or-rel-type[, ...] }
            | NODE[S] { * | label[, ...] }
            | RELATIONSHIP[S] { * | rel-type[, ...] }
        ]
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-read-syntax.asciidoc[]

Although we just granted the user 'jake' the right to read all properties, we may want to hide the `secret` property. The following example shows how to do that.


.Query
[source, cypher]
----
DENY READ { secret } ON GRAPH neo4j NODES Post TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY READ { secret } ON GRAPH neo4j NODES Post TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[role=enterprise-edition]
[[administration-security-reads-match]]
== The `MATCH` privilege

Users can be granted the right to find and do property reads on nodes and relationships using the `GRANT MATCH` privilege.
This is semantically the same as having both `TRAVERSE` and `READ` privileges.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-match-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
GRANT MATCH
    "{" { * | property[, ...] } "}"
    ON {DEFAULT GRAPH | GRAPH[S] { * | name[, ...] }}
        [
            ELEMENT[S] { * | label-or-rel-type[, ...] }
            | NODE[S] { * | label[, ...] }
            | RELATIONSHIP[S] { * | rel-type[, ...] }
        ]
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-match-syntax.asciidoc[]

For example if you want to grant the ability to read the properties `language` and `length` for nodes with the label `Message`,
as well as the ability to find these nodes, to a role `regularUsers` you can use the following `GRANT MATCH` query.


.Query
[source, cypher]
----
GRANT MATCH { language, length } ON GRAPH neo4j NODES Message TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT MATCH { language, length } ON GRAPH neo4j NODES Message TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

Like all other privileges, the `MATCH` privilege can also be denied.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-match-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
DENY MATCH
    "{" { * | property[, ...] } "}"
    ON {DEFAULT GRAPH | GRAPH[S] { * | name[, ...] }}
        [
            ELEMENT[S] { * | label-or-rel-type[, ...] }
            | NODE[S] { * | label[, ...] }
            | RELATIONSHIP[S] { * | rel-type[, ...] }
        ]
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-match-syntax.asciidoc[]

Please note that the effect of denying a `MATCH` privilege depends on whether concrete property keys are specified or a `+*+`.
If you specify concrete property keys then `DENY MATCH` will only deny reading those properties.
Finding the elements to traverse would still be enabled.
If you specify `+*+` instead then both traversal of the element and all property reads will be disabled.
The following queries will show examples for this.

Denying to read the property ´content´ on nodes with the label `Message` for the role `regularUsers` would look like the following query.
Although not being able to read this specific property, nodes with that label can still be traversed (and, depending on other grants, other properties on it could still be read).


.Query
[source, cypher]
----
DENY MATCH { content } ON GRAPH neo4j NODES Message TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY MATCH { content } ON GRAPH neo4j NODES Message TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The following query exemplifies how it would look like if you want to deny both reading all properties and traversing nodes labeled with `Account`.


.Query
[source, cypher]
----
DENY MATCH { * } ON GRAPH neo4j NODES Account TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY MATCH { * } ON GRAPH neo4j NODES Account TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

