[[administration-security-writes]]
= Write privileges
:description: This section explains how to use Cypher to manage write privileges on graphs. 


* xref:administration/security/writes.adoc#administration-security-writes-create[The `CREATE` privilege]
* xref:administration/security/writes.adoc#administration-security-writes-delete[The `DELETE` privilege]
* xref:administration/security/writes.adoc#administration-security-writes-set-label[The `SET LABEL` privilege]
* xref:administration/security/writes.adoc#administration-security-writes-remove-label[The `REMOVE LABEL` privilege]
* xref:administration/security/writes.adoc#administration-security-writes-set-property[The `SET PROPERTY` privilege]
* xref:administration/security/writes.adoc#administration-security-writes-merge[The `MERGE` privilege]
* xref:administration/security/writes.adoc#administration-security-writes-write[The `WRITE` privilege]
* xref:administration/security/writes.adoc#administration-security-writes-all[The `ALL GRAPH PRIVILEGES` privilege]


Write privileges are defined for different parts of the graph:

* `CREATE` - allows creating nodes and relationships.
* `DELETE` - allows deleting nodes and relationships.
* `SET LABEL` - allows setting the specified node labels using the `SET` clause.
* `REMOVE LABEL` - allows removing the specified node labels using the `REMOVE` clause.
* `SET PROPERTY` - allows setting properties on nodes and relationships.

There are also compound privileges which combine the above specific privileges:

* `MERGE` - allows match, create and set property to permit the `MERGE` command.
* `WRITE` - allows all write operations on an entire graph.
* `ALL GRAPH PRIVILEGES` - allows all read and write operation on an entire graph.


[role=enterprise-edition]
[[administration-security-writes-create]]
== The `CREATE` privilege

The `CREATE` privilege allows a user to create new node and relationship elements in a graph.
See the Cypher xref:clauses/create.adoc[CREATE] clause.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-create-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
GRANT CREATE ON GRAPH[S] { * | name[, ...] }
    [
        ELEMENT[S] { * | label-or-rel-type[, ...] }
        | NODE[S] { * | label[, ...] }
        | RELATIONSHIP[S] { * | rel-type[, ...] }
    ]
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-create-syntax.asciidoc[]

For example, granting the ability to create elements on the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT CREATE ON GRAPH neo4j ELEMENTS * TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT CREATE ON GRAPH neo4j ELEMENTS * TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The `CREATE` privilege can also be denied.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-create-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
DENY CREATE ON GRAPH[S] { * | name[, ...] }
    [
        ELEMENT[S] { * | label-or-rel-type[, ...] }
        | NODE[S] { * | label[, ...] }
        | RELATIONSHIP[S] { * | rel-type[, ...] }
    ]
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-create-syntax.asciidoc[]

For example, denying the ability to create nodes with the label `foo` on all graphs to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
DENY CREATE ON GRAPH * NODES foo TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY CREATE ON GRAPH * NODES foo TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
If the user attempts to create nodes with a label that does not already exist in the database, then the user must also possess the
xref:administration/security/administration.adoc#administration-security-administration-database-tokens[CREATE NEW LABEL] privilege. The same applies to new relationships - the
xref:administration/security/administration.adoc#administration-security-administration-database-tokens[CREATE NEW RELATIONSHIP TYPE] privilege is required.


====

[role=enterprise-edition]
[[administration-security-writes-delete]]
== The `DELETE` privilege

The `DELETE` privilege allows a user to delete node and relationship elements in a graph.
See the Cypher xref:clauses/delete.adoc[DELETE] clause.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-delete-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
GRANT DELETE ON GRAPH[S] { * | name[, ...] }
    [
        ELEMENT[S] { * | label-or-rel-type[, ...] }
        | NODE[S] { * | label[, ...] }
        | RELATIONSHIP[S] { * | rel-type[, ...] }
    ]
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-delete-syntax.asciidoc[]

For example, granting the ability to delete elements on the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT DELETE ON GRAPH neo4j ELEMENTS * TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT DELETE ON GRAPH neo4j ELEMENTS * TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The `DELETE` privilege can also be denied.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-delete-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
DENY DELETE ON GRAPH[S] { * | name[, ...] }
    [
        ELEMENT[S] { * | label-or-rel-type[, ...] }
        | NODE[S] { * | label[, ...] }
        | RELATIONSHIP[S] { * | rel-type[, ...] }
    ]
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-delete-syntax.asciidoc[]

For example, denying the ability to delete relationships with the relationship type `bar` on all graphs to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
DENY DELETE ON GRAPH * RELATIONSHIPS bar TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY DELETE ON GRAPH * RELATIONSHIPS bar TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Users with `DELETE` privilege, but restricted `TRAVERSE` privileges, will not be able to do `DETACH DELETE` in all cases.
 See link:{neo4j-docs-base-uri}/operations-manual/{page-version}/authentication-authorization/access-control#detach-delete-restricted-user[Operations Manual -> Fine-grained access control] for more info.


====

[role=enterprise-edition]
[[administration-security-writes-set-label]]
== The `SET LABEL` privilege

The `SET LABEL` privilege allows you to set labels on a node using the xref:clauses/set.adoc#set-set-a-label-on-a-node[SET clause].

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-set-label-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
GRANT SET LABEL { * | label[, ...] }
    ON GRAPH[S] { * | name[, ...] }
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-set-label-syntax.asciidoc[]

For example, granting the ability to set any label on nodes of the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT SET LABEL * ON GRAPH neo4j TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT SET LABEL * ON GRAPH neo4j TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Unlike many of the other read and write privileges, it is not possible to restrict the `SET LABEL` privilege to specific ELEMENTS, NODES or RELATIONSHIPS.


====

The `SET LABEL` privilege can also be denied.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-set-label-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
DENY SET LABEL { * | label[, ...] }
    ON GRAPH[S] { * | name[, ...] }
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-set-label-syntax.asciidoc[]

For example, denying the ability to set the label `foo` on nodes of all graphs to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
DENY SET LABEL foo ON GRAPH * TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY SET LABEL foo ON GRAPH * TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
If no instances of this label exist in the database, then the xref:administration/security/administration.adoc#administration-security-administration-database-tokens[CREATE NEW LABEL] privilege is also required.


====

[role=enterprise-edition]
[[administration-security-writes-remove-label]]
== The `REMOVE LABEL` privilege

The `REMOVE LABEL` privilege allows you to remove labels from a node using the xref:clauses/remove.adoc#remove-remove-a-label-from-a-node[REMOVE clause].

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-remove-label-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
GRANT REMOVE LABEL { * | label[, ...] }
    ON GRAPH[S] { * | name[, ...] }
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-remove-label-syntax.asciidoc[]

For example, granting the ability to remove any label from nodes of the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT REMOVE LABEL * ON GRAPH neo4j TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT REMOVE LABEL * ON GRAPH neo4j TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Unlike many of the other read and write privileges, it is not possible to restrict the `REMOVE LABEL` privilege to specific ELEMENTS, NODES or RELATIONSHIPS.


====

The `REMOVE LABEL` privilege can also be denied.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-remove-label-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
DENY REMOVE LABEL { * | label[, ...] }
    ON GRAPH[S] { * | name[, ...] }
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-remove-label-syntax.asciidoc[]

For example, denying the ability to remove the label `foo` from nodes of all graphs to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
DENY REMOVE LABEL foo ON GRAPH * TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY REMOVE LABEL foo ON GRAPH * TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[role=enterprise-edition]
[[administration-security-writes-set-property]]
== The `SET PROPERTY` privilege

The `SET PROPERTY` privilege allows a user to set a property on a node or relationship element in a graph using the xref:clauses/set.adoc#set-set-a-property[SET clause].

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-set-property-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
GRANT SET PROPERTY "{" { * | property[, ...] } "}"
    ON GRAPH[S] { * | name[, ...] }
        [
            ELEMENT[S] { * | label-or-rel-type[, ...] }
            | NODE[S] { * | label[, ...] }
            | RELATIONSHIP[S] { * | rel-type[, ...] }
        ]
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-set-property-syntax.asciidoc[]

For example, granting the ability to set any property on all elements of the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT SET PROPERTY {*} ON GRAPH neo4j ELEMENTS * TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT SET PROPERTY {*} ON GRAPH neo4j ELEMENTS * TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The `SET PROPERTY` privilege can also be denied.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-set-property-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
DENY SET PROPERTY "{" { * | property[, ...] } "}"
    ON GRAPH[S] { * | name[, ...] }
        [
            ELEMENT[S] { * | label-or-rel-type[, ...] }
            | NODE[S] { * | label[, ...] }
            | RELATIONSHIP[S] { * | rel-type[, ...] }
        ]
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-set-property-syntax.asciidoc[]

For example, denying the ability to set the property `foo` on nodes with the label `bar` on all graphs to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
DENY SET PROPERTY { foo } ON GRAPH * NODES bar TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY SET PROPERTY { foo } ON GRAPH * NODES bar TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
If the users attempts to set a property with a property name that does not already exist in the database the user must also possess the
xref:administration/security/administration.adoc#administration-security-administration-database-tokens[CREATE NEW PROPERTY NAME] privilege.


====

[role=enterprise-edition]
[[administration-security-writes-merge]]
== The `MERGE` privilege

The `MERGE` privilege is a compound privilege that combines `TRAVERSE` and `READ` (i.e. `MATCH`) with `CREATE` and `SET PROPERTY`. This is intended to
 permit use of xref:clauses/merge.adoc[the MERGE command] but is applicable to all reads and writes that require these privileges.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-merge-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
GRANT MERGE "{" { * | property[, ...] } "}"
    ON GRAPH[S] { * | name[, ...] }
        [
            ELEMENT[S] { * | label-or-rel-type[, ...] }
            | NODE[S] { * | label[, ...] }
            | RELATIONSHIP[S] { * | rel-type[, ...] }
        ]
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-merge-syntax.asciidoc[]

For example, granting `MERGE` on all elements of the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT MERGE {*} ON GRAPH neo4j ELEMENTS * TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT MERGE {*} ON GRAPH neo4j ELEMENTS * TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

It is not possible to deny the `MERGE` privilege. If it is desirable to prevent a users from creating elements and setting properties, use
xref:administration/security/writes.adoc#administration-security-writes-create[DENY CREATE] or xref:administration/security/writes.adoc#administration-security-writes-set-property[DENY SET PROPERTY].

[NOTE]
====
If the users attempts to create nodes with a label that does not already exist in the database the user must also possess the
xref:administration/security/administration.adoc#administration-security-administration-database-tokens[CREATE NEW LABEL] privilege. The same applies to new relationships and properties - the
xref:administration/security/administration.adoc#administration-security-administration-database-tokens[CREATE NEW RELATIONSHIP TYPE] or
xref:administration/security/administration.adoc#administration-security-administration-database-tokens[CREATE NEW PROPERTY NAME] privileges are required.


====

[role=enterprise-edition]
[[administration-security-writes-write]]
== The `WRITE` privilege

The `WRITE` privilege allows the user to execute any write command on a graph.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-write-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
GRANT WRITE
    ON GRAPH[S] { * | name[, ...] }
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-write-syntax.asciidoc[]

For example, granting the ability to write on the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT WRITE ON GRAPH neo4j TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT WRITE ON GRAPH neo4j TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Unlike the more specific write commands, it is not possible to restrict `WRITE` privileges to specific ELEMENTS, NODES or RELATIONSHIPS.
If it is desirable to prevent a user from writing to a subset of database objects, a `GRANT WRITE` can be combined with more specific
`DENY` commands to target these elements.


====

The `WRITE` privilege can also be denied.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-write-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
DENY WRITE
    ON GRAPH[S] { * | name[, ...] }
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-write-syntax.asciidoc[]

For example, denying the ability to write on the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
DENY WRITE ON GRAPH neo4j TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY WRITE ON GRAPH neo4j TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Users with `WRITE` privilege but restricted `TRAVERSE` privileges will not be able to do `DETACH DELETE` in all cases.
 See link:{neo4j-docs-base-uri}/operations-manual/{page-version}/authentication-authorization/access-control#detach-delete-restricted-user[Operations Manual -> Fine-grained access control] for more info.


====

[role=enterprise-edition]
[[administration-security-writes-all]]
== `ALL GRAPH PRIVILEGES`

The `ALL GRAPH PRIVILEGES` privilege allows the user to execute any command on a graph.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-all-graph-privileges-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
GRANT ALL [ [ GRAPH ] PRIVILEGES ]
    ON GRAPH[S] { * | name[, ...] }
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/grant-all-graph-privileges-syntax.asciidoc[]

For example, granting all graph privileges on the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT ALL GRAPH PRIVILEGES ON GRAPH neo4j TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT ALL GRAPH PRIVILEGES ON GRAPH neo4j TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====

Unlike the more specific read and write commands, it is not possible to restrict `ALL GRAPH PRIVILEGES` privileges to specific ELEMENTS,
NODES or RELATIONSHIPS. If it is desirable to prevent a user from reading or writing to a subset of database objects,
a `GRANT ALL GRAPH PRIVILEGES` can be combined with more specific `DENY` commands to target these elements.


====

The `ALL GRAPH PRIVILEGES` privilege can also be denied.

// tag::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-all-graph-privileges-syntax.asciidoc[]
// tag::include-neo4j-documentation[]
.Command syntax
[source, cypher, role=noplay]
-----
DENY ALL [ [ GRAPH ] PRIVILEGES ]
    ON GRAPH[S] { * | name[, ...] }
    TO role[, ...]
-----
// end::include-neo4j-documentation[]
// end::neo4j-cypher-docs/docs/dev/ql/administration/security/deny-all-graph-privileges-syntax.asciidoc[]

For example, denying all graph privileges on the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
DENY ALL GRAPH PRIVILEGES ON GRAPH neo4j TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY ALL GRAPH PRIVILEGES ON GRAPH neo4j TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

