:description: This page explains how to drop indexes used for search performance.
= Drop indexes

An index can be dropped (removed) using the name with the `DROP INDEX index_name` command.
This command can drop indexes of any type, except those backing constraints.
The name of the index can be found using the xref:indexes/search-performance-indexes/managing-indexes.adoc#list-indexes[`SHOW INDEXES` command], given in the output column `name`.

[source, syntax, role="noheader"]
----
DROP INDEX index_name [IF EXISTS]
----

The `DROP INDEX` command is optionally idempotent.
This means that its default behavior is to throw an error if an attempt is made to drop the same index twice.
With `IF EXISTS`, no error is thrown and nothing happens should the index not exist.
As of Neo4j 5.17, an informational notification is instead returned detailing that the index does not exist.

[NOTE]
Dropping an index requires link:{neo4j-docs-base-uri}/operations-manual/current/database-administration/authentication-authorization/database-administration/#access-control-database-administration-index[the `DROP INDEX` privilege].

[[drop-indexes-examples]]
== Examples

* xref:indexes/search-performance-indexes/managing-indexes.adoc#drop-an-index[]
* xref:indexes/search-performance-indexes/managing-indexes.adoc#drop-an-index-by-param[]
* xref:indexes/search-performance-indexes/managing-indexes.adoc#drop-index-backing-constraint[]
* xref:indexes/search-performance-indexes/managing-indexes.adoc#drop-a-non-existing-index[]

[[drop-an-index]]
=== Drop an index

The following statement will attempt to drop the index named `example_index`.

.Dropping an index
[source, cypher]
----
DROP INDEX example_index
----

If an index with that name exists it is removed, if not the command fails.

[[drop-an-index-by-param]]
==== Drop an index using a parameter

_This feature was introduced in Neo4j 5.16._

The following statement will attempt to drop the index named `range_index_param` using a parameter for the index name.

.Parameters
[source, parameters]
----
{
  "name": "range_index_param"
}
----

.Dropping an index
[source, cypher]
----
DROP INDEX $name
----

If an index with that name exists it is removed, if not the command fails.

[[drop-index-backing-constraint]]
=== Failure to drop an index backing a constraint

It is not possible to drop indexes that back constraints.

.Dropping an index backing a constraint
[source, cypher,role=test-fail]
----
DROP INDEX uniqueBookIsbn
----

.Error message
[source, error]
----
Unable to drop index: Index belongs to constraint: `uniqueBookIsbn`
----

Dropping the index-backed constraint will also remove the backing index.
For more information, see xref:constraints/managing-constraints.adoc#drop-constraint[Drop a constraint by name].

[[drop-a-non-existing-index]]
=== Drop a non-existing index

If it is uncertain if an index exists and you want to drop it if it does but not get an error should it not, use `IF EXISTS`.

The following statement will attempt to drop the index named `missing_index_name`.

.Dropping an index with `IF EXISTS`
[source, cypher]
----
DROP INDEX missing_index_name IF EXISTS
----

If an index with that name exists it is removed, if not the command does nothing.
As of Neo4j 5.17, additionally, an informational notification is returned.

.Notification
[source]
----
`DROP INDEX missing_index_name IF EXISTS` has no effect. `missing_index_name` does not exist.
----
