= Property operators
:description: Information about Cypher's graph element operators, which enable the querying and manipulation of nodes and relationships.

Property operators allow you to manipulate and query `NODE` and `RELATIONSHIP` values.
Cypher contains the following graph element operators:

* Static property access: dot operator (`.`)
* Dynamic property access: subscript operator (`[]`)

For functions that return metadata about `NODE` and `RELATIONSHIPS` values, see:

* xref:functions/scalar.adoc#functions-elementid[`elementId()`]
* xref:functions/scalar.adoc#functions-endnode[`endNode()`]
* xref:functions/scalar.adoc#functions-id[`id()`]
* xref:functions/list.adoc#functions-keys[`keys()`]
* xref:functions/list.adoc#functions-labels[`labels()`]
* xref:functions/scalar.adoc#functions-properties[`properties()`]
* xref:functions/scalar.adoc#functions-startnode[`startNode()`]
* xref:functions/scalar.adoc#functions-type[`type()`]


== Example graph

CREATE (alice:Person {name:'Alice', age: 65, role: 'Project manager', skills: ['Java', 'Python']}),
       (cecil:Person {name: 'Cecil', age: 25, role: 'Software developer', skills: ['Java', 'Python']}),
       (cecilia:Person {name: 'Cecilia', age: 31, role: 'Software developer', skills: ['JavaScript', 'TypeScript']}),  
       (charlie:Person {name: 'Charlie', age: 61, role: 'Security engineer', skills: ['C++', 'Python']}),
       (daniel:Person {name: 'Daniel', age: 39, role: 'Director', skills: ['Ruby', 'Go']}),  
       (eskil:Person {name: 'Eskil', age: 39, role: 'CEO'}),  

       (cecil)-[:WORKS_FOR {since: date('2022-01-01')}]->(alice),
       (cecilia)-[:WORKS_FOR {since: date('2020-10-15')}]->(alice),
       (charlie)-[:WORKS_FOR {since: date('2009-11-08')}]->(daniel),
       (alice)-[:WORKS_FOR]->(daniel),
       (daniel)-[:WORKS_FOR]->(eskil)

== Static property access

Property values can be accessed statically by specifying a property name after the `.` operator.

MATCH (p:Person)
RETURN p.name

MATCH (:Person)-[r:WORKS_FOR]-(:Person)
RETURN r.since


== Dynamic property access

Property values can be accessed dynamically by using the subscript operator, `[]`.

LET nodeProperty = 'name'
MATCH (:Person)
RETURN p[propertyName] AS 










== Dynamic property access