= String concatenation operators
:description: Information about Cypher's string operators.
:table-caption!:

Cypher contains two operators for the concatenation of `STRING` values:

* `||`
* `+`

The two operators are functionally equivalent.
However, `||` is xref:appendix/gql-conformance/index.adoc[GQL conformant], while `+` is not.

For additional expressions that evaluate `STRING` values, see xref:functions/string.adoc[String functions].

[[examples]]
== Examples

.`||` and `+`
[source, cypher]
----
RETURN 'Neo' || '4j' AS result1
       'Neo' + '4j' AS result2
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| result1 | result2

| "Neo4j" | "Neo4j"

2+d|Rows: 1
|===

The xref:functions/string.adoc#functions-tostring[`toString()`] function can be used to concatenate non-`STRING` values into a `STRING` value.

.Concatenation using `toString()` function
[source, cypher]
----
RETURN 'The number is: ' || toString(42) AS result
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| result

| "The number is: 42"

1+d| Rows: 1
|===

Cypher does not insert spaces when concatenating `STRING` values.

.Adding whitespaces in `STRING` concatenation
[source, cypher]
----
RETURN 'Alpha' || 'Beta' AS result1, 
       'Alpha' || ' ' || 'Beta' AS result2
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| result1 | result2

| "AlphaBeta" | "Alpha Beta"

1+d| Rows: 1
|===

.Concatenating `STRING` properties
[source, cypher]
----
CREATE (p:Person {firstName: 'Keanu', lastName: 'Reeves'})
SET p.fullName = p.firstName || ' ' || p.lastName
RETURN p.fullName AS fullName
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| fullName

| "Keanu Reeves"

1+d| Rows: 1
|===

`STRING` values in a `LIST` can be concatenated using the xref:functions/list.adoc#functions-reduce[`reduce()`] function.

.Concatenate `STRING` values in a `LIST`
[source, cypher]
----
RETURN reduce(acc = '', item IN ['Neo', '4j'] | acc + item) AS result
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| result

| "Neo4j"

1+d| Rows: 1
|===

Concatenating a `STRING` value with `NULL` returns `NULL`.
To skip the first `NULL` value in a list of expressions, use the xref:functions/scalar.adoc#functions-coalesce[`coalesce()`] function.

In the following example, `coalesce()` is used with `reduce()` to replace each `NULL` value in the `LIST` with an empty `STRING` (`''`).
This ensures that all `NULL` values are effectively skipped, allowing the `reduce()` function to concatenate the remaining `STRING` values.

.Using `reduce()` and `coalesce()` to skip `NULL` values when concatenating a `LIST`
[source, cypher]
----
WITH ['Neo', NULL, '4j', NULL, 'Hello', NULL] AS items
RETURN reduce(acc = '', item IN items | acc + coalesce(item, '')) AS result
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| result

| "Neo4jHello"

1+d| Rows: 1
|===