:description: Information about mandatory GQL features not currently supported by Cypher.
= Currently unsupported mandatory GQL features

Cypher supports most mandatory GQL features.
There are, however, currently a few mandatory GQL features not yet in Cypher that Neo4j is actively working towards implementing.
The table below provides an overview of these GQL features and, where applicable, their functional equivalents in Neo4j.

Unlike optional GQL features, mandatory GQL features are not assigned a GQL feature ID code.
The below table is instead listed in order of their appearance in the link:https://www.iso.org/standard/76120.html[ISO/IEC 39075:2024(en) GQL Standard].

[options="header",cols="2a,3a,5a"]
|===
| GQL Standard subclause
| Description
| Comment and similar Neo4j functionality

| 4.9.2
| GQL-status objects
| Exposing successful execution results, errors, exceptions, and warnings as GQL-status objects.

| 7.1-7.3
| Session management
| GQL defines the following session commands: `SESSION SET`, `SESSION RESET`, and `SESSION CLOSE`.
Neo4j offers session management through the link:{neo4j-docs-base-uri}/create-applications[driver] session API.

| 8.1-8.4
| Transaction management
| GQL defines the following transaction commands: `START TRANSACTION`, `COMMIT`, and `ROLLBACK`.

Neo4j offers transaction management through the link:{neo4j-docs-base-uri}/create-applications[driver] transaction API.
Cypher Shell also offers specific link:{neo4j-docs-base-uri}/operations-manual/{page-version}/tools/cypher-shell/#cypher-shell-commands[commands] to manage transactions.

| 11.1
| Graph expressions
| GQL defines the following graph reference values commands: `CURRENT_GRAPH` and `CURRENT_PROPERTY_GRAPH`.

| 17.1
| Schema reference
| GQL defines an `AT` clause for selecting the current schema and the following schema selection options: `HOME_SCHEMA` and `CURRENT_SCHEMA`.

| 21.3
| <token>, <separator>, and <identifier>
| GQL specifies a list of link:https://standards.iso.org/iso-iec/39075/ed-1/en/ISO_IEC_39075(en).bnf.txt[reserved words] that cannot be used for unquoted variable names, labels, and property names.
Cypher also specifies a list of xref:syntax/reserved.adoc[reserved keywords], but it differs from GQL's.
|===