= Query caches

Cypher utilizes a number of different caches to speed up query planning.

Out of the box, the set of query caches are _per database_.
That means that for each new database, a new set of caches will be initialized.

The max number of entries per cache is configured with `server.memory.query_cache.per_db_cache_num_entries`.

[NOTE]
====
This setting is only deciding cache size when `server.memory.query_cache.sharing_enabled` is set to `false`.
====

Query caches may consume a lot of memory, especially when running many active databases.
To combat this, and improve predictability on memory consumption,
it is possible to configure the DBMS such that only one set of caches is utilized for all databases.

More information on this topic can be found in the following section:

* xref:query-caches/unified-query-caches.adoc[]

[[Configuration]]
== Configuration summary

See below a summary of query cache configurations.

.Query cache configurations
[options="header", width="100%", cols="4a,1a,3a"]
|===
| Setting | Default value | Description

| `server.memory.query_cache.sharing_enabled`
| `false`
| label:enterprise-edition[Enterprise only] Enable sharing cache space between different databases. With this option turned on, databases will share cache space,
but not cache entries.

| `server.memory.query_cache.shared_cache_num_entries`
| `1000`
| label:enterprise-edition[Enterprise only] The number of cached queries for all databases. This setting is only deciding cache size when
`server.memory.query_cache.sharing_enabled` is set to `true`.

| `server.memory.query_cache.per_db_cache_num_entries`
| `1000`
| The number of cached queries per database.
This setting is only deciding cache size when `server.memory.query_cache.sharing_enabled` is set to `false`.

|===