:description: Different caches to speed up query planning.
[[query-caches]]
= Query caches

Out of the box, the set of query caches is _per database_.
That means that a new set of caches is initialized for each new database.

The maximum number of entries per cache is configured using `server.memory.query_cache.per_db_cache_num_entries`.
It determines the cache size only when `server.memory.query_cache.sharing_enabled` is set to `false`.

Query caches may consume a lot of memory, especially when running many active databases.
To tackle this and improve predictability on memory consumption, you can configure the DBMS to use only one set of caches for all databases.
For more information, see xref:query-caches/unified-query-caches.adoc[Unifying query caches].

[[configure-caches]]
== Configure caches

The following is a summary of the query cache configurations.
For more information, see link:{neo4j-docs-base-uri}/operations-manual/{page-version}/reference/configuration-settings/[Operations Manual -> Configuration settings].

.Query cache configurations
[options="header", width="100%", cols="4m,3a,1m"]
|===
| Setting
| Description
| Default

| link:{neo4j-docs-base-uri}/operations-manual/{page-version}/reference/configuration-settings/#config_server.memory.query_cache.sharing_enabled[server.memory.query_cache.sharing_enabled]
| label:enterprise-edition[Enterprise only] Enable sharing cache space between different databases. With this option turned on, databases will share cache space, but not cache entries.
| false

| link:{neo4j-docs-base-uri}/operations-manual/{page-version}/reference/configuration-settings/#config_server.memory.query_cache.shared_cache_num_entries[server.memory.query_cache.shared_cache_num_entries]
|label:enterprise-edition[Enterprise only] The number of cached queries for all databases. This setting is only deciding cache size when `server.memory.query_cache.sharing_enabled` is set to `true`.
| 1000

| link:{neo4j-docs-base-uri}/operations-manual/{page-version}/reference/configuration-settings/#config_server.memory.query_cache.per_db_cache_num_entries[server.memory.query_cache.per_db_cache_num_entries]
| The number of cached queries per database.
This setting is only deciding cache size when `server.memory.query_cache.sharing_enabled` is set to `false`.
| 1000
|===