:description: How to share query caches space between databases.
[role=enterprise-edition]
[[unifying-query-caches]]
= Unifying query caches

[abstract]
--
This section explains how to enable sharing of cache space and unifying query caches across databases.
--

To enable the unified query caches, set option `server.memory.query_cache.sharing_enabled=true`.

.Unified query cache configurations
[options="header", width="100%", cols="4a,1a,3a"]
|===
| Setting | Default value | Description

| `server.memory.query_cache.sharing_enabled`
| `false`
| Enable sharing cache space between different databases. With this option turned on, databases will share cache space,
but not cache entries.

| `server.memory.query_cache.shared_cache_num_entries`
| `1000`
| The number of cached queries for all databases. This setting is only deciding cache size when
`server.memory.query_cache.sharing_enabled` is set to `true`.
|===

When this feature is enabled, all databases will utilize only on set of query caches.
A database may store and retrieve entries from the shared cache, but it may not retrieve entries produced by another database.

[IMPORTANT]
====
While databases utilize the same set of caches, a database may not observe entries originating from other databases.
====

The database may, however, evict entries from other databases as necessary, according to the constrained cache size and cache eviction policy.
In essence, databases may compete for cache space, but may not observe each other's entries.

When this option is turned on, the cache space available to all databases is configured with
`server.memory.query_cache.shared_cache_num_entries`.
