= Aura and Cypher

== Introduction

Aura is Neo4j's fully managed cloud service. 
It consists of AuraDB and AuraDS.
AuraDB is a graph database service for developers building intelligent applications, and AuraDS is a Graph Data Science (GDS) service for data scientists building predictive models and analytics workflows. 

AuraDB is available on the following tiers: 

* AuraDB Free
* AuraDB Pro
* AuraDB Enterprise

For more information, see link:{neo4j-docs-base-uri}/aura/auradb[Aura docs - Neo4j AuraDB overview].

AuraDS is available on the following tiers: 

* AuraDS Pro
* AuraDS Enterprise

For more information, see link:{neo4j-docs-base-uri}/aura/aurads[Aura docs - Neo4j AuraDS overview]

== Using Cypher on Aura

Most Cypher features are available on all tiers of Aura. 
There are, however, some features which are not available to Aura instances.
For example, it is not possible to create, alter, or drop databases using Aura, nor is it possible to alter or drop servers.

There are also certain Cypher features which are only available on AuraDB Enterprise instances.
These can be categorized as the role-based access-control features of Cypher. 
For example, it is not possible to create, alter, or drop roles using AuraDB Free, AuraDB Pro, AuraDS Pro, or AuraDS Enterprise, but it is possible using AuraDB Enterprise. 

The Cypher Manual uses two different labels to differentiate this distinction:

[options="header,cols=""2a,2a"]
|===
| Label | Description
| label:not-on-aura[] | Cypher feature not available on any tier of Aura.
| label:aura-db-enterprise[] | Cypher feature only available on AuraDB Enterprise.
|===

////
TODO: remove comment blocks once Aura Cheat Sheet has been published. 

== Aura and the Cypher Cheat Sheet

Each different tier of Aura has a customized version of the Cypher Cheat Sheet which only shows the features of Cypher available for the chosen tier. 

The Aura Cheat Sheet can be accessed here: //Add url when available
Note that the default tier is AuraDB Enterprise. 
////
