[[cypher-aura]]
= Cypher and Aura
:description: This section provides an introduction to the Cypher query language.

This section gives a brief overview of Aura, and how Cypher differs to users of Aura.

== What is Aura?

Aura is Neo4j's fully managed cloud service. 
It consists of AuraDB and AuraDS.
AuraDB is a graph database service for developers building intelligent applications, and AuraDS is a Graph Data Science (GDS) service for data scientists building predictive models and analytics workflows. 

AuraDB is available on the following tiers:

* AuraDB Free
* AuraDB Pro
* AuraDB Enterprise

For more information, see link:{neo4j-docs-base-uri}/aura/auradb[Aura docs - Neo4j AuraDB overview].

AuraDS is available on the following tiers:

* AuraDS Pro
* AuraDS Enterprise

For more information, see link:{neo4j-docs-base-uri}/aura/aurads[Aura docs - Neo4j AuraDS overview].

== Using Cypher on Aura

Most Cypher features are available on all tiers of Aura. 
There are, however, some features which are not available to Aura instances.
For example, it is not possible to create, alter, or drop databases using Aura, nor is it possible to alter or drop servers.

There are also certain Cypher features which are only available on AuraDB Enterprise instances.
These can be categorized as the role-based access-control features of Cypher. 
For example, it is not possible to create, alter, or drop roles using AuraDB Free, AuraDB Pro, AuraDS Pro, or AuraDS Enterprise, but it is possible using AuraDB Enterprise. 

The Cypher Manual uses two different labels to differentiate this distinction:

[options="header,cols=""2a,2a"]
|===
| Label | Description
| label:not-on-aura[Not Available on Aura] | Cypher feature not available on any tier of Aura.
| label:aura-db-enterprise[AuraDB Enterprise] | Cypher feature only available on AuraDB Enterprise.
|===

== Aura and the Cypher Cheat Sheet

Each different tier of Aura has a customized version of the Cypher Cheat Sheet which only shows the features of Cypher available for the chosen tier. 

The Cypher Cheat Sheet can be accessed link:{neo4j-docs-base-uri}/cypher-cheat-sheet/{page-version}/auradb-enterprise/[here].
You can select your desired Aura tier and Neo4j version by using the dropdown menus provided.
Note that the default tier is AuraDB Enterprise. 
