[[cypher-intro]]
ifdef::backend-pdf[]
= Neo4j {neo4j-version} Cypher Manual
endif::[]
ifndef::backend-pdf[]
= Introduction
:description: This section provides an introduction to the Cypher query language.
endif::[]

Welcome to the Neo4j Cypher Manual. 

Cypher is Neo4j’s declarative query language, allowing users to unlock the full potential of property graph databases. 

The Cypher Manual aims to be as instructive as possible to readers from a variety of backgrounds and professions, such as developers, administrators, and academic researchers. 

If you are new to Cypher and Neo4j, you can visit the link:{neo4j-docs-base-uri}/getting-started/{page-version}/cypher-intro/[Getting Started Guide -> Introduction to Cypher] chapter. 
Additionally, https://graphacademy.neo4j.com/[Neo4j GraphAcademy] has a variety of free courses tailored for all levels of experience.

For a reference of all available Cypher features, see the link:{neo4j-docs-base-uri}/cypher-cheat-sheet/{page-version}/[Cypher Cheat Sheet].

For a downloadable PDF version of the Cypher Manual, visit the link:{neo4j-docs-base-uri}/resources/docs-archive/#_cypher_query_language[Neo4j documentation archive].

This introduction will cover the following topics:

* xref:introduction/cypher_overview.adoc[]
* xref:introduction/cypher_neo4j.adoc[]
* xref:introduction/cypher_aura.adoc[]


ifndef::backend-pdf[]
License: link:{common-license-page-uri}[Creative Commons 4.0]
endif::[]

//License page should be added at the end when generating pdf. (neo4j-manual-modeling-antora)
ifdef::backend-pdf[]
License: Creative Commons 4.0
endif::[]
