[[cypher-intro]]
= Introduction
:description: This section provides an introduction to the Cypher query language.

Welcome to the Neo4j Cypher Manual. 

Cypher is Neo4j’s declarative query language, allowing users to unlock the full potential of property graph databases. 

For a reference of all available Cypher features, see the link:{neo4j-docs-base-uri}/cypher-cheat-sheet/{page-version}/[Cypher Cheat Sheet].

This introduction will cover the following topics:

* xref:introduction/index.adoc#intended-readership[]
// * xref:* xref:introduction/Index.adoc#structure-content[]
* xref:introduction/cypher_tutorial.adoc[]
* xref:introduction/cypher_neo4j.adoc[]
* xref:introduction/cypher_aura.adoc[]

[[intended-readership]]
== Intended readership

The Cypher Manual aims to be as instructive as possible to readers from a variety of backgrounds and professions, such as developers, administrators, and academic researchers. 
In so doing, it assumes a degree of prior knowledge of Cypher.

The Cypher Manual is, therefore, not primarily intended for beginners (in other words, readers who have never used Cypher before).
Beginners are instead encouraged to visit the link:{neo4j-docs-base-uri}/getting-started/{page-version}/cypher-intro/[Cypher Getting Started Guide], and enroll in the free Cypher courses offered by Neo4j’s https://graphacademy.neo4j.com/[Graph Academy].

////
TODO: add when new structure of the Manual has been published 

[[structure-content]]
== Cypher Manual: content and structure

Chapter 1: Clauses
Chapter 2: Patterns
Chapter 3: Syntax
Chapter 4: Values and Types
Chapter 5: Expressions
Chapter 6: Functions
Chapter 7: Procedures
Chapter 8: Indexes and Constraints
Chapter 9: Query Profiling
Chapter 10: Administration
////

