:description: Neo4j role-based access control and fine-grained security.

[[access-control]]
= Access control

[abstract]
--
This section explains how to manage Neo4j role-based access control and fine-grained security.
--

Neo4j has a complex security model stored in the system graph, which is maintained on a special database called the `system` database.
All administrative commands need to be executed against the `system` database.
When connected to the DBMS over `bolt`, administrative commands are automatically routed to the `system` database.
For more information on how to manage multiple databases, refer to the section on xref::databases.adoc[administering databases].

The concept of _role-based access control_ was introduced in Neo4j 3.1.
Since then, it has been possible to create users and assign them to roles to control whether users can read, write and administer the database.
In Neo4j 4.0 this model was enhanced significantly with the addition of _privileges_, which are the underlying access-control rules by which the users rights are defined.

The original built-in roles still exist with almost the exact same access rights, but they are no-longer statically defined (see xref::access-control/built-in-roles.adoc[Built-in roles]).
Instead they are defined in terms of their underlying _privileges_ and they can be modified by adding an removing these access rights.

In addition, any new roles can be assigned to any combination of _privileges_ to create specific access controls.
Another new major capability is the _sub-graph_ access control, through which read access to the graph can be limited to specific combinations of labels, relationship types, and properties.


[[access-control-syntax]]
== Syntax summaries

Almost all administration commands have variations.
The most common are parts of the command that are optional or that can have multiple values.

See below a summary of the syntax to check all versions of a command.
These summaries use some special characters to indicate such variations.

.Special characters in syntax summaries
[options="header", width="100%", cols="1a,3a,3a"]
|===
| Character | Meaning | Example

| `\|`
| Or
Used to indicate alternative parts of a command.
Needs to be part of a grouping.
| If the syntax needs to specify either a name or `+*+`, this can be indicated with `+* \| name+`.

| `+{+` and `+}+`
| Used to group parts of the command. Commonly found together with `\|`.
| In order to use the `or` in the syntax summary, it needs to be in a group: `+{* \| name}+`.

| `[` and `]`
| Used to indicate an optional part of the command.
It also groups alternatives together, when there can be either of the alternatives or nothing.
| If a keyword in the syntax can either be in singular or plural, we can indicate that the `S` is optional with `GRAPH[S]`.

| `...`
| Repeated pattern.
Related to the command part immediately before this is repeated.
| A comma separated list of names would be `+name[, ...]+`.

| `"`
| When a special character is part of the syntax itself, we surround it with `"` to indicate this.
| To include `+{+` in the syntax use `+"{" { * \| name } "}"+`. In this case, you will get either `+{*}+` or `+{name}+`.

|===

The special characters in the table above are the only ones that need to be escaped using `"` in the syntax summaries.

Here is an example that uses all special characters is granting the `READ` privilege:

[source, syntax, role="noheader"]
----
GRANT READ
  "{" { * | property[, ...] } "}"
  ON {HOME GRAPH | GRAPH[S] { * | name[, ...] }}
    [ ELEMENT[S] { * | label-or-rel-type[, ...] }
    | NODE[S] { * | label[, ...] }
    | RELATIONSHIP[S] { * | rel-type[, ...] }]
  TO role[, ...]
----

Note that this command includes `+{+` and `+}+` in the syntax, and between them there can be a grouping of properties or the character `+*+`.
It also has multiple optional parts, including the entity part of the command which is the grouping following the graph name.

However, there is no need to escape any characters when creating a constraint for a node property.
This is because `(` and `)` are not special characters, and `[` and `]` indicate that the constraint name is optional, and therefore not part of the command.

[source, syntax, role="noheader"]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR (n:LabelName)
REQUIRE n.propertyName IS NOT NULL
----

include::manage-users.adoc[leveloffset=+1]

include::manage-roles.adoc[leveloffset=+1]

include::manage-privileges.adoc[leveloffset=+1]

include::built-in-roles.adoc[leveloffset=+1]

include::privileges-read.adoc[leveloffset=+1]

include::privileges-write.adoc[leveloffset=+1]

include::database-administration.adoc[leveloffset=+1]

include::dbms-administration.adoc[leveloffset=+1]

include::limitations.adoc[leveloffset=+1]
