:description: This section explains how to use Cypher to manage roles in Neo4j.

[role=enterprise-edition]
[[access-control-manage-roles]]
= Managing roles

[abstract]
--
This section explains how to use Cypher to manage roles in Neo4j.
--

Roles can be created and managed using a set of Cypher administration commands executed against the `system` database.

When connected to the DBMS over bolt, administration commands are automatically routed to the `system` database.


[[access-control-role-syntax]]
== Role management command syntax

[cols="<15s,<85"]
|===

| Command
m| SHOW ROLES

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
SHOW [ALL\|POPULATED] ROLES
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a|
List roles.

When using the `RETURN` clause, the `YIELD` clause is mandatory and may not be omitted.

For more information, see xref::access-control/manage-roles.adoc#access-control-list-roles[Listing roles].

| Required privilege
a|
[source, privilege, role="noheader", indent=0]
----
GRANT SHOW ROLE
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-role-management[DBMS ROLE MANAGEMENT privileges])

|===


[cols="<15s,<85"]
|===

| Command
m| SHOW ROLES WITH USERS

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
SHOW [ALL\|POPULATED] ROLES WITH USERS
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a|
List roles and users assigned to them.

When using the `RETURN` clause, the `YIELD` clause is mandatory and may not be omitted.

For more information, see xref::access-control/manage-roles.adoc#access-control-list-roles[Listing roles].

| Required privilege
a|
[source, privilege, role="noheader", indent=0]
----
GRANT SHOW ROLE
----

[source, privilege, role="noheader", indent=0]
----
GRANT SHOW USER
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-role-management[DBMS ROLE MANAGEMENT privileges])

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges])

|===


[cols="<15s,<85"]
|===

| Command
m| SHOW ROLE PRIVILEGES

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
SHOW ROLE[S] name[, ...] PRIVILEGE[S] [AS [REVOKE] COMMAND[S]]
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a|
List the privileges granted to the specified roles.

When using the `RETURN` clause, the `YIELD` clause is mandatory and may not be omitted.

For more information, see xref::access-control/manage-privileges.adoc#access-control-list-privileges[Listing privileges].

| Required privilege
a|
[source, privilege, role="noheader", indent=0]
----
GRANT SHOW PRIVILEGE
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-privilege-management[DBMS PRIVILEGE MANAGEMENT privileges])

|===


[cols="<15s,<85"]
|===

| Command
m| CREATE ROLE

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
CREATE ROLE name [IF NOT EXISTS] [AS COPY OF otherName]
----

| Description
a|
Create a new role.

For more information, see xref::access-control/manage-roles.adoc#access-control-create-roles[Creating roles].

| Required privilege
a|
[source, privilege, role="noheader", indent=0]
----
GRANT CREATE ROLE
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-role-management[DBMS ROLE MANAGEMENT privileges])

|===

[cols="<15s,<85"]
|===
| Command
m| CREATE OR REPLACE ROLE

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
CREATE OR REPLACE ROLE name [AS COPY OF otherName]
----

| Description
a|
Create a new role, or if a role with the same name exists, replace it.

For more information, see xref::access-control/manage-roles.adoc#access-control-create-roles[Creating roles].

| Required privilege
a|
[source, privilege, role="noheader", indent=0]
----
GRANT CREATE ROLE
----

[source, privilege, role="noheader", indent=0]
----
GRANT DROP ROLE
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-role-management[DBMS ROLE MANAGEMENT privileges])

|===


[cols="<15s,<85"]
|===

| Command
m| RENAME ROLE

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
RENAME ROLE name [IF EXISTS] TO otherName
----

| Description
a|
Change the name of a role.

For more information, see xref::access-control/manage-roles.adoc#access-control-rename-roles[Renaming roles].

| Required privilege
a|
[source, privilege, role="noheader", indent=0]
----
GRANT RENAME ROLE
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-role-management[DBMS ROLE MANAGEMENT privileges])

|===


[cols="<15s,<85"]
|===

| Command
m| DROP ROLE

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
DROP ROLE name [IF EXISTS]
----

| Description
a| Remove a role.

For more information, see xref::access-control/manage-roles.adoc#access-control-drop-roles[Deleting roles].

| Required privilege
a|
[source, privilege, role="noheader", indent=0]
----
GRANT DROP ROLE
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-role-management[DBMS ROLE MANAGEMENT privileges])

|===


[cols="<15s,<85"]
|===
| Command
m| GRANT ROLE TO

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
GRANT ROLE[S] name[, ...] TO user[, ...]
----

| Description
a|
Assign roles to users.

For more information, see xref::access-control/manage-roles.adoc#access-control-assign-roles[Assigning roles to users].

| Required privilege
a|
[source, privilege, role="noheader", indent=0]
----
GRANT ASSIGN ROLE
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-role-management[DBMS ROLE MANAGEMENT privileges])

|===


[cols="<15s,<85"]
|===

| Command
m| REVOKE ROLE

| Syntax
a|
[source, syntax, role="noheader", indent=0]
----
REVOKE ROLE[S] name[, ...] FROM user[, ...]
----

| Description
a|
Remove roles from users.

For more information, see xref::access-control/manage-roles.adoc#access-control-revoke-roles[Revoking roles from users].

| Required privilege
a|
[source, privilege, role="noheader", indent=0]
----
GRANT REMOVE ROLE
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-role-management[DBMS ROLE MANAGEMENT privileges])

|===


[[access-control-list-roles]]
== Listing roles

Available roles can be seen using `SHOW ROLES`:

[source, cypher, role=noplay, indent=0]
----
SHOW ROLES
----

This is the same command as `SHOW ALL ROLES`.

When first starting a Neo4j DBMS there are a number of built-in roles:

* `PUBLIC` - a role that all users have granted, by default it gives access to the home database and execute privileges for procedures and functions.
* `reader` - can perform traverse and read operations on all databases except `system`.
* `editor` - can perform traverse, read, and write operations on all databases except `system`, but cannot make new labels or relationship types.
* `publisher` - can do the same as `editor`, but also create new labels and relationship types.
* `architect` - can do the same as `publisher` as well as create and manage indexes and constraints.
* `admin` - can do the same as all the above, as well as manage databases, aliases, users, roles, and privileges.

.Result
[options="header,footer", width="100%", cols="m"]
|===
|role

|"PUBLIC"
|"admin"
|"architect"
|"editor"
|"publisher"
|"reader"

1+a|Rows: 6
|===

More information about the built-in roles can be found in xref:4.4@operations-manual:ROOT:authentication-authorization/built-in-roles/index.adoc[Operations Manual -> Built-in roles]

There are multiple versions of this command, the default being `SHOW ALL ROLES`.
To only show roles that are assigned to users, the command is `SHOW POPULATED ROLES`.
To see which users are assigned to roles `WITH USERS` can be appended to the commands.
This will give one result row for each user, so if a role is assigned to two users then it will show up twice in the result.

[source, cypher, role=noplay, indent=0]
----
SHOW POPULATED ROLES WITH USERS
----

The table of results will show information about the role and what database it belongs to:

.Result
[options="header,footer", width="100%", cols="m,m"]
|===
|role
|member

|"PUBLIC"
|"neo4j"

|"PUBLIC"
|"bob"

|"PUBLIC"
|"user1"

|"PUBLIC"
|"user2"

|"PUBLIC"
|"user3"

|"admin"
|"neo4j"

2+a|Rows: 6
|===

It is also possible to filter and sort the results by using `YIELD`, `ORDER BY`, and `WHERE`:

[source, cypher, role=noplay, indent=0]
----
SHOW ROLES YIELD role
ORDER BY role
WHERE role ENDS WITH 'r'
----

In this example:

* The results have been filtered to only return the roles ending in 'r'.
* The results are ordered by the 'action' column using `ORDER BY`.

It is also possible to use `SKIP` and `LIMIT` to paginate the results.

.Result
[options="header,footer", width="100%", cols="m"]
|===
|role

|"editor"
|"publisher"
|"reader"

1+a|Rows: 3
|===

[NOTE]
====
The `SHOW ROLE name PRIVILEGES` command is found in xref::access-control/manage-privileges.adoc#access-control-list-privileges[Listing privileges].
====


[[access-control-create-roles]]
== Creating roles

Roles can be created using `CREATE ROLE`.

[source, cypher, role=noplay, indent=0]
----
CREATE ROLE name [IF NOT EXISTS] [AS COPY OF otherName]
----

Roles can be created or replaced by using `CREATE OR REPLACE ROLE`.

[source, cypher, role=noplay, indent=0]
----
CREATE OR REPLACE ROLE name [AS COPY OF otherName]
----

[NOTE]
====
The following naming rules apply:

* The first character must be an ASCII alphabetic character.
* Subsequent characters can be ASCII alphabetic, numeric characters, and underscore.
* Role names are case sensitive.
====

A role can be copied, keeping its privileges, using `CREATE ROLE name AS COPY OF otherName`.

.Copy a role
======
[source, cypher, role=noplay, indent=0]
----
CREATE ROLE mysecondrole AS COPY OF myrole
----
======

Created roles will appear on the list provided by `SHOW ROLES`.

.List roles
======
[source, cypher, role=noplay, indent=0]
----
SHOW ROLES
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|role

|"PUBLIC"
|"admin"
|"architect"
|"editor"
|"myrole"
|"mysecondrole"
|"publisher"
|"reader"

1+a|Rows: 8
|===
======

The `CREATE ROLE` command is optionally idempotent, with the default behavior to throw an exception if the role already exists.
Appending `IF NOT EXISTS` to the `CREATE ROLE` command will ensure that no exception is thrown and nothing happens should the role already exist.


.Create role if not exists
======

[source, cypher, role=noplay, indent=0]
----
CREATE ROLE myrole IF NOT EXISTS
----

======


The `CREATE OR REPLACE ROLE` command will result in any existing role being deleted and a new one created.


.Create or replace role
======

[source, cypher, role=noplay, indent=0]
----
CREATE OR REPLACE ROLE myrole
----

This is equivalent to running `DROP ROLE myrole IF EXISTS` followed by `CREATE ROLE myrole`.

======


[NOTE]
====
* The `CREATE OR REPLACE ROLE` command does not allow you to use the `IF NOT EXISTS`.
====


[[access-control-rename-roles]]
== Renaming roles

Roles can be renamed using `RENAME ROLE` command:

[source, cypher, role=noplay, indent=0]
----
RENAME ROLE mysecondrole TO mythirdrole
----

[source, cypher, role=noplay, indent=0]
----
SHOW ROLES
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|role

|"PUBLIC"
|"admin"
|"architect"
|"editor"
|"myrole"
|"mythirdrole"
|"publisher"
|"reader"

1+a|Rows: 8
|===

[NOTE]
====
The `RENAME ROLE` command is only available when using native authentication and authorization.
====


[[access-control-assign-roles]]
== Assigning roles to users

Users can be given access rights by assigning them roles using `GRANT ROLE`:

[source, cypher, role=noplay, indent=0]
----
GRANT ROLE myrole TO bob
----

The roles assigned to each user can be seen in the list provided by `SHOW USERS`:

[source, cypher, role=noplay, indent=0]
----
SHOW ROLES
----

.Result
[options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user
|roles
|passwordChangeRequired
|suspended
|home

|"bob"
|["myrole","PUBLIC"]
|false
|false
|<null>

|"neo4j"
|["admin","PUBLIC"]
|true
|false
|<null>

|"user1"
|["PUBLIC"]
|true
|false
|<null>

|"user2"
|["PUBLIC"]
|true
|false
|<null>

|"user3"
|["PUBLIC"]
|true
|false
|<null>

5+a|Rows: 5
|===

It is possible to assign multiple roles to multiple users in one command:

[source, cypher, role=noplay, indent=0]
----
GRANT ROLES role1, role2 TO user1, user2, user3
----

[source, cypher, role=noplay, indent=0]
----
SHOW ROLES
----

.Result
[options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user
|roles
|passwordChangeRequired
|suspended
|home

|"bob"
|["myrole","PUBLIC"]
|false
|false
|<null>

|"neo4j"
|["admin","PUBLIC"]
|true
|false
|<null>

|"user1"
|["role1","role2","PUBLIC"]
|true
|false
|<null>

|"user2"
|["role1","role2","PUBLIC"]
|true
|false
|<null>

|"user3"
|["role1","role2","PUBLIC"]
|true
|false
|<null>

5+a|Rows: 5
|===


[[access-control-revoke-roles]]
== Revoking roles from users

Users can lose access rights by revoking their role using `REVOKE ROLE`:

[source, cypher, role=noplay, indent=0]
----
REVOKE ROLE myrole FROM bob
----

The roles revoked from users can no longer be seen in the list provided by `SHOW USERS`:

[source, cypher, role=noplay, indent=0]
----
SHOW ROLES
----

.Result
[options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user
|roles
|passwordChangeRequired
|suspended
|home

|"bob"
|["PUBLIC"]
|false
|false
|<null>

|"neo4j"
|["admin","PUBLIC"]
|true
|false
|<null>

|"user1"
|["role1","role2","PUBLIC"]
|true
|false
|<null>

|"user2"
|["role1","role2","PUBLIC"]
|true
|false
|<null>

|"user3"
|["role1","role2","PUBLIC"]
|true
|false
|<null>

5+a|Rows: 5
|===

It is possible to revoke multiple roles from multiple users in one command:

[source, cypher, role=noplay, indent=0]
----
REVOKE ROLES role1, role2 FROM user1, user2, user3
----


[[access-control-drop-roles]]
== Deleting roles

Roles can be deleted using `DROP ROLE` command:

[source, cypher, role=noplay, indent=0]
----
DROP ROLE mythirdrole
----

When a role has been deleted, it will no longer appear on the list provided by `SHOW ROLES`:

[source, cypher, role=noplay, indent=0]
----
SHOW ROLES
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|role

|"PUBLIC"
|"admin"
|"architect"
|"editor"
|"myrole"
|"publisher"
|"reader"

1+a|Rows: 8
|===

This command is optionally idempotent, with the default behavior to throw an exception if the role does not exists.
Appending `IF EXISTS` to the command will ensure that no exception is thrown and nothing happens should the role not exist:

[source, cypher, role=noplay, indent=0]
----
DROP ROLE mythirdrole IF EXISTS
----

