:description: This section explains how to use Cypher to manage users in Neo4j.

[[access-control-manage-users]]
= Managing users

[abstract]
--
This section explains how to use Cypher to manage users in Neo4j.
--

Users can be created and managed using a set of Cypher administration commands executed against the `system` database.
When connected to the DBMS over `bolt`, administration commands are automatically routed to the `system` database.


[[access-control-user-syntax]]
== User management command syntax

[NOTE]
====
The syntax descriptions use xref:access-control/index.adoc#access-control-syntax[the style] from access control.
====

[cols="<15s,<85"]
|===

| Command
m| SHOW CURRENT USER

| Syntax
a|
[source, syntax, role="noheader"]
----
SHOW CURRENT USER
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a|
Lists the current user.

When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.

For more information, see xref::access-control/manage-users.adoc#access-control-current-users[Listing current user].

| Required privilege
a| None

|===


[cols="<15s,<85"]
|===

| Command
m| SHOW USERS

| Syntax
a|
[source, syntax, role="noheader"]
----
SHOW USER[S]
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a|
Lists all users.

When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.

For more information, see xref::access-control/manage-users.adoc#access-control-list-users[Listing users].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT SHOW USER
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges])

|===


[cols="<15s,<85"]
|===
| Command
m| SHOW USER PRIVILEGES

| Syntax
a|
[source, syntax, role="noheader"]
----
SHOW USER[S] [name[, ...]] PRIVILEGE[S] [AS [REVOKE] COMMAND[S]]
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a|
Lists the privileges granted to the specified users or the current user if no user is specified.

When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.

For more information, see xref::access-control/manage-privileges.adoc#access-control-list-privileges[Listing privileges].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT SHOW PRIVILEGE
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-privilege-management[DBMS PRIVILEGE MANAGEMENT privileges])

[source, privilege, role="noheader"]
----
GRANT SHOW USER
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges])
|===


[cols="<15s,<85"]
|===
| Command
m| CREATE USER

| Syntax
a|
[source, syntax, role="noheader"]
----
CREATE USER name [IF NOT EXISTS]
  SET [PLAINTEXT \| ENCRYPTED] PASSWORD 'password'
  [[SET PASSWORD] CHANGE [NOT] REQUIRED]
  [SET STATUS {ACTIVE \| SUSPENDED}]
  [SET HOME DATABASE name]
----

| Description
a|
Creates a new user.

For more information, see xref::access-control/manage-users.adoc#access-control-create-users[Creating users].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT CREATE USER
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges])

|===

[cols="<15s,<85"]
|===
| Command
m| CREATE OR REPLACE USER

| Syntax
a|
[source, syntax, role="noheader"]
----
CREATE OR REPLACE USER name
  SET [PLAINTEXT \| ENCRYPTED] PASSWORD 'password'
  [[SET PASSWORD] CHANGE [NOT] REQUIRED]
  [SET STATUS {ACTIVE \| SUSPENDED}]
  [SET HOME DATABASE name]
----

| Description
a|
Creates a new user, or if a user with the same name exists, replace it.

For more information, see xref::access-control/manage-users.adoc#access-control-create-users[Creating users].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT CREATE USER
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges])


[source, privilege, role="noheader"]
----
GRANT DROP USER
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges])

|===

[cols="<15s,<85"]
|===
| Command
m| RENAME USER

| Syntax
a|
[source, syntax, role="noheader"]
----
RENAME USER name [IF EXISTS] TO otherName
----

| Description
a|
Changes the name of a user.

For more information, see xref::access-control/manage-users.adoc#access-control-rename-users[Renaming users].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT RENAME USER
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges])

|===

[cols="<15s,<85"]
|===
| Command
m| ALTER USER

| Syntax
a|
[source, syntax, role="noheader"]
----
ALTER USER name [IF EXISTS]
  [SET [PLAINTEXT \| ENCRYPTED] PASSWORD 'password']
  [[SET PASSWORD] CHANGE [NOT] REQUIRED]
  [SET STATUS {ACTIVE \| SUSPENDED} ]
  [SET HOME DATABASE name]
  [REMOVE HOME DATABASE]
----

| Description
a|
Modifies the settings for an existing user.
At least one `SET` or `REMOVE` clause is required.
`SET` and `REMOVE` clauses cannot be combined in the same command.

For more information, see xref::access-control/manage-users.adoc#access-control-alter-users[Modifying users].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT SET PASSWORD
----

[source, privilege, role="noheader"
----
GRANT SET USER STATUS
----

[source, privilege, role="noheader"]
----
GRANT SET USER HOME DATABASE
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges])

|===


[cols="<15s,<85"]
|===

| Command
m| ALTER CURRENT USER SET PASSWORD

| Syntax
a|
[source, syntax, role="noheader"]
----
ALTER CURRENT USER SET PASSWORD FROM 'oldPassword' TO 'newPassword'
----

| Description
a|
Changes the current user's password.

For more information, see xref::access-control/manage-users.adoc#access-control-alter-password[Changing the current user's password].

| Required privilege
a| None

|===


[cols="<15s,<85"]
|===

| Command
m| DROP USER

| Syntax
a|
[source, syntax, role="noheader"]
----
DROP USER name [IF EXISTS]
----

| Description
a|
Removes an existing user.

For more information, see xref::access-control/manage-users.adoc#access-control-drop-users[Delete users].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT DROP USER
----

(see xref::access-control/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges])

|===


[NOTE]
====
The `SHOW USER[S] PRIVILEGES` command is only available in Neo4j Enterprise Edition. label:enterprise-edition[]
====


[[access-control-current-users]]
== Listing current user

The currently logged-in user can be seen using `SHOW CURRENT USER`, which will produce a table with the following columns:

[options="header", width="100%", cols="2a,4,^.^,^.^"]
|===
| Column
| Description
| Community Edition
| Enterprise Edition

| user
| User name
| {check-mark}
| {check-mark}

| roles
| Roles granted to the user.
| {cross-mark}
| {check-mark}

| passwordChangeRequired
| If `true`, the user must change their password at the next login.
| {check-mark}
| {check-mark}

| suspended
| If `true`, the user is currently suspended (cannot log in).
| {cross-mark}
| {check-mark}

| home
| The home database configured by the user, or `null` if no home database has been configured.
If this database is unavailable and the user does not specify a database to use, they will not be able to log in.
| {cross-mark}
| {check-mark}
|===

[source, cypher, role=noplay]
----
SHOW CURRENT USER
----

.Result
[options="header,footer", width="100%", cols="2m,2m,3m,2m,2m"]
|===
|user
|roles
|passwordChangeRequired
|suspended
|home

|"jake"
|["PUBLIC"]
|false
|false
|<null>

5+a|Rows: 1
|===

[NOTE]
====
This command is only supported for a logged-in user and will return an empty result if authorization has been disabled.
====


[[access-control-list-users]]
== Listing users

Available users can be seen using `SHOW USERS`, which will produce a table of users with the following columns:

[options="header", width="100%", cols="2a,4,^.^,^.^"]
|===
| Column
| Description
| Community Edition
| Enterprise Edition

| user
| User name
| {check-mark}
| {check-mark}

| roles
| Roles granted to the user.
| {cross-mark}
| {check-mark}

| passwordChangeRequired
| If `true`, the user must change their password at the next login.
| {check-mark}
| {check-mark}

| suspended
| If `true`, the user is currently suspended (cannot log in).
| {cross-mark}
| {check-mark}

| home
| The home database configured by the user, or `null` if no home database has been configured.
A home database will be resolved if it is either pointing to a database or a database alias.
If this database is unavailable and the user does not specify a database to use, they will not be able to log in.
| {cross-mark}
| {check-mark}
|===

[source, cypher, role=noplay]
----
SHOW USERS
----

.Result
[role="queryresult" options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user
|roles
|passwordChangeRequired
|suspended
|home

|"neo4j"
|["admin","PUBLIC"]
|false
|false
|<null>

5+a|Rows: 1
|===

When first starting a Neo4j DBMS, there is always a single default user `neo4j` with administrative privileges.
It is possible to set the initial password using link:{neo4j-docs-base-uri}/operations-manual/{page-version}/configuration/set-initial-password[neo4j-admin set-initial-password], otherwise it is necessary to change the password after the first login.

.Show user
======
This example shows how to:

* Reorder the columns using a `YIELD` clause.
* Filter the results using a `WHERE` clause.

[source, cypher, role=noplay]
----
SHOW USER YIELD user, suspended, passwordChangeRequired, roles, home
WHERE user = 'jake'
----
======

.Show user
======
It is possible to add a `RETURN` clause to further manipulate the results after filtering.
In this example, the `RETURN` clause is used to filter out the `roles` column and rename the `user` column to `adminUser`.

[source,cypher,role=noplay]
----
SHOW USERS YIELD roles, user
WHERE 'admin' IN roles
RETURN user AS adminUser
----
======

[NOTE]
====
The `SHOW USER name PRIVILEGES` command is described in xref::access-control/manage-privileges.adoc#access-control-list-privileges[Listing privileges].
====


[[access-control-create-users]]
== Creating users

Users can be created using `CREATE USER`.

[source, syntax, role="noheader"]
----
CREATE USER name [IF NOT EXISTS]
  SET [PLAINTEXT | ENCRYPTED] PASSWORD 'password'
  [[SET PASSWORD] CHANGE [NOT] REQUIRED]
  [SET STATUS {ACTIVE | SUSPENDED}]
  [SET HOME DATABASE name]
----

Users can be created or replaced using `CREATE OR REPLACE USER`.

[source, syntax, role="noheader"]
----
CREATE OR REPLACE USER name
  SET [PLAINTEXT | ENCRYPTED] PASSWORD 'password'
  [[SET PASSWORD] CHANGE [NOT] REQUIRED]
  [SET STATUS {ACTIVE | SUSPENDED}]
  [SET HOME DATABASE name]
----

* For `SET PASSWORD`:
** The `password` can either be a string value or a string parameter.
** The default Neo4j password length is at least 8 characters.
** All passwords are encrypted (hashed) when stored in the Neo4j `system` database.
`PLAINTEXT` and `ENCRYPTED` just refer to the format of the password in the Cypher command, i.e. whether Neo4j needs to hash it or it has already been hashed.
Consequently, it is never possible to get the plaintext of a password back out of the database.
A password can be set in either fashion at any time.
** The optional `PLAINTEXT` in `SET PLAINTEXT PASSWORD` has the same behavior as `SET PASSWORD`.
** The optional `ENCRYPTED` is used to recreate an existing user when the plaintext password is unknown, but the encrypted password is available in the _data/scripts/databasename/restore_metadata.cypher_ file of a database backup.
See link:{neo4j-docs-base-uri}/operations-manual/{page-version}/backup-restore/restore-backup#restore-backup-example[Operations Manual -> Restore a database backup -> Example]. +
With `ENCRYPTED`, the password string is expected to be in the format of `<encryption-version>,<hash>,<salt>`, where, for example:
*** `0` is the first version and refers to the `SHA-256` cryptographic hash function with iterations `1`.
*** `1` is the second version and refers to the `SHA-256` cryptographic hash function with iterations `1024`.
* If the optional `SET PASSWORD CHANGE [NOT] REQUIRED` is omitted, the default is `CHANGE REQUIRED`.
The `SET PASSWORD` part is only optional if it directly follows the `SET PASSWORD` clause.
* The default for `SET STATUS` is `ACTIVE`.
* `SET HOME DATABASE` can be used to configure a home database for a user.
A home database will be resolved if it is either pointing to a database or a database alias.
If no home database is set, the DBMS default database is used as the home database for the user.
* The `SET PASSWORD CHANGE [NOT] REQUIRED`, `SET STATUS`, and `SET HOME DATABASE` clauses can be applied in any order.

[NOTE]
====
User names are case sensitive.
The created user will appear on the list provided by `SHOW USERS`.

* In Neo4j Community Edition there are no roles, but all users have implied administrator privileges.
* In Neo4j Enterprise Edition all users are automatically assigned the xref::access-control/built-in-roles.adoc#access-control-built-in-roles-public[`PUBLIC` role], giving them a base set of privileges.
====


.Create user
======
For example, you can create the user `jake` in a suspended state, with the home database `anotherDb`, and the requirement to change the password by using the command:

[source,cypher,role=noplay]
----
CREATE USER jake
SET PASSWORD 'abcd1234' CHANGE REQUIRED
SET STATUS SUSPENDED
SET HOME DATABASE anotherDb
----

======


.Create user
======
Or you can recreate the user `jake` in an active state, with an encrypted password (taken from the _data/scripts/databasename/restore_metadata.cypher_ of a database backup), and the requirement to not change the password by running:

[source,cypher,role=noplay]
----
CREATE USER jake2
SET ENCRYPTED PASSWORD '1,6d57a5e0b3317055454e455f96c98c750c77fb371f3f0634a1b8ff2a55c5b825,190ae47c661e0668a0c8be8a21ff78a4a34cdf918cae3c407e907b73932bd16c' CHANGE NOT REQUIRED
SET STATUS ACTIVE
----

======

[NOTE]
====
The `SET STATUS {ACTIVE | SUSPENDED}` and `SET HOME DATABASE` parts of the commands are only available in Neo4j Enterprise Edition. label:enterprise-edition[]
====

The `CREATE USER` command is optionally idempotent, with the default behavior to throw an exception if the user already exists.
Appending `IF NOT EXISTS` to the `CREATE USER` command will ensure that no exception is thrown and nothing happens should the user already exist.


.Create user if not exists
======
[source,cypher,role=noplay]
----
CREATE USER jake IF NOT EXISTS
SET PLAINTEXT PASSWORD 'abcd1234'
----

======

The `CREATE OR REPLACE USER` command will result in any existing user being deleted and a new one created.


.Create or replace user
======
[source,cypher,role=noplay]
----
CREATE OR REPLACE USER jake
SET PLAINTEXT PASSWORD 'abcd1234'
----

This is equivalent to running `DROP USER jake IF EXISTS` followed by `CREATE USER jake SET PASSWORD 'abcd1234'`.

======

[NOTE]
====
The `CREATE OR REPLACE USER` command does not allow the use of `IF NOT EXISTS`.
====


[[access-control-rename-users]]
== Renaming users

Users can be renamed with the `RENAME USER` command.

[source, cypher, role=noplay]
----
RENAME USER jake TO bob
----

[source, cypher, role=noplay]
----
SHOW USERS
----

.Result
[options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user |roles |passwordChangeRequired |suspended |home

|"bob"
|["PUBLIC"]
|true
|false
|<null>

|"neo4j"
|["admin","PUBLIC"]
|true
|false
|<null>

5+a|Rows: 2

|===

[NOTE]
====
The `RENAME USER` command is only available when using native authentication and authorization.
====


[[access-control-alter-users]]
== Modifying users

Users can be modified with `ALTER USER`.

[source, syntax, role="noheader"]
----
ALTER USER name [IF EXISTS]
  [SET [PLAINTEXT | ENCRYPTED] PASSWORD 'password']
  [[SET PASSWORD] CHANGE [NOT] REQUIRED]
  [SET STATUS {ACTIVE | SUSPENDED}]
  [SET HOME DATABASE name]
  [REMOVE HOME DATABASE name]
----

* At least one `SET` or `REMOVE` clause is required for the command.
* `SET` and `REMOVE` clauses cannot be combined in the same command.
* The `SET PASSWORD CHANGE [NOT] REQUIRED`, `SET STATUS`, and `SET HOME DATABASE` clauses can be applied in any order.
The `SET PASSWORD` clause must come first, if used.
* For `SET PASSWORD`:
** The `password` can either be a string value or a string parameter.
** All passwords are encrypted (hashed) when stored in the Neo4j `system` database.
`PLAINTEXT` and `ENCRYPTED` just refer to the format of the password in the Cypher command, i.e. whether Neo4j needs to hash it or it has already been hashed.
Consequently, it is never possible to get the plaintext of a password back out of the database.
A password can be set in either fashion at any time.
** The optional `PLAINTEXT` in `SET PLAINTEXT PASSWORD` has the same behavior as `SET PASSWORD`.
** The optional `ENCRYPTED` is used to update an existing user's password when the plaintext password is unknown, but the encrypted password is available in the _data/scripts/databasename/restore_metadata.cypher_ file of a database backup.
See link:{neo4j-docs-base-uri}/operations-manual/{page-version}/backup-restore/restore-backup#restore-backup-example[Operations Manual -> Restore a database backup -> Example]. +
With `ENCRYPTED`, the password string is expected to be in the format of `<encryption-version>,<hash>,<salt>`, where, for example:
*** `0` is the first version and refers to the `SHA-256` cryptographic hash function with iterations `1`.
*** `1` is the second version and refers to the `SHA-256` cryptographic hash function with iterations `1024`.
* If the optional `SET PASSWORD CHANGE [NOT] REQUIRED` is omitted, the default is `CHANGE REQUIRED`.
The `SET PASSWORD` part is only optional if it directly follows the `SET PASSWORD` clause.
* For `SET PASSWORD CHANGE [NOT] REQUIRED`, the `SET PASSWORD` is only optional if it directly follows the `SET PASSWORD` clause.
* `SET HOME DATABASE` can be used to configure a home database for a user.
A home database will be resolved if it is either pointing to a database or a database alias.
If no home database is set, the DBMS default database is used as the home database for the user.
* `REMOVE HOME DATABASE` is used to unset the home database for a user.
This results in the DBMS default database being used as the home database for the user.

For example, you can modify the user `bob` with a new password and active status, and remove the requirement to change his password:

[source, cypher, role=noplay]
----
ALTER USER bob
SET PASSWORD 'abcd5678' CHANGE NOT REQUIRED
SET STATUS ACTIVE
----

Or you may decide to assign the user `bob` a different home database:

[source, cypher, role=noplay]
----
ALTER USER bob
SET HOME DATABASE anotherDbOrAlias
----

Or remove the home database from the user `bob`:

[source, cypher, role=noplay]
----
ALTER USER bob
REMOVE HOME DATABASE
----

[NOTE]
====
When altering a user, it is only necessary to specify the changes required.
For example, leaving out the `CHANGE [NOT] REQUIRED` part of the query will leave that unchanged.
====

[NOTE]
====
The `SET STATUS {ACTIVE | SUSPENDED}`, `SET HOME DATABASE`, and `REMOVE HOME DATABASE` parts of the command are only available in Neo4j Enterprise Edition. label:enterprise-edition[]
====

The changes to the user will appear on the list provided by `SHOW USERS`:

[source, cypher, role=noplay]
----
SHOW USERS
----

.Result
[options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user |roles |passwordChangeRequired |suspended |home

|"bob"
|["PUBLIC"]
|false
|false
|<null>

|"neo4j"
|["admin","PUBLIC"]
|true
|false
|<null>

5+a|Rows: 2

|===

The default behavior of this command is to throw an exception if the user does not exist.
Adding an optional parameter `IF EXISTS` to the command makes it idempotent and ensures that no exception is thrown.
Nothing happens should the user not exist.

[source, cypher, role=noplay]
----
ALTER USER nonExistingUser IF EXISTS SET PASSWORD 'abcd1234'
----


[[access-control-alter-password]]
== Changing the current user's password

Users can change their password using `ALTER CURRENT USER SET PASSWORD`.
The old password is required in addition to the new one, and either or both can be a string value or a string parameter.
When a user executes this command it will change their password as well as set the `CHANGE NOT REQUIRED` flag.

[source, cypher, role=test-skip]
----
ALTER CURRENT USER
SET PASSWORD FROM 'password1' TO 'password2'
----

[NOTE]
====
This command works only for a logged-in user and cannot be run with auth disabled.
====


[[access-control-drop-users]]
== Delete users

Users can be deleted with `DROP USER`.

[source, cypher, role=noplay]
----
DROP USER bob
----

Deleting a user will not automatically terminate associated connections, sessions, transactions, or queries.

However, when a user has been deleted, it will no longer appear on the list provided by `SHOW USERS`:

[source, cypher, role=noplay]
----
SHOW USERS
----

.Result
[options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user |roles |passwordChangeRequired |suspended |home

|"neo4j"
|["admin","PUBLIC"]
|true
|false
|<null>

5+a|Rows: 1

|===
