[role=enterprise-edition]
[[access-control-privileges-immutable]]
= Immutable privileges
:description: This section explains how to use Cypher to manage immutable privileges. 

Unlike regular privileges, having xref:access-control/dbms-administration.adoc#access-control-dbms-administration-privilege-management[privilege management] privileges is not sufficient to enable immutable privileges to be added or removed. They can only be administered when auth is disabled -- that is, when the configuration setting <<config_dbms.security.auth_enabled,`dbms.security.auth_enabled`>> is set to `false`.

[[access-control-privileges-immutable-usecase]]
== When to use immutable privileges

Immutable privileges are useful for restricting the actions of users who themselves are able to xref:access-control/dbms-administration.adoc#access-control-dbms-administration-privilege-management[administer privileges].

For example, you may want to prevent all users from performing Database Management, even the `admin` user (who are themselves able to add or remove privileges).
To do so, you could run:

[source, cypher, role=noplay]
----
DENY DATABASE MANAGEMENT ON DBMS TO PUBLIC
----
However, this would not be adequate.
In case the `admin` user subsequently runs this:
[source, cypher, role=noplay]
----
REVOKE DENY DATABASE MANAGEMENT ON DBMS TO PUBLIC
----
They would effectively regain Database Management privileges.
Instead, run the following query to prevent this scenario:
[source, cypher, role=noplay]
----
DENY IMMUTABLE DATABASE MANAGEMENT ON DBMS TO PUBLIC
----


[[access-control-privileges-immutable-admin]]
== How to administer immutable privileges

Immutable privileges can only be administered when auth is disabled -- that is, when the configuration setting <<config_dbms.security.auth_enabled,`dbms.security.auth_enabled`>> is set to `false`, for example.
Under these conditions, immutable privileges can be added and removed in a similar manner to regular privileges, using the `IMMUTABLE` keyword.

See the link:{neo4j-docs-base-uri}/operations-manual/{page-version}/tutorial/tutorial-immutable-privileges[Immutable privileges tutorial] for examples of how to administer immutable privileges.

See xref:access-control/manage-privileges.adoc[Managing Privileges] for more detail on syntax.
