:description: Information about droppping Neo4j's constraints.
= Drop constraints

Constraints are dropped using the `DROP CONSTRAINT` command.
For the full command syntax to drop constraints, see xref:constraints/syntax.adoc#drop-constraint[Syntax -> Drop constraints].
The constraints dropped on this page are created on the page xref:constraints/create-constraints.adoc[].

[NOTE]
Dropping a constraint requires the link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-constraints[`DROP CONSTRAINT` privilege].

[[drop-constraint-by-name]]
== Drop a constraint by name

A constraint can be dropped using the name with the `DROP CONSTRAINT constraint_name` command.
It is the same command for all constraint types.
The name of the constraint can be found using the xref:constraints/list-constraints.adoc[`SHOW CONSTRAINTS` command], given in the output column `name`.

////
The below constraints are created on constraints/create-constraints.adoc

[source, cypher, role=test-setup]
----
CREATE CONSTRAINT book_isbn
FOR (book:Book) REQUIRE book.isbn IS UNIQUE;
CREATE CONSTRAINT sequels
FOR ()-[sequel:SEQUEL_OF]-() REQUIRE sequel.order IS UNIQUE;
CREATE CONSTRAINT book_title_year
FOR (book:Book) REQUIRE (book.title, book.publicationYear) IS UNIQUE;
CREATE CONSTRAINT prequels
FOR ()-[prequel:PREQUEL_OF]-() REQUIRE (prequel.order, prequel.author) IS UNIQUE;
CREATE CONSTRAINT author_name
FOR (author:Author) REQUIRE author.name IS NOT NULL;
CREATE CONSTRAINT wrote_year
FOR ()-[wrote:WROTE]-() REQUIRE wrote.year IS NOT NULL;
CREATE CONSTRAINT movie_title
FOR (movie:Movie) REQUIRE movie.title IS :: STRING;
CREATE CONSTRAINT part_of
FOR ()-[part:PART_OF]-() REQUIRE part.order IS :: INTEGER;
CREATE CONSTRAINT movie_tagline
FOR (movie:Movie) REQUIRE movie.tagline IS :: STRING | LIST<STRING NOT NULL>;
CREATE CONSTRAINT part_of_tags
FOR ()-[part:PART_OF]-() REQUIRE part.tags IS :: STRING | LIST<STRING NOT NULL>;
CREATE CONSTRAINT director_imdbId
FOR (director:Director) REQUIRE (director.imdbId) IS NODE KEY;
CREATE CONSTRAINT ownershipId
FOR ()-[owns:OWNS]-() REQUIRE owns.ownershipId IS RELATIONSHIP KEY;
CREATE CONSTRAINT actor_fullname
FOR (actor:Actor) REQUIRE (actor.firstname, actor.surname) IS NODE KEY;
CREATE CONSTRAINT knows_since_how
FOR ()-[knows:KNOWS]-() REQUIRE (knows.since, knows.how) IS RELATIONSHIP KEY;
CREATE CONSTRAINT node_uniqueness_param
FOR (book:Book) REQUIRE book.prop1 IS UNIQUE;
CREATE CONSTRAINT rel_exist_param
FOR ()-[wrote:WROTE]-() REQUIRE wrote.published IS NOT NULL
----
////

.Drop a constraint by name
======

.Drop the constraint `book_isbn`
// tag::schema_constraints_drop[]
[source, cypher]
----
DROP CONSTRAINT book_isbn
----
// end::schema_constraints_drop[]

.Result
[source, queryresult]
----
Removed 1 constraint.
----

======

[role=label--new-5.16]
[[drop-constraint-with-parameter]]
== Drop a constraint with a parameter

Constraints can be dropped with a parameterized name.

.Drop a constraint using a parameter
======

.Parameters
[source, parameters]
----
{
  "name": "actor_fullname"
}
----

.Drop a constraint with a parameterized name
// tag::schema_constraints_drop_parameter[]
[source, cypher]
----
DROP CONSTRAINT $name
----
// end::schema_constraints_drop_parameter[]

.Result
[source, queryresult]
----
Removed 1 constraint.
----

======

[[drop-constraint-nonexisting-constraint]]
== Drop a non-existing constraint

If it is uncertain if any constraint with a given name exists and you want to drop it if it does but not get an error should it not, use `IF EXISTS`.
This will ensure that no error is thrown.
Instead, an informational notification is returned stating that the constraint does not exist.

.Drop a non-existing constraint
======

.Drop the non-existing constraint `missing_constraint_name`
[source, cypher]
----
DROP CONSTRAINT missing_constraint_name IF EXISTS
----

.Result
[source, queryresult]
----
(no changes, no records)
----

.Notification
[source]
----
`DROP CONSTRAINT missing_constraint_name IF EXISTS` has no effect. `missing_constraint_name` does not exist.
----

======