:description: Overview of Neo4j's constraints used for ensuring data integrity.
include::https://raw.githubusercontent.com/neo4j-graphacademy/courses/main/asciidoc/courses/cypher-indexes-constraints/ad.adoc[]
= Constraints

Neo4j offers several constraints to ensure the quality and integrity of data in a graph.
The following constraints are available in Neo4j:

* *Uniqueness constraints*: ensures that property values are unique for all nodes with a specific label or all relationships with a specific type. 
* *Existence constraints*: ensures that a property exists either for all nodes with a specific label or for all relationships with a specific type. label:enterprise-edition[]
* *Key constraints*: ensures that, for a given node label or relationship type and set of properties, all properties are present on the respective nodes or relationships, and the combination of property values is unique. label:enterprise-edition[]
* *Type constraints*: ensures that a property have the required property type for all nodes with a specific label or for all relationships with a specific type. label:enterprise-edition[]

To learn more about creating, listing, and dropping these constraints, as well as information about index-backed constraints, common fail cases when creating constraints, and more, see xref:constraints/managing-constraints.adoc[].

For reference material about the Cypher commands used to manage constraints, see xref:constraints/syntax.adoc[].

