:description: Overview of Neo4j's constraints used for ensuring data integrity.
include::https://raw.githubusercontent.com/neo4j-graphacademy/courses/main/asciidoc/courses/cypher-indexes-constraints/ad.adoc[]
= Constraints

Neo4j offers several constraints to ensure the quality and integrity of data in a graph.
The following constraints are available in Neo4j:

* *Property uniqueness constraints* ensure that the combined property values are unique for all nodes with a specific label or all relationships with a specific type. 
* *Property existence constraints* ensure that a property exists either for all nodes with a specific label or for all relationships with a specific type.
label:enterprise-edition[]
* *Property type constraints* ensure that a property has the required property type for all nodes with a specific label or for all relationships with a specific type. label:enterprise-edition[]
* *Key constraints* ensure that property values are unique and exists for all nodes with a specific label or all relationships with a specific type. label:enterprise-edition[]

To learn more about creating, listing, and dropping these constraints, as well as information about index-backed constraints, sonstraint creation failures and data violation scenarios, and more, see xref:constraints/managing-constraints.adoc[].

For reference material about the Cypher commands used to manage constraints, see xref:constraints/syntax.adoc[].

