:description: Overview of Neo4j constraints used for ensuring data integrity.
include::https://raw.githubusercontent.com/neo4j-graphacademy/courses/main/asciidoc/courses/cypher-indexes-constraints/ad.adoc[]
= Constraints

Cypher offers several constraints to ensure the quality and integrity of data in a graph.
For information about how to create these constraints, see:

* xref:constraints/uniqueness.adoc[]: ensures that property values are unique for all nodes with a specific label or all relationships with a specific type. 
* xref:constraints/existence.adoc[]: ensures that a property exists either for all nodes with a specific label or for all relationships with a specific type. label:enterprise-edition[]
* xref:constraints/type.adoc[]: ensures that a property have the required property type for all nodes with a specific label or for all relationships with a specific type. label:enterprise-edition[]
* xref:constraints/key.adoc[]: ensures that, for a given node label or relationship type and set of properties, all properties are present on the respective nodes or relationships, and the combination of property values is unique. label:enterprise-edition[]

This section also contains the following pages:

* xref:constraints/list-drop-constraints.adoc[]
* xref:constraints/syntax.adoc[]

== General information

Adding constraints is an atomic operation that can take a while -- all existing data has to be scanned before a Neo4j DBMS can use a constraint.

[[multiple-constrains]]
=== Multiple constraints on the same property combinations

Some constraint types are allowed on the same label/relationship type and property combination.
For example, it is possible to have a uniqueness and an existence constraint on the same label/relationship type and property combination, though this would be the equivalent of having a node or relationship key constraint.
A more useful example would be to combine a property type and an existence constraint to ensure that the property exists and has the given type.

[[index-implications]]
=== Implications on indexes

Creating a property key and property uniqueness constraints has the following implications on indexes:

* Adding a property key or property uniqueness constraint on a single property also adds an index on that property, and therefore, an index of the same index type, label/relationship type, and property combination cannot be added separately.
* Adding a property key or property uniqueness constraint for a set of properties also adds an index on those properties, and therefore, an index of the same index type, label/relationship type, and properties combination cannot be added separately.
* Cypher will use these indexes for lookups just like other indexes.
Refer to xref:indexes/search-performance-indexes/managing-indexes.adoc[] for more details on indexes.
* If a property key or property uniqueness constraint is dropped and the backing index is still required, the index need to be created explicitly.
