:description: Information about using indexes in Neo4j.
= Indexes

An index is a copy of specified primary data in a Neo4j database, such as nodes, relationships, or properties.
The data stored in the index provides an access path to the data in the primary storage and allows users to evaluate query filters more efficiently (and, in some cases, semantically interpret query filters).
In short, much like indexes in a book, their function in a Neo4j graph database is to make data retrieval more efficient. 

Once an index has been created, it will be automatically populated and updated by the DBMS. 

Neo4j supports two categories of indexes: 

- xref:indexes/search-performance-indexes/overview.adoc[Search-performance indexes], for speeding up data retrieval based on _exact_ matches.
This category includes range, text, point, and token lookup indexes.
- xref:indexes/semantic-indexes/overview.adoc[Semantic indexes], for _approximate_ matches and to compute similarity scores between a query string and the matching data.
This category includes full-text and vector indexes.
