= Search-performance indexes

Search-performance indexes enable quicker retrieval of exact matches between an index and the primary data storage.
There are four different search-performance indexes available in Neo4j:

* Range indexes: Neo4j’s default index.
Supports most types of predicates, including node label and relationship types.

* Text indexes: solves predicates operating on `STRING` values, and optimized for certain types of `STRING` predicates.

* Point indexes - solves predicates on spatial `POINT` values.
Optimized for retrieving data based on its geographic coordinates.

* Token lookup indexes: only solves node label and relationship type predicates.
Two token lookup indexes (one for node labels and one for relationship types) are present when a database is created in Neo4j.

To learn more about creating, listing, and deleting these indexes, as well as more details about the predicates supported by each index type, see xref:indexes/indexes-for-search-performance.adoc[Managing search-performance Indexes].

In general, range indexes should be used for all node label and relationship type predicates that do not evaluate `STRING` or `POINT` value properties.
To learn about when and why to create search-performance indexes, and how Cypher queries access different types of indexes, see xref:indexes/using-indexes.adoc[Using search-performance indexes].

Search-performance indexes are used automatically, and if several indexes are available, the xref:planning-and-tuning/execution-plans.adoc[Cypher planner] will try to use the index that can most efficiently solve a particular predicate.
It is, however, possible to explicitly force a query to use a particular index with the `USING` keyword. For more information, see xref:indexes/index-hints.adoc[Index hints].
