
[[indexes-syntax]]
= Syntax

This page contains the syntax for creating, modifying, and dropping the various indexes available in Neo4j.
It also includes information about naming rules. 

== Indexes for search performance

.+Create a range index on nodes+
[options="noheader", width="100%", cols="2, 8a"]
|===

| Syntax
|
[source, syntax, role="noheader"]
----
CREATE [RANGE] INDEX [index_name] [IF NOT EXISTS]
FOR (n:LabelName)
ON (n.propertyName_1[,
    n.propertyName_2,
    ...
    n.propertyName_n])
[OPTIONS "{" option: value[, ...] "}"]
----

| Description
|
Create a range index on nodes, either on a single property or composite.

Index provider can be specified using the `OPTIONS` clause.
There is only one available index provider for this index.

|===


.+Create a range index on relationships+
[options="noheader", width="100%", cols="2, 8a"]
|===

| Syntax
|
[source, syntax, role="noheader"]
----
CREATE [RANGE] INDEX [index_name] [IF NOT EXISTS]
FOR ()-"["r:TYPE_NAME"]"-()
ON (r.propertyName_1[,
    r.propertyName_2,
    ...
    r.propertyName_n])
[OPTIONS "{" option: value[, ...] "}"]
----

| Description
|
Create a range index on relationships, either on a single property or composite.

Index provider can be specified using the `OPTIONS` clause.
There is only one available index provider for this index.

|===


.+Create a text index on nodes+
[options="noheader", width="100%", cols="2, 8a"]
|===

| Syntax
|
[source, syntax, role="noheader"]
----
CREATE TEXT INDEX [index_name] [IF NOT EXISTS]
FOR (n:LabelName)
ON (n.propertyName)
[OPTIONS "{" option: value[, ...] "}"]
----

| Description
|
Create a text index on nodes where the property has a string value.

Index provider can be specified using the `OPTIONS` clause.

|===


.+Create a text index on relationships+
[options="noheader", width="100%", cols="2, 8a"]
|===

| Syntax
|
[source, syntax, role="noheader"]
----
CREATE TEXT INDEX [index_name] [IF NOT EXISTS]
FOR ()-"["r:TYPE_NAME"]"-()
ON (r.propertyName)
[OPTIONS "{" option: value[, ...] "}"]
----

| Description
|
Create a text index on relationships where the property has a string value.

Index provider can be specified using the `OPTIONS` clause.

|===


.+Create a point index on nodes+
[options="noheader", width="100%", cols="2, 8a"]
|===

| Syntax
|
[source, syntax, role="noheader"]
----
CREATE POINT INDEX [index_name] [IF NOT EXISTS]
FOR (n:LabelName)
ON (n.propertyName)
[OPTIONS "{" option: value[, ...] "}"]
----

| Description
|
Create a point index on nodes where the property has a point value.

Index provider and configuration can be specified using the `OPTIONS` clause.
There is only one available index provider for this index.

|===


.+Create a point index on relationships+
[options="noheader", width="100%", cols="2, 8a"]
|===

| Syntax
|
[source, syntax, role="noheader"]
----
CREATE POINT INDEX [index_name] [IF NOT EXISTS]
FOR ()-"["r:TYPE_NAME"]"-()
ON (r.propertyName)
[OPTIONS "{" option: value[, ...] "}"]
----

| Description
|
Create a point index on relationships where the property has a point value.

Index provider and configuration can be specified using the `OPTIONS` clause.
There is only one available index provider for this index.

|===


.+Create a node label lookup index+
[options="noheader", width="100%", cols="2, 8a"]
|===

| Syntax
|
[source, syntax, role="noheader"]
----
CREATE LOOKUP INDEX [index_name] [IF NOT EXISTS]
FOR (n)
ON EACH labels(n)
[OPTIONS "{" option: value[, ...] "}"]
----

| Description
|
Create a node label lookup index.

Index provider can be specified using the `OPTIONS` clause.
There is only one available index provider for this index.

|===


.+Create a relationship type lookup index+
[options="noheader", width="100%", cols="2, 8a"]
|===

| Syntax
|
[source, syntax, role="noheader"]
----
CREATE LOOKUP INDEX [index_name] [IF NOT EXISTS]
FOR ()-"["r"]"-()
ON [EACH] type(r)
[OPTIONS "{" option: value[, ...] "}"]
----

| Description
|
Create a relationship type lookup index.

Index provider can be specified using the `OPTIONS` clause.
There is only one available index provider for this index.

|===


.+Drop an index+
[options="noheader", width="100%", cols="2, 8a"]
|===

| Syntax
|
[source, syntax, role="noheader"]
----
DROP INDEX index_name [IF EXISTS]
----

| Description
| Drop an index of any index type.

| Note
|
The command is optionally idempotent. This means that its default behavior is to throw an error if an attempt is made to drop the same index twice.
With `IF EXISTS`, no error is thrown and nothing happens should the index not exist.

|===


.List indexes
[options="noheader", width="100%", cols="2, 8a"]
|===

| Syntax
|
[source, syntax, role="noheader"]
----
SHOW [ALL \| FULLTEXT \| LOOKUP \| POINT \| RANGE \| TEXT] INDEX[ES]
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
| List indexes in the database, either all or filtered on index type.

| Note
| When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.

|===


Creating an index requires xref::administration/access-control/database-administration.adoc#access-control-database-administration-index[the `CREATE INDEX` privilege],
while dropping an index requires xref::administration/access-control/database-administration.adoc#access-control-database-administration-index[the `DROP INDEX` privilege] and
listing indexes require xref::administration/access-control/database-administration.adoc#access-control-database-administration-index[the `SHOW INDEX` privilege].

== Fill text search indexes

== Vector search indexes
