= Predicate operators

[[where-example-graph]]
== Example graph

The following graph is used for the examples below:

To recreate the graph, run the following query in an empty Neo4j database:

[source, cypher, role=test-setup]
----
CREATE
  (alice:Person {name:'Alice', age: 65, email: 'alice@example.com', occupation: 'Project manager'}),
  (bob:Person {name: 'Bob', age: 25, email: 'bob@example.com', occupation: 'Software developer'}),
  (cecilia:Person {name: 'Cecilia', age: 31, occupation: 'Software developer'}),
  (charlie:Person {name: 'Charlie', age: 61, occupation: 'Security engineer'}),
  (daniel:Person {name: 'Daniel', age: 39, email: 'daniel@example.com', occupation: 'Director'}),
  (eskil:Person {name: 'Eskil', age: 39, email: 'eskil@example.com}),
  (bob)-[:WORKS_FOR]->(alice),
  (cecilia)-[:WORKS_FOR]->(alice),
  (alice)-[:WORKS_FOR]->(daniel),
  (charlie)-[:WORKS_FOR]->(daniel),
  (bob)-[:LOVES]->(eskil),
  (charlie)-[:LOVES]->(alice)
----

[[boolean-operators]]
== Boolean operators

The boolean operators comprise:

* conjunction: `AND`
* disjunction: `OR`
* exclusive disjunction: `XOR`
* negation: `NOT`

.Truth table for boolean operators
[options="header", cols="^,^,^,^,^,^", width="85%"]
|===
|a | b | a `AND` b | a `OR` b | a `XOR` b | `NOT` a
|`false` | `false` | `false` | `false` | `false` | `true`
|`false` | `null` | `false` | `null` | `null` | `true`
|`false` | `true` | `false` | `true` | `true` | `true`
|`true` | `false` | `false` | `true` | `true` | `false`
|`true` | `null` | `null` | `true` | `null` | `false`
|`true` | `true` | `true` | `true` | `false` | `false`
|`null` | `false` | `false` | `null` | `null` | `null`
|`null` | `null` | `null` | `null` | `null` | `null`
|`null` | `true` | `null` | `true` | `null` | `null`
|===

.Boolean operators
=====

.`AND` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.age > 30 AND n.occupation = 'Software developer'
RETURN n.name AS name, n.age AS age, n.occupation AS occupation
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| name | age | occupation

| "Cecilia" | 31  | "Software developer"

3+d|Rows: 1
|===

.`OR` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.age < 30 OR n.occupation = 'Software developer'
RETURN n.name AS name, n.age AS age, n.occupation AS occupation
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| name | age | occupation

| "Cecilia" | 31  | "Software developer"
| "Bob" | 25 | "Software developer"

3+d|Rows: 2
|===

.`XOR` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.age > 30 XOR n.occupation = 'Software developer'
RETURN n.name AS name, n.age AS age, n.occupation AS occupation
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| name | age | occupation

| "Alice"   | 65  | "Project manager"
| "Bob"     | 25  | "Software developer"
| "Charlie" | 61  | "Security engineer"
| "Daniel"  | 39  | "Director"

3+d|Rows: 4
|===

.`NOT` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.age > 30 AND NOT n.occupation = 'Software developer'
RETURN n.name AS name, n.age AS age, n.occupation AS occupation
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| name | age | occupation

| "Alice"   | 65  | "Project manager"
| "Charlie" | 61  | "Security engineer"
| "Daniel"  | 39  | "Director"

3+d|Rows: 3
|===

.Combining boolean operators
[source, cypher]
----
 MATCH (n:Person)
WHERE n.occupation = 'Software developer' XOR (n.age > 60 AND n.occupation = 'Security engineer') OR NOT (n.occupation = 'Director' OR n.name = 'Eskil')
RETURN n.name AS name, n.age AS age, n.occupation AS occupation
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name      | age | occupation

| "Alice"   | 65  | "Project manager"
| "Cecilia" | 31  | "Software developer"
| "Daniel"  | 39  | "Director"

3+d|Rows: 3

|===


.Filtering numbers with boolean operators
[source, cypher]
----
WITH [2, 4, 7, 9, 12] AS numberlist
UNWIND numberlist AS number
WITH number
WHERE number = 4 OR (number > 6 AND number < 10)
RETURN number
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| number
| 4
| 7
| 9

1+d|Rows: 3
|===

=====


