= Predicate operators
:table-caption!:

Predicate operators define conditions to filter and retrieve data in queries.
They are categorized as follows:

* xref:expressions/predicate-expressions/operators.adoc#boolean-operators[Boolean operators] (`AND`, `OR`, `XOR`, `NOT`)
* xref:expressions/predicate-expressions/operators.adoc#comparison-operators[Comparison operators] (`=`, `<>`, `<`, `>`, `<=`, `>=`, `IS NULL`, `IS NOT NULL`)
*  xref:expressions/predicate-expressions/operators.adoc#string-operators[String operators] (`=~`, `STARTS WITH`, `ENDS WITH`, `CONTAINS`, `IS NORMALIZED`, `IS NOT NORMALIZED`)
* xref:expressions/predicate-expressions/operators.adoc#list-operators[List operators] (`IN`)

[[where-example-graph]]
== Example graph

The following graph is used for the examples below:

To recreate the graph, run the following query in an empty Neo4j database:

[source, cypher, role=test-setup]
----
CREATE
  (alice:Person {name:'Alice', age: 65, email: 'alice@example.com', occupation: 'Project manager'}),
  (bob:Person {name: 'Bob', age: 25, email: 'bob@example.com', occupation: 'Software developer'}),
  (cecilia:Person {name: 'Cecilia', age: 31, occupation: 'Software developer'}),
  (charlie:Person {name: 'Charlie', age: 61, occupation: 'Security engineer'}),
  (daniel:Person {name: 'Daniel', age: 39, email: 'daniel@example.com', occupation: 'Director'}),
  (eskil:Person {name: 'Eskil', age: 39, email: 'eskil@example.com'}),
  (bob)-[:WORKS_FOR]->(alice),
  (cecilia)-[:WORKS_FOR]->(alice),
  (alice)-[:WORKS_FOR]->(daniel),
  (charlie)-[:WORKS_FOR]->(daniel),
  (bob)-[:LOVES]->(eskil),
  (charlie)-[:LOVES]->(alice)
----

[[boolean-operators]]
== Boolean operators

The boolean operators comprise:

* Conjunction: `AND`
* Disjunction: `OR`
* Exclusive disjunction: `XOR`
* Negation: `NOT`

.Truth table for boolean operators
[options="header", cols="^,^,^,^,^,^", width="85%"]
|===
|a | b | a `AND` b | a `OR` b | a `XOR` b | `NOT` a
|`false` | `false` | `false` | `false` | `false` | `true`
|`false` | `null` | `false` | `null` | `null` | `true`
|`false` | `true` | `false` | `true` | `true` | `true`
|`true` | `false` | `false` | `true` | `true` | `false`
|`true` | `null` | `null` | `true` | `null` | `false`
|`true` | `true` | `true` | `true` | `false` | `false`
|`null` | `false` | `false` | `null` | `null` | `null`
|`null` | `null` | `null` | `null` | `null` | `null`
|`null` | `true` | `null` | `true` | `null` | `null`
|===

.Boolean operators
=====

.`AND` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.age > 30 AND n.occupation = 'Software developer'
RETURN n.name AS name, n.age AS age, n.occupation AS occupation
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| name | age | occupation

| "Cecilia" | 31 | "Software developer"

3+d|Rows: 1
|===

.`OR` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.age < 30 OR n.occupation = 'Software developer'
RETURN n.name AS name, n.age AS age, n.occupation AS occupation
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| name | age | occupation

| "Cecilia" | 31  | "Software developer"
| "Bob" | 25 | "Software developer"

3+d|Rows: 2
|===

.`XOR` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.age > 30 XOR n.occupation = 'Software developer'
RETURN n.name AS name, n.age AS age, n.occupation AS occupation
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| name | age | occupation

| "Alice" | 65 | "Project manager"
| "Bob" | 25 | "Software developer"
| "Charlie" | 61 | "Security engineer"
| "Daniel" | 39 | "Director"

3+d|Rows: 4
|===

.`NOT` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.age > 30 AND NOT n.occupation = 'Software developer'
RETURN n.name AS name, n.age AS age, n.occupation AS occupation
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| name | age | occupation

| "Alice" | 65 | "Project manager"
| "Charlie" | 61 | "Security engineer"
| "Daniel" | 39 | "Director"

3+d|Rows: 3
|===

.Combining boolean operators
[source, cypher]
----
MATCH (n:Person)
WHERE n.occupation = 'Software developer' XOR (n.age > 60 AND n.occupation = 'Security engineer') OR NOT (n.occupation = 'Director' OR n.name = 'Eskil')
RETURN n.name AS name, n.age AS age, n.occupation AS occupation
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
|===
| name | age | occupation

| "Alice" | 65 | "Project manager"
| "Cecilia" | 31 | "Software developer"
| "Daniel" | 39 | "Director"

3+d|Rows: 3

|===


.Filtering numbers with boolean operators
[source, cypher]
----
WITH [2, 4, 7, 9, 12] AS numberlist
UNWIND numberlist AS number
WITH number
WHERE number = 4 OR (number > 6 AND number < 10)
RETURN number
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| number
| 4
| 7
| 9

1+d|Rows: 3
|===

=====

[[comparison-operators]]
== Comparison operators

The comparison operators comprise:

* Equality: `=`
* Inequality: `<>`
* Less than: `<`
* Greater than: `>`
* Less than or equal to: `\<=`
* Greater than or equal to: `>=`
* `IS NULL`
* `IS NOT NULL`

[TIP]
For more information about `null`, see xref:values-and-types/working-with-null.adoc[].

.Comparison operators
=====

.Equality operator (`=`)
[source, cypher]
----
MATCH (n:Person)
WHERE n.occupation = 'Software developer'
RETURN n.name AS name, n.occupation AS occupation
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | occupation

| "Bob" | "Software developer"
| "Cecilia" | "Software developer"

2+d|Rows: 2
|===

.Inequality operator (`<>`)
[source, cypher]
----
MATCH (n:Person)
WHERE n.occupation <> 'Software developer'
RETURN n.name AS name, n.occupation AS occupation
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | occupation

| "Alice" | "Project manager"
| "Charlie" | "Security engineer"
| "Daniel" | "Director"

2+d|Rows: 3
|===

.Less than operator (`<`)
[source, cypher]
----
MATCH (n:Person)
WHERE n.age < 39
RETURN n.name AS name, n.age AS age
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | age

| "Bob" | 25
| "Cecilia" | 31

2+d|Rows: 2
|===

.Less than or equal operator (`<=`)
[source, cypher]
----
MATCH (n:Person)
WHERE n.age <= 39
RETURN n.name AS name, n.age AS age
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | age

| "Bob" | 25
| "Cecilia" | 31
| "Daniel" | 39
| "Eskil" | 39

2+d|Rows: 4
|===

.Greater than operator (`>`)
[source, cypher]
----
MATCH (n:Person)
WHERE n.age > 39
RETURN n.name AS name, n.age AS age
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | age

| "Alice" | 65
| "Charlie" | 61

2+d|Rows: 2
|===

.Greater than or equal operator (`>`)
[source, cypher]
----
MATCH (n:Person)
WHERE n.age > 39
RETURN n.name AS name, n.age AS age
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | age

| "Alice" | 65
| "Charlie" | 61
| "Daniel" | 39
| "Eskil" | 39

2+d|Rows: 4
|===

.`IS NULL` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.email IS NULL
RETURN n.name AS name
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===

| name

| "Cecilia"
| "Charlie"

1+d|Rows: 2
|===

.`IS NOT NULL` operator
[source, cypher]
----
MATCH (n:Person)
WHERE n.email IS NOT NULL
RETURN n.name AS name
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | email

| "Alice" | "alice@example.com"
| "Bob" | "bob@example.com"
| "Daniel" | "daniel@example.com"
| "Eskil" | "eskil@example.com"

2+d|Rows: 4

|===

=====

[[equality-and-comparison]]
=== Equality and comparison of values

The equality (`=`) and inequality (`<>`) operators allows for comparing the equality of different values.

Values of the same type are only equal if they are the same identical value (e.g. `3 = 3` and `"x" <> "xy"`).

Maps are only equal if they map exactly the same keys to equal values and lists are only equal if they contain the same sequence of equal values (e.g. `[3, 4] = [1+2, 8/2]`).

Values of different types are considered as equal according to the following rules:

* `PATH` values are treated as lists of alternating nodes and relationships and are equal to all lists that contain an identical sequence of nodes and relationships.
* Testing any value against `null` with either the `=` or `<>` operator always evaluates to `null`.
This includes `null = null` and `null <> null`.
To reliably test if a value is `null` use `v IS NULL` or `v IS NOT NULL` (the latter is equivalent to `NOT(v IS NULL)`).

Other combinations of value types cannot be compared with each other.
For example, nodes, relationships, and literal maps cannot be compared to one another.
Comparing incomparable values will throw an error.

[[ordering-and-comparison]]
=== Ordering and comparison of values

xref:clauses/order-by.adoc[`ORDER BY`] requires that all values are orderable.
The following points explain how comparisons are made when using the `\<=`, `<`,`>=`, `>` operators.

* Numerical values are compared for ordering using numerical order (e.g. `3 < 4` is `true`).
* All comparability tests with `java.lang.Double.NaN` evaluate as `false`.
For example, `1 > b` and `1 < b` are both `false` when `b` is NaN.
* String values are compared for ordering using lexicographic order (e.g. `"x" < "xy"`).
* Boolean values are compared for ordering such that `false < true`.
* When comparing values for ordering, if one of the arguments is `null`, the result is always `null`.
* xref:values-and-types/spatial.adoc[Spatial values] cannot be compared using the operators `\<=`, `<`,`>=`, `>`.
To compare spatial values within a specific range, use either the xref:functions/spatial.adoc#functions-withinBBox[`point.withinBBox()`] or the xref:functions/spatial.adoc#functions-point-wgs84-2d[`point()`] function.

This section also includes the following categories:

* xref:expressions/predicate-expressions/operators.adoc#value-hierarchy[Hierarchy of values]
* xref:expressions/predicate-expressions/operators.adoc#ordering-lists-maps[Ordering list and map values]
* xref:expressions/predicate-expressions/operators.adoc#ordering-spatial-temporal[Ordering spatial and temporal values]
 
[[value-hierarchy]]
==== Hierarchy of values

Values of different types are ordered based on a predefined hierarchy, from least to greatest, as outlined in the following list:

* xref::values-and-types/maps.adoc#cypher-literal-maps[`MAP`]
* xref::values-and-types/property-structural-constructed.adoc#structural-types[`NODE`]
* xref::values-and-types/property-structural-constructed.adoc#structural-types[`RELATIONSHIP`]
* xref::values-and-types/lists.adoc[`LIST`]
* xref::patterns/fixed-length-patterns.adoc#path-patterns[`PATH`]
* xref::values-and-types/temporal.adoc[`ZONED DATETIME`]
* xref::values-and-types/temporal.adoc[`LOCAL DATETIME`]
* xref::values-and-types/temporal.adoc[`DATE`]
* xref::values-and-types/temporal.adoc[`ZONED TIME`]
* xref::values-and-types/temporal.adoc[`LOCAL TIME`]
* xref::values-and-types/temporal.adoc[`DURATION`]
* xref::values-and-types/spatial.adoc[`POINT`]
* xref::expressions/expressions-overview.adoc#string[`STRING`]
* xref::expressions/expressions-overview.adoc#boolean[`BOOLEAN`]
* Numbers: xref::expressions/expressions-overview.adoc#numerical[`INTEGER`, `FLOAT`]

[NOTE]
`null` is ordered after all other values.

.Sorting rules for mixed Cypher types
[source, cypher]
----
WITH [42, "hello", null, true, {name: "Alice"}, [1, 2, 3], date("2024-02-10")] AS v
UNWIND v AS values
RETURN values
ORDER BY values
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| values

| {name: "Alice"}
| [1, 2, 3]
| 2024-02-10
| "hello"
| TRUE
| 42
| NULL

1+d|Rows: 7

|===

[[ordering-lists-maps]]
==== Ordering list and map values
 
*Lists are compared in lexicographic order:*

* Elements are compared pairwise from the start to the end of the list.
The order is defined by the first pair where the elements differ.
For example, `[1, 'foo', 3]` is less than `[1, 2, 'bar']` because `'foo'` is less than `2`.
* If one list is shorter, it is padded with an empty element, which is considered less than any other value (including `null`).
For example, `[1, 'foo']` is less than `[1, 'foo', 3]`, and `[1]` is less than `[1, null]`.

*Maps are ordered by size, keys, and values:*

* Maps are compared primarily by size: the smallest map has the fewest entries. For example, `{a: 1}` is less than `{a: 0, b: 'foo'}`.
* Maps of equal size are compared by the alphabetical order of their keys.
For example, `{b: 100, a: 'foo'}` is less than `{a: '', c: null}` because `['a', 'b']` is less than `['a', 'c']`.
* For maps with identical key sets, the comparison is based on the values.
After sorting keys alphabetically, values are compared pairwise.
For example, `{b: 100, a: 'foo'}` is less than `{a: 'foo', b: null}` because `['foo', 100]` is less than `['foo', null]`.

For more information about `LIST` and `MAP` values, see xref::values-and-types/property-structural-constructed.adoc#constructed-types[Values and types -> Constructed types].

[[ordering-spatial-temporal]]
==== Ordering spatial and temporal values

The following applies to ordering of xref:values-and-types/spatial.adoc[spatial types]:

* `POINT` values are ordered after lists and before temporal types.
* `POINT` values of different coordinate reference systems (CRS) are ordered by the CRS code (the value of SRID field).
For the currently supported set of xref::values-and-types/spatial.adoc#cypher-spatial-crs[CRS], the following ascending order applies: `4326`, `4979`, `7302`, `9157`.
* `POINT` values with the same CRS are ordered by each coordinate value in turn; first `x`, then `y`, and finally `z`.
* Note that this ordering is different to the order returned by the spatial index, which follows the space filling curve.

The following applies to the ordering of xref:values-and-types/temporal.adoc[temporal types]:

* Temporal types are ordered after spatial types but before strings.
* Temporal values follow a chronological order.
For example, `2023-01-01` comes before `2024-01-01`.
* Temporal values are first sorted by type, then by value.
For example, `DATETIME` is considered "greater" than a `DATE` and `2023-02-10T12:00:00` comes before `2023-02-10T15:00:00` because it is chronologically earlier.
* Since there is no perfect way to compare duration values (because months and years have varying lengths), Cypher defines a specific rule for sorting them in `ORDER BY`:
** 1 year is treated as 365.2425 days (to account for leap years).
** 1 month is treated as 30.436875 days (which is 1/12 of a year).
** 1 day is always 24 hours.

The following applies to comparing temporal types:

* xref::values-and-types/temporal.adoc#cypher-temporal-instants[Temporal instant values] (like `DATETIME` and `DATE`) can be compared if they are of the same type.
An earlier instant is considered smaller (less than) compared to a later instant.
* Instants at the same point in time but with different time zones are not considered equal.
To ensure consistent ordering, Cypher sorts them first by their actual point in time.
If two instants have the same time but different time zones, they are ordered by their UTC offset (west to east, meaning negative offsets come first).
If they have the same time and offset but different named time zones, they are sorted alphabetically by the time zone name.
* Duration values cannot be directly compared.
Since the length of a day, month, or year varies, Cypher does not define a strict ordering for durations.
Compare two durations `(e.g, duration1 < duration2)`, the result will always be `null`.

[[string-operators]]
== String operators

[[list-operators]]
== List operators

