= Path pattern expressions

A path pattern is the top level pattern that is matched against paths in a graph.
Similar to xref::subqueries/existential.adoc[existential subqueries], path pattern expressions can be used to assert whether a specified path exists at least once in a graph.
While existential subqueries are more powerful and capable of performing anything achievable with path pattern expressions, path pattern expressions are more concise.

For more information about graph pattern matching in Cypher, see xref:patterns/index.adoc[].

== Rules

Path pattern expressions have the following restrictions (use cases that require extended functionality should consider using xref::subqueries/existential.adoc[existential subqueries] instead):

* Path pattern expressions may only use a subset of xref::patterns/reference.adoc#graph-patterns[graph pattern] semantics.

* A path pattern expression must be a xref::patterns/reference.adoc#path-patterns[path pattern] of length greater than zero.
In other words, it must contain at least one xref::patterns/reference.adoc#relationship-patterns[relationship] or xref::patterns/reference.adoc#variable-length-relationships[variable-length relationship].

* Path pattern expressions may not declare new variables.
They can only reference existing variables.

* Path pattern expressions may only be used in positions where a xref:expressions/expressions-overview.adoc#boolean[boolean expression] is expected.
The following sections will demonstrate how to use path pattern expressions in a `WHERE` clause.

== Example graph

The following graph is used for the examples below:

To recreate the graph, run the following query in an empty Neo4j database:

[source, cypher]
----
CREATE (alice:Person {name:'Alice', age: 65, role: 'Project manager'}),
       (cecil:Person {name: 'Cecil', age: 25, role: 'Software developer'}),
       (cecilia:Person {name: 'Cecilia', age: 31, role: 'Software developer'}),
       (charlie:Person {name: 'Charlie', age: 61, role: 'Security engineer'}),
       (daniel:Person {name: 'Daniel', age: 39, role: 'Director'}),
       (eskil:Person {name: 'Eskil', age: 39, role: 'CEO'}),
       (cecil)-[:WORKS_FOR {since: 2023}]->(alice),
       (cecilia)-[:WORKS_FOR {since: 2015}]->(alice),
       (alice)-[:WORKS_FOR {since: 2020}]->(daniel),
       (charlie)-[:WORKS_FOR {since: 2003}]->(daniel),
       (daniel)-[:WORKS_FOR {since: 2024}]->(eskil)
----

[[filter-on-patterns]]
=== Filter on fixed-length patterns

.Query
[source, cypher]
----
MATCH
  (cecil:Person {name: 'Cecil'}),
  (other:Person)
WHERE (cecil)-->(other)
RETURN other.name, other.age
----

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| other.name | other.age
| "Andy" | 36
2+|Rows: 1
|===


[[filter-on-patterns-using-not]]
=== Filter on patterns using `NOT`

The `NOT` operator can be used to exclude a pattern:

.Query
[source, cypher]
----
MATCH
  (peter:Person {name: 'Peter'}),
  (other:Person)
WHERE NOT (other)-->(peter)
RETURN other.name, other.age
----

The `name` and `age` values for nodes that do not have an outgoing relationship to `Peter` are returned:

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| other.name | other.age
| "Timothy" | 25
| "Peter" | 35
2+|Rows: 2
|===


