:description: Overview of the semantic indexes available in Neo4j.
= Semantic indexes

Unlike search-performance indexes, semantic indexes capture the semantic meaning or context of the data in a database.
This is done by returning an approximation score, which indicates the similarity between a query string and the data in a database.

Two semantic indexes are available in Neo4j:

* xref:indexes/semantic-indexes/full-text-indexes.adoc[Full-text indexes]: enables searching within the content of `STRING` properties and for similarity comparisons between query strings and `STRING` values stored in the database.
* xref:indexes/semantic-indexes/vector-indexes.adoc[Vector indexes]: enables similarity searches and complex analytical queries by representing nodes or properties as vectors in a multidimensional space.

[NOTE]
Unlike search-performance indexes, semantic indexes are not automatically used by the xref:planning-and-tuning/execution-plans.adoc[Cypher planner].
To use semantic indexes, they must be explicitly called with specific procedures.
