= Subqueries

Cypher includes three different types of subquery expressions:

* xref:subqueries/call-subquery.adoc[]
* xref:subqueries/existential.acoc[Existential subquery expressions]
* xref:subqueries/count.adoc[Count subquery expressions]
* xref:subqueries/collect.adoc[Collect subquery expressions] label:new[Introduced in 5.6]

Subquery expressions can appear anywhere that an expression is valid.
A subquery has a scope, as indicated by the opening and closing braces, `{` and `}`.
Any variable that is defined in the outside scope can be referenced inside the subquery's own scope.
Variables introduced inside the subquery are not part of the outside scope and therefore can't be accessed on the outside.

[[expressions-subquery-example]]

== Example graph
The following graph is used for the examples below:

////
[source, cypher, role=test-setup]
----
MATCH (n:A|B|C|D|E) DETACH DELETE n;
CREATE
(andy:Swedish:Person {name: 'Andy', age: 36}),
(timothy:Person {name: 'Timothy', nickname: 'Tim', age: 25}),
(peter:Person {name: 'Peter', nickname: 'Pete', age: 35}),
(andy)-[:HAS_DOG {since: 2016}]->(:Dog {name:'Andy'}),
(timothy)-[:HAS_CAT {since: 2019}]->(:Cat {name:'Mittens'}),
(fido:Dog {name:'Fido'})<-[:HAS_DOG {since: 2010}]-(peter)-[:HAS_DOG {since: 2018}]->(:Dog {name:'Ozzy'}),
(fido)-[:HAS_TOY]->(:Toy{name:'Banana'})
----
////

image:graph_expression_subqueries.svg[]





