= CALL subqueries in transactions
:description: This page describes how to use CALL...IN TRANSACTIONS subquery with Cypher.

`CALL` subqueries can be made to execute in separate, inner transactions, producing intermediate commits.
This can be useful when doing large write operations, like batch updates, imports, and deletes.

To execute a `CALL` subquery in separate transactions, add the modifier `IN TRANSACTIONS` after the subquery.
An outer transaction is opened to report back the accumulated statistics for the inner transactions
(created and deleted nodes, relationships, etc.) and it will succeed or fail depending on the results
of those inner transactions.
By default, inner transactions group together batches of 1000 rows.
Cancelling the outer transaction will cancel the inner ones as well.

[NOTE]
`CALL { ... } IN TRANSACTIONS` is only allowed in xref::introduction/cypher-neo4j.adoc#cypher-neo4j-transactions[implicit transactions]. +
If you are using link:https://neo4j.com/docs/browser/[Neo4j Browser], you must prepend any queries using `CALL { ... } IN TRANSACTIONS` with `:auto`.

[NOTE]
The examples on this page use a xref:subqueries/call-subquery.adoc#variable-scope-clause[variable scope clause] to import variables into the `CALL` subquery.

== Syntax

[source, syntax]
----
CALL {
    subQuery
} IN [[concurrency] CONCURRENT] TRANSACTIONS
[OF batchSize ROW[S]]
[DISJOINT BY {NONE | AUTO | (<expr>, ...)}]
[REPORT STATUS AS statusVar]
[ON ERROR {CONTINUE | BREAK | FAIL | RETRY [FOR] [duration SEC[OND[S]]] [THEN {CONTINUE | BREAK | FAIL}]}]
----

== Loading CSV data

This example uses a CSV file and the `LOAD CSV` clause to import data into the database.
It creates nodes in separate transactions using `CALL { ... } IN TRANSACTIONS`:

.friends.csv
[source, csv, role="noheader" filename="friends.csv"]
----
1,Bill,26
2,Max,27
3,Anna,22
4,Gladys,29
5,Summer,24
----

.Query
// tag::subqueries_in_transactions_basic_example[]
[source, cypher]
----
LOAD CSV FROM 'file:///friends.csv' AS line
CALL (line) {
  CREATE (:Person {name: line[1], age: toInteger(line[2])})
} IN TRANSACTIONS
----
// end::subqueries_in_transactions_basic_example[]


.Result
[role="queryresult",options="footer",cols="1*<m"]
|===
1+|(empty result)
1+d|Rows: 0 +
Nodes created: 5 +
Properties set: 10 +
Labels added: 5 +
Transactions committed: 1
|===

As the size of the CSV file in this example is small, only a single separate transaction is started and committed.


[[delete-with-call-in-transactions]]
== Deleting a large volume of data

Using `CALL { ... } IN TRANSACTIONS` is the recommended way of deleting a large volume of data.


.+DETACH DELETE on all nodes+
======

.Query
[source, cypher]
----
MATCH (n)
CALL (n) {
  DETACH DELETE n
} IN TRANSACTIONS
----

.Result
[role="queryresult",options="footer",cols="1*<m"]
|===
1+|(empty result)
1+d|Rows: 0 +
Nodes deleted: 5 +
Relationships deleted: 2 +
Transactions committed: 1
|===

======


.+DETACH DELETE on only some nodes+
======

The `CALL { ... } IN TRANSACTIONS` subquery should not be modified.

Any necessary filtering can be done before the subquery.

.Query
[source, cypher]
----
MATCH (n:Label) WHERE n.prop > 100
CALL (n) {
  DETACH DELETE n
} IN TRANSACTIONS
----

.Result
[role="queryresult",options="footer",cols="1*<m"]
|===
1+|(empty result)
1+d|Rows: 0
|===

======

[NOTE]
====
The batching is performed on the input rows fed into `CALL { ... } IN TRANSACTIONS`, so the data must be supplied from outside the call in order for the batching to have an effect.
That is why the nodes are matched outside the subqueries in the examples above.
If the `MATCH` clause were inside the subquery, the data deletion would run as one single transaction.
====


[[batching]]
== Batching

The amount of work to do in each separate transaction can be specified in terms of how many input rows
to process before committing the current transaction and starting a new one.
The number of input rows is set with the modifier `OF n ROWS` (or `OF n ROW`).
If omitted, the default batch size is `1000` rows.
The number of rows can be expressed using any expression that evaluates to a positive integer and does not refer to nodes or relationships.

This example loads a CSV file with one transaction for every `2` input rows:

.friends.csv
[source, csv, role="noheader", filename="friends.csv"]
----
1,Bill,26
2,Max,27
3,Anna,22
4,Gladys,29
5,Summer,24
----

.Query
// tag::subqueries_in_transactions_batching[]
[source, cypher]
----
LOAD CSV FROM 'file:///friends.csv' AS line
CALL (line) {
  CREATE (:Person {name: line[1], age: toInteger(line[2])})
} IN TRANSACTIONS OF 2 ROWS
----
// end::subqueries_in_transactions_batching[]

.Result
[role="queryresult",options="footer",cols="1*<m"]
|===
1+|(empty result)
1+d|Rows: 0 +
Nodes created: 5 +
Properties set: 10 +
Labels added: 5 +
Transactions committed: 3
|===

The query now starts and commits three separate transactions:

. The first two executions of the subquery (for the first two input rows from `LOAD CSV`) take place in the first transaction.
. The first transaction is then committed before proceeding.
. The next two executions of the subquery (for the next two input rows) take place in a second transaction.
. The second transaction is committed.
. The last execution of the subquery (for the last input row) takes place in a third transaction.
. The third transaction is committed.

You can also use `CALL { ... } IN TRANSACTIONS OF n ROWS` to delete all your data in batches in order to avoid a huge garbage collection or an `OutOfMemory` exception.
For example:

.Query
[source, cypher]
----
MATCH (n)
CALL (n) {
  DETACH DELETE n
} IN TRANSACTIONS OF 2 ROWS
----

.Result
[role="queryresult",options="footer",cols="1*<m"]
|===
1+|(empty result)
1+d|Rows: 0 +
Nodes deleted: 9 +
Relationships deleted: 2 +
Transactions committed: 5
|===

[NOTE]
====
Up to a point, using a larger batch size will be more performant.
The batch size of `2 ROWS` is an example given the small data set used here.
For larger data sets, you might want to use larger batch sizes, such as `10000 ROWS`.
====


[[composite-databases]]
== Composite databases

////
[source, cypher, test-setup]
----
CREATE OR REPLACE COMPOSITE DATABASE `composite`;
CREATE OR REPLACE DATABASE `remoteGraph1`;
CREATE OR REPLACE DATABASE `remoteGraph2`;
CREATE ALIAS `composite.remoteGraph1` FOR DATABASE `remoteGraph1`;
CREATE ALIAS `composite.remoteGraph2` FOR DATABASE `remoteGraph2`;
----
////

`CALL { ... } IN TRANSACTIONS` can be used with link:{neo4j-docs-base-uri}/operations-manual/current/scalability/composite-databases/concepts/[composite databases].

Even though composite databases allow accessing multiple graphs in a single query, only one graph can be modified in a single transaction.
`CALL { ... } IN TRANSACTIONS` offers a way of constructing queries which modify multiple graphs.

While the previous examples are generally valid for composite databases, there's a few extra factors that come into play when working with composite databases in subqueries.
The following examples show how you can use `CALL { ... } IN TRANSACTIONS` on a composite database.

[IMPORTANT]
====
Your application needs to be connected to the composite database when submitting queries involving its constituents. Select the composite database in UI tools or when running queries via client libraries.
====

.Import a CSV file on all constituents
====
.friends.csv
[source, csv, filename="friends.csv"]
----
1,Bill,26
2,Max,27
3,Anna,22
4,Gladys,29
5,Summer,24
----

.Create `Person` nodes on all constituents, drawing data from friends.csv
[source, cypher, test-database=composite]
----
UNWIND graph.names() AS graphName
LOAD CSV FROM 'file:///friends.csv' AS line
CALL (graphName, line) {
  USE graph.byName( graphName )
  CREATE (:Person {name: line[1], age: toInteger(line[2])})
} IN TRANSACTIONS
----
====

.Remove all nodes and relationships from all constituents
====
.Query
[source, cypher, test-database=composite]
----
UNWIND graph.names() AS graphName
CALL (graphName) {
  USE graph.byName( graphName )
  MATCH (n)
  RETURN elementId(n) AS id
}
CALL (graphName, id) {
  USE graph.byName( graphName )
  WITH id
  MATCH (n)
  WHERE elementId(n) = id
  DETACH DELETE n
} IN TRANSACTIONS
----

[NOTE]
Since the batching is performed on the input rows fed into `CALL { ... } IN TRANSACTIONS`, the data must be supplied from outside the subquery in order for the batching to have an effect.
That is why the nodes are matched in a subquery _preceding_ the one that actually deletes the data.
If the `MATCH` clause were inside the second subquery, the data deletion would run as one single transaction.

====

[NOTE]
====
There is currently a known issue.
When an error occurs during `CALL { ... } IN TRANSACTIONS` processing, the error message includes information about how many transactions have been committed.
That information is inaccurate on composite databases, as it always reports `(Transactions committed: 0)`.
====

[NOTE]
====
`CALL { ... } IN CONCURRENT TRANSACTIONS` currently provides no extra parallelism for composite databases.
The subquery is executed in parallel on each target graph by default.
====

[discrete]
[[composite-databases-batching]]
=== Batch size in composite databases
Because `CALL { ... } IN TRANSACTIONS` subqueries targeting different graphs can't be interleaved, if a `USE` clause evaluates to a different target than the current one, the current batch is committed and the next batch is created.

The batch size declared with `IN TRANSACTIONS OF ... ROWS` represents an upper limit of the batch size, but the real batch size depends on how many input rows target one database *in sequence*.
Every time the target database changes, the batch is committed.

.Behavior of `IN TRANSACTIONS OF ROWS` on composite databases
====
The next example assumes the existence of two constituents `remoteGraph1` and `remoteGraph2` for the composite database `composite`.

While the declared batch size is 3, only the first 2 rows act on `composite.remoteGraph1`, so the batch size for the first transaction is 2. That is followed by 3 rows on `composite.remoteGraph2`, 1 on `composite.remoteGraph2` and finally 2 on `composite.remoteGraph1`.

.Query
[source, cypher, test-database=composite]
----
WITH ['composite.remoteGraph1', 'composite.remoteGraph2'] AS graphs
UNWIND [0, 0, 1, 1, 1, 1, 0, 0] AS i
WITH graphs[i] AS g
CALL (g) {
  USE graph.byName( g )
  CREATE ()
} IN TRANSACTIONS OF 3 ROWS
----
====


[[error-behavior]]
== Error behavior

`CALL { ... } IN TRANSACTIONS` has four different behavioral options in case an error occurs in any of the inner transactions: xref:subqueries/subqueries-in-transactions.adoc#on-error-continue[`ON ERROR CONTINUE`], xref:subqueries/subqueries-in-transactions.adoc#on-error-break[`ON ERROR BREAK`], xref:subqueries/subqueries-in-transactions.adoc#on-error-fail[`ON ERROR FAIL`], and xref:subqueries/subqueries-in-transactions.adoc#on-error-retry[`ON ERROR RETRY`].

[IMPORTANT]
If an error occurs, any inner transactions that were successfully committed remain unchanged and are not rolled back. However, any inner transactions that failed are fully rolled back. This behavior applies regardless of which `ON ERROR` option is used.


[[on-error-continue]]
=== `ON ERROR CONTINUE`

`ON ERROR CONTINUE` ignores recoverable errors and continues the execution of subsequent inner transactions.
The outer transaction succeeds.
When an inner query fails, `ON ERROR CONTINUE` ensures the outer transaction continues, returning `null` for the failed inner query.

.`ON ERROR CONTINUE`
=====

In the below query, the last subquery execution in the second inner transaction fails
due to division by zero:

.Subquery with failing transaction
[source, cypher, role=test-fail]
----
UNWIND [4, 2, 1, 0] AS i
CALL (i) {
  CREATE (:Person {num: 100/i}) // Note, fails when i = 0
} IN TRANSACTIONS OF 2 ROWS
RETURN i
----

.GQLSTATUS error chain
[role="queryresult",stripes="all",cols="1"]
|===
| link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/22N28/[22N28]: error: data exception - overflow error. The result of the operation '/ by zero' has caused an overflow.

link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/22012/[22012]: error: data exception - division by zero
|===

Since the failure occurred after the first transaction was committed, the database retains the successfully created nodes.

.Return nodes created prior to failed transaction
[source, cypher]
----
MATCH (e:Person)
RETURN e.num
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| e.num

| 25
| 50

1+d|Rows: 2
|===

In the following example, `ON ERROR CONTINUE` is used after a failed inner transaction to execute the remaining inner transactions and not fail the outer transaction:

.Transactions batched in 1 row with `ON ERROR CONTINUE`
// tag::subqueries_in_transactions_error_behavior[]
[source, cypher]
----
UNWIND [1, 0, 2, 4] AS i
CALL (i) {
  CREATE (n:Person {num: 100/i}) // Note, fails when i = 0
  RETURN n
} IN TRANSACTIONS
  OF 1 ROW
  ON ERROR CONTINUE
RETURN n.num
----
// end::subqueries_in_transactions_error_behavior[]


.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| n.num

| 100
| null
| 50
| 25

1+d|Rows: 4
|===

Note the difference in results when batching in transactions of 2 rows:

.Transactions batched in 2 rows with `ON ERROR CONTINUE`
[source, cypher]
----
UNWIND [1, 0, 2, 4] AS i
CALL (i) {
  CREATE (n:Person {num: 100/i})
  RETURN n
} IN TRANSACTIONS
  OF 2 ROWS
  ON ERROR CONTINUE
RETURN n.num
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| n.num

| null
| null
| 50
| 25

1+d|Rows: 4
|===

In this case, the first inner transaction includes `i = 1` and `i = 0`.
Since `i = 0` causes an error, the entire transaction is rolled back, resulting in `null` for both elements.

=====

[[on-error-break]]
=== `ON ERROR BREAK`

`ON ERROR BREAK` ignores recoverable errors and stops the execution of subsequent inner transactions.
The outer transaction succeeds.
When an inner query fails, `ON ERROR BREAK` ensures the outer transaction continues but stops executing any further inner transactions.
Expected variables from the failed inner query are bound as `null` for all subsequent transactions, including the failed one.

.`ON ERROR BREAK`
=====

In this example, `ON ERROR BREAK` ensures that once an inner transaction fails `(i = 0)`, no further inner transactions execute, while the outer transaction remains successful.

.Transactions batched in 1 row with `ON ERROR BREAK`
[source, cypher]
----
UNWIND [1, 0, 2, 4] AS i
CALL (i) {
  CREATE (n:Person {num: 100/i}) // Note, fails when i = 0
  RETURN n
} IN TRANSACTIONS
  OF 1 ROW
  ON ERROR BREAK
RETURN n.num
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| n.num

| 100
| null
| null
| null

1+d|Rows: 4
|===

When batching in transactions of 2 rows, the first transaction (`i = 1, 0`) encounters an error at `i = 0`, causing execution to stop immediately.
As a result, all remaining transactions also return null.

.Transactions batched in 2 rows with `ON ERROR BREAK`
[source, cypher]
----
UNWIND [1, 0, 2, 4] AS i
CALL (i) {
  CREATE (n:Person {num: 100/i})
  RETURN n
} IN TRANSACTIONS
  OF 2 ROWS
  ON ERROR BREAK
RETURN n.num
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| n.num

| null
| null
| null
| null

1+d|Rows: 4
|===

=====

[[on-error-fail]]
=== `ON ERROR FAIL`

`ON ERROR FAIL` acknowledges a recoverable error and stops the execution of subsequent inner transactions, causing the outer transaction to fail.

[NOTE]
`ON ERROR FAIL` is the default behavior if no error-handling flag is explicitly specified.

.`ON ERROR FAIL`
=====

In the following example, `ON ERROR FAIL` is used after the failed inner transaction to prevent the remaining inner transactions from executing and to cause the outer transaction to fail as well.

.Transactions batched in 1 row with `ON ERROR FAIL`
[source, cypher, role=test-fail]
----
UNWIND [1, 0, 2, 4] AS i
CALL (i) {
  CREATE (n:Person {num: 100/i}) // Note, fails when i = 0
  RETURN n
} IN TRANSACTIONS
  OF 1 ROW
  ON ERROR FAIL
RETURN n.num
----

.GQLSTATUS error chain
[role="queryresult",stripes="all",cols="1"]
|===
| link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/22N28/[22N28]: error: data exception - overflow error. The result of the operation '/ by zero' has caused an overflow.

link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/22012/[22012]: error: data exception - division by zero
|===
=====


[[on-error-retry]]
=== `ON ERROR RETRY`

`ON ERROR RETRY` uses an exponential delay between retry attempts for transaction batches that fail due to transient errors (i.e. errors where retrying a transaction can be expected to give a different result), with an optional xref:subqueries/subqueries-in-transactions.adoc#specify-retry-duration[maximum retry duration].
If the transaction still fails after the maximum duration, the failure is handled according to an optionally specified xref:subqueries/subqueries-in-transactions.adoc#fallback-error-handling[fallback error handling mode] (`THEN CONTINUE`, `THEN BREAK`, `THEN FAIL` (default)).

`ON ERROR RETRY` increases query robustness by handling transient errors without manual intervention.
It is particularly suitable for xref:subqueries/subqueries-in-transactions.adoc#concurrent-transactions[concurrent transactions], reducing the likelihood of a query failing due to xref:subqueries/subqueries-in-transactions.adoc#deadlocks[deadlocks].
For concurrent transactions, `PROFILE` reports the number of retries.
For more information, see xref:subqueries/subqueries-in-transactions.adoc#concurrency-statistics[Measuring concurrency with `PROFILE`].


.Basic retry with default duration
=====

The below example demonstrates a basic retry scenario.
If a transient error occurs during the creation of a `User` node, the transaction will be retried for the default maximum retry duration (`30` seconds).
If the retry succeeds, the query continues.

If the retry fails after the default duration, the query fails because it behaves like xref:subqueries/subqueries-in-transactions#on-error-fail[`ON ERROR FAIL`] (the default fallback).

.`ON ERROR RETRY`
[source, cypher]
----
UNWIND range(1, 100) AS i
CALL (i) {
    MERGE (u:User {id: i})
    ON CREATE SET u.created = timestamp()
} IN TRANSACTIONS ON ERROR RETRY
----

=====

[[specify-retry-duration]]
==== Specify a maximum retry duration

The default maximum retry duration is `30` seconds.
A new default can be set using link:{neo4j-docs-base-uri}/operations-manual/current/configuration/configuration-settings/#config_dbms.cypher.transactions.default_subquery_retry_timeout[`dbms.cypher.transactions.default_subquery_retry_timeout`].

A maximum retry duration can be specified for individual queries as follows: `ON ERROR RETRY [FOR] <duration> SEC[OND[S]]`, where <duration> is an `INTEGER` or `FLOAT` value representing seconds that is greater than or equal to `0`.
Decimal values are allowed, and the `<duration>` can be set with a parameter.
Note that this `<duration>` overrides the default value.

The duration timer starts when the first retry is scheduled.
As a result, regardless of the specified duration, a minimum of one retry will be attempted.
If the transaction still fails with a transient error, a new attempt with made unless the duration has expired.
For example, a value of `0` (or close to `0`) will result in a retry, but guarantees that only a single retry will be attempted.

.Set a maximum time limit for retries
=====

In this example, the retry duration is explicitly set to `2.5` seconds.
This means that the transaction will be retried until it succeeds or until `2.5` seconds have elapsed.

.`ON ERROR RETRY` with a set duration
[source, cypher]
----
UNWIND range(1, 100) AS i
CALL (i) {
    MERGE (u:User {id: i})
    ON CREATE SET u.created = timestamp()
} IN TRANSACTIONS ON ERROR RETRY FOR 2.5 SECONDS
----

.Parameter
[source, parameters]
----
{
  "duration": 10
}
----

.`ON ERROR RETRY` using a parameter for the duration
[source, cypher]
----
UNWIND range(1, 100) AS i
CALL (i) {
    MERGE (u:User {id: i})
    ON CREATE SET u.created = timestamp()
} IN TRANSACTIONS ON ERROR RETRY FOR $duration SECONDS
----
=====


[[fallback-error-handling]]
==== Fallback error handling options

`ON ERROR RETRY` can be combined with the other xref:subqueries/subqueries-in-transactions.adoc#error-behavior[`ON ERROR` options] via the `THEN` clause to specify a fallback behavior.
The fallback behavior specifies what will happen if a transaction has not succeeded within the time limit.
Specifically:

* `ON ERROR RETRY ... THEN CONTINUE`: the query will ignore recoverable errors and continue with the execution of subsequent inner transactions.
The outer transaction succeeds, and `null` will be returned for any failed inner transactions.
See xref:subqueries/subqueries-in-transactions.adoc#on-error-continue[`ON ERROR CONTINUE`] for more information about this behavior.

* `ON ERROR RETRY ... THEN BREAK`: the query will ignore recoverable errors and stop the execution of subsequent inner transactions.
The outer transaction succeeds, and `null` will be returned for the failed inner transaction and all subsequent ones.
See xref:subqueries/subqueries-in-transactions.adoc#on-error-break[`ON ERROR BREAK`] for more information about this behavior.

* `ON ERROR RETRY ... THEN FAIL` (default): the query will acknowledge a recoverable error and stop the execution of subsequent inner transactions, causing the outer transaction to fail.
See xref:subqueries/subqueries-in-transactions.adoc#on-error-fail[`ON ERROR FAIL`] for more information about this behavior.

[NOTE]
Because `THEN FAIL` is the default fallback option it does not have to be specified.

// tag::tabs[]
[.tabs]

.ON ERROR RETRY THEN CONTINUE
[source,cypher]
----
UNWIND range(1, 100) AS i
CALL (i) {
    MERGE (u:User {id: i})
    ON CREATE SET u.created = timestamp()
} IN TRANSACTIONS ON ERROR RETRY FOR 1 SECOND THEN CONTINUE
----

.ON ERROR RETRY THEN BREAK
[source,cypher]
----
UNWIND range(1, 100) AS i
CALL (i) {
    MERGE (u:User {id: i})
    ON CREATE SET u.created = timestamp()
} IN TRANSACTIONS ON ERROR RETRY FOR 1 SECOND THEN BREAK
----

.ON ERROR RETRY THEN FAIL
[source,cypher]
----
UNWIND range(1, 100) AS i
CALL (i) {
    MERGE (u:User {id: i})
    ON CREATE SET u.created = timestamp()
} IN TRANSACTIONS ON ERROR RETRY FOR 1 SECOND THEN FAIL
----

// end::tabs[]

[[status-report]]
== Status report

Users can also report the execution status of the inner transactions by using `REPORT STATUS AS var`.
This flag is disallowed for `ON ERROR FAIL`. For more information, see xref:subqueries/subqueries-in-transactions.adoc#error-behavior[Error behavior].

After each execution of the inner query finishes (successfully or not), a status value is created that records information about the execution and the transaction that executed it:

* If the inner execution produces one or more rows as output, then a binding to this status value is added to each row, under the selected variable name.
* If the inner execution fails then a single row is produced containing a binding to this status value under the selected variable, and null bindings for all variables that should have been returned by the inner query (if any).

The status value is a map value with the following fields:

* `started`: `true` when the inner transaction was started, `false` otherwise.
* `committed`, `true` when the inner transaction changes were successfully committed, `false` otherwise.
* `transactionId`: the inner transaction id, or `null` if the transaction was not started.
* `errorMessage`, the inner transaction error message, or `null` in case of no error.

Example of reporting status with `ON ERROR CONTINUE`:

.Query
[source, cypher, role=test-result-skip]
----
UNWIND [1, 0, 2, 4] AS i
CALL (i) {
  CREATE (n:Person {num: 100/i}) // Note, fails when i = 0
  RETURN n
} IN TRANSACTIONS
  OF 1 ROW
  ON ERROR CONTINUE
  REPORT STATUS AS s
RETURN n.num, s
----

.Result
[role="queryresult",options="header,footer",cols="1m,4m"]
|===
| n.num | s
| 100     | {"committed": true, "errorMessage": null, "started": true, "transactionId": "neo4j-transaction-835" }
| null    | {"committed": false, "errorMessage": "/ by zero", "started": true, "transactionId": "neo4j-transaction-836" }
| 50      | {"committed": true, "errorMessage": null, "started": true, "transactionId": "neo4j-transaction-837" }
| 25      | {"committed": true, "errorMessage": null, "started": true, "transactionId": "neo4j-transaction-838" }
2+d|Rows: 4
|===

Example of reporting status with `ON ERROR BREAK`:

.Query
[source, cypher]
----
UNWIND [1, 0, 2, 4] AS i
CALL (i) {
  CREATE (n:Person {num: 100/i}) // Note, fails when i = 0
  RETURN n
} IN TRANSACTIONS
  OF 1 ROW
  ON ERROR BREAK
  REPORT STATUS AS s
RETURN n.num, s.started, s.committed, s.errorMessage
----

.Result
[role="queryresult",options="header,footer",cols="4*<m"]
|===
| n.num | s.started | s.committed | s.errorMessage
| 100     | true        | true          | null
| null    | true        | false         | "/ by zero"
| null    | false       | false         | null
| null    | false       | false         | null
4+d|Rows: 4
|===

Reporting status with `ON ERROR FAIL` is disallowed:

.Query
[source, cypher, role=test-fail]
----
UNWIND [1, 0, 2, 4] AS i
CALL (i) {
  CREATE (n:Person {num: 100/i}) // Note, fails when i = 0
  RETURN n
} IN TRANSACTIONS
  OF 1 ROW
  ON ERROR FAIL
  REPORT STATUS AS s
RETURN n.num, s.errorMessage
----

.Error
[source, error, role="noheader"]
----
REPORT STATUS can only be used when specifying ON ERROR CONTINUE or ON ERROR BREAK
----


[[concurrent-transactions]]
== Concurrent transactions

By default, `CALL { ... } IN TRANSACTIONS` is single-threaded; one CPU core is used to sequentially execute batches.

However, `CALL` subqueries can also execute batches in parallel by appending `IN [n] CONCURRENT TRANSACTIONS`, where `n` is a concurrency value used to set the maximum number of transactions that can be executed in parallel.
This allows `CALL` subqueries to utilize multiple CPU cores simultaneously, which can significantly reduce the time required to execute a large, outer transaction.

The concurrency value is optional.
If not specified, a default value based on the amount of available CPU cores will be chosen.
If a negative number is specified (which can only be done through a parameter), the concurrency will be the number of available CPU cores reduced by the absolute value of that number.
To measure the concurrency a query achieves, see xref:subqueries/subqueries-in-transactions.adoc#concurrency-statistics[Measuring concurrency with `PROFILE`].

[NOTE]
Queries using `CONCURRENT TRANSACTIONS` can currently only use the xref:planning-and-tuning/runtimes/concepts.adoc#runtimes-slotted-runtime[slotted runtime].

[NOTE]
When using `CONCURRENT TRANSACTIONS` on a composite database, there is no additional parallelism in the query execution.
See xref:subqueries/subqueries-in-transactions.adoc#composite-databases[CALL subqueries in transactions for composite databases] for more information.

.Load a CSV file in concurrent transactions
====

`CALL { ... } IN CONCURRENT TRANSACTIONS` is particularly suitable for importing data without dependencies.
This example creates `Person` nodes from a unique `tmdbId` value assigned to each person row in the CSV file (444 in total) in 3 concurrent transactions.

.`CALL` subquery run in `CONCURRENT TRANSACTIONS`
// tag::subqueries_in_transactions_concurrent_transactions[]
[source, cypher]
----
LOAD CSV WITH HEADERS FROM 'https://data.neo4j.com/importing-cypher/persons.csv' AS row
CALL (row) {
  CREATE (p:Person {tmdbId: row.person_tmdbId})
  SET p.name = row.name, p.born = row.born
} IN 3 CONCURRENT TRANSACTIONS OF 10 ROWS
RETURN count(*) AS personNodes
----
// end::subqueries_in_transactions_concurrent_transactions[]

.Result
[role="queryresult",options="header,footer",cols="m"]
|===
| personNodes
| 444
1+d| Rows: 1
|===

====

[[non-determinism]]
=== Concurrency and non-deterministic results

`CALL { ... } IN TRANSACTIONS` uses _ordered_ semantics by default, where batches are committed in a sequential row-by-row order.
For example, in `CALL { <I> } IN TRANSACTIONS`, any writes done in the execution of `<I~1~>` must be observed by `<I~2~>`, and so on.

In contrast, `CALL { ... } IN CONCURRENT TRANSACTIONS` uses _concurrent_ semantics, where both the number of rows committed by a particular batch and the order of committed batches is undefined.
That is,  in `CALL { <I> } IN CONCURRENT TRANSACTIONS`, writes committed in the execution of `<I~1~>` may or may not be observed by `<I~2~>`, and so on.

The results of `CALL` subqueries executed in concurrent transactions may, therefore, not be deterministic.
To guarantee deterministic results, ensure that the results of committed batches are not dependent on each other.

[NOTE]
Using `CALL { ... } IN CONCURRENT TRANSACTIONS` can impact xref:subqueries/subqueries-in-transactions.adoc#error-behavior[error behavior.]
Specifically, when using `ON ERROR BREAK` or `ON ERROR FAIL` and one transaction fails, then any concurrent transactions _may_ not be interrupted and rolled back (though subsequent ones would).
This is because no timing guarantees can be given for concurrent transactions.
That is, an ongoing transaction may or may not commit successfully in the time window when the error is being handled.
Use the xref:subqueries/subqueries-in-transactions.adoc#status-report[status report] to determine which batches were committed and which failed or did not start.


[[deadlocks]]
=== Deadlocks

When a write transaction occurs, Neo4j takes locks to preserve data consistency while updating.
For example, when creating or deleting a relationship, a write lock is taken on both the specific relationship and its connected nodes.

A deadlock happens when two transactions are blocked by each other because they are attempting to concurrently modify a node or a relationship that is locked by the other transaction (for more information about locks and deadlocks in Neo4j, see link:{neo4j-docs-base-uri}/operations-manual/current/database-internals/concurrent-data-access/#_locks[Operations Manual -> Concurrent data access].

A deadlock may occur when using `CALL { ... } IN CONCURRENT TRANSACTIONS` if the transactions for two or more batches try to take the same locks in an order that results in a circular dependency between them.
If so, the impacted transactions are always rolled back, and an error is thrown unless the query is appended with one of the following error options:

* xref:subqueries/subqueries-in-transactions.adoc#on-error-continue[`ON ERROR CONTINUE`]
* xref:subqueries/subqueries-in-transactions.adoc#on-error-break[`ON ERROR BREAK`]
* xref:subqueries/subqueries-in-transactions.adoc#on-error-retry[`ON ERROR RETRY`]

The latter is particularly suited for concurrent transactions, because it retries recoverable transient errors with exponential backoff between retries until the xref:subqueries/subqueries-in-transactions.adoc#specify-retry-duration[maximum retry duration] has been reached.

[NOTE]
Deadlock detection and transaction retries can be time-consuming.
When importing data that includes a significant number of relationships to be merged between the same nodes but processed in different batches, increasing the concurrency may not enhance performance.
On the contrary, it could slow down the import process.

.Finding and retrying deadlocked transactions
=====

The following query tries to create `Movie` and `Year` nodes connected by a `RELEASED_IN` relationship.
Note that there are only three different years in the CSV file, meaning that only three `Year` nodes should be created.

.Query with concurrent transaction causing a deadlock
[source, cypher, role=test-fail]
----
LOAD CSV WITH HEADERS FROM 'https://data.neo4j.com/importing-cypher/movies.csv' AS row
CALL (row) {
    MERGE (m:Movie {movieId: row.movieId})
    MERGE (y:Year {year: row.year})
    MERGE (m)-[r:RELEASED_IN]->(y)
} IN 2 CONCURRENT TRANSACTIONS OF 10 ROWS
----

The deadlock occurs because the two transactions are simultaneously trying to lock and merge the same `Year`.

.GQLSTATUS error chain
[role="queryresult",stripes="all",cols="1"]
|===
| link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/50N05/[50N05]: error: general processing exception - deadlock detected. Deadlock detected while trying to acquire locks. See log for more details.
|===

.Query using `ON ERROR CONTINUE` to ignore deadlocks and complete outer transaction
[source, cypher]
----
LOAD CSV WITH HEADERS FROM 'https://data.neo4j.com/importing-cypher/movies.csv' AS row
CALL (row) {
   MERGE (m:Movie {movieId: row.movieId})
   MERGE (y:Year {year: row.year})
   MERGE (m)-[r:RELEASED_IN]->(y)
} IN 2 CONCURRENT TRANSACTIONS OF 10 ROWS ON ERROR CONTINUE REPORT STATUS as status
WITH status
WHERE status.errorMessage IS NOT NULL
RETURN status.transactionId AS transaction, status.committed AS commitStatus, status.errorMessage AS errorMessage
----

.Result
[source, "queryresult"]
----
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| transaction             | commitStatus | errorMessage                                                                                                                                                                                                                                                                                                                                                     |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "neo4j-transaction-486" | false        | "ForsetiClient[transactionId=486, clientId=8] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=485, clientId=13]} on NODE_RELATIONSHIP_GROUP_DELETE(18) because holders of that lock are waiting for ForsetiClient[transactionId=486, clientId=8].                                                                                                  |
|                         |              \  Wait list:ExclusiveLock[                                                                                                                                                                                                                                                                                                                                        |
|                         |              \ Client[485] waits for [ForsetiClient[transactionId=486, clientId=8]]]"                                                                                                                                                                                                                                                                                           |
| "neo4j-transaction-486" | false        | "ForsetiClient[transactionId=486, clientId=8] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=485, clientId=13]} on NODE_RELATIONSHIP_GROUP_DELETE(18) because holders of that lock are waiting for ForsetiClient[transactionId=486, clientId=8].                                                                                                  |
|                         |              \  Wait list:ExclusiveLock[                                                                                                                                                                                                                                                                                                                                        |
|                         |              \ Client[485] waits for [ForsetiClient[transactionId=486, clientId=8]]]"                                                                                                                                                                                                                                                                                           |
| "neo4j-transaction-486" | false        | "ForsetiClient[transactionId=486, clientId=8] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=485, clientId=13]} on NODE_RELATIONSHIP_GROUP_DELETE(18) because holders of that lock are waiting for ForsetiClient[transactionId=486, clientId=8].                                                                                                  |
|                         |              \  Wait list:ExclusiveLock[                                                                                                                                                                                                                                                                                                                                        |
|                         |              \ Client[485] waits for [ForsetiClient[transactionId=486, clientId=8]]]"                                                                                                                                                                                                                                                                                           |
| "neo4j-transaction-486" | false        | "ForsetiClient[transactionId=486, clientId=8] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=485, clientId=13]} on NODE_RELATIONSHIP_GROUP_DELETE(18) because holders of that lock are waiting for ForsetiClient[transactionId=486, clientId=8].                                                                                                  |
|                         |              \  Wait list:ExclusiveLock[                                                                                                                                                                                                                                                                                                                                        |
|                         |              \ Client[485] waits for [ForsetiClient[transactionId=486, clientId=8]]]"                                                                                                                                                                                                                                                                                           |
| "neo4j-transaction-486" | false        | "ForsetiClient[transactionId=486, clientId=8] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=485, clientId=13]} on NODE_RELATIONSHIP_GROUP_DELETE(18) because holders of that lock are waiting for ForsetiClient[transactionId=486, clientId=8].                                                                                                  |
|                         |              \  Wait list:ExclusiveLock[                                                                                                                                                                                                                                                                                                                                        |
|                         |              \ Client[485] waits for [ForsetiClient[transactionId=486, clientId=8]]]"                                                                                                                                                                                                                                                                                           |
| "neo4j-transaction-486" | false        | "ForsetiClient[transactionId=486, clientId=8] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=485, clientId=13]} on NODE_RELATIONSHIP_GROUP_DELETE(18) because holders of that lock are waiting for ForsetiClient[transactionId=486, clientId=8].                                                                                                  |
|                         |              \  Wait list:ExclusiveLock[                                                                                                                                                                                                                                                                                                                                        |
|                         |              \ Client[485] waits for [ForsetiClient[transactionId=486, clientId=8]]]"                                                                                                                                                                                                                                                                                           |
| "neo4j-transaction-486" | false        | "ForsetiClient[transactionId=486, clientId=8] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=485, clientId=13]} on NODE_RELATIONSHIP_GROUP_DELETE(18) because holders of that lock are waiting for ForsetiClient[transactionId=486, clientId=8].                                                                                                  |
|                         |              \  Wait list:ExclusiveLock[                                                                                                                                                                                                                                                                                                                                        |
|                         |              \ Client[485] waits for [ForsetiClient[transactionId=486, clientId=8]]]"                                                                                                                                                                                                                                                                                           |
| "neo4j-transaction-486" | false        | "ForsetiClient[transactionId=486, clientId=8] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=485, clientId=13]} on NODE_RELATIONSHIP_GROUP_DELETE(18) because holders of that lock are waiting for ForsetiClient[transactionId=486, clientId=8].                                                                                                  |
|                         |              \  Wait list:ExclusiveLock[                                                                                                                                                                                                                                                                                                                                        |
|                         |              \ Client[485] waits for [ForsetiClient[transactionId=486, clientId=8]]]"                                                                                                                                                                                                                                                                                           |
| "neo4j-transaction-486" | false        | "ForsetiClient[transactionId=486, clientId=8] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=485, clientId=13]} on NODE_RELATIONSHIP_GROUP_DELETE(18) because holders of that lock are waiting for ForsetiClient[transactionId=486, clientId=8].                                                                                                  |
|                         |              \  Wait list:ExclusiveLock[                                                                                                                                                                                                                                                                                                                                        |
|                         |              \ Client[485] waits for [ForsetiClient[transactionId=486, clientId=8]]]"                                                                                                                                                                                                                                                                                           |
| "neo4j-transaction-486" | false        | "ForsetiClient[transactionId=486, clientId=8] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=485, clientId=13]} on NODE_RELATIONSHIP_GROUP_DELETE(18) because holders of that lock are waiting for ForsetiClient[transactionId=486, clientId=8].                                                                                                  |
|                         |              \  Wait list:ExclusiveLock[                                                                                                                                                                                                                                                                                                                                        |
|                         |              \ Client[485] waits for [ForsetiClient[transactionId=486, clientId=8]]]"                                                                                                                                                                                                                                                                                           |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
----

These are transient errors, meaning that re-running the transactions may be successful.
To retry the any failed inner transactions, use the error option `ON ERROR RETRY`, which retries any failing transactions until the maximum retry duration has been reached.

The following query uses `ON ERROR RETRY ... THEN CONTINUE` to retry the above query for a maximum of `3` seconds and then continue the execution of subsequent inner transactions by ignoring any recoverable errors.

.Query using `ON ERROR RETRY ... THEN CONTINUE` to retry deadlocked inner transactions and complete outer transaction
// tag::subqueries_in_transactions_deadlock_example[]
[source, cypher]
----
LOAD CSV WITH HEADERS FROM 'https://data.neo4j.com/importing-cypher/movies.csv' AS row
CALL (row) {
   MERGE (m:Movie {movieId: row.movieId})
   MERGE (y:Year {year: row.year})
   MERGE (m)-[r:RELEASED_IN]->(y)
} IN 2 CONCURRENT TRANSACTIONS OF 10 ROWS ON ERROR RETRY FOR 3 SECONDS THEN CONTINUE REPORT STATUS AS status
RETURN status.transactionId as transaction, status.committed AS successfulTransaction
----
// end::subqueries_in_transactions_deadlock_example[]

The result shows that all transactions are now successful:

.Result
[source, "queryresult"]
----
+-------------------------------------------------+
| transaction             | successfulTransaction |
+-------------------------------------------------+
| "neo4j-transaction-500" | true                  |
| "neo4j-transaction-500" | true                  |
| "neo4j-transaction-500" | true                  |
| "neo4j-transaction-500" | true                  |
| "neo4j-transaction-500" | true                  |
| "neo4j-transaction-500" | true                  |
| "neo4j-transaction-500" | true                  |
| "neo4j-transaction-500" | true                  |
| "neo4j-transaction-500" | true                  |
| "neo4j-transaction-500" | true                  |
| "neo4j-transaction-501" | true                  |
| "neo4j-transaction-501" | true                  |
| "neo4j-transaction-501" | true                  |
| "neo4j-transaction-501" | true                  |
| "neo4j-transaction-501" | true                  |
| "neo4j-transaction-501" | true                  |
| "neo4j-transaction-501" | true                  |
| "neo4j-transaction-501" | true                  |
| "neo4j-transaction-501" | true                  |
| "neo4j-transaction-501" | true                  |
| "neo4j-transaction-502" | true                  |
| "neo4j-transaction-502" | true                  |
| "neo4j-transaction-502" | true                  |
| "neo4j-transaction-502" | true                  |
| "neo4j-transaction-502" | true                  |
| "neo4j-transaction-502" | true                  |
| "neo4j-transaction-502" | true                  |
| "neo4j-transaction-502" | true                  |
| "neo4j-transaction-502" | true                  |
| "neo4j-transaction-502" | true                  |
| "neo4j-transaction-504" | true                  |
| "neo4j-transaction-504" | true                  |
| "neo4j-transaction-504" | true                  |
| "neo4j-transaction-504" | true                  |
| "neo4j-transaction-504" | true                  |
| "neo4j-transaction-504" | true                  |
| "neo4j-transaction-504" | true                  |
| "neo4j-transaction-504" | true                  |
| "neo4j-transaction-504" | true                  |
| "neo4j-transaction-504" | true                  |
| "neo4j-transaction-503" | true                  |
| "neo4j-transaction-503" | true                  |
| "neo4j-transaction-503" | true                  |
| "neo4j-transaction-503" | true                  |
| "neo4j-transaction-503" | true                  |
| "neo4j-transaction-503" | true                  |
| "neo4j-transaction-503" | true                  |
| "neo4j-transaction-503" | true                  |
| "neo4j-transaction-503" | true                  |
| "neo4j-transaction-503" | true                  |
| "neo4j-transaction-505" | true                  |
| "neo4j-transaction-505" | true                  |
| "neo4j-transaction-505" | true                  |
| "neo4j-transaction-505" | true                  |
| "neo4j-transaction-505" | true                  |
| "neo4j-transaction-505" | true                  |
| "neo4j-transaction-505" | true                  |
| "neo4j-transaction-505" | true                  |
| "neo4j-transaction-505" | true                  |
| "neo4j-transaction-505" | true                  |
| "neo4j-transaction-506" | true                  |
| "neo4j-transaction-506" | true                  |
| "neo4j-transaction-506" | true                  |
| "neo4j-transaction-506" | true                  |
| "neo4j-transaction-506" | true                  |
| "neo4j-transaction-506" | true                  |
| "neo4j-transaction-506" | true                  |
| "neo4j-transaction-506" | true                  |
| "neo4j-transaction-506" | true                  |
| "neo4j-transaction-506" | true                  |
| "neo4j-transaction-507" | true                  |
| "neo4j-transaction-507" | true                  |
| "neo4j-transaction-507" | true                  |
| "neo4j-transaction-507" | true                  |
| "neo4j-transaction-507" | true                  |
| "neo4j-transaction-507" | true                  |
| "neo4j-transaction-507" | true                  |
| "neo4j-transaction-507" | true                  |
| "neo4j-transaction-507" | true                  |
| "neo4j-transaction-507" | true                  |
| "neo4j-transaction-508" | true                  |
| "neo4j-transaction-508" | true                  |
| "neo4j-transaction-508" | true                  |
| "neo4j-transaction-508" | true                  |
| "neo4j-transaction-508" | true                  |
| "neo4j-transaction-508" | true                  |
| "neo4j-transaction-508" | true                  |
| "neo4j-transaction-508" | true                  |
| "neo4j-transaction-508" | true                  |
| "neo4j-transaction-508" | true                  |
| "neo4j-transaction-509" | true                  |
| "neo4j-transaction-509" | true                  |
| "neo4j-transaction-509" | true                  |
+-------------------------------------------------+
----

=====

Deadlock resolution and transaction retries are time-consuming, however.
The preferred strategy for dealing with deadlocks should instead be one of prevention.


////
[source, cypher, role=test-setup]
----
MATCH (n)
DETACH DELETE n;
----
////

[role=label--new-Neo4j-2026.06 label--cypher-25-only]
[[disjoint-by]]
=== Batch scheduling and deadlock prevention with `DISJOINT BY`

Batch scheduling prevents deadlocks in concurrent transactions by ensuring that batches sharing resources never run at the same time, while batches that do not share resources run concurrently.
This can be particularly useful when importing relationships.
To check how much batch scheduling limits the concurrency of a query, see xref:subqueries/subqueries-in-transactions.adoc#concurrency-statistics[Measuring concurrency with `PROFILE`].

The default batch scheduling strategy for all queries run against a database can be configured with the link:{neo4j-docs-base-uri}/operations-manual/current/configuration/configuration-settings/#config_dbms.cypher.transactions.default_subquery_batch_strategy[`dbms.cypher.transactions.default_subquery_batch_strategy`] setting.
Accepted values for this setting are `NONE` (no scheduling), `AUTO` (automatic inference), and `DEFAULT` (the product default, currently `NONE`).

Alternatively, `DISJOINT BY` can be added to individual `CALL { ... } IN CONCURRENT TRANSACTIONS` statements to control batch scheduling at the query level.

There are three forms of `DISJOINT BY`:

* xref:subqueries/subqueries-in-transactions.adoc#lock-expressions[`DISJOINT BY (<expr>, ...)`]: declares lock-prone resources explicitly per row.
* xref:subqueries/subqueries-in-transactions.adoc#automatic-inference[`DISJOINT BY AUTO`]: the runtime infers lock-prone resources automatically.
* xref:subqueries/subqueries-in-transactions.adoc#disabled-inference[`DISJOINT BY NONE`]: disables scheduling explicitly, overriding any database-level default.

[NOTE]
====

* `DISJOINT BY` overrides the database-wide setting.
For example, if `dbms.cypher.transactions.default_subquery_batch_strategy` is set to `AUTO`, a query with `DISJOINT BY NONE` will run without batch scheduling.

* `DISJOINT BY` can only be run together with concurrent transactions; it is not valid in a regular `CALL { ... } IN TRANSACTIONS` subquery.

====

[[lock-expressions]]
==== Declaring lock expressions with `DISJOINT BY`

`DISJOINT BY (<expr>, ...)` allows you to declare the expressions identifying locked resources for a `CALL { ... } IN CONCURRENT TRANSACTIONS` statement.

The expressions must use only variables imported from the outer query, since they are evaluated before the subquery runs; for example, `elementId(n)` or `n.id`, where `n` is an imported variable.
They act as constraints on batch composition: the xref:planning-and-tuning/runtimes/index.adoc[runtime] ensures that no two concurrent batches share a value for any of the declared expressions.

For example, given `DISJOINT BY (n.id, n.category)`, two batches are scheduled concurrently only if they share no values for either `n.id` or `n.category`.
Any row in one batch that shares a value for either expression with a row in another batch causes those batches to be run sequentially.
With a batch size of `2` (i.e. `IN CONCURRENT TRANSACTIONS OF 2 ROWS DISJOINT BY (n.id, n.category)`), the batching and execution could look something like this:

.Simplified batch scheduling model
[source]
----
row 1: id=1, category=A
row 2: id=2, category=A
row 3: id=3, category=A
row 4: id=4, category=A
row 5: id=5, category=B
row 6: id=6, category=B

Batches:
  Batch A: rows 1, 2  (category=A)
  Batch B: rows 3, 4  (category=A)
  Batch C: rows 5, 6  (category=B)

Execution:
  Batch A ------->
                  Batch B -------->
  Batch C ------------------------>
----

Batch A and Batch B share `category=A` and are therefore serialized; Batch C shares no values with either and runs concurrently throughout.

No automatic lock expression inference is performed when using `DISJOINT BY (<expr>, ...)`; the supplied list is the entire lock expression set for that subquery.

.`DISJOINT BY (<expr>, ...)`: importing nodes and relationships
====

This example imports movies and their release years from a CSV file, creating `Movie` and `Year` nodes and `RELEASED_IN` relationships between them.
For this import, xref:schema/constraints/create-constraints.adoc#create-key-constraints[key constraints] are in place to ensure the existence of unique `movieId` properties for `Movie` nodes and `year` properties for `Year` nodes, and to provide index-backed lookups for these properties (key constraints are xref:schema/constraints/create-constraints.adoc#constraints-and-backing-indexes[backed by indexes]).

With these constraints and indexes, two concurrent batches attempting to `MERGE` the same `Movie` or `Year` node simultaneously will contend on the key constraint lock, causing a deadlock.

.Create node key constraints
[source, cypher]
----
CREATE CONSTRAINT movie_id IF NOT EXISTS FOR (m:Movie) REQUIRE m.movieId IS KEY;
CREATE CONSTRAINT year IF NOT EXISTS FOR (y:Year) REQUIRE y.year IS KEY;
----

.Import with explicit lock expressions
// tag::subqueries_in_transactions_deadlock_prevention_disjoint_by_lock_expression[]
[source, cypher]
----
LOAD CSV WITH HEADERS FROM 'https://data.neo4j.com/importing-cypher/movies.csv' AS line
CALL (line) {
  MERGE (m:Movie {movieId: line.movieId})
  MERGE (y:Year {year: line.year})
  MERGE (m)-[:RELEASED_IN]->(y)
} IN CONCURRENT TRANSACTIONS
  DISJOINT BY (line.year, line.movieId)
  ON ERROR RETRY THEN CONTINUE
----
// end::subqueries_in_transactions_deadlock_prevention_disjoint_by_lock_expression[]

`DISJOINT BY (line.year, line.movieId)` declares that `line.year` and `line.movieId` identify the locked resources for each batch.

`ON ERROR RETRY THEN CONTINUE` provides a fallback for transient errors.

====


[[automatic-inference]]
==== Automatic lock inference with `DISJOINT BY AUTO`

`DISJOINT BY AUTO` instructs the runtime to infer lock expressions automatically from the subquery body, without requiring the user to declare them explicitly.
This is useful when the locked resources are straightforward to infer statically; for example, `MERGE` patterns on uniquely constrained properties.
Indexes on the merged properties are required in order for `DISJOINT BY AUTO` to infer locking expressions.
If the runtime cannot infer any lock expressions, the subquery executes with no scheduling restriction.

To see which lock expressions (if any) were inferred by the planner, prepend the statement with xref:planning-and-tuning/execution-plans.adoc#reading-explain-and-profile-query-plans[`EXPLAIN`].

.`DISJOINT BY AUTO`: importing actors and movies
====

This example imports actors and their roles from a CSV file, creating `Person` and `Movie` nodes and `ACTS_IN` relationships between them.
With key constraints (and backing indexes) on the `name` properties of `Person` nodes and the `title` properties of `Movie` nodes, the runtime infers the lock expressions `(line.person, line.movie)` automatically from the `MERGE` patterns as can be seen in the `TransactionForEach` operator `Details` column in the query plan produced by prepending the statement with `EXPLAIN` (the same expressions a user would write manually with `DISJOINT BY (line.person, line.movie)`).

////
[source, cypher, role=test-setup]
----
MATCH (n)
DETACH DELETE n;
DROP CONSTRAINT movie_id;
----
////

.Create node key constraints
[source, cypher]
----
CREATE CONSTRAINT person_name IF NOT EXISTS FOR (p:Person) REQUIRE p.name IS KEY;
CREATE CONSTRAINT movie_title IF NOT EXISTS FOR (m:Movie) REQUIRE m.title IS KEY;
----

.Import with automatic lock inference
[source, cypher]
----
EXPLAIN
LOAD CSV WITH HEADERS FROM 'https://data.neo4j.com/intro/movies/actors.csv' AS line
CALL (line) {
  MERGE (p:Person {name: line.person})
  MERGE (m:Movie  {title: line.movie})
  CREATE (p)-[:ACTS_IN {role: line.roles}]->(m)
} IN CONCURRENT TRANSACTIONS
  DISJOINT BY AUTO
----

.Query plan
[role="queryplan"]
----
+----------------------+----+---------------------------------------------------------------------------------------------+----------------+
| Operator             | Id | Details                                                                                     | Estimated Rows |
+----------------------+----+---------------------------------------------------------------------------------------------+----------------+
| +ProduceResults      |  0 |                                                                                             |             10 |
| |                    +----+---------------------------------------------------------------------------------------------+----------------+
| +EmptyResult         |  1 |                                                                                             |             10 |
| |                    +----+---------------------------------------------------------------------------------------------+----------------+
| +TransactionForeach  |  2 | IN CONCURRENT TRANSACTIONS OF 1000 ROWS DISJOINT BY (line.person, line.movie) ON ERROR FAIL |             10 |
| |\                   +----+---------------------------------------------------------------------------------------------+----------------+
| | +Create            |  3 | (p)-[anon_0:ACTS_IN {role: line.roles}]->(m)                                                |             10 |
| | |                  +----+---------------------------------------------------------------------------------------------+----------------+
| | +Apply             |  4 |                                                                                             |             10 |
| | |\                 +----+---------------------------------------------------------------------------------------------+----------------+
| | | +MergeUniqueNode |  5 | UNIQUE m:Movie(title) WHERE title = line.movie,                                             |             10 |
| | |                  +----+---------------------------------------------------------------------------------------------+----------------+
| | +MergeUniqueNode   |  6 | UNIQUE p:Person(name) WHERE name = line.person,                                             |             10 |
| |                    +----+---------------------------------------------------------------------------------------------+----------------+
| +LoadCSV             |  7 | line                                                                                        |             10 |
+----------------------+----+---------------------------------------------------------------------------------------------+----------------+
----

====

[[disabled-inference]]
==== Disabling batch scheduling with `DISJOINT BY NONE`

`DISJOINT BY NONE` explicitly disables batch scheduling, overriding `dbms.cypher.transactions.default_subquery_batch_strategy`.

////
[source, cypher, role=test-setup]
----
MATCH (n)
DETACH DELETE n;
DROP CONSTRAINT movie_title;
----
////

.`DISJOINT BY NONE`: importing independent nodes
====

This example imports movies from a CSV file, creating `Movie` nodes.
With a key constraint on the `movieId` property of `Movie` nodes, each row is guaranteed to operate on a distinct node; concurrent batches cannot contend on the same resource, making batch scheduling unnecessary.

.Importing nodes without batch scheduling
[source, cypher]
----
LOAD CSV WITH HEADERS FROM 'https://data.neo4j.com/importing-cypher/movies.csv' AS line
CALL (line) {
  MERGE (m:Movie {movieId: line.movieId})
} IN CONCURRENT TRANSACTIONS
  DISJOINT BY NONE
----

====
[[task-division]]
=== Deadlock prevention by task division

Deadlock prevention can also be achieved by dividing a task into two distinct subqueries: a data-independent subquery run in parallel with maximum concurrency, and a data-dependent subquery executed serially (i.e.  one transaction at a time) to avoid deadlocks.
In the below example, nodes and properties are created in a concurrent subquery, while the relationships connecting those nodes are created in a serial subquery.
This method benefits from the performance of concurrent transactions while avoiding deadlocks.

.Avoiding deadlocks by dividing an import task into a data-independent concurrent subquery followed by a data-dependent serial subquery
// tag::subqueries_in_transactions_deadlock_prevention_task_division[]
[source, cypher]
----
LOAD CSV WITH HEADERS FROM 'https://data.neo4j.com/importing-cypher/movies.csv' AS row
CALL (row) {
   MERGE (m:Movie {movieId: row.movieId})
   MERGE (y:Year {year: row.year})
   RETURN m, y
} IN CONCURRENT TRANSACTIONS OF 10 ROWS ON ERROR RETRY THEN CONTINUE REPORT STATUS AS nodeStatus
CALL (m, y) {
   MERGE (m)-[r:RELEASED_IN]->(y)
} IN TRANSACTIONS OF 10 ROWS ON ERROR RETRY THEN CONTINUE REPORT STATUS AS relationshipStatus
RETURN nodeStatus.transactionId as nodeTransaction,
       nodeStatus.committed AS successfulNodeTransaction,
       relationshipStatus.transactionId as relationshipTransaction,
       relationshipStatus.committed AS successfulRelationshipTransaction
----
// end::subqueries_in_transactions_deadlock_prevention_task_division[]

[role=label--new-Neo4j-2026.10]
[[concurrency-statistics]]
=== Measuring concurrency with `PROFILE`

The concurrency value in `IN [n] CONCURRENT TRANSACTIONS` sets the maximum number of batches that can run at the same time.
The concurrency a query actually achieves can be lower.
For example, the input rows may be produced too slowly to keep all transactions busy, or xref:subqueries/subqueries-in-transactions.adoc#disjoint-by[batch scheduling with `DISJOINT BY`] may hold back batches that conflict with batches already running.

To see how much concurrency a query achieved, and what limited it, prepend the query with xref:planning-and-tuning/execution-plans.adoc#reading-explain-and-profile-query-plans[`PROFILE`].
The xref:planning-and-tuning/operators/operators-detail.adoc#query-plan-transaction-apply[`TransactionApply`] or xref:planning-and-tuning/operators/operators-detail.adoc#query-plan-transaction-foreach[`TransactionForeach`] operator that runs the concurrent transactions then records concurrency statistics.
The query plan shows the peak and average number of batches running at the same time in the xref:planning-and-tuning/execution-plans.adoc#query-plan-table-columns[`Concurrency` column], for example `peak 4 / avg 3.64`.
The average shows how well the concurrency was sustained.

The `Concurrency` column shows only the peak and the average.
The complete set of statistics is included in the profiled plan returned to drivers and the HTTP API, as a map in the `concurrent-transactions` argument of the operator.
Statistics are only recorded for `IN CONCURRENT TRANSACTIONS`, not for `IN TRANSACTIONS`.

The statistics follow each batch through two states:

* _Queued_: the batch is complete and waiting to start, because the concurrency limit is reached or because the batch conflicts with a running batch.
* _Running_: the batch is being executed in its inner transaction, until that transaction has committed or rolled back.

A batch that is retried with xref:subqueries/subqueries-in-transactions.adoc#on-error-retry[`ON ERROR RETRY`] passes through both states again, and each attempt is counted separately.
The delay between retry attempts is not counted as queued time.

.Concurrency statistics
[cols="2m,5a", options="header"]
|===
| Statistic | Description

| concurrencyLimit
| The maximum number of batches allowed to run at the same time.
This is the concurrency value `n` of `IN [n] CONCURRENT TRANSACTIONS`, resolved to an actual number if `n` is omitted or negative.

| peakConcurrency
| The highest number of batches running at the same time.

| avgConcurrency
| The time-weighted average number of batches running at the same time, measured from when the first batch started until the last batch finished.

| peakQueuedBatches
| The highest number of batches queued at the same time.

| avgQueuedBatches
| The time-weighted average number of queued batches, measured from when the first batch was queued until the last batch finished.

| peakStartGapNanos
| The longest time, in nanoseconds, that a batch spent queued before it started running.

| avgStartGapNanos
| The average time, in nanoseconds, that a batch spent queued before it started running.

| batchesQueued
| The number of batch attempts that were queued.
With `DISJOINT BY`, batch scheduling can start a batch before it is full, so this can be higher than the number of rows divided by the batch size.

| batchesStarted
| The number of batch attempts that started running.
This is lower than `batchesQueued` if the query stopped before all queued batches had run, for example because of an error.

| innerTransactionsStarted
| The number of inner transactions that were started.

| innerTransactionsCommitted
| The number of inner transactions that were committed successfully.
The difference from `innerTransactionsStarted` is the number of inner transactions that failed and were rolled back.

| retries
| The number of times that a failed batch was scheduled to run again by `ON ERROR RETRY`.
A retry is counted when it is scheduled, even if the query ends before the retried batch runs.
|===

Read the statistics against `concurrencyLimit`:

* *`avgConcurrency` close to `concurrencyLimit`*: the transactions were busy almost all the time.
If `avgQueuedBatches` is also high, a higher concurrency value may make the query faster if CPU cores are available.
* *Low `avgConcurrency` and `avgQueuedBatches` close to `0`*: batches were not produced fast enough to keep the transactions busy.
The bottleneck is the part of the query that produces the input rows, for example `LOAD CSV`.
* *Low `avgConcurrency` and high `avgQueuedBatches`*: batches were ready but could not start.
This happens when many batches share values for the `DISJOINT BY` expressions, because such batches cannot run at the same time, or when the part of the query after the subquery consumes the returned rows too slowly for new batches to be started.
* *High `retries`*: many batches failed with transient errors, such as xref:subqueries/subqueries-in-transactions.adoc#deadlocks[deadlocks], and were run again.
xref:subqueries/subqueries-in-transactions.adoc#disjoint-by[Batch scheduling with `DISJOINT BY`] can prevent deadlocks between concurrent batches.

.Measure the concurrency of an import with `PROFILE`
====

This example creates 50,000 `TRANSFER` relationships between 1,000 `Account` nodes in batches of 100 rows, with 4 concurrent transactions.
Because many rows refer to the same accounts, `DISJOINT BY (sourceId, targetId)` ensures that batches that share an account never run at the same time.

.Create a key constraint
[source, cypher]
----
CREATE CONSTRAINT account_id IF NOT EXISTS FOR (a:Account) REQUIRE a.id IS KEY
----

.Profile a concurrent import
[source, cypher]
----
PROFILE
UNWIND range(1, 50000) AS i
WITH i, i % 1000 AS sourceId, (i * 7) % 1000 AS targetId
CALL (i, sourceId, targetId) {
  MERGE (a:Account {id: sourceId})
  MERGE (b:Account {id: targetId})
  CREATE (a)-[:TRANSFER {seq: i}]->(b)
} IN 4 CONCURRENT TRANSACTIONS OF 100 ROWS
  DISJOINT BY (sourceId, targetId)
  ON ERROR RETRY
----

.Query plan
[role="queryplan", subs="attributes+"]
----
Cypher 25

Planner COST

Runtime SLOTTED

Runtime version {neo4j-version}

+----------------------+----+------------------------------------------------------------------------------------------------------+----------------+-------+---------+----------------+------------------------+-------------------+
| Operator             | Id | Details                                                                                              | Estimated Rows | Rows  | DB Hits | Memory (Bytes) | Page Cache Hits/Misses | Concurrency       |
+----------------------+----+------------------------------------------------------------------------------------------------------+----------------+-------+---------+----------------+------------------------+-------------------+
| +ProduceResults      |  0 |                                                                                                      |             10 |     0 |       0 |              0 |                    0/0 |                   |
| |                    +----+------------------------------------------------------------------------------------------------------+----------------+-------+---------+----------------+------------------------+-------------------+
| +EmptyResult         |  1 |                                                                                                      |             10 |     0 |       0 |                |                    0/0 |                   |
| |                    +----+------------------------------------------------------------------------------------------------------+----------------+-------+---------+----------------+------------------------+-------------------+
| +TransactionForeach  |  2 | IN $autoint_6 CONCURRENT TRANSACTIONS OF $autoint_5 ROWS DISJOINT BY (sourceId, targetId) ON ERROR R |             10 | 50000 |       0 |         661416 |               297433/4 | peak 4 / avg 3.64 |
| |                    |    | ETRY THEN FAIL                                                                                       |                |       |         |                |                        |                   |
| |\                   +----+------------------------------------------------------------------------------------------------------+----------------+-------+---------+----------------+------------------------+-------------------+
| | +Create            |  3 | (a)-[anon_0:TRANSFER {seq: i}]->(b)                                                                  |             10 | 50000 |  150000 |                |               193715/0 |                   |
| | |                  +----+------------------------------------------------------------------------------------------------------+----------------+-------+---------+----------------+------------------------+-------------------+
| | +Apply             |  4 |                                                                                                      |             10 | 50000 |       0 |                |                    0/0 |                   |
| | |\                 +----+------------------------------------------------------------------------------------------------------+----------------+-------+---------+----------------+------------------------+-------------------+
| | | +MergeUniqueNode |  5 | UNIQUE b:Account(id) WHERE id = targetId,                                                            |             10 | 50000 |  100000 |                |               100384/0 |                   |
| | |                  +----+------------------------------------------------------------------------------------------------------+----------------+-------+---------+----------------+------------------------+-------------------+
| | +Apply             |  6 |                                                                                                      |             10 | 50000 |       0 |                |                    0/0 |                   |
| | |\                 +----+------------------------------------------------------------------------------------------------------+----------------+-------+---------+----------------+------------------------+-------------------+
| | | +MergeUniqueNode |  7 | UNIQUE a:Account(id) WHERE id = sourceId,                                                            |             10 | 50000 |  100000 |                |               100408/0 |                   |
| | |                  +----+------------------------------------------------------------------------------------------------------+----------------+-------+---------+----------------+------------------------+-------------------+
| | +Argument          |  8 | i, sourceId, targetId                                                                                |             10 | 50000 |       0 |                |                    0/0 |                   |
| |                    +----+------------------------------------------------------------------------------------------------------+----------------+-------+---------+----------------+------------------------+-------------------+
| +Projection          |  9 | i % $autoint_2 AS sourceId, (i * $autoint_3) % $autoint_4 AS targetId                                |             10 | 50000 |       0 |                |                    0/0 |                   |
| |                    +----+------------------------------------------------------------------------------------------------------+----------------+-------+---------+----------------+------------------------+-------------------+
| +Unwind              | 10 | range($autoint_0, $autoint_1) AS i                                                                   |             10 | 50000 |       0 |                |                    0/0 |                   |
+----------------------+----+------------------------------------------------------------------------------------------------------+----------------+-------+---------+----------------+------------------------+-------------------+

Total database accesses: 350000, total allocated memory: 2883584
----

The `Concurrency` column of the `TransactionForeach` operator shows `peak 4 / avg 3.64`: at some point all four transactions were running, and on average 3.64 batches ran at the same time.
The query therefore stayed close to its concurrency limit of `4` for most of its execution, and batch scheduling did not noticeably restrict it.
The exact values vary between runs.

====

[[restrictions]]
== Restrictions

These are the restrictions on queries that use `CALL { ... } IN TRANSACTIONS`:

* A nested `CALL { ... } IN TRANSACTIONS` inside a `CALL { ... }` clause is not supported.
* A `CALL { ... } IN TRANSACTIONS` in a `UNION` is not supported.
* A `CALL { ... } IN TRANSACTIONS` after a write clause is not supported, unless that write clause is inside a `CALL { ... } IN TRANSACTIONS`.


[[further-reading]]
== Further reading

* link:https://medium.com/neo4j/introducing-concurrent-writes-to-cypher-subqueries-5102198931ab[Neo4j Developer Blog: Introducing Concurrent Writes to Cypher Subqueries]
