[[administration-databases]]
= Databases
:description: This section explains how to use Cypher to manage Neo4j databases: creating, deleting, starting and stopping individual databases within a single server. 


* xref:administration/databases.adoc#administration-databases-introduction[Introduction]
* xref:administration/databases.adoc#administration-databases-show-databases[Listing databases]
* xref:administration/databases.adoc#administration-databases-create-database[Creating databases]
* xref:administration/databases.adoc#administration-databases-stop-database[Stopping databases]
* xref:administration/databases.adoc#administration-databases-start-database[Starting databases]
* xref:administration/databases.adoc#administration-databases-drop-database[Deleting databases]


[[administration-databases-introduction]]
== Introduction

Neo4j allows the same server to manage multiple databases. The metadata for these databases,
including the associated security model, is maintained in a special database called the `system` database.
All multi-database administrative commands need to be executing against the `system` database.

[[administration-databases-show-databases]]
== Listing databases

There are three different commands for listing databases. Listing all databases, listing a particular database or listing the default database.

All available databases can be seen using the command `SHOW DATABASES`.


.Query
[source, cypher]
----
SHOW DATABASES
----

.Result
[role="queryresult",options="header,footer",cols="7*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+ | +default+
| +"neo4j"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +true+
| +"system"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+
7+d|Rows: 2
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
SHOW DATABASES
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Note that the results of this command are filtered according to the `ACCESS` privileges the user has.
However, a user with `CREATE/DROP DATABASE` or `DATABASE MANAGEMENT` privileges can see all databases regardless of their `ACCESS` privileges.
If a user has not been granted `ACCESS` privilege to any databases, the command can still be executed but will only return the `system` database, which is always visible.


====

A particular database can be seen using the command `SHOW DATABASE name`.


.Query
[source, cypher]
----
SHOW DATABASE system
----

.Result
[role="queryresult",options="header,footer",cols="7*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+ | +default+
| +"system"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+
7+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
SHOW DATABASE system
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The default database can be seen using the command `SHOW DEFAULT DATABASE`.


.Query
[source, cypher]
----
SHOW DEFAULT DATABASE
----

.Result
[role="queryresult",options="header,footer",cols="6*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+
| +"neo4j"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+
6+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
SHOW DEFAULT DATABASE
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Note that for failed databases, the `currentStatus` and `requestedStatus` are different.
This often implies an error, but **does not always**.
For example, a database may take a while to transition from `offline` to `online` due to performing recovery.
Or, during normal operation a database's `currentStatus` may be transiently different from its `requestedStatus` due to a necessary automatic process, such as one Neo4j instance copying store files from another.
The possible statuses are `initial`, `online`, `offline`, `store copying` and `unknown`.


====

[role=enterprise-edition]
[[administration-databases-create-database]]
== Creating databases

Databases can be created using `CREATE DATABASE`.


.Query
[source, cypher]
----
CREATE DATABASE customers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
CREATE DATABASE customers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Database names are subject to the xref:syntax/naming.adoc[standard Cypher restrictions on valid identifiers].
The following naming rules apply:


* Database name length must be between 3 and 63 characters.
* The first character must be an ASCII alphabetic character.
* Subsequent characters can be ASCII alphabetic (`mydatabase`), numeric characters (`mydatabase2`), dots (`main.db`), and dashes (enclosed within backticks, e.g., `CREATE DATABASE ++`main-db`++`).
* Names cannot end with dots or dashes.
* Names that begin with an underscore or with the prefix `system` are reserved for internal use.
          


====

When a database has been created, it will show up in the listing provided by the command `SHOW DATABASES`.


.Query
[source, cypher]
----
SHOW DATABASES
----

.Result
[role="queryresult",options="header,footer",cols="7*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+ | +default+
| +"customers"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+
| +"neo4j"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +true+
| +"system"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+
7+d|Rows: 3
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
SHOW DATABASES
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

This command is optionally idempotent, with the default behavior to throw an exception if the database already exists. Appending `IF NOT EXISTS` to the command will ensure that no exception is thrown and nothing happens should the database already exist. Adding `OR REPLACE` to the command will result in any existing database being deleted and a new one created.


.Query
[source, cypher]
----
CREATE DATABASE customers IF NOT EXISTS
----

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
CREATE DATABASE customers IF NOT EXISTS
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
CREATE OR REPLACE DATABASE customers
----

This is equivalent to running `DROP DATABASE customers IF EXISTS` followed by `CREATE DATABASE customers`.

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
CREATE OR REPLACE DATABASE customers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
The `IF NOT EXISTS` and `OR REPLACE` parts of this command cannot be used together.


====

[role=enterprise-edition]
[[administration-databases-stop-database]]
== Stopping databases

Databases can be stopped using the command `STOP DATABASE`.


.Query
[source, cypher]
----
STOP DATABASE customers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
STOP DATABASE customers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The status of the stopped database can be seen using the command `SHOW DATABASE name`.


.Query
[source, cypher]
----
SHOW DATABASE customers
----

.Result
[role="queryresult",options="header,footer",cols="7*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+ | +default+
| +"customers"+ | +"localhost:7687"+ | +"standalone"+ | +"offline"+ | +"offline"+ | +""+ | +false+
7+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
SHOW DATABASE customers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[role=enterprise-edition]
[[administration-databases-start-database]]
== Starting databases

Databases can be started using the command `START DATABASE`.


.Query
[source, cypher]
----
START DATABASE customers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
START DATABASE customers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The status of the started database can be seen using the command `SHOW DATABASE name`.


.Query
[source, cypher]
----
SHOW DATABASE customers
----

.Result
[role="queryresult",options="header,footer",cols="7*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+ | +default+
| +"customers"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+
7+d|Rows: 1
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
SHOW DATABASE customers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[role=enterprise-edition]
[[administration-databases-drop-database]]
== Deleting databases

Databases can be deleted using the command `DROP DATABASE`.


.Query
[source, cypher]
----
DROP DATABASE customers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
DROP DATABASE customers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

When a database has been deleted, it will no longer show up in the listing provided by the command `SHOW DATABASES`.


.Query
[source, cypher]
----
SHOW DATABASES
----

.Result
[role="queryresult",options="header,footer",cols="7*<m"]
|===
| +name+ | +address+ | +role+ | +requestedStatus+ | +currentStatus+ | +error+ | +default+
| +"neo4j"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +true+
| +"system"+ | +"localhost:7687"+ | +"standalone"+ | +"online"+ | +"online"+ | +""+ | +false+
7+d|Rows: 2
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
SHOW DATABASES
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

This command is optionally idempotent, with the default behavior to throw an exception if the database does not exists. Appending `IF EXISTS` to the command will ensure that no exception is thrown and nothing happens should the database not exist.


.Query
[source, cypher]
----
DROP DATABASE customers IF EXISTS
----

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
DROP DATABASE customers IF EXISTS
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

