#  copy this workflow into your repo
name: "Documentation Teardown"

on:
  pull_request_target:
    branches:
      - "3.5"
      - "4.[0-9]"
      - "5.x"
      - "dev"
    types:
      - closed

jobs:
  teardown-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Teardown documentation
        run: |
          npm install -g surge
          surge teardown ${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.pull_request.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
          
