#  copy this workflow into your repo
name: "Documentation Teardown"

on:
  pull_request_target:
    branches:
      - dev
    types:
      - closed

jobs:
  teardown-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - id: get-deploy-url
        env:
          ORG: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
          DEPLOYID: ${{ github.event.pull_request.number }}
        run: |
          deployurl=$ORG-$REPO-$DEPLOYID.surge.sh
          echo "deploy-url=$deployurl" >> $GITHUB_OUTPUT

      - name: Teardown documentation
        shell: bash
        env:
          SURGE_TOKEN: "${{ secrets.DOCS_SURGE_TOKEN }}"
          DEPLOY_URL: ${{ steps.get-deploy-url.outputs.deploy-url }}
        run: |
          npm install -g surge
          surge teardown $DEPLOY_URL --token "$SURGE_TOKEN"

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.pull_request.number }}
          header: docs-pr-changes
          message: |
            Thanks for the documentation updates.

            The preview documentation has now been torn down - reopening this PR will republish it.
          GITHUB_TOKEN: ${{ secrets.DOCS_PR_COMMENT_TOKEN }}
      
