#  copy this workflow into your repo
name: "Documentation Teardown"

on:
  pull_request_target:
    branches:
      - "3.5"
      - "4.[0-9]"
      - "5.x"
      - "dev"
    types:
      - closed

jobs:
  teardown-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Teardown documentation
        shell: bash
        env:
          SURGE_TOKEN: "${{ secrets.DOCS_SURGE_TOKEN }}"
        run: |
          npm install -g surge
          surge teardown ${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.pull_request.number }}.surge.sh --token "$SURGE_TOKEN"
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.pull_request.number }}
          message: |
            Thanks for the documentation updates.

            The preview documentation has now been torn down - reopening this PR will republish it.
          GITHUB_TOKEN: ${{ secrets.DOCS_PR_COMMENT_TOKEN }}
      
