# Runs the check-links script in package.json
# That script should be set up to use https://github.com/neo4j-documentation/link-checker

# Can be run manually, or as part of PR verification.
# To run the action against a PR, add the 'check-links' label to the PR.

name: "Check links"

on:
  pull_request:
    branches:
      - "3.5"
      - "4.[0-9]"
      - "5.0"
      - "5.x"
      - "dev"
      - "feature-*"
    types: [labeled, opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      do-check:
        type: boolean


jobs:
  docs-check-links:
    if: contains( github.event.pull_request.labels.*.name, 'check-links') || inputs.do-check
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - run: npm install --omit=dev

    - run: npm run build
    
    - run: npm run check-links
    