# Use this starter workflow to verify PRs that include a change to the docs
# The default setup runs against PRs targeting your default branch
# Default artifact retention is 7 days

name: "Verify PR"

on:
  pull_request:
    branches:
    - "3.5"
    - "4.[0-9]"
    - "5.0"
    - "5.x"
    - "dev"
    - "feature-*"

jobs:

  # note that the build job requires a build-verify script in package.json
  # build-verify should build html with Antora, and output a .json log file
  # eg 'antora playbook.yml --log-format=json --log-file ./build/log/log.json'
  docs-build-for-pr:
    uses: recrwplay/actions-demo/.github/workflows/reusable-docs-build.yml@main
    with:
      deploy-id: ${{ github.event.number }}
      retain-artifacts: 14

  docs-verify-for-pr:
    needs: docs-build-for-pr
    uses: recrwplay/actions-demo/.github/workflows/reusable-docs-verify.yml@main
